"""全仓单轨契约零兼容门禁实现包。

包内模块职责：

- ``constants``：扫描根、禁用字段清单与全部单轨正则的唯一定义处。
- ``heuristics``：行级 / 上下文级判据（注释行、测试路径、拒绝语境、sha256 负例）。
- ``ownership``：退役领域身份字段的对象归属判定（ContractGraph + contracts 结构）。
- ``scanner``：Inventory、扫描文件枚举与 ``scan_file`` 主扫描流程；其模块级
  ``ROOT`` 是 contract 测试注入临时 fixture 树的挂点。
- ``report``：inventory 报告落盘、CLI 参数与 main 入口。

``__all__`` 即入口脚本的 re-export 面：既有消费者（contract 测试）依赖的
全部符号（含下划线私有符号）都在此单点列出。
"""
from __future__ import annotations

import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[3]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from .constants import (  # noqa: E402
    ALIASES_LINE,
    APP_REMOTE_CONFIG_SINGLE_IDENTITY_PATHS,
    APP_ROUTER_SINGLE_TRACK_PATH,
    AUTH_REQUIRED_LINE,
    CANONICAL_SHA256_DIGEST,
    COMPAT_SMELLS,
    CONTRACT_COMPAT_ALIAS,
    CUSTOM_CONTROL_VERSION_FIELDS,
    DART_WIRE_ID_KEY,
    DOC_DUAL_TRACK_TEACHING,
    EXPLICIT_INVALID_SHA256_FIXTURE,
    FORBIDDEN_APP_REMOTE_CONFIG_PACKAGE_VERSION,
    FORBIDDEN_ENVELOPE_FIELDS,
    FROZEN_IDENTITY_PATTERNS,
    FROZEN_VERSIONED_LOCAL_IDENTITIES,
    GO_BSON_ID_TAG,
    GO_BSON_MAP_ID_KEY,
    GO_JSON_ID_TAG,
    GO_MAP_ID_KEY,
    ID_COMPAT_TEACHING,
    MAP_LIST_FIRST_PRESENT,
    MULTI_KEY_DECODE,
    MULTI_KEY_GO_TEMPLATE,
    MULTI_KEY_HELPER_ID,
    NEGATIVE_ID_TEST_LINE,
    NUMERIC_SCHEMA_LITERAL,
    OPTIONAL_ALIAS_HELPER,
    POLICY_DIGEST_LITERAL_ASSIGNMENT,
    POSITIVE_ALIAS_TEST,
    PUBLIC_IDENTITY_RETIRED_PATTERNS,
    PUBLIC_USER_MODEL_RETIRED_PATTERNS,
    PUBLIC_USER_MODEL_SINGLE_TRACK_ROOT,
    RETIRED_CIRCLE_SNAPSHOT_SEGMENT,
    RETIRED_CLIENT_STATE_SYNC_DERIVED_FIELD,
    RETIRED_CREATE_ROUTE_EXTRA,
    RETIRED_CUSTOM_IDENTITY,
    RETIRED_DOMAIN_IDENTITY_FIELDS,
    RETIRED_GROUP_AVATAR_LAYOUT,
    RETIRED_MESSAGE_EVENT_ID_SEGMENT,
    RETIRED_MOCK_EXPERIMENT_RUNTIME,
    RETIRED_PERSONA_MIGRATION_TYPE,
    RETIRED_QUOTA_LOG_VERSION,
    RETIRED_QUOTA_SHARD_VERSION,
    RETIRED_RUNTIME_ERROR_MESSAGE_ALIAS,
    RETIRED_SEARCH_RECOMMENDATION_IDENTITY,
    RETIRED_USER_IDENTITY,
    ROOT,
    RUNTIME_ERROR_SINGLE_TRACK_PATHS,
    SCAN_ROOTS,
    SCHEMA_VALUE_V_SUFFIX,
    SHA256_ALGORITHM_IDENTITY_CONTEXT,
    SHA256_LITERAL,
    SHA256_NEGATIVE_FIXTURE_CONTEXT,
    SHA256_REJECTION_ASSERTION,
    SKIP_DIR_NAMES,
    SKIP_EMPTY_ALIASES,
    SOURCE_KEYS_ALIAS_LINE,
    TEXT_SUFFIXES,
    TOP_LEVEL_VERSION,
    VERSIONED_GOLDEN_ASSET_NAME,
    VERSIONED_INLINE,
    VERSIONED_INTERPOLATED_QUEUE_IDENTITY,
    VERSIONED_LOCAL_IDENTITY_LITERAL,
    VERSIONED_MIGRATION_IDENTITY,
    VERSIONED_SCHEMA_VALUE,
)
from .heuristics import (  # noqa: E402
    _custom_control_version_fields,
    _is_canonical_concatenated_sha256,
    _is_comment_line,
    _is_elasticsearch_bulk_metadata_context,
    _is_explicit_sha256_negative_fixture,
    _is_external_provider_path,
    _is_governance_scanner,
    _is_governance_test,
    _is_mongo_seed_scenario,
    _is_persistence_go_path,
    _is_rejection_context,
    _is_sha256_algorithm_identity,
    _is_sha256_documentation_placeholder,
    _is_test_path,
    _json_object_has_dual_id,
    is_external_grafana_dashboard_schema,
)
from .ownership import (  # noqa: E402
    CONTRACT_GRAPH_PATH,
    CONTRACT_OBJECT_DIR_GLOBS,
    CONTRACT_OBJECT_SOURCE_ROOT,
    CONTRACT_PROSE_KEYS,
    RECOMMENDATION_CANONICAL_IDENTITY_FIELDS,
    RETIRED_DOMAIN_IDENTITY_OBJECTS,
    _contract_graph_object_segments,
    _contract_object_source_dirs,
    _object_declares_identifiers,
    _path_owns_object,
    _path_owns_segments,
    _recommendation_identity_object_segments,
    _retired_domain_identity_applies,
    _scope_object_segments,
    _yaml_declared_identifiers,
)
from .report import main, write_inventory  # noqa: E402
from .scanner import (  # noqa: E402
    Finding,
    Inventory,
    is_contract_yaml,
    is_custom_control_document,
    is_metadata_object_yaml,
    iter_files,
    scan_file,
    scan_versioned_golden_assets,
    should_skip,
)

__all__ = [
    "ALIASES_LINE",
    "APP_REMOTE_CONFIG_SINGLE_IDENTITY_PATHS",
    "APP_ROUTER_SINGLE_TRACK_PATH",
    "AUTH_REQUIRED_LINE",
    "CANONICAL_SHA256_DIGEST",
    "COMPAT_SMELLS",
    "CONTRACT_COMPAT_ALIAS",
    "CONTRACT_GRAPH_PATH",
    "CONTRACT_OBJECT_DIR_GLOBS",
    "CONTRACT_OBJECT_SOURCE_ROOT",
    "CONTRACT_PROSE_KEYS",
    "CUSTOM_CONTROL_VERSION_FIELDS",
    "DART_WIRE_ID_KEY",
    "DOC_DUAL_TRACK_TEACHING",
    "EXPLICIT_INVALID_SHA256_FIXTURE",
    "FORBIDDEN_APP_REMOTE_CONFIG_PACKAGE_VERSION",
    "FORBIDDEN_ENVELOPE_FIELDS",
    "FROZEN_IDENTITY_PATTERNS",
    "FROZEN_VERSIONED_LOCAL_IDENTITIES",
    "Finding",
    "GO_BSON_ID_TAG",
    "GO_BSON_MAP_ID_KEY",
    "GO_JSON_ID_TAG",
    "GO_MAP_ID_KEY",
    "ID_COMPAT_TEACHING",
    "Inventory",
    "MAP_LIST_FIRST_PRESENT",
    "MULTI_KEY_DECODE",
    "MULTI_KEY_GO_TEMPLATE",
    "MULTI_KEY_HELPER_ID",
    "NEGATIVE_ID_TEST_LINE",
    "NUMERIC_SCHEMA_LITERAL",
    "OPTIONAL_ALIAS_HELPER",
    "POLICY_DIGEST_LITERAL_ASSIGNMENT",
    "POSITIVE_ALIAS_TEST",
    "PUBLIC_IDENTITY_RETIRED_PATTERNS",
    "PUBLIC_USER_MODEL_RETIRED_PATTERNS",
    "PUBLIC_USER_MODEL_SINGLE_TRACK_ROOT",
    "RECOMMENDATION_CANONICAL_IDENTITY_FIELDS",
    "RETIRED_CIRCLE_SNAPSHOT_SEGMENT",
    "RETIRED_CLIENT_STATE_SYNC_DERIVED_FIELD",
    "RETIRED_CREATE_ROUTE_EXTRA",
    "RETIRED_CUSTOM_IDENTITY",
    "RETIRED_DOMAIN_IDENTITY_FIELDS",
    "RETIRED_DOMAIN_IDENTITY_OBJECTS",
    "RETIRED_GROUP_AVATAR_LAYOUT",
    "RETIRED_MESSAGE_EVENT_ID_SEGMENT",
    "RETIRED_MOCK_EXPERIMENT_RUNTIME",
    "RETIRED_PERSONA_MIGRATION_TYPE",
    "RETIRED_QUOTA_LOG_VERSION",
    "RETIRED_QUOTA_SHARD_VERSION",
    "RETIRED_RUNTIME_ERROR_MESSAGE_ALIAS",
    "RETIRED_SEARCH_RECOMMENDATION_IDENTITY",
    "RETIRED_USER_IDENTITY",
    "ROOT",
    "RUNTIME_ERROR_SINGLE_TRACK_PATHS",
    "SCAN_ROOTS",
    "SCHEMA_VALUE_V_SUFFIX",
    "SHA256_ALGORITHM_IDENTITY_CONTEXT",
    "SHA256_LITERAL",
    "SHA256_NEGATIVE_FIXTURE_CONTEXT",
    "SHA256_REJECTION_ASSERTION",
    "SKIP_DIR_NAMES",
    "SKIP_EMPTY_ALIASES",
    "SOURCE_KEYS_ALIAS_LINE",
    "TEXT_SUFFIXES",
    "TOP_LEVEL_VERSION",
    "VERSIONED_GOLDEN_ASSET_NAME",
    "VERSIONED_INLINE",
    "VERSIONED_INTERPOLATED_QUEUE_IDENTITY",
    "VERSIONED_LOCAL_IDENTITY_LITERAL",
    "VERSIONED_MIGRATION_IDENTITY",
    "VERSIONED_SCHEMA_VALUE",
    "_contract_graph_object_segments",
    "_contract_object_source_dirs",
    "_custom_control_version_fields",
    "_is_canonical_concatenated_sha256",
    "_is_comment_line",
    "_is_elasticsearch_bulk_metadata_context",
    "_is_explicit_sha256_negative_fixture",
    "_is_external_provider_path",
    "_is_governance_scanner",
    "_is_governance_test",
    "_is_mongo_seed_scenario",
    "_is_persistence_go_path",
    "_is_rejection_context",
    "_is_sha256_algorithm_identity",
    "_is_sha256_documentation_placeholder",
    "_is_test_path",
    "_json_object_has_dual_id",
    "_object_declares_identifiers",
    "_path_owns_object",
    "_path_owns_segments",
    "_recommendation_identity_object_segments",
    "_retired_domain_identity_applies",
    "_scope_object_segments",
    "_yaml_declared_identifiers",
    "is_contract_yaml",
    "is_custom_control_document",
    "is_external_grafana_dashboard_schema",
    "is_metadata_object_yaml",
    "iter_files",
    "main",
    "scan_file",
    "scan_versioned_golden_assets",
    "should_skip",
    "write_inventory",
]
