// Code generated by internal/metadata/codegen. DO NOT EDIT.
package circlefile

import "time"

// GeoPoint represents a geographic coordinate.
type GeoPoint struct {
	Latitude  float64 `json:"latitude" bson:"latitude"`
	Longitude float64 `json:"longitude" bson:"longitude"`
}

var _ = time.Now

// CircleFileStatus enumerates allowed wire values for CircleFileStatus.
type CircleFileStatus string

const (
	CircleFileStatusActive CircleFileStatus = "active"

	CircleFileStatusDeleted CircleFileStatus = "deleted"
)

// CircleFileType enumerates allowed wire values for CircleFileType.
type CircleFileType string

const (
	CircleFileTypeFile CircleFileType = "file"

	CircleFileTypeFolder CircleFileType = "folder"
)

// CircleFile domain model.
type CircleFile struct {
	ID                string           `json:"id" bson:"_id"`
	Version           int64            `json:"version" bson:"version"`
	CircleID          string           `json:"circleId" bson:"circleId"`
	GroupID           string           `json:"groupId" bson:"groupId"`
	ParentFolderID    string           `json:"parentFolderId" bson:"parentFolderId"`
	Name              string           `json:"name" bson:"name"`
	FileType          CircleFileType   `json:"fileType" bson:"fileType"`
	AssetID           string           `json:"assetId" bson:"assetId"`
	MimeType          string           `json:"mimeType" bson:"mimeType"`
	SizeBytes         int64            `json:"sizeBytes" bson:"sizeBytes"`
	UploaderPersonaID string           `json:"uploaderPersonaId" bson:"uploaderPersonaId"`
	Status            CircleFileStatus `json:"status" bson:"status"`
	CreatedAt         time.Time        `json:"createdAt" bson:"createdAt"`
	UpdatedAt         time.Time        `json:"updatedAt" bson:"updatedAt"`
}
