// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../../components/content/post/video_post_card_widget_test.dart' as source_0;

void main() {
  source_0.main();
}
