// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../../ui/chat/widgets/chat_assistant_ui_widget_test.dart' as source_test;

void main() {
  source_test.main();
}
