// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../../ui/chat/widgets/chat_detail_page_assistant_ui_regression_test.dart' as source_0;

void main() {
  source_0.main();
}
