// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../../ui/chat/widgets/chat_mock_remote_consistency_test.dart' as legacy_test;

void main() {
  legacy_test.main();
}
