import { KpiCard, PageScaffold, SectionCard } from '@ops-ui';
import { Database, FileText, Image, RefreshCw, Shapes } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../shared/api/client.js';
import type { CountFacet, Overview } from '../shared/api/types.js';
import { Status } from '../components/Ui.js';
const drill = (key: string, value: string) => `/explore?${new URLSearchParams([[key, value], ['page', '1'], ['pageSize', '20']])}`;
function MetricGroup({ title, items, param }: { title: string; items: CountFacet[]; param: string }) { return <SectionCard title={title}><div className="metric-list">{items.map((item) => <Link key={item.id} to={drill(param, item.id)}><span>{item.label}</span><strong>{item.count.toLocaleString()}</strong></Link>)}{!items.length && <div className="empty">暂无数据</div>}</div></SectionCard>; }
export function OverviewPage() {
  const [data, setData] = useState<Overview>(); const [error, setError] = useState(''); const [refreshing, setRefreshing] = useState(false); const [refreshNote, setRefreshNote] = useState('');
  useEffect(() => { const controller = new AbortController(); api.overview('', controller.signal).then(setData).catch((reason: Error) => { if (!controller.signal.aborted) setError(reason.message); }); return () => controller.abort(); }, []);
  async function refresh() { const before = data?.readToken; const started = performance.now(); setRefreshing(true); setRefreshNote('正在重建内容池快照，当前页面继续显示旧快照。'); try { const result = await api.refresh(); const next = await api.overview(`?readToken=${encodeURIComponent(result.readToken)}`); setData(next); const elapsed = performance.now() - started; setRefreshNote(`刷新完成，用时 ${Math.round(elapsed)}ms${before && before !== next.readToken ? `；已从旧快照 ${before} 切换。` : '。'}`); } catch (reason) { setRefreshNote(`刷新失败，仍显示旧快照：${(reason as Error).message}`); } finally { setRefreshing(false); } }
  return <PageScaffold title="内容池总览" subtitle="只读取当前快照；刷新必须由操作员显式触发。" meta={data ? <span className="snapshot">readToken {data.readToken}</span> : undefined} actions={<button className="button button--primary" disabled={refreshing} onClick={refresh}><RefreshCw size={16} className={refreshing ? 'spin' : ''} />{refreshing ? '刷新中…' : '刷新内容池'}</button>}><Status loading={!data && !error} error={error} />{refreshNote && <div className={`notice ${refreshNote.startsWith('刷新失败') ? 'notice--error' : ''}`}>{refreshNote}</div>}{data && <><div className="kpi-grid"><Link to="/explore"><KpiCard label="当前对象总数" value={data.total.toLocaleString()} icon={<Database />} trendLabel="可下钻对象指标" trendTone="positive" description="点击查看同一集合" /></Link><KpiCard label="文本体量" value={data.volume.textBytes.toLocaleString()} icon={<FileText />} trendLabel="非过滤 metric" trendTone="warning" description="真实随体文本与结构化字节" /><KpiCard label="媒体体量" value={data.volume.mediaBytes.toLocaleString()} icon={<Image />} trendLabel="非过滤 metric" trendTone="warning" description="真实 media 目录字节" /><KpiCard label="动态形态" value={data.contentForms.length.toLocaleString()} icon={<Shapes />} trendLabel="可下钻对象维度" trendTone="positive" description="含未知 renderer 形态" /></div>{data.staleRead && <div className="notice notice--warning">当前响应标记为 stale_read。</div>}<div className="two-col"><MetricGroup title="人工复核" items={data.reviewStates} param="humanStates" /><MetricGroup title="来源平台" items={data.sourcePlatforms} param="sourcePlatforms" /><SectionCard title="内容形态"><div className="metric-list">{data.contentForms.map((item) => <Link key={item.id} to={drill('contentFormIds', item.id)}><span>{item.label}</span><strong>{item.count}</strong></Link>)}</div></SectionCard><SectionCard title="生产质量（不补零）"><div className="quality-list">{data.qualityScores.map((score) => <div key={`${score.contentFormId}:${score.dimension}`}><strong>{score.contentFormId} · {score.dimension}</strong><span>n={score.n} · mean={score.mean.toFixed(2)} · {JSON.stringify(score.distribution)}</span></div>)}{!data.qualityScores.length && <div className="empty">没有已申报评分</div>}</div></SectionCard></div></>}</PageScaffold>;
}
