-- Code generated by codegen_storage. DO NOT EDIT.

CREATE TABLE IF NOT EXISTS user_devices (
    id                       VARCHAR(36) PRIMARY KEY,
    user_id                  VARCHAR(36) NOT NULL,
    device_id                VARCHAR(128) NOT NULL,
    platform                 VARCHAR(16) NOT NULL,
    push_token               VARCHAR(512),
    app_version              VARCHAR(32),
    last_active_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at               TIMESTAMPTZ NOT NULL DEFAULT NOW()
    ,CONSTRAINT fk_user_devices_user_id FOREIGN KEY (user_id) REFERENCES user_profiles(user_id) ON DELETE CASCADE
);

ALTER TABLE user_devices ADD CONSTRAINT uq_user_devices_user_device UNIQUE (user_id, device_id);
