-- Code generated by codegen_storage. DO NOT EDIT.

CREATE TABLE IF NOT EXISTS invite_records (
    id                       VARCHAR(36) PRIMARY KEY,
    inviter_sub_account_id   VARCHAR(36) NOT NULL,
    inviter_owner_account_id VARCHAR(36) NOT NULL,
    channel                  VARCHAR(16) NOT NULL,
    link_code                VARCHAR(32) NOT NULL UNIQUE,
    invitee_phone_hash       VARCHAR(64),
    status                   VARCHAR(16) NOT NULL DEFAULT 'generated',
    expire_at                TIMESTAMPTZ NOT NULL,
    generated_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    delivered_at             TIMESTAMPTZ,
    viewed_at                TIMESTAMPTZ,
    accepted_at              TIMESTAMPTZ,
    converted_at             TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_invite_records_inviter_sub ON invite_records (inviter_sub_account_id);

CREATE INDEX IF NOT EXISTS idx_invite_records_link_code ON invite_records (link_code);

CREATE INDEX IF NOT EXISTS idx_invite_records_status ON invite_records (status);

CREATE INDEX IF NOT EXISTS idx_invite_records_expire_at ON invite_records (expire_at);

CREATE UNIQUE INDEX IF NOT EXISTS uq_invite_idempotent ON invite_records (inviter_sub_account_id, channel, invitee_phone_hash) WHERE status = 'generated' AND invitee_phone_hash IS NOT NULL;
