// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../../ui/intersection/pages/object_intersection_list_page_test.dart' as source_test;

void main() {
  source_test.main();
}
