// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../../common/assistant/protocol/assistant_answer_protocol_leak_regression_test.dart' as source_0;

void main() {
  source_0.main();
}
