// Code generated by contracts/platform_ops/human_authority/generate_binding.py; DO NOT EDIT.

package model

const CanonicalHumanContractSource = "quwoquan_ops/policies/human_agent_delivery_contract.yaml"
const CanonicalHumanContractSHA256 = "sha256:1d18b9adffc2a0d04e0208c649a41a1a5ed3ddf546f6c6ca27fce02cc1a86930"
const CanonicalAuthorityFieldsSource = "quwoquan_service/control-plane/platform-ops/contracts/platform_ops/human_authority/fields.yaml"
const CanonicalAuthorityFieldsSHA256 = "sha256:e0d48389883190f2a5ae4d414ac21f734d0951488dbc26dfe1c320918e3393e9"

var GeneratedAuthorityReceiptClaimFields = []string{
	"schemaVersion",
	"receiptId",
	"decisionId",
	"decisionUnitId",
	"actorId",
	"actorAuthenticated",
	"role",
	"scope",
	"evidenceFingerprint",
	"decisionKind",
	"actions",
	"issuedAt",
	"expiresAt",
	"providerKind",
	"providerVersion",
	"providerCommit",
	"contractVersion",
	"issuer",
	"nativeProtection",
	"releaseEligible",
	"testKey",
}

var GeneratedAuthorityStateAttestationFields = []string{
	"schemaVersion",
	"receiptId",
	"decisionId",
	"decisionUnitId",
	"payloadDigest",
	"state",
	"previousGeneration",
	"generation",
	"etag",
	"winnerIdempotencyKey",
	"winnerCommandDigest",
	"stateActorId",
	"stateAt",
	"chainCommit",
	"providerKind",
	"providerVersion",
	"providerCommit",
	"contractVersion",
	"issuer",
}

var GeneratedAuthorizationReceiptWrapperFields = []string{
	"schemaVersion",
	"canonicalBytes",
	"payloadDigest",
	"signatureAlgorithm",
	"keyId",
	"signature",
	"attestationCanonicalBytes",
	"attestationDigest",
	"attestationSignature",
	"receiptId",
	"decisionId",
	"decisionUnitId",
	"state",
	"previousGeneration",
	"generation",
	"etag",
	"winnerIdempotencyKey",
	"winnerCommandDigest",
	"stateActorId",
	"stateAt",
	"chainCommit",
	"providerKind",
	"providerVersion",
	"providerCommit",
	"contractVersion",
	"issuer",
	"releaseEligible",
	"testKey",
}

const GeneratedAuthorityReceiptClaimFieldsJSON = "[\"schemaVersion\",\"receiptId\",\"decisionId\",\"decisionUnitId\",\"actorId\",\"actorAuthenticated\",\"role\",\"scope\",\"evidenceFingerprint\",\"decisionKind\",\"actions\",\"issuedAt\",\"expiresAt\",\"providerKind\",\"providerVersion\",\"providerCommit\",\"contractVersion\",\"issuer\",\"nativeProtection\",\"releaseEligible\",\"testKey\"]"
const GeneratedAuthorityStateAttestationFieldsJSON = "[\"schemaVersion\",\"receiptId\",\"decisionId\",\"decisionUnitId\",\"payloadDigest\",\"state\",\"previousGeneration\",\"generation\",\"etag\",\"winnerIdempotencyKey\",\"winnerCommandDigest\",\"stateActorId\",\"stateAt\",\"chainCommit\",\"providerKind\",\"providerVersion\",\"providerCommit\",\"contractVersion\",\"issuer\"]"
const GeneratedAuthorizationReceiptWrapperFieldsJSON = "[\"schemaVersion\",\"canonicalBytes\",\"payloadDigest\",\"signatureAlgorithm\",\"keyId\",\"signature\",\"attestationCanonicalBytes\",\"attestationDigest\",\"attestationSignature\",\"receiptId\",\"decisionId\",\"decisionUnitId\",\"state\",\"previousGeneration\",\"generation\",\"etag\",\"winnerIdempotencyKey\",\"winnerCommandDigest\",\"stateActorId\",\"stateAt\",\"chainCommit\",\"providerKind\",\"providerVersion\",\"providerCommit\",\"contractVersion\",\"issuer\",\"releaseEligible\",\"testKey\"]"

var GeneratedHumanAuthorityRoles = []string{
	"business_sponsor",
	"product_owner",
	"business_acceptance_representative",
	"experience_design_owner",
	"domain_solution_architecture_owner",
	"engineering_delivery_owner",
	"quality_owner",
	"security_privacy_legal_compliance_owner",
	"release_owner",
	"environment_reliability_owner",
	"operations_support_market_channel_owner",
}

var GeneratedDecisionKinds = []string{
	"problem_acceptance",
	"product_scope",
	"experience_direction",
	"solution_risk",
	"delivery_authorization",
	"implementation_exception",
	"quality_uat_acceptance",
	"integration_acceptance",
	"artifact_acceptance",
	"nonproduction_acceptance",
	"commercial_readiness",
	"production_campaign_approval",
	"channel_publication",
	"outcome_acceptance",
	"knowledge_landing",
	"routine_execution",
}

var GeneratedSoDPolicies = []string{
	"role-record-only",
	"independent-principal-required",
}

var GeneratedDecisionUnitResponsibilities = []string{
	"required_input_providers",
	"independent_impact_assessors",
	"hard_veto_owners",
	"accountable_decider",
	"authorized_executor",
	"evidence_owner",
	"result_acceptor",
}

type GeneratedRouterRule struct {
	Stage           string
	DecisionKind    string
	AccountableRole string
	HardVetoRoles   []string
}

var GeneratedRouterRules = []GeneratedRouterRule{
	{Stage: "concept_intake", DecisionKind: "problem_acceptance", AccountableRole: "business_sponsor", HardVetoRoles: []string{}},
	{Stage: "product_definition", DecisionKind: "product_scope", AccountableRole: "product_owner", HardVetoRoles: []string{}},
	{Stage: "experience_design", DecisionKind: "experience_direction", AccountableRole: "experience_design_owner", HardVetoRoles: []string{}},
	{Stage: "solution_risk_design", DecisionKind: "solution_risk", AccountableRole: "domain_solution_architecture_owner", HardVetoRoles: []string{"security_privacy_legal_compliance_owner", "quality_owner", "environment_reliability_owner"}},
	{Stage: "delivery_planning_authorization", DecisionKind: "delivery_authorization", AccountableRole: "engineering_delivery_owner", HardVetoRoles: []string{"security_privacy_legal_compliance_owner"}},
	{Stage: "agent_led_implementation", DecisionKind: "implementation_exception", AccountableRole: "engineering_delivery_owner", HardVetoRoles: []string{}},
	{Stage: "quality_business_uat", DecisionKind: "quality_uat_acceptance", AccountableRole: "quality_owner", HardVetoRoles: []string{"security_privacy_legal_compliance_owner"}},
	{Stage: "integration_trusted_ci", DecisionKind: "integration_acceptance", AccountableRole: "engineering_delivery_owner", HardVetoRoles: []string{}},
	{Stage: "immutable_artifact", DecisionKind: "artifact_acceptance", AccountableRole: "release_owner", HardVetoRoles: []string{"security_privacy_legal_compliance_owner", "quality_owner"}},
	{Stage: "nonproduction_validation", DecisionKind: "nonproduction_acceptance", AccountableRole: "environment_reliability_owner", HardVetoRoles: []string{"quality_owner", "security_privacy_legal_compliance_owner"}},
	{Stage: "commercial_readiness", DecisionKind: "commercial_readiness", AccountableRole: "product_owner", HardVetoRoles: []string{"quality_owner", "security_privacy_legal_compliance_owner", "environment_reliability_owner"}},
	{Stage: "production_campaign", DecisionKind: "production_campaign_approval", AccountableRole: "release_owner", HardVetoRoles: []string{"environment_reliability_owner", "security_privacy_legal_compliance_owner"}},
	{Stage: "channel_distribution", DecisionKind: "channel_publication", AccountableRole: "operations_support_market_channel_owner", HardVetoRoles: []string{"security_privacy_legal_compliance_owner", "release_owner"}},
	{Stage: "outcome_observation_acceptance", DecisionKind: "outcome_acceptance", AccountableRole: "product_owner", HardVetoRoles: []string{}},
	{Stage: "feedback_knowledge_distillation", DecisionKind: "knowledge_landing", AccountableRole: "engineering_delivery_owner", HardVetoRoles: []string{}},
	{Stage: "agent_led_implementation", DecisionKind: "routine_execution", AccountableRole: "", HardVetoRoles: []string{}},
	{Stage: "nonproduction_validation", DecisionKind: "routine_execution", AccountableRole: "", HardVetoRoles: []string{}},
	{Stage: "production_campaign", DecisionKind: "routine_execution", AccountableRole: "", HardVetoRoles: []string{}},
}

type GeneratedSoDPolicy struct {
	SeparateRoleRecordsRequired         bool
	DistinctAuthenticatedActorsRequired bool
}

var GeneratedSoDPolicyRules = map[string]GeneratedSoDPolicy{
	"independent-principal-required": {SeparateRoleRecordsRequired: true, DistinctAuthenticatedActorsRequired: true},
	"role-record-only":               {SeparateRoleRecordsRequired: true, DistinctAuthenticatedActorsRequired: false},
}

const GeneratedDefaultSoDPolicy = "role-record-only"

var GeneratedRiskSoDPolicies = map[string]string{
	"compliance":          "independent-principal-required",
	"irreversible_data":   "independent-principal-required",
	"production_critical": "independent-principal-required",
	"safety":              "independent-principal-required",
}
