// Code generated by generate_canonical_test_bridges.py. DO NOT EDIT.

import '../../../../ui/entity/pages/suggest_homepage_page_widget_test.dart' as source_0;
import '../../../../ui/entity/pages/homepage_picker_page_widget_test.dart' as source_1;

void main() {
  source_0.main();
  source_1.main();
}
