import 'dart:io';

class DartRuntimeErrorGenerator {
  const DartRuntimeErrorGenerator();

  void generate() {
    final output = _outputFile(Directory.current);
    output.parent.createSync(recursive: true);
    output.writeAsStringSync(render(Directory.current));
  }

  bool isCurrent(Directory repoRoot) {
    final output = _outputFile(repoRoot);
    return output.existsSync() && output.readAsStringSync() == render(repoRoot);
  }

  String render(Directory repoRoot) {
    final codes = _readCodes(repoRoot);
    final buffer = StringBuffer()
      ..writeln('// Code generated by runtime_error_codegen. DO NOT EDIT.')
      ..writeln()
      ..writeln('abstract final class RuntimeFailureCodes {');
    for (final code in codes) {
      final declaration =
          "  static const String ${_identifier(code)} = '$code';";
      if (declaration.length <= 80) {
        buffer.writeln(declaration);
      } else {
        buffer
          ..writeln('  static const String ${_identifier(code)} =')
          ..writeln("      '$code';");
      }
    }
    buffer.writeln('}');
    return buffer.toString();
  }

  List<String> _readCodes(Directory repoRoot) {
    final source = File(
      '${repoRoot.path}/quwoquan_service/contracts/runtime_errors/errors/runtime_failure_codes.yaml',
    );
    final pattern = RegExp(r'^\s*-\s*code:\s*([A-Z]+\.[A-Z]+\.[a-z0-9_]+)\s*$');
    return <String>[
      for (final line in source.readAsLinesSync())
        if (pattern.firstMatch(line)?.group(1) case final String code) code,
    ];
  }

  File _outputFile(Directory repoRoot) => File(
    '${repoRoot.path}/quwoquan_service/contracts/runtime_errors/packages/dart/'
    'quwoquan_runtime_errors/lib/src/runtime_failure_codes.g.dart',
  );

  String _identifier(String code) {
    final parts = code.toLowerCase().split(RegExp(r'[._-]+'));
    return parts.first +
        parts
            .skip(1)
            .map((part) => part[0].toUpperCase() + part.substring(1))
            .join();
  }
}
