// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../app/navigation/native_back_navigation_policy_test.dart' as legacy_test;

void main() {
  legacy_test.main();
}
