"""verify_object_alert_coverage 的实现包：re-export 全部原模块符号。

薄入口 ``verify_object_alert_coverage.py`` 与既有消费者（gate importer、
local_contract 测试）都从这里取符号；判定口径见 ``cli`` 模块 docstring。
"""

from .constants import (
    ALERTS_ROOT,
    CONTRACT_GRAPH,
    COVERAGE_ALERTS_NAME,
    COVERAGE_DASHBOARD_NAME,
    COVERAGE_DASHBOARD_UID,
    DASHBOARDS_ROOT,
    DURATION_SOURCE_METRIC,
    GENERATED_HEADER,
    MONITORING_ROOT,
    PROMETHEUS_CONFIG,
    PROMETHEUS_COVERAGE_RULE,
    PROMETHEUS_RULE_GLOB,
    RECORDING_RULE_DIR_SUFFIX,
    REPO_ROOT,
    REQUEST_SOURCE_METRIC,
    SCRIPT_NAME,
    SERVICES_ROOT,
    _PATH_PARAMETER_RE,
    _PROMQL_LABEL_RE,
    _PROMQL_SELECTOR_RE,
    _RECORD_METRIC_RE,
    _display_path,
    _number_label,
    _quoted,
)
from .models import (
    ContractInputError,
    DomainReport,
    OBJECT_SURFACE_NONE,
    OBJECT_SURFACE_PENDING,
    OBJECT_SURFACE_READY,
    OBJECT_SURFACE_RUNTIME_ONLY,
    ObjectSurface,
    OperationContract,
    RuleExpression,
    VerificationReport,
    _number,
)
from .contract_inputs import (
    _GO_METRIC_OPTS,
    _PY_METRIC_CTOR,
    _go_opts_field,
    load_domain_services,
    load_emitted_series,
    load_object_surfaces,
    load_operations,
    runtime_domain_services,
)
from .promql import (
    _LABEL_MATCHER_BLOCK,
    _decode_promql_string,
    _load_alert_expressions,
    _load_dashboard_expressions,
    _matcher_accepts,
    _record_metric_selectors,
    _selector_labels,
    _walk_dashboard_expressions,
)
from .generated_docs import (
    _alert_name_domain,
    _drift_issues,
    _escape_promql_regex_literal,
    _group_name,
    _recording_rule_files,
    _threshold_label,
    coverage_alert_document,
    coverage_dashboard_document,
    domain_ready_selector,
    generated_documents,
    record_metric,
    record_metrics,
    recording_rule_documents,
    route_matcher,
    source_expression,
    write_generated_documents,
)
from .verification import (
    _domain_reports,
    _expression_covers,
    _verify_consumer_selectors,
    _verify_metric_identifier_semantics,
    _verify_object_surfaces,
    _verify_prometheus_rule_files,
    _verify_recording_rules,
    verify_coverage,
)
from .cli import _parse_args, _print_report, main

__all__ = [
    "ALERTS_ROOT",
    "CONTRACT_GRAPH",
    "COVERAGE_ALERTS_NAME",
    "COVERAGE_DASHBOARD_NAME",
    "COVERAGE_DASHBOARD_UID",
    "DASHBOARDS_ROOT",
    "DURATION_SOURCE_METRIC",
    "GENERATED_HEADER",
    "MONITORING_ROOT",
    "PROMETHEUS_CONFIG",
    "PROMETHEUS_COVERAGE_RULE",
    "PROMETHEUS_RULE_GLOB",
    "RECORDING_RULE_DIR_SUFFIX",
    "REPO_ROOT",
    "REQUEST_SOURCE_METRIC",
    "SCRIPT_NAME",
    "SERVICES_ROOT",
    "ContractInputError",
    "DomainReport",
    "OBJECT_SURFACE_NONE",
    "OBJECT_SURFACE_PENDING",
    "OBJECT_SURFACE_READY",
    "OBJECT_SURFACE_RUNTIME_ONLY",
    "ObjectSurface",
    "OperationContract",
    "RuleExpression",
    "VerificationReport",
    "coverage_alert_document",
    "coverage_dashboard_document",
    "domain_ready_selector",
    "generated_documents",
    "load_domain_services",
    "load_emitted_series",
    "load_object_surfaces",
    "load_operations",
    "main",
    "record_metric",
    "record_metrics",
    "recording_rule_documents",
    "route_matcher",
    "runtime_domain_services",
    "source_expression",
    "verify_coverage",
    "write_generated_documents",
]
