import 'package:quwoquan_cloud_contracts/quwoquan_cloud_contracts.dart';

/// Object-local typed fixture for the canonical Content Post projection.
///
/// This helper never decodes transport maps. Tests that exercise the wire
/// boundary must round-trip the generated [ContentPostProjection.toWire] and
/// [ContentPostProjection.fromWire] APIs explicitly.
ContentPostProjection contentPostProjectionFixture({
  String postId = 'post-1',
  String contentType = 'micro',
  String? contentIdentity,
  AssistantUsePolicy? assistantUsePolicy = AssistantUsePolicy.inherit,
  String? authorId = 'author-1',
  String? authorDisplayName = 'Author',
  String? authorAvatarUrl = '',
  String? authorAvatarAssetId,
  MediaDeliveryAccessMode? authorAvatarAccessMode,
  String? authorBackgroundUrl,
  String? authorRoleLabel = '',
  List<String>? authorIdentityTags = const <String>[],
  bool? authorVerified = false,
  String? title,
  String? body,
  String? summary,
  String? coverUrl,
  String? articleTemplate,
  String? articleFontPreset,
  List<String>? mediaUrls,
  String? videoUrl,
  String? mediaAssetId,
  int? mediaAssetVersion,
  List<PostMediaItem>? mediaItems,
  String? hlsCmafMasterManifestUrl,
  int? hlsCmafDescriptorVersion,
  String? thumbnailUrl,
  int? width,
  int? height,
  int? durationMs,
  int likeCount = 0,
  int commentCount = 0,
  int shareCount = 0,
  DateTime? createdAt,
  DateTime? updatedAt,
  DateTime? publishedAt,
  String? contentVertical,
  String? recallPath,
  String? supplySource,
  List<IntersectionReason>? intersectionReasons,
}) => ContentPostProjection(
  postId: postId,
  contentType: contentType,
  contentIdentity: contentIdentity,
  assistantUsePolicy: assistantUsePolicy,
  authorId: authorId,
  authorDisplayName: authorDisplayName,
  authorAvatarUrl: authorAvatarUrl,
  authorAvatarAssetId: authorAvatarAssetId,
  authorAvatarAccessMode: authorAvatarAccessMode,
  authorBackgroundUrl: authorBackgroundUrl,
  authorRoleLabel: authorRoleLabel,
  authorIdentityTags: authorIdentityTags,
  authorVerified: authorVerified,
  title: title,
  body: body,
  summary: summary,
  coverUrl: coverUrl,
  articleTemplate: articleTemplate,
  articleFontPreset: articleFontPreset,
  mediaUrls: mediaUrls,
  videoUrl: videoUrl,
  mediaAssetId: mediaAssetId,
  mediaAssetVersion: mediaAssetVersion,
  mediaItems: mediaItems,
  hlsCmafMasterManifestUrl: hlsCmafMasterManifestUrl,
  hlsCmafDescriptorVersion: hlsCmafDescriptorVersion,
  thumbnailUrl: thumbnailUrl,
  width: width,
  height: height,
  durationMs: durationMs,
  likeCount: likeCount,
  commentCount: commentCount,
  shareCount: shareCount,
  createdAt: createdAt ?? DateTime.utc(2026),
  updatedAt: updatedAt,
  publishedAt: publishedAt,
  contentVertical: contentVertical,
  recallPath: recallPath,
  supplySource: supplySource,
  intersectionReasons: intersectionReasons,
);
