// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../../../cloud/content/location/contract/error_permission_l10n_contract_test.dart' as source_test;

void main() {
  source_test.main();
}
