// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../components/object_page/intersection_target_navigator_test.dart' as source_0;

void main() {
  source_0.main();
}
