// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../components/object_page/interactive_intersection_text_test.dart' as source_test;

void main() {
  source_test.main();
}
