// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../components/pageflip/backward_partition_pixel_test.dart' as source_test;

void main() {
  source_test.main();
}
