// Code generated by generate_canonical_test_bridges.py. DO NOT EDIT.
package local_contract

import (
	"os/exec"
	"testing"
)

func TestCreateSemanticProjectionLocalContractTest(t *testing.T) {
	cmd := exec.Command(
		"go",
		"test",
		"../../../../../internal/application/post",
		"-run",
		"^(TestCreatePostProjectsPublishedSemanticMentions|TestCreatePostRejectsClientSuppliedRefsDivergingFromMentions|TestCreatePostRejectsPublishedMentionWithInvalidTargetRef)$",
		"-count=1",
	)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("source bridge failed for quwoquan_service/services/content-service/internal/application/post/create_semantic_projection_test.go: %v\n%s", err, output)
	}
}
