part of 'ui_text_constants.dart';

String _footprintTypeLabel(String type) =>
    const {
      'viewed': '看过',
      'liked': '赞过',
      'commented': '评论过',
      'shared': '转发过',
    }[type] ??
    type;

String _contentLabelForKey(String labelKey) {
  switch (labelKey) {
    case 'discovery_rail_moment':
      return UITextConstants.discoveryRailMoment;
    case 'discovery_rail_work':
      return UITextConstants.discoveryRailWorks;
    case 'creation_filter_all':
      return UITextConstants.creationFilterAll;
    case 'creation_filter_moment':
      return UITextConstants.creationFilterMoment;
    case 'creation_filter_work':
      return UITextConstants.creationFilterWork;
    case 'profile_tab_creations':
      return UITextConstants.profileTabCreations;
    case 'profile_tab_interaction':
      return UITextConstants.profileTabInteraction;
    case 'profile_tab_lifestyle':
      return UITextConstants.profileTabLifestyle;
    case 'homepage_tab_record':
      return UITextConstants.objectTabRecord;
    case 'homepage_tab_discussion':
      return UITextConstants.objectTabDiscussion;
    case 'homepage_tab_related_circles':
      return UITextConstants.objectTabRelatedCircles;
    case 'homepage_sub_all':
      return UITextConstants.creationSubAll;
    case 'homepage_sub_image':
      return UITextConstants.creationSubImage;
    case 'homepage_sub_video':
      return UITextConstants.creationSubVideo;
    case 'homepage_sub_article':
      return UITextConstants.creationSubArticle;
    case 'homepage_sub_campus_life':
      return UITextConstants.homepageSubCampusLife;
    case 'circle_tab_record':
      return UITextConstants.objectTabRecord;
    case 'circle_tab_discussion':
      return UITextConstants.objectTabDiscussion;
    case 'circle_tab_members':
      return UITextConstants.objectTabMembers;
    case 'circle_section_works':
      return UITextConstants.circleWorksTab;
    case 'circle_section_interaction':
      return UITextConstants.circleInteractionTab;
    case 'circle_section_chat':
      return UITextConstants.circleGroups;
    case 'circle_section_storage':
      return UITextConstants.circleAssetsTab;
    case 'lifestyle_sub_footprint':
      return UITextConstants.lifestyleSubFootprint;
    case 'lifestyle_sub_soul':
      return UITextConstants.lifestyleSubSoul;
    case 'lifestyle_sub_taste':
      return UITextConstants.lifestyleSubTaste;
    case 'lifestyle_sub_private':
      return UITextConstants.lifestyleSubPrivate;
    case 'creation_sub_all':
      return UITextConstants.creationSubAll;
    case 'creation_sub_micro':
      return UITextConstants.creationSubMicro;
    case 'creation_sub_image':
      return UITextConstants.creationSubImage;
    case 'creation_sub_video':
      return UITextConstants.creationSubVideo;
    case 'creation_sub_article':
      return UITextConstants.creationSubArticle;
    case 'creation_sub_text':
      return UITextConstants.creationSubText;
    case 'interaction_sub_all':
      return UITextConstants.interactionSubAll;
    case 'interaction_sub_likes':
      return UITextConstants.interactionSubLikes;
    case 'interaction_sub_comments':
      return UITextConstants.interactionSubComments;
    case 'interaction_sub_shares':
      return UITextConstants.interactionSubShares;
    case 'work_format_all':
      return UITextConstants.workFormatFilterAll;
    case 'work_format_image':
      return UITextConstants.workFormatFilterImage;
    case 'work_format_video':
      return UITextConstants.workFormatFilterVideo;
    case 'work_format_article':
      return UITextConstants.workFormatFilterArticle;
    case 'article_paper_theme_system':
      return UITextConstants.articlePaperThemeSystem;
    case 'article_paper_theme_dark_paper':
      return UITextConstants.articlePaperThemeDarkPaper;
    case 'article_paper_theme_cool_gray':
      return UITextConstants.articlePaperThemeCoolGray;
    case 'article_paper_theme_warm_black':
      return UITextConstants.articlePaperThemeWarmBlack;
    case 'article_paper_theme_ink_green':
      return UITextConstants.articlePaperThemeInkGreen;
    case 'article_paper_theme_deep_brown':
      return UITextConstants.articlePaperThemeDeepBrown;
    case 'share_template_moment_title':
      return UITextConstants.shareTemplateMomentTitle;
    case 'share_template_moment_subtitle':
      return UITextConstants.shareTemplateMomentSubtitle;
    case 'share_template_work_title':
      return UITextConstants.shareTemplateWorkTitle;
    case 'share_template_work_subtitle':
      return UITextConstants.shareTemplateWorkSubtitle;
    case 'tab_photo':
      return UITextConstants.discoveryTabPhoto;
    case 'tab_video':
      return UITextConstants.discoveryTabVideo;
    case 'tab_moment':
      return UITextConstants.discoveryTabMoment;
    case 'tab_article':
      return UITextConstants.discoveryTabArticle;
    default:
      return labelKey;
  }
}
