// Code generated by generate_canonical_test_bridges.py. DO NOT EDIT.
package local_contract

import (
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"testing"
)

func TestCommentMemoryStoreLocalContractTest(t *testing.T) {
	exists := func(path string) bool {
		info, err := os.Stat(path)
		return err == nil && info.IsDir()
	}
	repoRoot := func() string {
		_, filename, _, ok := runtime.Caller(0)
		if !ok {
			t.Fatal("cannot resolve bridge file path")
		}
		for dir := filepath.Dir(filename); ; dir = filepath.Dir(dir) {
			if exists(filepath.Join(dir, "quwoquan_service")) && exists(filepath.Join(dir, "quwoquan_ops")) {
				return dir
			}
			parent := filepath.Dir(dir)
			if parent == dir {
				t.Fatal("cannot locate quwoquan repo root")
			}
		}
		return ""
	}
	cmd := exec.Command(
		"go",
		"test",
		"../../../../../internal/infrastructure/persistence",
		"-run",
		"^(TestMemoryCommentReactionStore_ThreeStateDerivedCounts|TestMemoryCommentStore_CRUDAndAuthoritativeCounts|TestMemoryCommentStore_TopLevelCursorPagination|TestMemoryCommentStore_TopLevelSortModes)$",
		"-count=1",
	)
	cmd.Env = append(os.Environ(), "QWQ_OUTPUT_ROOT="+filepath.Join(repoRoot(), ".qwq_output"))
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("source bridge failed for quwoquan_service/services/content-service/internal/infrastructure/persistence/comment_memory_store_test.go: %v\n%s", err, output)
	}
}
