#!/usr/bin/env python3
"""从中性 Reviewer executor 生成 Cursor 与 Codex harness adapter。

中性源只声明执行器名称、描述、访问级别与正文。Cursor Markdown 和 Codex
TOML 都是可重建的薄适配器，不拥有 Review 语义。

用法：
    python3 quwoquan_ops/tools/generate_agent_adapters.py
    python3 quwoquan_ops/tools/generate_agent_adapters.py --check
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
CONTRACT_REL = Path("quwoquan_ops/policies/agent_governance_contract.yaml")
SOURCE_REL = Path(".agents/skills/review/references/reviewer-executor.md")
CURSOR_TARGET_REL = Path(".cursor/agents/reviewer.md")
CODEX_TARGET_REL = Path(".codex/agents/reviewer.toml")

GENERATOR_REL = "quwoquan_ops/tools/generate_agent_adapters.py"
FRONTMATTER_RE = re.compile(r"\A---\n(?P<fm>.*?)\n---\n(?P<body>.*)\Z", re.S)
ALLOWED_FIELDS = {"name", "description", "access"}
ACCESS_TO_CURSOR_READONLY = {"read-only": True, "workspace-write": False}
ACCESS_TO_CODEX_SANDBOX = {
    "read-only": "read-only",
    "workspace-write": "workspace-write",
}


def _validate_projection_contract(repo_root: Path) -> None:
    contract_path = repo_root / CONTRACT_REL
    try:
        contract = yaml.safe_load(contract_path.read_text(encoding="utf-8")) or {}
    except (OSError, yaml.YAMLError) as error:
        raise ValueError(f"{CONTRACT_REL.as_posix()}: 无法读取（{error}）") from error
    projection = contract.get("tracked_projections") or {}
    expected = {
        "authoring_source": SOURCE_REL.as_posix(),
        "generator": GENERATOR_REL,
        "outputs": [CURSOR_TARGET_REL.as_posix(), CODEX_TARGET_REL.as_posix()],
        "manual_edit": "forbidden",
    }
    if projection != expected:
        raise ValueError(
            f"{CONTRACT_REL.as_posix()}#tracked_projections 与生成器入口不一致"
        )


def _parse_source(text: str, rel: str) -> tuple[dict[str, str], str]:
    match = FRONTMATTER_RE.match(text)
    if match is None:
        raise ValueError(f"{rel}: 缺少 YAML frontmatter")
    try:
        parsed = yaml.safe_load(match.group("fm"))
    except yaml.YAMLError as error:
        reason = str(error).splitlines()[0]
        raise ValueError(f"{rel}: frontmatter 不是合法 YAML（{reason}）") from error
    if not isinstance(parsed, dict):
        raise ValueError(f"{rel}: frontmatter 不是键值映射")

    unknown = sorted(str(key) for key in parsed if str(key) not in ALLOWED_FIELDS)
    if unknown:
        raise ValueError(f"{rel}: 含非中性字段 {', '.join(unknown)}")

    fields = {str(key): "" if value is None else str(value) for key, value in parsed.items()}
    for required in ("name", "description", "access"):
        if not fields.get(required):
            raise ValueError(f"{rel}: frontmatter 缺 {required}")
    if fields["access"] not in ACCESS_TO_CURSOR_READONLY:
        allowed = ", ".join(sorted(ACCESS_TO_CURSOR_READONLY))
        raise ValueError(f"{rel}: access={fields['access']} 非法，只允许 {allowed}")

    body = match.group("body").strip()
    if not body:
        raise ValueError(f"{rel}: 正文为空")
    return fields, body


def _toml_basic_string(value: str) -> str:
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\t", "\\t")
    )
    return f'"{escaped}"'


def _toml_multiline_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
    return f'"""\n{escaped}\n"""'


def render_cursor(fields: dict[str, str], body: str) -> str:
    readonly = "true" if ACCESS_TO_CURSOR_READONLY[fields["access"]] else "false"
    description = json.dumps(fields["description"], ensure_ascii=False)
    return "\n".join(
        [
            "---",
            f"# Generated by {GENERATOR_REL} from {SOURCE_REL.as_posix()}. DO NOT EDIT.",
            f"name: {fields['name']}",
            f"description: {description}",
            f"readonly: {readonly}",
            "---",
            "",
            body,
            "",
        ]
    )


def render_codex(fields: dict[str, str], body: str) -> str:
    source = SOURCE_REL.as_posix()
    return "\n".join(
        [
            f"# Generated by {GENERATOR_REL} from {source}. DO NOT EDIT.",
            "",
            f"name = {_toml_basic_string(fields['name'])}",
            f"description = {_toml_basic_string(fields['description'])}",
            "sandbox_mode = "
            + _toml_basic_string(ACCESS_TO_CODEX_SANDBOX[fields["access"]]),
            "",
            f"developer_instructions = {_toml_multiline_string(body)}",
            "",
        ]
    )


def expected_outputs(repo_root: Path) -> dict[Path, str]:
    _validate_projection_contract(repo_root)
    source = repo_root / SOURCE_REL
    if not source.is_file():
        raise ValueError(f"{SOURCE_REL.as_posix()}: 中性 Reviewer executor 不存在")
    fields, body = _parse_source(
        source.read_text(encoding="utf-8"), SOURCE_REL.as_posix()
    )
    if fields["name"] != "reviewer":
        raise ValueError(
            f"{SOURCE_REL.as_posix()}: name 必须为 reviewer，实际为 {fields['name']}"
        )
    return {
        CURSOR_TARGET_REL: render_cursor(fields, body),
        CODEX_TARGET_REL: render_codex(fields, body),
    }


def _orphan_adapters(repo_root: Path, expected: set[Path]) -> list[Path]:
    candidates: list[Path] = []
    for directory, suffix in ((Path(".cursor/agents"), "*.md"), (Path(".codex/agents"), "*.toml")):
        absolute = repo_root / directory
        if absolute.is_dir():
            candidates.extend(path.relative_to(repo_root) for path in absolute.glob(suffix))
    return sorted(path for path in candidates if path not in expected)


def sync(repo_root: Path, *, check: bool) -> list[str]:
    outputs = expected_outputs(repo_root)
    issues: list[str] = []

    for relative, rendered in outputs.items():
        target = repo_root / relative
        current = target.read_text(encoding="utf-8") if target.is_file() else None
        if current == rendered:
            continue
        if check:
            reason = "缺失" if current is None else "与中性源不一致"
            issues.append(f"{relative.as_posix()}: {reason}")
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(rendered, encoding="utf-8")
        print(f"[generate-agent-adapters] wrote {relative.as_posix()}")

    for relative in _orphan_adapters(repo_root, set(outputs)):
        if check:
            issues.append(f"{relative.as_posix()}: 无中性源的孤儿 adapter")
            continue
        (repo_root / relative).unlink()
        print(f"[generate-agent-adapters] removed {relative.as_posix()}")

    return issues


def main(argv: list[str] | None = None, *, repo_root: Path = REPO_ROOT) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="只校验，不写盘")
    args = parser.parse_args(argv)

    try:
        issues = sync(repo_root, check=args.check)
    except ValueError as error:
        print(f"[generate-agent-adapters] FAIL: {error}", file=sys.stderr)
        return 1

    if issues:
        print("[generate-agent-adapters] FAIL: adapter 不是最新", file=sys.stderr)
        for issue in issues:
            print(f"  - {issue}", file=sys.stderr)
        print(f"  修复：python3 {GENERATOR_REL}", file=sys.stderr)
        return 1

    print("[generate-agent-adapters] OK: Cursor/Codex Reviewer adapter 已同步")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
