// Code generated by generate_canonical_test_bridges.py. DO NOT EDIT.
package local_contract

import (
	"os/exec"
	"testing"
)

func TestAuthorImpactTravelLocalContractTest(t *testing.T) {
	cmd := exec.Command(
		"go",
		"test",
		"../../../../../internal/application/authorimpact",
		"-run",
		"^(TestDecorateAuthorImpact_RespectsPreseededCountTarget|TestDecorateAuthorImpact_TravelCountTargetFromAggregatedTag|TestTravelImpactObjectKindForTag)$",
		"-count=1",
	)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("source bridge failed for quwoquan_service/services/content-service/internal/application/authorimpact/author_impact_travel_test.go: %v\n%s", err, output)
	}
}
