// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../../cloud/services/assistant/assistant_creation_suggest_repository_test.dart' as source_test;

void main() {
  source_test.main();
}
