"""解析并验证 canonical target contract 摘要（逐字来自原 ``control_plane.py``）。"""

from __future__ import annotations

import hashlib
from collections.abc import Mapping
from pathlib import Path
from typing import Any

from quwoquan_ops.migrations.travel_to_gathering.control_plane_lib.codec import (
    _file_digest,
    _load_object,
    canonical_digest,
)
from quwoquan_ops.migrations.travel_to_gathering.control_plane_lib.constants import (
    CANONICAL_TARGET_OBJECT_IDS,
    HEX_DIGEST_RE,
    REQUIRED_TARGET_OPERATION_IDS,
    ROOT,
    TARGET_CONTRACT_BINDINGS,
    TARGET_CONTRACT_GRAPH,
    TARGET_GENERATED_MODELS,
    MigrationControlError,
    TargetContractBinding,
)


def _assert_generated_model_matches_fields(
    generated_text: str,
    fields_contract: Mapping[str, Any],
) -> None:
    if not generated_text.startswith(
        "// Code generated by internal/metadata/codegen. DO NOT EDIT."
    ):
        raise MigrationControlError(
            "TARGET_CONTRACT_DIGEST_MISSING",
            "canonical generated Gathering model header is missing",
        )
    root_fields = fields_contract.get("fields")
    if not isinstance(root_fields, list) or not root_fields:
        raise MigrationControlError(
            "TARGET_CONTRACT_DIGEST_MISSING",
            "canonical Gathering fields contract is empty",
        )
    missing: list[str] = []
    for field in root_fields:
        if not isinstance(field, dict):
            continue
        name = str(field.get("name") or "")
        if not name:
            continue
        bson_name = name
        if f'bson:"{bson_name}"' not in generated_text:
            missing.append(name)
    if missing:
        raise MigrationControlError(
            "TARGET_CONTRACT_DIGEST_MISMATCH",
            "canonical generated Gathering model is stale for: "
            + ", ".join(sorted(missing)),
        )


def resolve_target_contract(
    repository_root: Path = ROOT,
) -> TargetContractBinding:
    """解析并验证 Circle/Chat/Content canonical target contract 摘要。"""

    graph_path = repository_root / TARGET_CONTRACT_GRAPH
    if not graph_path.is_file():
        raise MigrationControlError(
            "TARGET_CONTRACT_DIGEST_MISSING",
            "canonical generated ContractGraph is missing",
        )
    graph = _load_object(graph_path, label="ContractGraph")
    sources = graph.get("sources")
    if not isinstance(sources, list):
        raise MigrationControlError(
            "TARGET_CONTRACT_DIGEST_MISSING",
            "ContractGraph has no canonical source digest set",
        )
    source_by_path: dict[str, str] = {}
    for source in sources:
        if not isinstance(source, dict):
            continue
        path = str(source.get("path") or "")
        digest = str(source.get("sha256") or "")
        if path and HEX_DIGEST_RE.fullmatch(digest):
            source_by_path[path] = digest

    selected_sources: list[dict[str, str]] = []
    contract_dirs: dict[str, Path] = {}
    for object_id, graph_prefix, contract_relative, filenames in (
        TARGET_CONTRACT_BINDINGS
    ):
        contract_dir = repository_root / contract_relative
        contract_dirs[object_id] = contract_dir
        for filename in filenames:
            graph_source = f"{graph_prefix}/{filename}"
            expected = source_by_path.get(graph_source)
            contract_path = contract_dir / filename
            if expected is None or not contract_path.is_file():
                raise MigrationControlError(
                    "TARGET_CONTRACT_DIGEST_MISSING",
                    f"canonical target source digest is missing: {graph_source}",
                )
            actual = hashlib.sha256(contract_path.read_bytes()).hexdigest()
            if actual != expected:
                raise MigrationControlError(
                    "TARGET_CONTRACT_DIGEST_MISMATCH",
                    f"canonical target source digest drift: {graph_source}",
                )
            selected_sources.append({"path": graph_source, "sha256": expected})

    objects = graph.get("objects")
    if not isinstance(objects, list):
        objects = []
    target_objects_by_id: dict[str, dict[str, Any]] = {}
    for object_id in CANONICAL_TARGET_OBJECT_IDS:
        matches = [
            value
            for value in objects
            if isinstance(value, dict) and value.get("id") == object_id
        ]
        if len(matches) != 1:
            raise MigrationControlError(
                "TARGET_CONTRACT_DIGEST_MISSING",
                f"ContractGraph must contain exactly one {object_id} object",
            )
        target_objects_by_id[object_id] = matches[0]
    if set(target_objects_by_id) != set(CANONICAL_TARGET_OBJECT_IDS):
        raise MigrationControlError(
            "TARGET_CONTRACT_DIGEST_MISSING",
            "ContractGraph canonical migration targets are incomplete",
        )
    operations = graph.get("operations")
    if not isinstance(operations, list):
        operations = []
    target_operations = sorted(
        (
            value
            for value in operations
            if isinstance(value, dict)
            and value.get("objectId") in CANONICAL_TARGET_OBJECT_IDS
        ),
        key=lambda value: str(value.get("id") or ""),
    )
    operation_ids = {
        str(value.get("id") or "")
        for value in target_operations
        if str(value.get("id") or "")
    }
    missing_operations = sorted(set(REQUIRED_TARGET_OPERATION_IDS) - operation_ids)
    if missing_operations:
        raise MigrationControlError(
            "TARGET_CONTRACT_DIGEST_MISSING",
            "ContractGraph canonical migration operations are missing: "
            + ", ".join(missing_operations),
        )

    fields_contract = _load_object(
        contract_dirs["circle.gathering"] / "fields.yaml",
        label="Gathering fields contract",
    )
    plan_fields_contract = _load_object(
        contract_dirs["circle.gathering_plan"] / "fields.yaml",
        label="GatheringPlan fields contract",
    )
    fields_by_object = {
        "circle.gathering": fields_contract,
        "circle.gathering_plan": plan_fields_contract,
    }
    generated_artifacts: list[dict[str, str]] = []
    for object_id, relative_path in TARGET_GENERATED_MODELS:
        generated_path = repository_root / relative_path
        if not generated_path.is_file():
            raise MigrationControlError(
                "TARGET_CONTRACT_DIGEST_MISSING",
                f"canonical generated model is missing: {object_id}",
            )
        generated_text = generated_path.read_text(encoding="utf-8")
        _assert_generated_model_matches_fields(
            generated_text,
            fields_by_object[object_id],
        )
        generated_artifacts.append(
            {
                "objectId": object_id,
                "path": relative_path.as_posix(),
                "digest": _file_digest(generated_path),
            }
        )
    generated_artifact_digest = canonical_digest(generated_artifacts)
    projection = {
        "objects": [
            target_objects_by_id[object_id]
            for object_id in CANONICAL_TARGET_OBJECT_IDS
        ],
        "operations": target_operations,
        "sources": sorted(selected_sources, key=lambda value: value["path"]),
        "generatedArtifacts": generated_artifacts,
    }
    return TargetContractBinding(
        digest=canonical_digest(projection),
        graph_digest=_file_digest(graph_path),
        generated_artifact_digest=generated_artifact_digest,
        sources=tuple(sorted(selected_sources, key=lambda value: value["path"])),
        fields_contract=fields_contract,
        plan_fields_contract=plan_fields_contract,
        object_ids=tuple(CANONICAL_TARGET_OBJECT_IDS),
        operation_ids=tuple(sorted(operation_ids)),
    )
