// Code generated by generate_canonical_test_bridges.py. DO NOT EDIT.
package local_contract

import (
	"os/exec"
	"testing"
)

func TestSearchSignalConsumerLocalContractTest(t *testing.T) {
	cmd := exec.Command(
		"go",
		"test",
		"../../../../../internal/infrastructure/recommendation",
		"-run",
		"^(TestSearchSignalConsumerProjectsAndAcks)$",
		"-count=1",
	)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("source bridge failed for quwoquan_service/services/content-service/internal/infrastructure/recommendation/search_signal_consumer_test.go: %v\n%s", err, output)
	}
}
