// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../../assistant/observability/logging/app_perf_probe_web_test.dart' as source_0;

void main() {
  source_0.main();
}
