// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../../assistant/observability/logging/app_log_service_web_test.dart' as source_test;

void main() {
  source_test.main();
}
