part of 'user_profile_repository.dart';

List<Map<String, dynamic>> _mockInteractionReceivedWiresFor(String userId) {
  if (_isContractFixtureUser(userId)) {
    return const <Map<String, dynamic>>[];
  }
  return <Map<String, dynamic>>[
    _interactionWire(
      activityId: 'mock-like-image-u1-${userId}_p1',
      activityType: 'like',
      direction: 'received',
      actorSubAccountId: 'u1',
      actorDisplayName: '你的皮炎有点辣',
      actorAvatarUrl:
          'media/avatar/s/mock/seed/u_1599566150163-29194dcaad36/v1/avatar.jpg',
      targetSubAccountId: userId,
      targetContentId: '${userId}_p1',
      targetContentType: 'image',
      targetContentSummary: '光影的节奏',
      displaySubAccountId: 'u1',
      displayName: '你的皮炎有点辣',
      displayAvatarUrl:
          'media/avatar/s/mock/seed/u_1599566150163-29194dcaad36/v1/avatar.jpg',
      primaryText: '点赞了你的记录',
      previewMediaKind: 'image',
      previewImageUrl:
          'media/image/s/mock/seed/p_1647956450271-2ff54205bebf/v1/image.jpg',
      previewText: '光影的节奏',
      filterKeys: const <String>['likes'],
      createdAt: '2025-12-21T09:30:00Z',
    ),
    _interactionWire(
      activityId: 'mock-view-profile-u2-$userId',
      activityType: 'view',
      direction: 'received',
      actorSubAccountId: 'u2',
      actorDisplayName: '海边的风',
      actorAvatarUrl:
          'media/avatar/s/mock/seed/u_1679823410021-6d22f8c1f3/v1/avatar.jpg',
      targetSubAccountId: userId,
      targetContentId: userId,
      targetContentType: 'profile',
      targetContentSummary: '主页访客',
      displaySubAccountId: 'u2',
      displayName: '海边的风',
      displayAvatarUrl:
          'media/avatar/s/mock/seed/u_1679823410021-6d22f8c1f3/v1/avatar.jpg',
      primaryText: '看过你的主页',
      previewMediaKind: 'text',
      previewText: '主页访客',
      previewRouteId: 'userProfile',
      filterKeys: const <String>['views'],
      createdAt: '2025-12-21T09:10:00Z',
    ),
    _interactionWire(
      activityId: 'mock-comment-image-u6-${userId}_p3',
      activityType: 'comment',
      direction: 'received',
      actorSubAccountId: 'u6',
      actorDisplayName: '松间小路',
      actorAvatarUrl:
          'media/avatar/s/mock/seed/u_1683323410021-a07a1ef39e/v1/avatar.jpg',
      targetSubAccountId: userId,
      targetContentId: '${userId}_p3',
      targetContentType: 'image',
      targetContentSummary: '构图很稳，光也温柔',
      displaySubAccountId: 'u6',
      displayName: '松间小路',
      displayAvatarUrl:
          'media/avatar/s/mock/seed/u_1683323410021-a07a1ef39e/v1/avatar.jpg',
      primaryText: '评论了你的记录：构图很稳，光也温柔',
      previewMediaKind: 'image',
      previewImageUrl:
          'media/image/s/mock/seed/p_1506905925346-21bda4d32df4/v1/image.jpg',
      previewText: '屋檐下的黄昏',
      filterKeys: const <String>['comments'],
      commentKind: 'comment',
      createdAt: '2025-12-21T08:40:00Z',
    ),
    _interactionWire(
      activityId: 'mock-comment-video-u7-${userId}_v2',
      activityType: 'comment',
      direction: 'received',
      actorSubAccountId: 'u7',
      actorDisplayName: '山海来信',
      actorAvatarUrl:
          'media/avatar/s/mock/seed/u_1684423410021-b19cc13e48/v1/avatar.jpg',
      targetSubAccountId: userId,
      targetContentId: '${userId}_v2',
      targetContentType: 'video',
      targetContentSummary: '这一段转场好自然',
      displaySubAccountId: 'u7',
      displayName: '山海来信',
      displayAvatarUrl:
          'media/avatar/s/mock/seed/u_1684423410021-b19cc13e48/v1/avatar.jpg',
      primaryText: '评论了你的记录：这一段转场好自然',
      previewMediaKind: 'video',
      previewImageUrl:
          'media/image/s/mock/seed/p_1646034296147-d8ed3aace9a4/v1/image.jpg',
      previewText: '雨后的山路',
      filterKeys: const <String>['comments'],
      commentKind: 'comment',
      createdAt: '2025-12-21T08:30:00Z',
    ),
    _interactionWire(
      activityId: 'mock-comment-article-u8-${userId}_a2',
      activityType: 'comment',
      direction: 'received',
      actorSubAccountId: 'u8',
      actorDisplayName: '纸上旅行',
      actorAvatarUrl:
          'media/avatar/s/mock/seed/u_1685523410021-ae81127c98/v1/avatar.jpg',
      targetSubAccountId: userId,
      targetContentId: '${userId}_a2',
      targetContentType: 'article',
      targetContentSummary: '读完想再走一次这条街',
      displaySubAccountId: 'u8',
      displayName: '纸上旅行',
      displayAvatarUrl:
          'media/avatar/s/mock/seed/u_1685523410021-ae81127c98/v1/avatar.jpg',
      primaryText: '评论了你的记录：读完想再走一次这条街',
      previewMediaKind: 'text',
      previewText: '午后街角路线笔记',
      filterKeys: const <String>['comments'],
      commentKind: 'comment',
      createdAt: '2025-12-21T08:20:00Z',
    ),
    _interactionWire(
      activityId: 'mock-comment-note-u9-${userId}_n2',
      activityType: 'comment',
      direction: 'received',
      actorSubAccountId: 'u9',
      actorDisplayName: '一颗橘子',
      actorAvatarUrl:
          'media/avatar/s/mock/seed/u_1686623410021-b736d21d10/v1/avatar.jpg',
      targetSubAccountId: userId,
      targetContentId: '${userId}_n2',
      targetContentType: 'micro',
      targetContentSummary: '这句话太有画面了',
      displaySubAccountId: 'u9',
      displayName: '一颗橘子',
      displayAvatarUrl:
          'media/avatar/s/mock/seed/u_1686623410021-b736d21d10/v1/avatar.jpg',
      primaryText: '评论了你的记录：这句话太有画面了',
      previewMediaKind: 'text',
      previewText: '风吹过露台的时候',
      filterKeys: const <String>['comments'],
      commentKind: 'comment',
      createdAt: '2025-12-21T08:10:00Z',
    ),
    _interactionWire(
      activityId: 'mock-reply-comment-u10-${userId}_c2',
      activityType: 'comment',
      direction: 'received',
      actorSubAccountId: 'u10',
      actorDisplayName: '胶片小店',
      actorAvatarUrl:
          'media/avatar/s/mock/seed/u_1687723410021-878c20ed3a/v1/avatar.jpg',
      targetSubAccountId: userId,
      targetContentId: '${userId}_p4',
      targetContentType: 'comment',
      targetContentSummary: '我也喜欢这个色调',
      displaySubAccountId: 'u10',
      displayName: '胶片小店',
      displayAvatarUrl:
          'media/avatar/s/mock/seed/u_1687723410021-878c20ed3a/v1/avatar.jpg',
      primaryText: '回复了你：我也喜欢这个色调',
      contextText: '你说：这组颜色像旧电影',
      previewMediaKind: 'image',
      previewImageUrl:
          'media/image/s/mock/seed/p_1627216661750-c59a4cea849c/v1/image.jpg',
      previewText: '旧巷口',
      filterKeys: const <String>['comments'],
      commentKind: 'reply',
      createdAt: '2025-12-21T08:00:00Z',
    ),
    _interactionWire(
      activityId: 'mock-share-image-u11-${userId}_p5',
      activityType: 'share',
      direction: 'received',
      actorSubAccountId: 'u11',
      actorDisplayName: '远方邮差',
      actorAvatarUrl:
          'media/avatar/s/mock/seed/u_1688823410021-a25ae178d1/v1/avatar.jpg',
      targetSubAccountId: userId,
      targetContentId: '${userId}_p5',
      targetContentType: 'image',
      targetContentSummary: '城市转角',
      displaySubAccountId: 'u11',
      displayName: '远方邮差',
      displayAvatarUrl:
          'media/avatar/s/mock/seed/u_1688823410021-a25ae178d1/v1/avatar.jpg',
      primaryText: '转发了你的记录：想给朋友也看看这张',
      previewMediaKind: 'image',
      previewImageUrl:
          'media/image/s/mock/seed/p_1501785888041-af3ef285b470/v1/image.jpg',
      previewText: '城市转角',
      filterKeys: const <String>['shares'],
      createdAt: '2025-12-21T07:50:00Z',
    ),
    _interactionWire(
      activityId: 'mock-deleted-u12-${userId}_gone',
      activityType: 'comment',
      direction: 'received',
      actorSubAccountId: 'u12',
      actorDisplayName: '看云的人',
      actorAvatarUrl:
          'media/avatar/s/mock/seed/u_1689923410021-4d774a1f7e/v1/avatar.jpg',
      targetSubAccountId: userId,
      targetContentId: '${userId}_gone',
      targetContentType: 'micro',
      targetContentSummary: '',
      displaySubAccountId: 'u12',
      displayName: '看云的人',
      displayAvatarUrl:
          'media/avatar/s/mock/seed/u_1689923410021-4d774a1f7e/v1/avatar.jpg',
      primaryText: '评论了你的记录：这条我也有共鸣',
      previewMediaKind: 'none',
      previewUnavailable: true,
      previewText: '',
      filterKeys: const <String>['comments'],
      commentKind: 'comment',
      createdAt: '2025-12-21T07:40:00Z',
    ),
  ];
}
