// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../../cloud/services/content/intersection_inbox_synthesis_test.dart' as source_test;

void main() {
  source_test.main();
}
