// Code generated by internal/metadata/codegen. DO NOT EDIT.
package event

// Event type constants for Post.
const (
	PostPublished       = "PostPublished"
	PostUpdated         = "PostUpdated"
	PostSettingsUpdated = "PostSettingsUpdated"
	PostPromotedToWork  = "PostPromotedToWork"
	PostDeleted         = "PostDeleted"
	PostQuoted          = "PostQuoted"
	ContentViewed       = "ContentViewed"
	PostPrivacyRedacted = "PostPrivacyRedacted"
	PostPurged          = "PostPurged"
	PostImported        = "PostImported"
	PostTombstoned      = "PostTombstoned"
)
