overrides:
  sys.integration-service.account_security_authority.base_url: http://user-service:18081
  sys.integration-service.account_security_authority.timeout_ms: 300
  sys.integration-service.redis.general.addr: ${REDIS_ADDR}
  sys.integration-service.redis.general.tls: true
secretRefs:
  sys.integration-service.mongodb.uri: INTEGRATION_MONGO_URI
externalBindings:
  identity.sms.otp:
    state: enabled
    adapter: ext.sms.aliyun
    endpointRef: environment_binding:integration.sms
  integration.push.delivery:
    state: enabled
    adapter: ext.push.dispatch
    endpointRef: environment_binding:integration.push
  integration.location.lookup:
    state: enabled
    adapter: ext.map.baidu
    endpointRef: environment_binding:integration.location
  location.poi.search:
    state: not_required
  location.route.read:
    state: not_required
