// Code generated by generate_canonical_test_bridges.py. DO NOT EDIT.
package local_contract

import (
	"os/exec"
	"testing"
)

func TestToolCoordinatorLocalContractTest(t *testing.T) {
	cmd := exec.Command(
		"go",
		"test",
		"../../../../internal/application",
		"-run",
		"^(TestDefaultToolCoordinatorCreatesDeviceActionProposal|TestDefaultToolCoordinatorExecutesCloudToolAdapters|TestDefaultToolCoordinatorMapsToolValidationFailures)$",
		"-count=1",
	)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("source bridge failed for quwoquan_service/services/assistant-service/internal/application/tool_coordinator_test.go: %v\n%s", err, output)
	}
}
