// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../ui/assistant/assistant_structured_run_response_read_view_test.dart' as source_test;

void main() {
  source_test.main();
}
