// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../ui/assistant/personal_assistant_stream_controller_test.dart' as source_0;

void main() {
  source_0.main();
}
