import { CAPABILITY_IDS, NODE_REGISTRY, validateSemanticDocumentEnvelope, type DocumentEnvelope } from '../generated/semanticDocument.js';

const headerKeys=['assets','canonicalDigest','canonicalizationVersion','dialectVersion','losses','offsetEncoding','policyVersion','requiredCapabilities','schemaVersion','semanticFingerprint','sourceMap'] as const;
const nodeKeys=['attributes','children','diagnostics','disposition','inlines','losses','nodeId','policyVersion','rawSlice','rawSliceFingerprint','requiredCapabilities','semanticFingerprint','sourceAnchor'] as const;

function sha256(text:string):string {
  const bytes=new TextEncoder().encode(text), bitLength=bytes.length*8, size=((bytes.length+9+63)>>6)<<6, data=new Uint8Array(size); data.set(bytes); data[bytes.length]=0x80; const view=new DataView(data.buffer); view.setUint32(size-4,bitLength>>>0); view.setUint32(size-8,Math.floor(bitLength/0x100000000));
  const k=[0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2];
  const h=[0x6a09e667,0xbb67ae85,0x3c6ef372,0xa54ff53a,0x510e527f,0x9b05688c,0x1f83d9ab,0x5be0cd19], w=new Uint32Array(64), r=(x:number,n:number)=>(x>>>n)|(x<<(32-n));
  for(let o=0;o<size;o+=64){for(let i=0;i<16;i++)w[i]=view.getUint32(o+i*4);for(let i=16;i<64;i++){const a=w[i-15],b=w[i-2],s0=r(a,7)^r(a,18)^(a>>>3),s1=r(b,17)^r(b,19)^(b>>>10);w[i]=(w[i-16]+s0+w[i-7]+s1)>>>0}let [a,b,c,d,e,f,g,q]=h;for(let i=0;i<64;i++){const s1=r(e,6)^r(e,11)^r(e,25),ch=(e&f)^(~e&g),t1=(q+s1+ch+k[i]+w[i])>>>0,s0=r(a,2)^r(a,13)^r(a,22),maj=(a&b)^(a&c)^(b&c),t2=(s0+maj)>>>0;q=g;g=f;f=e;e=(d+t1)>>>0;d=c;c=b;b=a;a=(t1+t2)>>>0}for(let i=0;i<8;i++)h[i]=(h[i]+[a,b,c,d,e,f,g,q][i])>>>0}return h.map(v=>v.toString(16).padStart(8,'0')).join('');
}
export class CanonicalMarkdownError extends Error {}
function normalized(v:unknown):unknown { if(typeof v==='string')return v.normalize('NFC');if(v===null||typeof v==='boolean')return v;if(typeof v==='number'){if(!Number.isFinite(v))throw new CanonicalMarkdownError('SEMANTIC_DOCUMENT.INVALID.CANONICAL_NUMBER');return v}if(Array.isArray(v))return v.map(normalized);if(typeof v==='object'){const out:Record<string,unknown>={};for(const k of Object.keys(v as object).sort())out[k.normalize('NFC')]=normalized((v as Record<string,unknown>)[k]);return out}throw new CanonicalMarkdownError('SEMANTIC_DOCUMENT.INVALID.FIELD_TYPE') }
export function canonicalJson(v:unknown):string{return JSON.stringify(normalized(v))}
function digest(v:Record<string,unknown>, excluded:Set<string>):string { const m:Record<string,unknown>={};for(const k of Object.keys(v))if(!excluded.has(k))m[k]=v[k];return sha256(canonicalJson(m)) }
function matches(v:unknown,a:string){return v===a||v==='sha256:'+a}
function nodeText(n:Record<string,unknown>):string { const a=n.attributes;if(a&&typeof a==='object')for(const k of ['plainText','text','caption']){const v=(a as Record<string,unknown>)[k];if(typeof v==='string'&&v)return v.replace(/\r\n?/g,'\n')}return '' }
function reviewBody(n:Record<string,unknown>):string {const text=nodeText(n),a=(n.attributes??{}) as Record<string,unknown>;switch(n.kind){case'documentTitle':return '# '+text;case'heading':return '#'.repeat(Math.max(2,Math.min(6,Number(a.level??2))))+' '+text;case'paragraph':return text;case'blockquote':return '> '+text.replace(/\n/g,'\n> ');case'codeBlock':return '```'+String(a.language??'')+'\n'+text+'\n```';case'preformatted':return '    '+text.replace(/\n/g,'\n    ');case'divider':return '---';case'listItem':return (a.listKind==='ordered'?'1. ':'- ')+text;default:return text}}
function renderableUnsafe(text:string){const l=text.toLowerCase();return /<\s*(script|style|iframe|object|embed|form|input|button|meta|link)(?:\s|>|\/)/.test(l)||/\bon[a-z]+\s*=|\bsrcdoc\s*=|(?:javascript|data)\s*:/.test(l)}
function validate(v:Record<string,unknown>){const r=validateSemanticDocumentEnvelope(v,new Set(CAPABILITY_IDS));if(r.code!=='ok')throw new CanonicalMarkdownError(`${r.code}:${r.detail}`);if((v.nodes as Record<string,unknown>[]).some(n=>n.kind==='unsupportedOpaque'))throw new CanonicalMarkdownError('SEMANTIC_DOCUMENT.UNSUPPORTED_OPAQUE.PUBLISH_FORBIDDEN');if(!matches(v.semanticFingerprint,digest(v,new Set(['semanticFingerprint','canonicalDigest']))))throw new CanonicalMarkdownError('SEMANTIC_DOCUMENT.INVALID.SEMANTIC_FINGERPRINT');if(!matches(v.canonicalDigest,digest(v,new Set(['canonicalDigest']))))throw new CanonicalMarkdownError('SEMANTIC_DOCUMENT.INVALID.CANONICAL_DIGEST')}
export function serializeEnvelope(envelope:DocumentEnvelope):string {const v=normalized(envelope) as Record<string,unknown>;validate(v);const h:Object={};for(const k of headerKeys)(h as Record<string,unknown>)[k]=v[k];const blocks:string[]=[];for(const n of v.nodes as Record<string,unknown>[]){if(!(String(n.kind) in NODE_REGISTRY))throw new CanonicalMarkdownError('SEMANTIC_DOCUMENT.UNSUPPORTED.NODE');const m:Record<string,unknown>={};for(const k of nodeKeys)m[k]=n[k]??null;const body=reviewBody(n);if(renderableUnsafe(body))throw new CanonicalMarkdownError('SEMANTIC_DOCUMENT.UNSAFE.RAW_HTML');blocks.push(`:::qwq-meta ${n.kind} ${canonicalJson(m)}\n\n${body}`)}return `---\n${canonicalJson(h)}\n---\n\n${blocks.join('\n\n')}\n`}
function exactKeys(v:Record<string,unknown>,keys:readonly string[]){return canonicalJson(Object.keys(v).sort())===canonicalJson([...keys].sort())}
export function parseCanonicalMarkdown(markdown:string):DocumentEnvelope {if(markdown.includes('\r')||!markdown.endsWith('\n'))throw new CanonicalMarkdownError('SEMANTIC_DOCUMENT.INVALID.CANONICAL_LINE_ENDING');const lines=markdown.slice(0,-1).split('\n');if(lines.length<5||lines[0]!=='---'||lines[2]!=='---'||lines[3]!=='')throw new CanonicalMarkdownError('SEMANTIC_DOCUMENT.INVALID.FRONTMATTER');let h:Record<string,unknown>;try{h=JSON.parse(lines[1])}catch{throw new CanonicalMarkdownError('SEMANTIC_DOCUMENT.INVALID.FRONTMATTER')}if(!exactKeys(h,headerKeys)||canonicalJson(h)!==lines[1])throw new CanonicalMarkdownError('SEMANTIC_DOCUMENT.INVALID.CANONICAL_FRONTMATTER');const nodes:Record<string,unknown>[]=[];for(let i=4;i<lines.length;){if(!lines[i].startsWith(':::qwq-meta '))throw new CanonicalMarkdownError('SEMANTIC_DOCUMENT.INVALID.METADATA_BINDING');const at=lines[i].indexOf(' ',12),kind=lines[i].slice(12,at),payload=lines[i].slice(at+1);let m:Record<string,unknown>;try{m=JSON.parse(payload)}catch{throw new CanonicalMarkdownError('SEMANTIC_DOCUMENT.INVALID.DIRECTIVE_ATTRIBUTE')}if(!exactKeys(m,nodeKeys)||canonicalJson(m)!==payload||lines[i+1]!=='')throw new CanonicalMarkdownError('SEMANTIC_DOCUMENT.INVALID.DIRECTIVE_ATTRIBUTE');const n={kind,...m};i+=2;const body:string[]=[];while(i<lines.length&&!lines[i].startsWith(':::qwq-meta '))body.push(lines[i++]);if(i<lines.length&&body.at(-1)==='')body.pop();const text=body.join('\n');if(text!==reviewBody(n)||renderableUnsafe(text))throw new CanonicalMarkdownError('SEMANTIC_DOCUMENT.INVALID.METADATA_BINDING');nodes.push(n)}const envelope={...h,nodes} as unknown as DocumentEnvelope;validate(envelope as unknown as Record<string,unknown>);if(serializeEnvelope(envelope)!==markdown)throw new CanonicalMarkdownError('SEMANTIC_DOCUMENT.INVALID.NON_CANONICAL_MARKDOWN');return envelope}
export function safeProjection(envelope:DocumentEnvelope):string{const tags:Record<string,string>={documentTitle:'h1',heading:'heading_level',paragraph:'p',blockquote:'blockquote',preformatted:'pre',codeBlock:'code',divider:'hr',list:'list',listItem:'li',definitionList:'dl',callout:'aside',factBox:'aside',factRow:'div',table:'table',tableCaption:'caption',tableRow:'tr',tableCell:'td_or_th',groupedDirectory:'nav',footnoteReference:'sup',footnoteDefinition:'li',footnoteList:'ol',hatnote:'aside',externalLinks:'section',seeAlso:'section',relatedResources:'section',figure:'figure',gallery:'gallery'};const events:unknown[]=[];const visit=(n:any,depth:number)=>{const links:string[]=[],assetIds:string[]=[],tableCells:unknown[]=[],footnoteEdges:string[]=[];const scan=(v:any)=>{if(Array.isArray(v))v.forEach(scan);else if(v&&typeof v==='object'){if(typeof v.href==='string'&&v.href)links.push(v.href);for(const k of ['assetId','figureId'])if(typeof v[k]==='string'&&v[k])assetIds.push(v[k]);if('row'in v&&'column'in v){const c:any={};for(const k of ['row','column','rowSpan','rowspan','columnSpan','colspan','scope','sortKey'])c[k]=v[k]??null;tableCells.push(c)}Object.values(v).forEach(scan)}};scan(n.attributes??{});const rid=n.attributes?.refId??n.attributes?.identifier;if(n.kind==='footnoteReference'&&rid)footnoteEdges.push(rid);events.push({order:events.length,depth,nodeId:n.nodeId,kind:n.kind,safeTag:tags[n.kind]??'section',text:nodeText(n),links:links.sort(),assetIds:assetIds.sort(),tableCells,footnoteEdges});(n.children??[]).forEach((c:any)=>visit(c,depth+1))};envelope.nodes.forEach(n=>visit(n,0));return canonicalJson(events)+'\n'}
