/// Circle 领域 canonical 契约对象的 local_contract 构造器。
///
/// 唯一目的：让测试只声明它真正断言的字段，其余必填字段取契约中性默认值。
/// 这里不做任何 wire 解析、映射或业务判定，避免成为第二真相源。
/// 仅供测试树使用，禁止被 `lib/**` 或任何环境 App 装配引用。
library;

import 'package:quwoquan_cloud_contracts/quwoquan_cloud_contracts.dart';

final DateTime circleContractTestEpoch = DateTime.utc(2026, 1, 1);

Circle buildCircleContract({
  required String circleId,
  String name = '契约测试圈子',
  String ownerId = 'fixture_user_owner',
  String? description,
  String? coverUrl,
  String? iconUrl,
  String? ownerDisplayNameSnapshot,
  String? category,
  String? subCategory,
  String? domainId,
  List<String>? tags,
  int memberCount = 0,
  int postCount = 0,
  int weeklyActiveCount = 0,
  int version = 1,
  CircleStatus status = CircleStatus.active,
  CircleVisibility visibility = CircleVisibility.public,
  CircleJoinPolicy joinPolicy = CircleJoinPolicy.open,
  CircleKind kind = CircleKind.interest,
  CircleDisplaySubjectType displaySubjectType = CircleDisplaySubjectType.circle,
  bool followEnabled = true,
  bool autoSyncChat = true,
  String? defaultPublicGroupId,
  List<CircleSectionConfig>? sectionConfig,
  int storageUsedBytes = 0,
  int storageQuotaBytes = 0,
  String? linkedHomepageId,
  HomepageType? linkedHomepageType,
  String? linkedHomepageTitle,
  DateTime? createdAt,
  DateTime? updatedAt,
}) {
  return Circle(
    id: circleId,
    name: name,
    description: description,
    coverUrl: coverUrl,
    iconUrl: iconUrl,
    ownerId: ownerId,
    ownerDisplayNameSnapshot: ownerDisplayNameSnapshot,
    category: category,
    subCategory: subCategory,
    tags: tags,
    memberCount: memberCount,
    postCount: postCount,
    weeklyActiveCount: weeklyActiveCount,
    version: version,
    status: status,
    visibility: visibility,
    joinPolicy: joinPolicy,
    kind: kind,
    displaySubjectType: displaySubjectType,
    followEnabled: followEnabled,
    defaultPublicGroupId: defaultPublicGroupId,
    autoSyncChat: autoSyncChat,
    sectionConfig: sectionConfig,
    storageUsedBytes: storageUsedBytes,
    storageQuotaBytes: storageQuotaBytes,
    domainId: domainId,
    linkedHomepageId: linkedHomepageId,
    linkedHomepageType: linkedHomepageType,
    linkedHomepageTitle: linkedHomepageTitle,
    createdAt: createdAt ?? circleContractTestEpoch,
    updatedAt: updatedAt ?? createdAt ?? circleContractTestEpoch,
  );
}

CircleFeedItemView buildCircleFeedItemContract({
  required String circleId,
  required String placementId,
  required String postId,
  String contentType = 'image',
  String? contentIdentity,
  AssistantUsePolicy? assistantUsePolicy,
  String? authorId,
  String? authorDisplayName,
  String? authorAvatarUrl,
  String? authorBackgroundUrl,
  String? authorRoleLabel,
  List<String>? authorIdentityTags,
  bool authorVerified = false,
  String? title,
  String? body,
  String? summary,
  String? coverUrl,
  List<String>? imageUrls,
  String? videoUrl,
  String? thumbnailUrl,
  int? width,
  int? height,
  int? durationMs,
  int likeCount = 0,
  int commentCount = 0,
  int shareCount = 0,
  DateTime? createdAt,
  DateTime? updatedAt,
  DateTime? publishedAt,
  String? contentVertical,
  String? recallPath,
  String? supplySource,
  bool pinned = false,
  bool featured = false,
}) {
  return CircleFeedItemView(
    circleId: circleId,
    placementId: placementId,
    postId: postId,
    contentType: contentType,
    contentIdentity: contentIdentity,
    assistantUsePolicy: assistantUsePolicy,
    authorId: authorId,
    authorDisplayName: authorDisplayName,
    authorAvatarUrl: authorAvatarUrl,
    authorBackgroundUrl: authorBackgroundUrl,
    authorRoleLabel: authorRoleLabel,
    authorIdentityTags: authorIdentityTags,
    authorVerified: authorVerified,
    title: title,
    body: body,
    summary: summary,
    coverUrl: coverUrl,
    imageUrls: imageUrls,
    videoUrl: videoUrl,
    thumbnailUrl: thumbnailUrl,
    width: width,
    height: height,
    durationMs: durationMs,
    likeCount: likeCount,
    commentCount: commentCount,
    shareCount: shareCount,
    createdAt: createdAt,
    updatedAt: updatedAt,
    publishedAt: publishedAt,
    contentVertical: contentVertical,
    recallPath: recallPath,
    supplySource: supplySource,
    pinned: pinned,
    featured: featured,
  );
}

CircleImpactItem buildCircleImpactItemContract({
  required String helpType,
  required String action,
  required String intersectionDimension,
  required int count,
  required String primaryText,
  String source = 'test',
  String tagRef = '',
  String subtitleText = '',
  String? impactId,
  List<IntersectionTextSpan> primarySpans = const <IntersectionTextSpan>[],
  List<IntersectionVisual> sampleVisuals = const <IntersectionVisual>[],
  IntersectionRepresentativeActor? representativeActor,
  List<IntersectionActionHint> actionHints = const <IntersectionActionHint>[],
  IntersectionTarget? countTarget,
  String evidenceSnapshotId = '',
  String countObjectKind = 'user',
  IntersectionPropagationPath? propagationPath,
  String iconKey = 'relationship',
}) {
  return CircleImpactItem(
    helpType: helpType,
    action: action,
    intersectionDimension: intersectionDimension,
    tagRef: tagRef,
    source: source,
    count: count,
    primaryText: primaryText,
    subtitleText: subtitleText,
    impactId: impactId ?? '$helpType:$action',
    primarySpans: primarySpans,
    sampleVisuals: sampleVisuals,
    representativeActor: representativeActor,
    actionHints: actionHints,
    countTarget: countTarget,
    evidenceSnapshotId: evidenceSnapshotId,
    countObjectKind: countObjectKind,
    propagationPath: propagationPath,
    iconKey: iconKey,
  );
}

CircleStatsWire buildCircleStatsContract({
  required String circleId,
  int memberCount = 0,
  int postCount = 0,
  int discussionCount = 0,
  int weeklyActiveCount = 0,
  int likeCount = 0,
  int storageUsedBytes = 0,
  int storageQuotaBytes = 0,
}) {
  return CircleStatsWire(
    circleId: circleId,
    memberCount: memberCount,
    postCount: postCount,
    discussionCount: discussionCount,
    weeklyActiveCount: weeklyActiveCount,
    likeCount: likeCount,
    storageUsedBytes: storageUsedBytes,
    storageQuotaBytes: storageQuotaBytes,
  );
}

CircleImpactSummary buildEmptyCircleImpactSummary(String circleId) =>
    CircleImpactSummary(
      circleId: circleId,
      total: 0,
      items: const <CircleImpactItem>[],
    );

const CircleSearchResultView emptyCircleSearchResultView =
    CircleSearchResultView(
      items: <CircleSearchItemView>[],
      facetBuckets: <CircleFacetBucketView>[],
    );
