// Code generated by generate_canonical_test_bridges.py. DO NOT EDIT.
package api_integration

import (
	"os/exec"
	"testing"
)

func TestAssistantMentionedStreamContractApiIntegrationTest(t *testing.T) {
	cmd := exec.Command(
		"go",
		"test",
		"..",
		"-run",
		"^(TestAssistantGeneratedMessageDoesNotWriteMentionStream|TestAssistantMentionedWritesReliableStream)$",
		"-count=1",
	)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("source bridge failed for quwoquan_service/services/chat-service/tests/assistant_mentioned_stream_contract_test.go: %v\n%s", err, output)
	}
}
