// Code generated by generate_canonical_test_bridges.py. DO NOT EDIT.
package api_integration

import (
	"os/exec"
	"testing"
)

func TestDirectConversationRelationshipGateApiIntegrationTest(t *testing.T) {
	cmd := exec.Command(
		"go",
		"test",
		"..",
		"-run",
		"^(TestCreateConversation_Direct_AllowsMutual|TestCreateConversation_Direct_Blocked|TestCreateConversation_Direct_RequiresMutualOrFormal)$",
		"-count=1",
	)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("source bridge failed for quwoquan_service/services/chat-service/tests/direct_conversation_relationship_gate_test.go: %v\n%s", err, output)
	}
}
