// Code generated by generate_canonical_test_bridges.py. DO NOT EDIT.
package api_integration

import (
	"os/exec"
	"testing"
)

func TestGroupAvatarSyncContractApiIntegrationTest(t *testing.T) {
	cmd := exec.Command(
		"go",
		"test",
		"..",
		"-run",
		"^(TestGroupAvatar_RecomputePublishesConversationAvatarPatch)$",
		"-count=1",
	)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("source bridge failed for quwoquan_service/services/chat-service/tests/group_avatar_sync_contract_test.go: %v\n%s", err, output)
	}
}
