package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"

	contractcodegen "quwoquan_service/internal/metadata/codegen"
)

type postPublicationPolicyYAML struct {
	Schema     string `yaml:"schema"`
	TextLimits struct {
		TitleMaxRunes            int `yaml:"title_max_runes"`
		MicroBodyMaxRunes        int `yaml:"micro_body_max_runes"`
		ArticleMarkdownMaxRunes  int `yaml:"article_markdown_max_runes"`
		SummaryMaxRunes          int `yaml:"summary_max_runes"`
		SemanticMentionsMaxItems int `yaml:"semantic_mentions_max_items"`
	} `yaml:"text_limits"`
	FormatRecommendation struct {
		ArticleBodyMinRunes      int  `yaml:"article_body_min_runes"`
		ArticleParagraphMinCount int  `yaml:"article_paragraph_min_count"`
		ArticleWhenTitlePresent  bool `yaml:"article_when_title_present"`
		ArticleWhenMediaPresent  bool `yaml:"article_when_media_present"`
		UserConfirmationRequired bool `yaml:"user_confirmation_required"`
	} `yaml:"format_recommendation"`
	RateLimit struct {
		PersonaWindowSeconds   int    `yaml:"persona_window_seconds"`
		PersonaMaxPublications int    `yaml:"persona_max_publications"`
		DependencyFailure      string `yaml:"dependency_failure"`
	} `yaml:"rate_limit"`
	Safety struct {
		Required             bool     `yaml:"required"`
		DependencyFailure    string   `yaml:"dependency_failure"`
		Decisions            []string `yaml:"decisions"`
		UnavailableAction    string   `yaml:"unavailable_action"`
		RejectErrorCode      string   `yaml:"reject_error_code"`
		UnavailableErrorCode string   `yaml:"unavailable_error_code"`
	} `yaml:"safety"`
}

func generatePostPublicationPolicy(
	source *contractcodegen.Source,
	outputDir string,
) error {
	var policy postPublicationPolicyYAML
	if err := source.Decode("content/content/post/publication_policy.yaml", &policy); err != nil {
		return err
	}
	if policy.Schema != "content_post_publication_policy" ||
		policy.TextLimits.TitleMaxRunes <= 0 ||
		policy.TextLimits.MicroBodyMaxRunes <= 0 ||
		policy.TextLimits.ArticleMarkdownMaxRunes <= 0 ||
		policy.TextLimits.SummaryMaxRunes <= 0 ||
		policy.TextLimits.SemanticMentionsMaxItems <= 0 ||
		policy.RateLimit.PersonaWindowSeconds <= 0 ||
		policy.RateLimit.PersonaMaxPublications <= 0 ||
		policy.RateLimit.DependencyFailure != "fail_closed" ||
		!policy.Safety.Required ||
		policy.Safety.DependencyFailure != "fail_closed" ||
		policy.Safety.UnavailableAction != "review" ||
		len(policy.Safety.Decisions) != 4 {
		return fmt.Errorf("content/content/post/publication_policy.yaml is incomplete or not fail-closed")
	}
	var buf bytes.Buffer
	buf.WriteString("// Code generated by tools/codegen_content_service from content/content/post/publication_policy.yaml. DO NOT EDIT.\n\n")
	buf.WriteString("package generated\n\n")
	buf.WriteString("const (\n")
	fmt.Fprintf(&buf, "\tPostPublicationTitleMaxRunes = %d\n", policy.TextLimits.TitleMaxRunes)
	fmt.Fprintf(&buf, "\tPostPublicationMicroBodyMaxRunes = %d\n", policy.TextLimits.MicroBodyMaxRunes)
	fmt.Fprintf(&buf, "\tPostPublicationArticleMarkdownMaxRunes = %d\n", policy.TextLimits.ArticleMarkdownMaxRunes)
	fmt.Fprintf(&buf, "\tPostPublicationSummaryMaxRunes = %d\n", policy.TextLimits.SummaryMaxRunes)
	fmt.Fprintf(&buf, "\tPostPublicationSemanticMentionsMaxItems = %d\n", policy.TextLimits.SemanticMentionsMaxItems)
	fmt.Fprintf(&buf, "\tPostPublicationArticleBodyMinRunes = %d\n", policy.FormatRecommendation.ArticleBodyMinRunes)
	fmt.Fprintf(&buf, "\tPostPublicationArticleParagraphMinCount = %d\n", policy.FormatRecommendation.ArticleParagraphMinCount)
	fmt.Fprintf(&buf, "\tPostPublicationPersonaRateWindowSeconds = %d\n", policy.RateLimit.PersonaWindowSeconds)
	fmt.Fprintf(&buf, "\tPostPublicationPersonaMaxPublications = %d\n", policy.RateLimit.PersonaMaxPublications)
	fmt.Fprintf(&buf, "\tPostPublicationRejectErrorCode = %q\n", policy.Safety.RejectErrorCode)
	fmt.Fprintf(&buf, "\tPostPublicationUnavailableErrorCode = %q\n", policy.Safety.UnavailableErrorCode)
	buf.WriteString(")\n\n")
	buf.WriteString("type PublicationSafetyDecision string\n\n")
	buf.WriteString("const (\n")
	buf.WriteString("\tPublicationSafetyAllow PublicationSafetyDecision = \"allow\"\n")
	buf.WriteString("\tPublicationSafetyReview PublicationSafetyDecision = \"review\"\n")
	buf.WriteString("\tPublicationSafetyReject PublicationSafetyDecision = \"reject\"\n")
	buf.WriteString("\tPublicationSafetyUnavailable PublicationSafetyDecision = \"unavailable\"\n")
	buf.WriteString(")\n")
	out, err := format.Source(buf.Bytes())
	if err != nil {
		return err
	}
	targetDir := outputDir
	if err := os.MkdirAll(targetDir, 0o755); err != nil {
		return err
	}
	return os.WriteFile(
		filepath.Join(targetDir, "post_publication_policy.go"),
		out,
		0o644,
	)
}
