apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ../../../quwoquan_service/services/assistant-service/environments/gamma/deploy
  - ../../../quwoquan_service/services/chat-service/environments/gamma/deploy
  - ../../../quwoquan_service/services/circle-service/environments/gamma/deploy
  - ../../../quwoquan_service/services/content-service/environments/gamma/deploy
  - ../../../quwoquan_service/services/entity-service/environments/gamma/deploy
  - ../../../quwoquan_service/services/integration-service/environments/gamma/deploy
  - ../../../quwoquan_service/services/notification-service/environments/gamma/deploy
  - ../../../quwoquan_service/services/product-ops-service/environments/gamma/deploy
  - ../../../quwoquan_service/services/realtime-gateway/environments/gamma/deploy
  - ../../../quwoquan_service/services/recommendation-service/environments/gamma/deploy
  - ../../../quwoquan_service/services/rtc-service/environments/gamma/deploy
  - ../../../quwoquan_service/services/search-service/environments/gamma/deploy
  - ../../../quwoquan_service/services/tag-service/environments/gamma/deploy
  - ../../../quwoquan_service/services/user-service/environments/gamma/deploy
  - ../../external/coturn/environments/gamma
  - ../../external/livekit/environments/gamma
  - ../../../quwoquan_service/control-plane/platform-ops/environments/gamma/deploy
