// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../../ui/user/providers/intersection_provider_cache_test.dart' as source_0;

void main() {
  source_0.main();
}
