// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../../ui/user/providers/persona_management_provider_test.dart' as source_test;

void main() {
  source_test.main();
}
