// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../../../ui/content/entry/widgets/article_wrap_paragraph_editor_test.dart' as source_test;

void main() {
  source_test.main();
}
