import 'package:quwoquan_cloud_contracts/quwoquan_cloud_contracts.dart';

IntersectionTarget intersectionTargetFixture({
  String objectType = '',
  String objectId = '',
  String objectKind = '',
  String routeId = '',
}) => IntersectionTarget(
  objectType: objectType,
  objectId: objectId,
  objectKind: objectKind,
  routeId: routeId,
);

IntersectionVisual intersectionVisualFixture({
  String assetKind = '',
  String imageUrl = '',
  String displayName = '',
  IntersectionTarget? target,
}) => IntersectionVisual(
  assetKind: assetKind,
  imageUrl: imageUrl,
  displayName: displayName,
  target: target,
);

IntersectionTextSpan intersectionTextSpanFixture({
  String text = '',
  String role = '',
  IntersectionTarget? target,
  IntersectionVisual? visual,
}) => IntersectionTextSpan(
  text: text,
  role: role,
  target: target,
  visual: visual,
);

IntersectionPoint intersectionPointFixture({
  String pointId = '',
  String pointClass = '',
  String dimension = '',
  String label = '',
  String displayText = '',
  String sourceRef = '',
  String visibility = '',
  int count = 0,
  String sampleText = '',
  List<String> sampleAvatarUrls = const <String>[],
  List<IntersectionVisual> sampleVisuals = const <IntersectionVisual>[],
}) => IntersectionPoint(
  pointId: pointId,
  pointClass: pointClass,
  dimension: dimension,
  label: label,
  displayText: displayText,
  sourceRef: sourceRef,
  visibility: visibility,
  count: count,
  sampleText: sampleText,
  sampleAvatarUrls: sampleAvatarUrls,
  sampleVisuals: sampleVisuals,
);

IntersectionActionHint intersectionActionHintFixture({
  String actionKey = '',
  String label = '',
  IntersectionTarget? target,
  bool isPrimary = false,
  int priority = 0,
  String actionTier = '',
  List<String> requiredGates = const <String>[],
  String dispatch = '',
}) => IntersectionActionHint(
  actionKey: actionKey,
  label: label,
  target: target,
  isPrimary: isPrimary,
  priority: priority,
  actionTier: actionTier,
  requiredGates: requiredGates,
  dispatch: dispatch,
);

IntersectionRepresentativeActor intersectionRepresentativeActorFixture({
  String actorId = '',
  String displayName = '',
  String avatarUrl = '',
  String relationLabel = '',
  String privacyState = '',
  IntersectionTarget? target,
  int evidenceRank = 0,
  String snapshotVersion = '',
}) => IntersectionRepresentativeActor(
  actorId: actorId,
  displayName: displayName,
  avatarUrl: avatarUrl,
  relationLabel: relationLabel,
  privacyState: privacyState,
  target: target,
  evidenceRank: evidenceRank,
  snapshotVersion: snapshotVersion,
);

IntersectionActorEvidence intersectionActorEvidenceFixture({
  String actorId = '',
  String displayName = '',
  String avatarUrl = '',
  String relationLabel = '',
  String relationSourceRef = '',
  String relationObjectId = '',
  String relationObjectName = '',
  String sourcePointId = '',
  String sourceRef = '',
  String actionSummaryText = '',
  int likeCount = 0,
  int commentCount = 0,
  int shareCount = 0,
  String privacyState = '',
  IntersectionTarget? target,
  int evidenceRank = 0,
  String snapshotVersion = '',
  int sortKey = 0,
}) => IntersectionActorEvidence(
  actorId: actorId,
  displayName: displayName,
  avatarUrl: avatarUrl,
  relationLabel: relationLabel,
  relationSourceRef: relationSourceRef,
  relationObjectId: relationObjectId,
  relationObjectName: relationObjectName,
  sourcePointId: sourcePointId,
  sourceRef: sourceRef,
  actionSummaryText: actionSummaryText,
  likeCount: likeCount,
  commentCount: commentCount,
  shareCount: shareCount,
  privacyState: privacyState,
  target: target,
  evidenceRank: evidenceRank,
  snapshotVersion: snapshotVersion,
  sortKey: sortKey,
);

IntersectionDimensionTally intersectionDimensionTallyFixture({
  String dimension = '',
  String label = '',
  int count = 0,
  int newCount = 0,
  String briefText = '',
  String subtitleText = '',
  List<IntersectionTextSpan> briefSpans = const <IntersectionTextSpan>[],
  List<IntersectionVisual> sampleVisuals = const <IntersectionVisual>[],
  String sourceRef = '',
  String countObjectKind = '',
  int strengthenedCount = 0,
  int reactivatedCount = 0,
  String iconKey = '',
}) => IntersectionDimensionTally(
  dimension: dimension,
  label: label,
  count: count,
  newCount: newCount,
  briefText: briefText,
  subtitleText: subtitleText,
  briefSpans: briefSpans,
  sampleVisuals: sampleVisuals,
  sourceRef: sourceRef,
  countObjectKind: countObjectKind,
  strengthenedCount: strengthenedCount,
  reactivatedCount: reactivatedCount,
  iconKey: iconKey,
);

IntersectionInboxSummary intersectionInboxSummaryFixture({
  int totalCount = 0,
  int totalNewCount = 0,
  List<IntersectionDimensionTally> dimensions =
      const <IntersectionDimensionTally>[],
  String generatedAt = '',
  int totalStrengthenedCount = 0,
  int totalReactivatedCount = 0,
}) => IntersectionInboxSummary(
  totalCount: totalCount,
  totalNewCount: totalNewCount,
  dimensions: dimensions,
  generatedAt: generatedAt,
  totalStrengthenedCount: totalStrengthenedCount,
  totalReactivatedCount: totalReactivatedCount,
);

IntersectionPropagationPath intersectionPropagationPathFixture({
  String pathKind = '',
  int hopCount = 0,
  int secondarySpreadCount = 0,
  String summaryText = '',
  IntersectionTarget? summaryTarget,
  List<IntersectionVisual> nodes = const <IntersectionVisual>[],
}) => IntersectionPropagationPath(
  pathKind: pathKind,
  hopCount: hopCount,
  secondarySpreadCount: secondarySpreadCount,
  summaryText: summaryText,
  summaryTarget: summaryTarget,
  nodes: nodes,
);

/// 构造完整 canonical 交集 wire 对象的 test-only fixture。
///
/// 测试不得再依赖已退出的宽松 DTO、`fromMap` 默认值或 `copyWith` 兼容层；所有
/// 字段都在这里显式落到当前生成类型。生产 composition 不可达本文件。
IntersectionReason intersectionReasonFixture({
  String kind = '',
  String vertical = '',
  String dimension = '',
  List<String> tagRefs = const <String>[],
  String relationKind = '',
  String objectKind = '',
  String relationObjectId = '',
  double strength = 0,
  String primaryText = '',
  String primaryTextL10nKey = '',
  String displayBinding = 'explicit_link',
  String secondaryText = '',
  String weightTier = '',
  String actionType = '',
  String actionTargetId = '',
  String source = '',
  String intersectionId = 'intersection_fixture',
  String intersectionClass = 'fact',
  String avatarUrl = '',
  String displayName = '',
  String confidenceLabel = '',
  String modelReasonBucket = '',
  String freshAt = '',
  String expiresAt = '',
  List<IntersectionPoint> intersectionPoints = const <IntersectionPoint>[],
  String pointSummarySnapshotId = '',
  int actorEvidenceTotalCount = 0,
  String actorEvidenceCompleteness = '',
  List<IntersectionActorEvidence> actorEvidence =
      const <IntersectionActorEvidence>[],
  int factPointCount = 0,
  int recommendedPointCount = 0,
  int totalPointCount = 0,
  List<IntersectionDimensionTally> dimensionPointSummary =
      const <IntersectionDimensionTally>[],
  String pointClassLabel = '',
  String connectionSummary = '',
  String lastRecommendedAt = '',
  String seenAt = '',
  String rankState = '',
  List<IntersectionTextSpan> primarySpans = const <IntersectionTextSpan>[],
  List<IntersectionVisual> sampleVisuals = const <IntersectionVisual>[],
  IntersectionRepresentativeActor? representativeActor,
  List<IntersectionActionHint> actionHints = const <IntersectionActionHint>[],
  String lifecycleState = '',
  double previousStrength = 0,
  double strengthDelta = 0,
  double edgeWeight = 0,
  String iconKey = '',
  String tone = '',
  IntersectionVisual? typeVisual,
  IntersectionVisual? objectVisual,
  String timeBucket = '',
  String dedupeKey = '',
  double anchorUserWeight = 0,
  int mutualCount = 0,
  String moment = '',
  String subjectId = '',
  String subjectContext = '',
}) {
  return IntersectionReason(
    kind: kind,
    vertical: vertical,
    dimension: dimension,
    tagRefs: tagRefs,
    relationKind: relationKind,
    objectKind: objectKind,
    relationObjectId: relationObjectId,
    strength: strength,
    primaryText: primaryText,
    primaryTextL10nKey: primaryTextL10nKey,
    displayBinding: displayBinding,
    secondaryText: secondaryText,
    weightTier: weightTier,
    actionType: actionType,
    actionTargetId: actionTargetId,
    source: source,
    intersectionId: intersectionId,
    intersectionClass: intersectionClass,
    avatarUrl: avatarUrl,
    displayName: displayName,
    confidenceLabel: confidenceLabel,
    modelReasonBucket: modelReasonBucket,
    freshAt: freshAt,
    expiresAt: expiresAt,
    intersectionPoints: intersectionPoints,
    pointSummarySnapshotId: pointSummarySnapshotId,
    actorEvidenceTotalCount: actorEvidenceTotalCount,
    actorEvidenceCompleteness: actorEvidenceCompleteness,
    actorEvidence: actorEvidence,
    factPointCount: factPointCount,
    recommendedPointCount: recommendedPointCount,
    totalPointCount: totalPointCount,
    dimensionPointSummary: dimensionPointSummary,
    pointClassLabel: pointClassLabel,
    connectionSummary: connectionSummary,
    lastRecommendedAt: lastRecommendedAt,
    seenAt: seenAt,
    rankState: rankState,
    primarySpans: primarySpans,
    sampleVisuals: sampleVisuals,
    representativeActor: representativeActor,
    actionHints: actionHints,
    lifecycleState: lifecycleState,
    previousStrength: previousStrength,
    strengthDelta: strengthDelta,
    edgeWeight: edgeWeight,
    iconKey: iconKey,
    tone: tone,
    typeVisual: typeVisual,
    objectVisual: objectVisual,
    timeBucket: timeBucket,
    dedupeKey: dedupeKey,
    anchorUserWeight: anchorUserWeight,
    mutualCount: mutualCount,
    moment: moment,
    subjectId: subjectId,
    subjectContext: subjectContext,
  );
}

IntersectionReason copyIntersectionReasonFixture(
  IntersectionReason source, {
  String? actionTargetId,
  String? displayBinding,
  String? freshAt,
  List<IntersectionPoint>? intersectionPoints,
  String? pointSummarySnapshotId,
  int? factPointCount,
  int? recommendedPointCount,
  int? totalPointCount,
  List<IntersectionDimensionTally>? dimensionPointSummary,
  String? pointClassLabel,
  List<IntersectionTextSpan>? primarySpans,
  List<IntersectionActionHint>? actionHints,
  String? rankState,
}) {
  return intersectionReasonFixture(
    kind: source.kind,
    vertical: source.vertical,
    dimension: source.dimension,
    tagRefs: source.tagRefs,
    relationKind: source.relationKind,
    objectKind: source.objectKind,
    relationObjectId: source.relationObjectId,
    strength: source.strength,
    primaryText: source.primaryText,
    primaryTextL10nKey: source.primaryTextL10nKey,
    displayBinding: displayBinding ?? source.displayBinding,
    secondaryText: source.secondaryText,
    weightTier: source.weightTier,
    actionType: source.actionType,
    actionTargetId: actionTargetId ?? source.actionTargetId,
    source: source.source,
    intersectionId: source.intersectionId,
    intersectionClass: source.intersectionClass,
    avatarUrl: source.avatarUrl,
    displayName: source.displayName,
    confidenceLabel: source.confidenceLabel,
    modelReasonBucket: source.modelReasonBucket,
    freshAt: freshAt ?? source.freshAt,
    expiresAt: source.expiresAt,
    intersectionPoints: intersectionPoints ?? source.intersectionPoints,
    pointSummarySnapshotId:
        pointSummarySnapshotId ?? source.pointSummarySnapshotId,
    actorEvidenceTotalCount: source.actorEvidenceTotalCount,
    actorEvidenceCompleteness: source.actorEvidenceCompleteness,
    actorEvidence: source.actorEvidence,
    factPointCount: factPointCount ?? source.factPointCount,
    recommendedPointCount:
        recommendedPointCount ?? source.recommendedPointCount,
    totalPointCount: totalPointCount ?? source.totalPointCount,
    dimensionPointSummary:
        dimensionPointSummary ?? source.dimensionPointSummary,
    pointClassLabel: pointClassLabel ?? source.pointClassLabel,
    connectionSummary: source.connectionSummary,
    lastRecommendedAt: source.lastRecommendedAt,
    seenAt: source.seenAt,
    rankState: rankState ?? source.rankState,
    primarySpans: primarySpans ?? source.primarySpans,
    sampleVisuals: source.sampleVisuals,
    representativeActor: source.representativeActor,
    actionHints: actionHints ?? source.actionHints,
    lifecycleState: source.lifecycleState,
    previousStrength: source.previousStrength,
    strengthDelta: source.strengthDelta,
    edgeWeight: source.edgeWeight,
    iconKey: source.iconKey,
    tone: source.tone,
    typeVisual: source.typeVisual,
    objectVisual: source.objectVisual,
    timeBucket: source.timeBucket,
    dedupeKey: source.dedupeKey,
    anchorUserWeight: source.anchorUserWeight,
    mutualCount: source.mutualCount,
    moment: source.moment,
    subjectId: source.subjectId,
    subjectContext: source.subjectContext,
  );
}
