// Code generated by generate_canonical_test_bridges.py. DO NOT EDIT.
package api_integration

import (
	"os/exec"
	"testing"
)

func TestOneToOneRelationshipGateApiIntegrationTest(t *testing.T) {
	cmd := exec.Command(
		"go",
		"test",
		"..",
		"-run",
		"^(TestInitiateCall_OneToOne_AllowsMutual|TestInitiateCall_OneToOne_Blocked|TestInitiateCall_OneToOne_RequiresMutual)$",
		"-count=1",
	)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("source bridge failed for quwoquan_service/services/rtc-service/tests/one_to_one_relationship_gate_test.go: %v\n%s", err, output)
	}
}
