// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../../ui/circle/journeys/circle_detail_journey_test.dart' as legacy_test;

void main() {
  legacy_test.main();
}
