package codegen

import (
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"

	"quwoquan_service/internal/metadata/ast"
	"quwoquan_service/internal/metadata/graph"
)

const (
	OperationSecurityOperationsPerChunk    = 16
	OperationSecurityMaxChunks             = 256
	OperationSecurityMaxGeneratedFileLines = 600
	OperationSecurityMaxGeneratedFileBytes = 128 * 1024
	OperationSecurityGeneratedHeader       = "// Code generated by qwq-contract operation-security. DO NOT EDIT."
)

type OperationSecurityGoFile struct {
	Suffix string
	Source []byte
}

// RenderOperationSecurityGoFiles emits a bounded main file and deterministic
// descriptor chunks. ForDomain remains the package's only lookup API.
func RenderOperationSecurityGoFiles(
	contractGraph *graph.ContractGraph,
	graphSHA256 string,
) ([]OperationSecurityGoFile, error) {
	operations := append([]ast.Operation(nil), contractGraph.Operations...)
	sort.Slice(operations, func(i, j int) bool { return operations[i].ID < operations[j].ID })

	chunkCount := (len(operations) + OperationSecurityOperationsPerChunk - 1) /
		OperationSecurityOperationsPerChunk
	if chunkCount > OperationSecurityMaxChunks {
		return nil, fmt.Errorf(
			"operation security needs %d chunks and exceeds hard limit %d",
			chunkCount,
			OperationSecurityMaxChunks,
		)
	}

	files := make([]OperationSecurityGoFile, 0, chunkCount+1)
	mainSource, err := renderOperationSecurityMain(graphSHA256, chunkCount)
	if err != nil {
		return nil, err
	}
	files = append(files, OperationSecurityGoFile{Suffix: "", Source: mainSource})

	for chunkIndex, start := 0, 0; start < len(operations); chunkIndex, start = chunkIndex+1, start+OperationSecurityOperationsPerChunk {
		end := start + OperationSecurityOperationsPerChunk
		if end > len(operations) {
			end = len(operations)
		}
		source, renderErr := renderOperationSecurityChunk(
			operations[start:end], graphSHA256, chunkIndex,
		)
		if renderErr != nil {
			return nil, renderErr
		}
		files = append(files, OperationSecurityGoFile{
			Suffix: fmt.Sprintf(".chunk%03d", chunkIndex),
			Source: source,
		})
	}
	return files, nil
}

func renderOperationSecurityMain(graphSHA256 string, chunkCount int) ([]byte, error) {
	var output strings.Builder
	writeOperationSecurityHeader(&output, graphSHA256)
	output.WriteString("package operationsecurity\n\n")
	output.WriteString("import \"quwoquan_service/runtime/auth\"\n\n")
	fmt.Fprintf(&output, "const ContractGraphSHA256 = %s\n\n", strconv.Quote(graphSHA256))
	output.WriteString("func ForDomain(domain string) []auth.OperationSecurityDescriptor {\n")
	output.WriteString("\tvar source []auth.OperationSecurityDescriptor\n")
	for chunkIndex := 0; chunkIndex < chunkCount; chunkIndex++ {
		fmt.Fprintf(
			&output,
			"\tsource = appendOperationSecurityChunk%03d(source, domain)\n",
			chunkIndex,
		)
	}
	output.WriteString("\treturn source\n}\n")
	return formatOperationSecuritySource("main", output.String())
}

func renderOperationSecurityChunk(
	operations []ast.Operation,
	graphSHA256 string,
	chunkIndex int,
) ([]byte, error) {
	byDomain := map[string][]ast.Operation{}
	for _, operation := range operations {
		byDomain[operation.Domain] = append(byDomain[operation.Domain], operation)
	}
	domains := make([]string, 0, len(byDomain))
	for domain := range byDomain {
		domains = append(domains, domain)
	}
	sort.Strings(domains)

	var output strings.Builder
	writeOperationSecurityHeader(&output, graphSHA256)
	output.WriteString("package operationsecurity\n\n")
	output.WriteString("import \"quwoquan_service/runtime/auth\"\n\n")
	fmt.Fprintf(
		&output,
		"func appendOperationSecurityChunk%03d(dst []auth.OperationSecurityDescriptor, domain string) []auth.OperationSecurityDescriptor {\n",
		chunkIndex,
	)
	output.WriteString("\tswitch domain {\n")
	for _, domain := range domains {
		fmt.Fprintf(&output, "\tcase %s:\n", strconv.Quote(domain))
		output.WriteString("\t\treturn append(dst,\n")
		for _, operation := range byDomain[domain] {
			writeOperationSecurityDescriptor(&output, operation, graphSHA256)
		}
		output.WriteString("\t\t)\n")
	}
	output.WriteString("\tdefault:\n\t\treturn dst\n\t}\n}\n")
	return formatOperationSecuritySource(fmt.Sprintf("chunk %03d", chunkIndex), output.String())
}

func writeOperationSecurityHeader(output *strings.Builder, graphSHA256 string) {
	output.WriteString(OperationSecurityGeneratedHeader + "\n")
	fmt.Fprintf(output, "// ContractGraph SHA256: %s\n\n", graphSHA256)
}

func writeOperationSecurityDescriptor(
	output *strings.Builder,
	operation ast.Operation,
	graphSHA256 string,
) {
	output.WriteString("\t\t\tauth.OperationSecurityDescriptor{\n")
	writeGoStringField(output, "CanonicalOperationID", operation.ID)
	writeGoStringField(output, "ContractGraphSHA256", graphSHA256)
	writeGoStringField(output, "Transport", operation.Transport)
	writeGoStringField(output, "Method", operation.Method)
	writeGoStringField(output, "OperationKind", string(operation.Kind))
	writeGoStringField(output, "MutationTarget", operation.MutationTarget)
	writeGoStringField(output, "InvariantTarget", operation.InvariantTarget)
	writeGoStringField(output, "PathTemplate", operation.PathTemplate)
	writeGoStringField(output, "AuthMode", operation.AuthMode)
	writeGoStringField(output, "ActorRequirement", operation.ActorRequirement)
	writeGoStringField(output, "Principal", operation.Principal)
	writeGoStringSliceField(output, "Scopes", operation.Scopes)
	writeGoStringSliceField(output, "Permissions", operation.Permissions)
	writeGoStringField(output, "OwnershipPolicy", operation.OwnershipPolicy)
	fmt.Fprintf(output, "\t\t\t\tTimeoutMilliseconds: %d,\n", operation.Reliability.TimeoutMilliseconds)
	if budget := operation.Reliability.StreamBudget; budget != nil {
		fmt.Fprintf(
			output,
			"\t\t\t\tStreamBudget: &auth.OperationStreamBudget{"+
				"HandshakeMilliseconds: %d, IdleMilliseconds: %d, MaxDurationMilliseconds: %d},\n",
			budget.HandshakeMilliseconds,
			budget.IdleMilliseconds,
			budget.MaxDurationMilliseconds,
		)
	}
	writeGoStringField(output, "Idempotency", operation.Reliability.Idempotency)
	writeGoStringField(output, "VersionPrecondition", string(operation.Concurrency.VersionPrecondition))
	writeGoStringField(output, "CommercialStatus", operation.Commercial.Status)
	output.WriteString("\t\t\t},\n")
}

func formatOperationSecuritySource(name, source string) ([]byte, error) {
	formatted, err := format.Source([]byte(source))
	if err != nil {
		return nil, fmt.Errorf("format generated operation security %s: %w", name, err)
	}
	if lines := bytesLineCount(formatted); lines > OperationSecurityMaxGeneratedFileLines {
		return nil, fmt.Errorf(
			"generated operation security %s has %d lines and exceeds hard limit %d",
			name,
			lines,
			OperationSecurityMaxGeneratedFileLines,
		)
	}
	if len(formatted) > OperationSecurityMaxGeneratedFileBytes {
		return nil, fmt.Errorf("generated operation security %s has %d bytes and exceeds hard limit %d", name, len(formatted), OperationSecurityMaxGeneratedFileBytes)
	}
	return formatted, nil
}

func bytesLineCount(source []byte) int {
	if len(source) == 0 {
		return 0
	}
	return strings.Count(string(source), "\n")
}

func writeGoStringField(output *strings.Builder, name, value string) {
	fmt.Fprintf(output, "\t\t\t\t%s: %s,\n", name, strconv.Quote(value))
}

func writeGoStringSliceField(output *strings.Builder, name string, values []string) {
	if len(values) == 0 {
		return
	}
	fmt.Fprintf(output, "\t\t\t\t%s: []string{", name)
	for index, value := range values {
		if index > 0 {
			output.WriteString(", ")
		}
		output.WriteString(strconv.Quote(value))
	}
	output.WriteString("},\n")
}
