// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../cloud/runtime/content_app_config_client_parsed_test.dart' as source_0;

void main() {
  source_0.main();
}
