// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../core/providers/app_remote_config_provider_test.dart' as source_test;

void main() {
  source_test.main();
}
