// Code generated by generate_canonical_test_bridges.py. DO NOT EDIT.
package api_integration

import (
	"os/exec"
	"testing"
)

func TestTagContractApiIntegrationTest(t *testing.T) {
	cmd := exec.Command(
		"go",
		"test",
		"..",
		"-run",
		"^(TestInvertedFilterByType|TestInvertedObjects|TestListDimensions|TestListTagChildrenGuangdongAndBeijingAreCompleteDirectLevel|TestListTagChildrenReturnsDirectAdminRegionChildren|TestListTagChildrenUnknownParentReturns404|TestRelatedObjects|TestRelatedTags|TestReservedEndpointsReturn501|TestResolveReturnsDefinition|TestResolveUnknownReturns404|TestSearchByTags|TestSearchTags|TestSharedTagsTwoObjects|TestSuggestTags|TestTagCooccurrence|TestValidateTagRefs)$",
		"-count=1",
	)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("source bridge failed for quwoquan_service/services/tag-service/tests/tag_contract_test.go: %v\n%s", err, output)
	}
}
