#!/usr/bin/env python3
"""
App UI 层 `Map<String, dynamic>` 字面量出现次数预算（防回退）。

UI 层由三处组成，页面、壳层与设计系统都不得用弱类型 Map 承载展示模型：
  lib/service/**/presentation/**  对象级页面与展示模型
  lib/runtime/shell/**            应用壳
  lib/design_system/**            设计系统

预算文件：quwoquan_ops/policies/gates/ui_map_literal_budget.json
  { "max_ui_map_string_dynamic_occurrences": <int> }

当前计数 > 预算 → exit 1。任一扫描根缺失 → exit 2：目录被搬走而计数静默归零，
会让门禁在债务仍然存在时显示为绿。

更新预算（刻意放宽时）：
  python3 quwoquan_app/scripts/runtime/page/verify_ui_map_literal_budget.py --write-baseline
"""

from __future__ import annotations


import sys
from pathlib import Path

_SCRIPTS_ROOT = next(
    parent
    for parent in Path(__file__).resolve().parents
    if parent.name == "scripts" and (parent / "_common" / "paths.py").is_file()
)
if str(_SCRIPTS_ROOT) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS_ROOT))

from _common.paths import APP_ROOT, REPO_ROOT, SCRIPTS_ROOT

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = REPO_ROOT
BUDGET_PATH = ROOT / "quwoquan_ops" / "policies" / "gates" / "ui_map_literal_budget.json"
APP_LIB = ROOT / "quwoquan_app" / "lib"
UI_SCAN_ROOTS = (
    APP_LIB / "service",
    APP_LIB / "runtime" / "shell",
    APP_LIB / "design_system",
)
PRESENTATION_SEGMENT = "presentation"
MAP_RE = re.compile(r"Map<String,\s*dynamic>")


def missing_scan_roots() -> list[Path]:
    return [root for root in UI_SCAN_ROOTS if not root.is_dir()]


def _is_ui_file(path: Path) -> bool:
    if path.name.endswith(".g.dart"):
        return False
    # service/ 下只有对象的 presentation 层属于 UI；application/domain/adapters
    # 的弱类型由各自的分层门禁负责。
    if path.is_relative_to(APP_LIB / "service"):
        return PRESENTATION_SEGMENT in path.parts
    return True


def count_ui() -> int:
    total = 0
    for root in UI_SCAN_ROOTS:
        for path in root.rglob("*.dart"):
            if not _is_ui_file(path):
                continue
            text = path.read_text(encoding="utf-8", errors="replace")
            total += len(MAP_RE.findall(text))
    return total


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--write-baseline",
        action="store_true",
        help="Write quwoquan_ops/policies/gates/ui_map_literal_budget.json from current count",
    )
    args = ap.parse_args()

    missing = missing_scan_roots()
    if missing:
        joined = ", ".join(str(path.relative_to(ROOT)) for path in missing)
        print(
            f"verify_ui_map_literal_budget: BLOCK: missing UI scan root(s) {joined} "
            f"(update UI_SCAN_ROOTS after moving UI code; a silent zero count hides debt)",
            file=sys.stderr,
        )
        return 2

    current = count_ui()

    if args.write_baseline:
        BUDGET_PATH.parent.mkdir(parents=True, exist_ok=True)
        payload = {
            "max_ui_map_string_dynamic_occurrences": current,
            "_comment": "Regenerated by verify_ui_map_literal_budget.py --write-baseline; do not increase without remediation plan.",
        }
        BUDGET_PATH.write_text(
            json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        print(f"verify_ui_map_literal_budget: wrote baseline count={current} -> {BUDGET_PATH}")
        return 0

    if not BUDGET_PATH.is_file():
        print(
            f"verify_ui_map_literal_budget: BLOCK: missing {BUDGET_PATH} "
            f"(run with --write-baseline once)",
            file=sys.stderr,
        )
        return 2

    data = json.loads(BUDGET_PATH.read_text(encoding="utf-8"))
    budget = data.get("max_ui_map_string_dynamic_occurrences")
    if not isinstance(budget, int):
        print("verify_ui_map_literal_budget: BLOCK: budget file missing int key", file=sys.stderr)
        return 2

    if current > budget:
        print(
            f"verify_ui_map_literal_budget: BLOCK: ui Map count {current} > budget {budget} "
            f"(reduce literals or intentionally run --write-baseline after review)",
            file=sys.stderr,
        )
        return 1

    print(
        f"verify_ui_map_literal_budget: ok ui Map<String,dynamic> count={current} budget={budget}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
