apiVersion: v1
kind: Service
metadata:
  name: circle-service
  labels:
    app.kubernetes.io/name: circle-service
spec:
  selector:
    app.kubernetes.io/name: circle-service
  ports:
    - name: http
      port: 18082
      targetPort: http
