// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../../ui/chat/pages/chat_conversation_page_composer_test.dart' as source_0;

void main() {
  source_0.main();
}
