#!/usr/bin/env python3
"""Generate canonical App test wrappers from the directory inventory."""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any

import yaml

from test_directory_inventory_lib import INVENTORY_PATH, ROOT


HEADER = "// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.\n"


def load_inventory() -> dict[str, Any]:
    with INVENTORY_PATH.open("r", encoding="utf-8") as handle:
        return yaml.safe_load(handle) or {}


def build_wrapper(target_path: Path, source_path: Path) -> str:
    rel_import = os.path.relpath(source_path, start=target_path.parent).replace(os.sep, "/")
    return (
        HEADER
        + "\n"
        + f"import '{rel_import}' as source_test;\n"
        + "\n"
        + "void main() {\n"
        + "  source_test.main();\n"
        + "}\n"
    )


def main() -> int:
    inventory = load_inventory()
    areas = inventory.get("areas") or {}
    app_area = areas.get("app") or {}
    entries = app_area.get("entries") or []
    changed = 0
    for entry in entries:
        if not isinstance(entry, dict):
            continue
        target_text = str(entry.get("target_path") or "")
        current_text = str(entry.get("current_path") or "")
        if not target_text.startswith("quwoquan_app/test/"):
            continue
        target_path = ROOT / target_text
        source_path = ROOT / current_text
        target_path.parent.mkdir(parents=True, exist_ok=True)
        new_content = build_wrapper(target_path, source_path)
        if target_path.exists():
            existing = target_path.read_text(encoding="utf-8")
            if existing == new_content:
                continue
            if not existing.startswith(HEADER):
                continue
        target_path.write_text(new_content, encoding="utf-8")
        changed += 1

    print(f"[wrapper] app canonical wrappers written: {changed}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
