// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../../ui/assistant/pages/assistant_skill_center_page_widget_test.dart' as source_test;

void main() {
  source_test.main();
}
