#!/usr/bin/env python3
"""对象 × 层 × 三层测试入口的 readiness 结构性证据闭合门禁（稳定 CLI 入口）。

结构性证据严格零值 + 动态商业 readiness 薄调用的完整判定说明保留在
``object_evidence_closure/arguments.py`` 的模块 docstring（同时驱动 --help），
实现单轨落在 ``object_evidence_closure/`` 包内。本文件只做 sys.path bootstrap，
并为既有消费者 re-export 包 API。
"""

from __future__ import annotations

import sys
from pathlib import Path

_BOOTSTRAP = next(
    path
    for path in Path(__file__).resolve().parents
    if (path / "repository_root.py").is_file()
)
if str(_BOOTSTRAP) not in sys.path:
    sys.path.insert(0, str(_BOOTSTRAP))

from repository_root import repository_root  # noqa: E402

_REPO_ROOT = repository_root()
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from quwoquan_ops.gate.object_evidence_closure import (  # noqa: E402
    ARTIFACT_EVIDENCE_FIELDS,
    BLIND_SPOT_CLASSIFICATIONS,
    BLIND_SPOT_IMPLEMENTATION_EVIDENCE,
    BLIND_SPOT_IMPLEMENTED,
    BLIND_SPOT_MISSING,
    BLIND_SPOT_REGISTRY,
    BLINDSPOT,
    DART_NON_CODE_RE,
    DynamicEvaluation,
    EVIDENCE_CLASS_BY_DIMENSION,
    Gap,
    LAYER_BY_MISSING_KEY,
    LEGACY_FLATTENED_EVIDENCE_FIELDS,
    PACKET_ALLOWED_FIELDS,
    PACKET_OPTIONAL_FIELDS,
    PACKET_REQUIRED_FIELDS,
    PACKET_STRING_LIST_FIELDS,
    PAGE_OBJECT_CONTRACT,
    PRODUCER_ARTIFACT_FIELDS,
    PRODUCER_BOOLEAN_FIELDS,
    PRODUCER_STORAGE_FIELDS,
    READINESS_EVALUATOR_BUILD_TIMEOUT_SECONDS,
    READINESS_EVALUATOR_PACKAGE,
    READINESS_EVALUATOR_RUN_TIMEOUT_SECONDS,
    READINESS_METADATA_DIR,
    REPORT_BLIND_SPOT_REGISTRY_FIELD,
    REPORT_GRAPH_FIELD,
    RESULT,
    ROOT,
    RUN_DIR,
    SERVICE_ROOT,
    SHA256_PATTERN,
    STATE_OWNER_KINDS,
    STORAGE_EVIDENCE_FIELDS,
    STRUCTURAL,
    artifact_gaps,
    artifact_integrity_gaps,
    blind_spot_gaps,
    bound_storages,
    build_readiness_evaluator,
    cells_from_gaps,
    collect_gaps,
    commercial_input_values,
    decode_single_json_document,
    derive_contract_graph,
    digest_readiness_input,
    display_path,
    domain_event_declaration_gaps,
    evaluate_dynamic_readiness,
    evidence_class,
    is_production_service_source,
    load_blind_spot_registry,
    load_blind_spot_registry_with_digest,
    load_graph,
    load_graph_with_digest,
    main,
    object_contract_dir,
    page_claims_and_consumers,
    parse_args,
    partition_by_evidence_class,
    print_blind_spots,
    print_gap_inventory,
    print_result_layer,
    print_structural_gaps,
    publication_gap_detail,
    readiness_input_bindings,
    resolve_repository_artifact,
    runtime_execution_consumers,
    select_graph_path,
    sha256_file,
    slice_owner_object,
    unclassified_dimensions,
    validate_contract_graph_shape,
    validate_report_graph_binding,
    validate_report_policy_bindings,
    verify_graph_digest,
    verify_optional_input_digest,
    verify_readiness_input_bindings,
    without_dart_non_code,
    write_reports,
)

__all__ = [
    "ARTIFACT_EVIDENCE_FIELDS",
    "BLIND_SPOT_CLASSIFICATIONS",
    "BLIND_SPOT_IMPLEMENTATION_EVIDENCE",
    "BLIND_SPOT_IMPLEMENTED",
    "BLIND_SPOT_MISSING",
    "BLIND_SPOT_REGISTRY",
    "BLINDSPOT",
    "DART_NON_CODE_RE",
    "DynamicEvaluation",
    "EVIDENCE_CLASS_BY_DIMENSION",
    "Gap",
    "LAYER_BY_MISSING_KEY",
    "LEGACY_FLATTENED_EVIDENCE_FIELDS",
    "PACKET_ALLOWED_FIELDS",
    "PACKET_OPTIONAL_FIELDS",
    "PACKET_REQUIRED_FIELDS",
    "PACKET_STRING_LIST_FIELDS",
    "PAGE_OBJECT_CONTRACT",
    "PRODUCER_ARTIFACT_FIELDS",
    "PRODUCER_BOOLEAN_FIELDS",
    "PRODUCER_STORAGE_FIELDS",
    "READINESS_EVALUATOR_BUILD_TIMEOUT_SECONDS",
    "READINESS_EVALUATOR_PACKAGE",
    "READINESS_EVALUATOR_RUN_TIMEOUT_SECONDS",
    "READINESS_METADATA_DIR",
    "REPORT_BLIND_SPOT_REGISTRY_FIELD",
    "REPORT_GRAPH_FIELD",
    "RESULT",
    "ROOT",
    "RUN_DIR",
    "SERVICE_ROOT",
    "SHA256_PATTERN",
    "STATE_OWNER_KINDS",
    "STORAGE_EVIDENCE_FIELDS",
    "STRUCTURAL",
    "artifact_gaps",
    "artifact_integrity_gaps",
    "blind_spot_gaps",
    "bound_storages",
    "build_readiness_evaluator",
    "cells_from_gaps",
    "collect_gaps",
    "commercial_input_values",
    "decode_single_json_document",
    "derive_contract_graph",
    "digest_readiness_input",
    "display_path",
    "domain_event_declaration_gaps",
    "evaluate_dynamic_readiness",
    "evidence_class",
    "is_production_service_source",
    "load_blind_spot_registry",
    "load_blind_spot_registry_with_digest",
    "load_graph",
    "load_graph_with_digest",
    "main",
    "object_contract_dir",
    "page_claims_and_consumers",
    "parse_args",
    "partition_by_evidence_class",
    "print_blind_spots",
    "print_gap_inventory",
    "print_result_layer",
    "print_structural_gaps",
    "publication_gap_detail",
    "readiness_input_bindings",
    "resolve_repository_artifact",
    "runtime_execution_consumers",
    "select_graph_path",
    "sha256_file",
    "slice_owner_object",
    "unclassified_dimensions",
    "validate_contract_graph_shape",
    "validate_report_graph_binding",
    "validate_report_policy_bindings",
    "verify_graph_digest",
    "verify_optional_input_digest",
    "verify_readiness_input_bindings",
    "without_dart_non_code",
    "write_reports",
]


if __name__ == "__main__":
    sys.exit(main())
