// Code generated by generate_canonical_test_bridges.py. DO NOT EDIT.
package api_integration

import (
	"os/exec"
	"testing"
)

func TestHomepageBundleContractApiIntegrationTest(t *testing.T) {
	cmd := exec.Command(
		"go",
		"test",
		"..",
		"-run",
		"^(TestHomepageBundle_DoesNotLeakContentDomainFacts|TestHomepageBundle_GuestViewOmitsRelationshipCapability|TestHomepageBundle_OwnerViewAggregatesIdentityTruth|TestHomepageBundle_ProfileCarriesBackgroundAndNicknameCustomized|TestHomepageBundle_StrangerViewExposesRelationToTarget|TestHomepageBundle_StrictPersonaReturnsNotFound)$",
		"-count=1",
	)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("source bridge failed for quwoquan_service/services/user-service/tests/homepage_bundle_contract_test.go: %v\n%s", err, output)
	}
}
