// Code generated by generate_canonical_test_bridges.py. DO NOT EDIT.
package api_integration

import (
	"os/exec"
	"testing"
)

func TestPersonaContractApiIntegrationTest(t *testing.T) {
	cmd := exec.Command(
		"go",
		"test",
		"..",
		"-run",
		"^(TestActivatePersona_Transaction|TestApplyPersonaProfileSync_ReturnsAppliedCount|TestCreatePersona_Success|TestCreatePersona_UserHandleReadonly|TestDeleteEmptyPersona_HistoryRequiresRetireConflict|TestDeletePersona_PrimaryForbidden|TestGetPersonaLifecycleGuard_ActivePersonaRequiresSuccessor|TestGetPersonaLifecycleGuard_HistoryCoverageBySource|TestGetPersonaLifecycleGuard_HistoryRequiresRetire|TestGetPersonaLifecycleGuard_RecordsMongoHistoryFallbackMetric|TestGetPersonaManagementSummary_ReturnsQuotaAndActiveContext|TestRetirePersona_PersistsRetiredStatus|TestRetiredPersona_CannotBeActivatedOrUpdated|TestUpdatePersona_ReflectsManagementFields|TestUpdatePersona_UserHandleReadonly)$",
		"-count=1",
	)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("source bridge failed for quwoquan_service/services/user-service/tests/persona_contract_test.go: %v\n%s", err, output)
	}
}
