// Code generated by generate_canonical_test_bridges.py. DO NOT EDIT.
package api_integration

import (
	"os/exec"
	"testing"
)

func TestProfileSyncContractApiIntegrationTest(t *testing.T) {
	cmd := exec.Command(
		"go",
		"test",
		"..",
		"-run",
		"^(TestUpdateProfile_AvatarVersionAndSyncPatch|TestUpdateProfile_PublishesUserAvatarUpdatedEvent)$",
		"-count=1",
	)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("source bridge failed for quwoquan_service/services/user-service/tests/profile_sync_contract_test.go: %v\n%s", err, output)
	}
}
