// Code generated by generate_canonical_test_bridges.py. DO NOT EDIT.
package api_integration

import (
	"os/exec"
	"testing"
)

func TestProfileCrudContractApiIntegrationTest(t *testing.T) {
	cmd := exec.Command(
		"go",
		"test",
		"..",
		"-run",
		"^(TestGetProfileEditSnapshot_ReturnsCommercialFields|TestGetProfileQRCard_IssuesOpaqueResolvableToken|TestGetProfile_CacheHit|TestGetProfile_NotFound|TestGetProfile_Success|TestResolveProfileQRToken_InvalidToken|TestUpdateProfile_DuplicateNicknameAllowed|TestUpdateProfile_InvalidRegionTagRefReturnsInvalidRegion|TestUpdateProfile_RegionTagRefUpdatesDerivedDisplay|TestUpdateProfile_RejectsBareBackgroundURL|TestUpdateProfile_RejectsClientRegionDisplayWithoutTagRef|TestUpdateProfile_Success)$",
		"-count=1",
	)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("source bridge failed for quwoquan_service/services/user-service/tests/profile_crud_contract_test.go: %v\n%s", err, output)
	}
}
