// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../../ui/chat/providers/voice_send_provider_test.dart' as legacy_test;

void main() {
  legacy_test.main();
}
