// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../../ui/user/pages/lin_mo_travel_intersection_acceptance_test.dart' as source_0;

void main() {
  source_0.main();
}
