// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../../../ui/discovery/post/journeys/discovery_post_interaction_journey_test.dart' as legacy_test;

void main() {
  legacy_test.main();
}
