// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../core/trackers/feed_performance_observability_test.dart' as source_test;

void main() {
  source_test.main();
}
