from __future__ import annotations


def canonical_intersection_reason(
    *,
    intersection_id: str = "intersection-001",
    subject_id: str = "persona-001",
    intersection_class: str = "fact",
) -> dict[str, object]:
    return {
        "kind": "sharedFollowees",
        "vertical": "general",
        "dimension": "relationship",
        "tagRefs": [],
        "relationKind": "follow",
        "objectKind": "person",
        "relationObjectId": "persona-002",
        "strength": 1.0,
        "primaryText": "你关注的人也关注了这里",
        "primaryTextL10nKey": "",
        "displayBinding": "host_implicit",
        "secondaryText": "",
        "weightTier": "heavy",
        "actionType": "view_object",
        "actionTargetId": "persona-002",
        "source": "relationship",
        "intersectionId": intersection_id,
        "intersectionClass": intersection_class,
        "avatarUrl": "",
        "displayName": "",
        "confidenceLabel": "",
        "modelReasonBucket": "",
        "freshAt": "2026-08-02T12:00:00Z",
        "expiresAt": "2026-08-09T12:00:00Z",
        "intersectionPoints": [],
        "pointSummarySnapshotId": "snapshot-001",
        "actorEvidenceTotalCount": 0,
        "actorEvidenceCompleteness": "complete",
        "actorEvidence": [],
        "factPointCount": 1,
        "recommendedPointCount": 0,
        "totalPointCount": 1,
        "dimensionPointSummary": [],
        "pointClassLabel": "事实交集",
        "connectionSummary": "",
        "lastRecommendedAt": "",
        "seenAt": "",
        "rankState": "fresh",
        "primarySpans": [],
        "sampleVisuals": [],
        "representativeActor": None,
        "actionHints": [],
        "lifecycleState": "active",
        "previousStrength": 0.0,
        "strengthDelta": 1.0,
        "edgeWeight": 1.0,
        "iconKey": "relationship",
        "tone": "sage",
        "typeVisual": None,
        "objectVisual": None,
        "timeBucket": "current",
        "dedupeKey": "relationship:persona-002",
        "anchorUserWeight": 1.0,
        "mutualCount": 1,
        "moment": "current",
        "subjectId": subject_id,
        "subjectContext": "feed",
    }
