// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../components/input/customizable_chat_input_bar_test.dart' as legacy_test;

void main() {
  legacy_test.main();
}
