// Code generated by generate_canonical_test_bridges.py. DO NOT EDIT.
package local_contract

import (
	"os/exec"
	"testing"
)

func TestLocationHandlerLocalContractTest(t *testing.T) {
	cmd := exec.Command(
		"go",
		"test",
		"../../../../../internal/adapters/http",
		"-run",
		"^(TestNearbyBothProvidersFailReturns500WithIntegrationErrorCode|TestNearbyNoProvidersReturns400WithLocationUnavailableCode|TestNearbyTimeoutReturns504WithUpstreamTimeoutCode|TestNearbyUsesDefaultCenterWhenLatLngMissing|TestSearchEmptyQueryReturnsBadRequest|TestSubmitExternalInteractionReturnsAcceptedAndRecordsAttempt)$",
		"-count=1",
	)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("source bridge failed for quwoquan_service/services/integration-service/internal/adapters/http/location_handler_test.go: %v\n%s", err, output)
	}
}
