// Command codegen_rec_policy captures a compile-time snapshot of the
// recommendation scoring policy metadata
// (contracts/metadata/recommendation/rec_model/policy.yaml) as a generated Go
// file in runtime/recpolicy. The snapshot is the fail-safe Baseline used when no
// live policy file is configured or a hot-reload candidate fails validation.
//
// The generated file embeds the YAML verbatim (single source) plus the
// captured policyVersion; the strong types, validation, and resolution logic
// live in hand-written, unit-tested recpolicy code (not in the generated file).
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strconv"

	"gopkg.in/yaml.v3"
)

func main() {
	var metadataDir, outDir string
	flag.StringVar(&metadataDir, "metadata-dir", "contracts/metadata", "metadata root directory")
	flag.StringVar(&outDir, "out-dir", "runtime/recpolicy", "Go output directory (recpolicy package)")
	flag.Parse()

	src := filepath.Join(metadataDir, "recommendation", "rec_model", "policy.yaml")
	raw, err := os.ReadFile(src)
	must(err)

	var meta struct {
		PolicyVersion string `yaml:"policyVersion"`
	}
	must(yaml.Unmarshal(raw, &meta))
	if meta.PolicyVersion == "" {
		fail("policy.yaml missing policyVersion")
	}

	content := fmt.Sprintf(`// Code generated by codegen_rec_policy. DO NOT EDIT.
// Source: contracts/metadata/recommendation/rec_model/policy.yaml

package recpolicy

// BaselinePolicyVersion is the policyVersion captured at codegen time.
const BaselinePolicyVersion = %q

// baselinePolicyYAML is a compile-time snapshot of policy.yaml, used as the
// fail-safe baseline when no live policy file is configured or a hot-reload
// candidate fails validation. Single source: the metadata YAML referenced above.
const baselinePolicyYAML = %s
`, meta.PolicyVersion, goStringLiteral(string(raw)))

	out := filepath.Join(outDir, "rec_policy_baseline.gen.go")
	must(os.WriteFile(out, []byte(content), 0o644))
	fmt.Printf("codegen_rec_policy: wrote %s (policyVersion=%s)\n", out, meta.PolicyVersion)
}

// goStringLiteral renders s as a Go string literal, preferring a raw (backtick)
// literal for readability and falling back to a quoted literal if s contains a
// backtick (which a raw literal cannot represent).
func goStringLiteral(s string) string {
	for i := 0; i < len(s); i++ {
		if s[i] == '`' {
			return strconv.Quote(s)
		}
	}
	return "`" + s + "`"
}

func must(err error) {
	if err != nil {
		fail(err.Error())
	}
}

func fail(msg string) {
	fmt.Fprintln(os.Stderr, "codegen_rec_policy: "+msg)
	os.Exit(1)
}
