"""travel-service -> Gathering 的 target-only 迁移证据控制面。

本模块只读取显式快照、canonical generated ContractGraph 与外部签名回执，只把
脱敏的证据/审批计划写入 ``QWQ_OUTPUT_ROOT``。它不包含数据库客户端、HTTP 写入口，
也不在本进程执行 cutover 或 rollback 环境写入。

实现单轨落在 ``control_plane_lib/`` 包内（constants / codec / target_contract /
snapshots / contract_validation / mapping_support / mapping / parity / evidence /
receipts / control_receipts / cli）；本文件是稳定模块入口，
``from quwoquan_ops.migrations.travel_to_gathering import control_plane`` 的
全部既有顶层符号（含测试消费的私有 ``_`` 符号）由这里 re-export，
``stackctl migration`` 经 ``register_parser`` / ``command`` 外挂注册的消费形态
保持不变。
"""

from __future__ import annotations

from quwoquan_ops.migrations.travel_to_gathering.control_plane_lib import (  # noqa: F401
    CANONICAL_TARGET_OBJECT_IDS,
    COMMAND_NAME,
    CONTROL_PHASES,
    CROSSWALK_PATH,
    DIGEST_RE,
    DISPOSITIONS,
    EMAIL_RE,
    ENVIRONMENTS,
    EVIDENCE_PHASES,
    HEX_DIGEST_RE,
    IDENTITY_KEY_RE,
    MIGRATION_ID,
    OPERATIONAL_EVIDENCE_SCHEMA,
    OPERATIONAL_EVIDENCE_TYPES,
    PHASES,
    PHONE_RE,
    RECEIPT_SCHEMA,
    REQUIRED_TARGET_OPERATION_IDS,
    ROLLBACK_MODES,
    ROOT,
    SAFE_WRITE_PLANES,
    SENSITIVE_KEY_RE,
    SOURCE_OBJECT_TYPES,
    SOURCE_SNAPSHOT_SCHEMA,
    SOURCE_STATUS_VALUES,
    TARGET_CONTRACT_BINDINGS,
    TARGET_CONTRACT_GRAPH,
    TARGET_GENERATED_MODELS,
    TARGET_OWNER_CONTRACT_FILENAMES,
    TARGET_SNAPSHOT_SCHEMA,
    TARGET_WRITE_SERVICES,
    TIMEZONE_RE,
    MappingResult,
    MigrationControlError,
    TargetContractBinding,
    _assert_generated_model_matches_fields,
    _assert_receipt_chain,
    _availability_sections,
    _binding_trip_id,
    _canonical_object_ref,
    _constraints,
    _control_receipt_base,
    _count_references,
    _dedupe_blockers,
    _dimension_projection,
    _disposition_summary,
    _duration_minutes,
    _ensure_output_path,
    _evidence_ref,
    _file_digest,
    _identity_digest,
    _index_objects,
    _load_migration_receipt,
    _load_object,
    _load_operational_evidence,
    _map_lifecycle_status,
    _map_membership_closed_reason,
    _map_plan_item,
    _mapping_record,
    _new_conflicts,
    _parse_timestamp,
    _pii_redaction_report,
    _record_conflict,
    _report_dir,
    _require_digest,
    _require_nonblank,
    _required_cli_path,
    _safe_blocker,
    _seal_receipt,
    _snapshot_digest,
    _source_object_id,
    _status_key,
    _target_plan_id,
    _target_revision_id,
    _trip_binding_issues,
    _validate_contract_document,
    _validate_control_write_set,
    _validate_external_evidence_write_set,
    _validate_field_value,
    _validate_scalar_type,
    build_cutover_receipt,
    build_inventory,
    build_mapping,
    build_parity,
    build_receipt,
    build_rollback_receipt,
    canonical_digest,
    command,
    execute,
    load_source_snapshot,
    load_target_snapshot,
    register_parser,
    resolve_target_contract,
    validate_gathering_document,
    validate_receipt,
)

__all__ = [
    "COMMAND_NAME",
    "DISPOSITIONS",
    "ENVIRONMENTS",
    "MIGRATION_ID",
    "SOURCE_OBJECT_TYPES",
    "SOURCE_SNAPSHOT_SCHEMA",
    "TARGET_SNAPSHOT_SCHEMA",
    "MigrationControlError",
    "TargetContractBinding",
    "build_cutover_receipt",
    "build_inventory",
    "build_mapping",
    "build_parity",
    "build_receipt",
    "build_rollback_receipt",
    "canonical_digest",
    "command",
    "execute",
    "load_source_snapshot",
    "load_target_snapshot",
    "register_parser",
    "resolve_target_contract",
    "validate_gathering_document",
    "validate_receipt",
]
