// Code generated by runtime/codegen. DO NOT EDIT.
package post

import "time"

// GeoPoint represents a geographic coordinate.
type GeoPoint struct {
	Latitude  float64 `json:"latitude" bson:"latitude"`
	Longitude float64 `json:"longitude" bson:"longitude"`
}

var _ = time.Now

// ContentReaction domain model.
type ContentReaction struct {
	ID          string    `json:"_id" bson:"_id"`
	PostId      string    `json:"postId" bson:"postId"`
	UserId      string    `json:"userId" bson:"userId"`
	Liked       bool      `json:"liked" bson:"liked"`
	Favorited   bool      `json:"favorited" bson:"favorited"`
	Shared      bool      `json:"shared" bson:"shared"`
	Reported    bool      `json:"reported" bson:"reported"`
	LikedAt     time.Time `json:"likedAt" bson:"likedAt"`
	FavoritedAt time.Time `json:"favoritedAt" bson:"favoritedAt"`
	UpdatedAt   time.Time `json:"updatedAt" bson:"updatedAt"`
}

// PostCircleDistribution domain model.
type PostCircleDistribution struct {
	ID            string    `json:"_id" bson:"_id"`
	PostId        string    `json:"postId" bson:"postId"`
	OwnerAuthorId string    `json:"ownerAuthorId" bson:"ownerAuthorId"`
	CircleId      string    `json:"circleId" bson:"circleId"`
	State         string    `json:"state" bson:"state"`
	CreatedAt     time.Time `json:"createdAt" bson:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt" bson:"updatedAt"`
}

// PostCircleReshare domain model.
type PostCircleReshare struct {
	ID             string    `json:"_id" bson:"_id"`
	PostId         string    `json:"postId" bson:"postId"`
	SourcePostId   string    `json:"sourcePostId" bson:"sourcePostId"`
	ResharerUserId string    `json:"resharerUserId" bson:"resharerUserId"`
	CircleId       string    `json:"circleId" bson:"circleId"`
	QuoteText      string    `json:"quoteText" bson:"quoteText"`
	State          string    `json:"state" bson:"state"`
	CreatedAt      time.Time `json:"createdAt" bson:"createdAt"`
	UpdatedAt      time.Time `json:"updatedAt" bson:"updatedAt"`
}

// DeletedPostTombstone domain model.
type DeletedPostTombstone struct {
	ID        string    `json:"_id" bson:"_id"`
	PostId    string    `json:"postId" bson:"postId"`
	AuthorId  string    `json:"authorId" bson:"authorId"`
	Reason    string    `json:"reason" bson:"reason"`
	DeletedAt time.Time `json:"deletedAt" bson:"deletedAt"`
	ExpireAt  time.Time `json:"expireAt" bson:"expireAt"`
}

// Post domain model.
type Post struct {
	ID                  string         `json:"_id" bson:"_id"`
	AuthorId            string         `json:"authorId" bson:"authorId"`
	PersonaId           string         `json:"personaId" bson:"personaId"`
	ContentType         string         `json:"contentType" bson:"contentType"`
	ContentIdentity     string         `json:"contentIdentity" bson:"contentIdentity"`
	Title               string         `json:"title" bson:"title"`
	Body                string         `json:"body" bson:"body"`
	Tags                any            `json:"tags" bson:"tags"`
	MediaUrls           any            `json:"mediaUrls" bson:"mediaUrls"`
	CoverUrl            string         `json:"coverUrl" bson:"coverUrl"`
	VideoUrl            string         `json:"videoUrl" bson:"videoUrl"`
	Location            GeoPoint       `json:"location" bson:"location"`
	LocationName        string         `json:"locationName" bson:"locationName"`
	Status              string         `json:"status" bson:"status"`
	Visibility          string         `json:"visibility" bson:"visibility"`
	AssistantUsePolicy  string         `json:"assistantUsePolicy" bson:"assistantUsePolicy"`
	CircleId            string         `json:"circleId" bson:"circleId"`
	CircleIds           any            `json:"circleIds" bson:"circleIds"`
	SourcePostId        string         `json:"sourcePostId" bson:"sourcePostId"`
	SourceType          string         `json:"sourceType" bson:"sourceType"`
	Summary             string         `json:"summary" bson:"summary"`
	IllustrationAssetId string         `json:"illustrationAssetId" bson:"illustrationAssetId"`
	PublishLocation     map[string]any `json:"publishLocation" bson:"publishLocation"`
	DeviceInfo          map[string]any `json:"deviceInfo" bson:"deviceInfo"`
	LikeCount           int64          `json:"likeCount" bson:"likeCount"`
	CommentCount        int64          `json:"commentCount" bson:"commentCount"`
	FavoriteCount       int64          `json:"favoriteCount" bson:"favoriteCount"`
	ShareCount          int64          `json:"shareCount" bson:"shareCount"`
	ViewCount           int64          `json:"viewCount" bson:"viewCount"`
	Embedding           any            `json:"embedding" bson:"embedding"`
	HelperReadSummary   string         `json:"helperReadSummary" bson:"helperReadSummary"`
	ModerationStatus    string         `json:"moderationStatus" bson:"moderationStatus"`
	CreatedAt           time.Time      `json:"createdAt" bson:"createdAt"`
	UpdatedAt           time.Time      `json:"updatedAt" bson:"updatedAt"`
	PublishedAt         time.Time      `json:"publishedAt" bson:"publishedAt"`
	DeletedAt           time.Time      `json:"deletedAt" bson:"deletedAt"`
}

// Comment domain model.
type Comment struct {
	ID               string    `json:"_id" bson:"_id"`
	PostId           string    `json:"postId" bson:"postId"`
	AuthorId         string    `json:"authorId" bson:"authorId"`
	PersonaId        string    `json:"personaId" bson:"personaId"`
	Content          string    `json:"content" bson:"content"`
	ReplyToCommentId string    `json:"replyToCommentId" bson:"replyToCommentId"`
	ReplyToUserId    string    `json:"replyToUserId" bson:"replyToUserId"`
	ReplyCount       int64     `json:"replyCount" bson:"replyCount"`
	LikeCount        int64     `json:"likeCount" bson:"likeCount"`
	Status           string    `json:"status" bson:"status"`
	CreatedAt        time.Time `json:"createdAt" bson:"createdAt"`
}

// MediaAsset domain model.
type MediaAsset struct {
	ID                 string    `json:"_id" bson:"_id"`
	PostId             string    `json:"postId" bson:"postId"`
	Type               string    `json:"type" bson:"type"`
	OriginUrl          string    `json:"originUrl" bson:"originUrl"`
	CdnUrl             string    `json:"cdnUrl" bson:"cdnUrl"`
	ThumbnailUrl       string    `json:"thumbnailUrl" bson:"thumbnailUrl"`
	Width              int64     `json:"width" bson:"width"`
	Height             int64     `json:"height" bson:"height"`
	DurationMs         int64     `json:"durationMs" bson:"durationMs"`
	FileSizeBytes      int64     `json:"fileSizeBytes" bson:"fileSizeBytes"`
	MimeType           string    `json:"mimeType" bson:"mimeType"`
	Status             string    `json:"status" bson:"status"`
	ModerationStatus   string    `json:"moderationStatus" bson:"moderationStatus"`
	Derivatives        any       `json:"derivatives" bson:"derivatives"`
	CoverStrategy      string    `json:"coverStrategy" bson:"coverStrategy"`
	ManualCoverAssetId string    `json:"manualCoverAssetId" bson:"manualCoverAssetId"`
	CreatedAt          time.Time `json:"createdAt" bson:"createdAt"`
	UpdatedAt          time.Time `json:"updatedAt" bson:"updatedAt"`
}
