// Code generated by internal/metadata/codegen. DO NOT EDIT.
package post

import "time"

// GeoPoint represents a geographic coordinate.
type GeoPoint struct {
	Latitude  float64 `json:"latitude" bson:"latitude"`
	Longitude float64 `json:"longitude" bson:"longitude"`
}

var _ = time.Now

// ClosedAccountAudit domain model.
type ClosedAccountAudit struct {
	ID             string    `json:"id" bson:"_id"`
	EventDigest    string    `json:"eventDigest" bson:"eventDigest"`
	AccountVersion int64     `json:"accountVersion" bson:"accountVersion"`
	SubjectCount   int64     `json:"subjectCount" bson:"subjectCount"`
	ClosedAt       time.Time `json:"closedAt" bson:"closedAt"`
	RecordedAt     time.Time `json:"recordedAt" bson:"recordedAt"`
}

// ClosedAccountSubjectTombstone domain model.
type ClosedAccountSubjectTombstone struct {
	ID             string    `json:"id" bson:"_id"`
	EventDigest    string    `json:"eventDigest" bson:"eventDigest"`
	AccountVersion int64     `json:"accountVersion" bson:"accountVersion"`
	ClosedAt       time.Time `json:"closedAt" bson:"closedAt"`
	RecordedAt     time.Time `json:"recordedAt" bson:"recordedAt"`
}

// DeletedPostTombstone domain model.
type DeletedPostTombstone struct {
	ID        string    `json:"id" bson:"_id"`
	PostId    string    `json:"postId" bson:"postId"`
	AuthorId  string    `json:"authorId" bson:"authorId"`
	Reason    string    `json:"reason" bson:"reason"`
	DeletedAt time.Time `json:"deletedAt" bson:"deletedAt"`
	ExpireAt  time.Time `json:"expireAt" bson:"expireAt"`
}

// Post domain model.
type Post struct {
	ID                        string         `json:"id" bson:"_id"`
	Version                   int64          `json:"version" bson:"version"`
	PublishIntentId           string         `json:"publishIntentId" bson:"publishIntentId"`
	LocalDraftId              string         `json:"localDraftId" bson:"localDraftId"`
	AuthorId                  string         `json:"authorId" bson:"authorId"`
	CreatorProfileId          string         `json:"creatorProfileId" bson:"creatorProfileId"`
	CreatorArchetype          string         `json:"creatorArchetype" bson:"creatorArchetype"`
	CreatorProfileVersion     string         `json:"creatorProfileVersion" bson:"creatorProfileVersion"`
	CreatorDisclosure         map[string]any `json:"creatorDisclosure" bson:"creatorDisclosure"`
	SourceAttribution         any            `json:"sourceAttribution" bson:"sourceAttribution"`
	ExperienceClaimMode       string         `json:"experienceClaimMode" bson:"experienceClaimMode"`
	AuthorQualitySignals      map[string]any `json:"authorQualitySignals" bson:"authorQualitySignals"`
	AuthorDisplayNameSnapshot string         `json:"authorDisplayNameSnapshot" bson:"authorDisplayNameSnapshot"`
	AuthorAvatarUrlSnapshot   string         `json:"authorAvatarUrlSnapshot" bson:"authorAvatarUrlSnapshot"`
	PersonaContextVersion     int64          `json:"personaContextVersion" bson:"personaContextVersion"`
	ContentType               string         `json:"contentType" bson:"contentType"`
	ContentIdentity           string         `json:"contentIdentity" bson:"contentIdentity"`
	Title                     string         `json:"title" bson:"title"`
	Body                      string         `json:"body" bson:"body"`
	TagRefs                   []string       `json:"tagRefs" bson:"tagRefs"`
	EntityRefs                []string       `json:"entityRefs" bson:"entityRefs"`
	SemanticMentions          any            `json:"semanticMentions" bson:"semanticMentions"`
	MediaAssetIds             []string       `json:"mediaAssetIds" bson:"mediaAssetIds"`
	MediaUrls                 []string       `json:"mediaUrls" bson:"mediaUrls"`
	MediaItems                any            `json:"mediaItems" bson:"mediaItems"`
	CoverUrl                  string         `json:"coverUrl" bson:"coverUrl"`
	ThumbnailUrl              string         `json:"thumbnailUrl" bson:"thumbnailUrl"`
	ArticleMarkdown           string         `json:"articleMarkdown" bson:"articleMarkdown"`
	MarkdownDialect           string         `json:"markdownDialect" bson:"markdownDialect"`
	ArticleMarkdownDigest     string         `json:"articleMarkdownDigest" bson:"articleMarkdownDigest"`
	ArticleAssetManifest      map[string]any `json:"articleAssetManifest" bson:"articleAssetManifest"`
	ArticleRenderProfile      map[string]any `json:"articleRenderProfile" bson:"articleRenderProfile"`
	ContentVertical           string         `json:"contentVertical" bson:"contentVertical"`
	EntityMentions            any            `json:"entityMentions" bson:"entityMentions"`
	ArticleTemplate           string         `json:"articleTemplate" bson:"articleTemplate"`
	ArticleFontPreset         string         `json:"articleFontPreset" bson:"articleFontPreset"`
	VideoUrl                  string         `json:"videoUrl" bson:"videoUrl"`
	Width                     int64          `json:"width" bson:"width"`
	Height                    int64          `json:"height" bson:"height"`
	DurationMs                int64          `json:"durationMs" bson:"durationMs"`
	CoverStrategy             string         `json:"coverStrategy" bson:"coverStrategy"`
	CoverFrameTimeMs          int64          `json:"coverFrameTimeMs" bson:"coverFrameTimeMs"`
	Location                  GeoPoint       `json:"location" bson:"location"`
	LocationName              string         `json:"locationName" bson:"locationName"`
	PrimaryHomepageId         string         `json:"primaryHomepageId" bson:"primaryHomepageId"`
	PrimaryHomepageType       string         `json:"primaryHomepageType" bson:"primaryHomepageType"`
	PrimaryHomepageSnapshot   map[string]any `json:"primaryHomepageSnapshot" bson:"primaryHomepageSnapshot"`
	Status                    string         `json:"status" bson:"status"`
	Visibility                string         `json:"visibility" bson:"visibility"`
	AssistantUsePolicy        string         `json:"assistantUsePolicy" bson:"assistantUsePolicy"`
	SourcePostId              string         `json:"sourcePostId" bson:"sourcePostId"`
	SourceType                string         `json:"sourceType" bson:"sourceType"`
	Summary                   string         `json:"summary" bson:"summary"`
	IllustrationAssetId       string         `json:"illustrationAssetId" bson:"illustrationAssetId"`
	PublishLocation           map[string]any `json:"publishLocation" bson:"publishLocation"`
	DeviceInfo                map[string]any `json:"deviceInfo" bson:"deviceInfo"`
	LikeCount                 int64          `json:"likeCount" bson:"likeCount"`
	CommentCount              int64          `json:"commentCount" bson:"commentCount"`
	PinnedCommentId           string         `json:"pinnedCommentId" bson:"pinnedCommentId"`
	ShareCount                int64          `json:"shareCount" bson:"shareCount"`
	ViewCount                 int64          `json:"viewCount" bson:"viewCount"`
	Embedding                 any            `json:"embedding" bson:"embedding"`
	HelperReadSummary         string         `json:"helperReadSummary" bson:"helperReadSummary"`
	ModerationStatus          string         `json:"moderationStatus" bson:"moderationStatus"`
	ContentDigest             string         `json:"contentDigest" bson:"contentDigest"`
	CreatedAt                 time.Time      `json:"createdAt" bson:"createdAt"`
	UpdatedAt                 time.Time      `json:"updatedAt" bson:"updatedAt"`
	PublishedAt               time.Time      `json:"publishedAt" bson:"publishedAt"`
	LastActiveAt              time.Time      `json:"lastActiveAt" bson:"lastActiveAt"`
	SourceTaskId              string         `json:"sourceTaskId" bson:"sourceTaskId"`
	DeletedAt                 time.Time      `json:"deletedAt" bson:"deletedAt"`
}

// UserAccountClosedProjectionFailure domain model.
type UserAccountClosedProjectionFailure struct {
	ID           string    `json:"id" bson:"_id"`
	EventDigest  string    `json:"eventDigest" bson:"eventDigest"`
	ErrorDigest  string    `json:"errorDigest" bson:"errorDigest"`
	Attempts     int64     `json:"attempts" bson:"attempts"`
	CreatedAt    time.Time `json:"createdAt" bson:"createdAt"`
	LastFailedAt time.Time `json:"lastFailedAt" bson:"lastFailedAt"`
	ExpireAt     time.Time `json:"expireAt" bson:"expireAt"`
}

// UserAccountClosedProjectionInbox domain model.
type UserAccountClosedProjectionInbox struct {
	ID             string    `json:"id" bson:"_id"`
	EventDigest    string    `json:"eventDigest" bson:"eventDigest"`
	AccountVersion int64     `json:"accountVersion" bson:"accountVersion"`
	MongoAppliedAt time.Time `json:"mongoAppliedAt" bson:"mongoAppliedAt"`
	CompletedAt    time.Time `json:"completedAt" bson:"completedAt"`
}

// UserAccountClosedSearchWork domain model.
type UserAccountClosedSearchWork struct {
	ID          string    `json:"id" bson:"_id"`
	EventId     string    `json:"eventId" bson:"eventId"`
	CanonicalId string    `json:"canonicalId" bson:"canonicalId"`
	ObjectType  string    `json:"objectType" bson:"objectType"`
	ObjectId    string    `json:"objectId" bson:"objectId"`
	CreatedAt   time.Time `json:"createdAt" bson:"createdAt"`
	DoneAt      time.Time `json:"doneAt" bson:"doneAt"`
	ExpireAt    time.Time `json:"expireAt" bson:"expireAt"`
}
