// Codegen for recommendation-service Python: reads ModelRelease metadata and projections,
// then generates pure operation descriptors and Pydantic contracts.
package main

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"

	contractcodegen "quwoquan_service/internal/metadata/codegen"
	"quwoquan_service/internal/metadata/validate"
)

const (
	genHeader = "# Code generated by tools/codegen_rec_model_python. DO NOT EDIT.\n"
)

func main() {
	metadataDir := flag.String("metadata-dir", "contracts/metadata", "metadata root directory")
	outputDir := flag.String("output-dir", "services/recommendation-service/internal/recommendation/recommendation_model_release/generated", "Python generated output directory")
	serviceDir := flag.String("service-dir", "recommendation/recommendation/recommendation_model_release", "service metadata directory")
	contentRankedWindowGoOutput := flag.String(
		"content-ranked-window-go-output",
		"services/content-service/generated/content/feed_delivery_page/recommendation_ranked_window.g.go",
		"generated Content-side Go transport derived from RankedRecommendationWindow",
	)
	contentFeatureProfileGoOutput := flag.String(
		"content-feature-profile-go-output",
		"services/content-service/generated/content/post/recommendation_feature_profile.g.go",
		"generated Content-side Go transport derived from RecommendationFeatureProfileView",
	)
	flag.Parse()

	if err := run(
		*metadataDir,
		*outputDir,
		*serviceDir,
		*contentRankedWindowGoOutput,
		*contentFeatureProfileGoOutput,
	); err != nil {
		fmt.Fprintf(os.Stderr, "codegen_rec_model_python: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("generated Python code at %s\n", *outputDir)
}

func run(
	metadataDir,
	outputDir,
	serviceDir,
	contentRankedWindowGoOutput,
	contentFeatureProfileGoOutput string,
) error {
	source, err := contractcodegen.NewSource(metadataDir, validate.ProfileBaseline)
	if err != nil {
		return fmt.Errorf("compile ContractGraph: %w", err)
	}
	servicePath := serviceDir
	projectionsPath := filepath.Join(servicePath, "projections")

	fields, err := loadFields(source, filepath.Join(servicePath, "fields.yaml"))
	if err != nil {
		return fmt.Errorf("load fields: %w", err)
	}
	operations, err := loadOperations(source, filepath.Join(servicePath, "operations.yaml"))
	if err != nil {
		return fmt.Errorf("load operations: %w", err)
	}

	projections, err := loadProjections(source, projectionsPath)
	if err != nil {
		return fmt.Errorf("load projections: %w", err)
	}

	if err := os.MkdirAll(filepath.Join(outputDir, "models"), 0755); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Join(outputDir, "api"), 0755); err != nil {
		return err
	}
	operationsPy := generateOperationsPy(operations)
	if err := os.WriteFile(filepath.Join(outputDir, "api", "operations.py"), []byte(operationsPy), 0644); err != nil {
		return err
	}

	reqRespPy := generateRequestResponsePy(fields)
	if err := os.WriteFile(filepath.Join(outputDir, "models", "request_response.py"), []byte(reqRespPy), 0644); err != nil {
		return err
	}

	projPy := generateProjectionsPy(projections)
	if err := os.WriteFile(filepath.Join(outputDir, "models", "projections.py"), []byte(projPy), 0644); err != nil {
		return err
	}

	modelsInit := generateModelsInit(projections)
	if err := os.WriteFile(filepath.Join(outputDir, "models", "__init__.py"), []byte(modelsInit), 0644); err != nil {
		return err
	}

	if err := os.Remove(filepath.Join(outputDir, "api", "routes.py")); err != nil && !os.IsNotExist(err) {
		return err
	}

	schemasPy := generateSchemasPy(fields)
	if err := os.WriteFile(filepath.Join(outputDir, "api", "schemas.py"), []byte(schemasPy), 0644); err != nil {
		return err
	}

	apiInit := generateAPIInit()
	if err := os.WriteFile(filepath.Join(outputDir, "api", "__init__.py"), []byte(apiInit), 0644); err != nil {
		return err
	}

	rootInit := generateRootInit()
	if err := os.WriteFile(filepath.Join(outputDir, "__init__.py"), []byte(rootInit), 0644); err != nil {
		return err
	}

	rankedWindowPath := filepath.Join(filepath.Dir(servicePath), "ranked_recommendation_window")
	if source.Has(filepath.Join(rankedWindowPath, "fields.yaml")) {
		rankedOutputDir := filepath.Join(filepath.Dir(outputDir), "ranked_recommendation_window")
		if err := generateObjectTransportPackage(
			source,
			rankedWindowPath,
			rankedOutputDir,
			rankedWindowTransportOrder,
		); err != nil {
			return fmt.Errorf("generate ranked recommendation window: %w", err)
		}
		if strings.TrimSpace(contentRankedWindowGoOutput) != "" {
			rankedFields, err := loadFields(
				source,
				filepath.Join(rankedWindowPath, "fields.yaml"),
			)
			if err != nil {
				return fmt.Errorf("load ranked recommendation window Go fields: %w", err)
			}
			rankedOperations, err := loadOperations(
				source,
				filepath.Join(rankedWindowPath, "operations.yaml"),
			)
			if err != nil {
				return fmt.Errorf("load ranked recommendation window Go operations: %w", err)
			}
			if err := writeRankedWindowGoTransport(
				contentRankedWindowGoOutput,
				rankedFields,
				rankedOperations,
			); err != nil {
				return fmt.Errorf("generate Content ranked window Go transport: %w", err)
			}
		}
	}

	featureProfilePath := filepath.Join(filepath.Dir(servicePath), "recommendation_feature_profile_view")
	if source.Has(filepath.Join(featureProfilePath, "fields.yaml")) {
		featureProfileOutputDir := filepath.Join(
			filepath.Dir(outputDir),
			"recommendation_feature_profile_view",
		)
		if err := generateObjectTransportPackage(
			source,
			featureProfilePath,
			featureProfileOutputDir,
			featureProfileTransportOrder,
		); err != nil {
			return fmt.Errorf("generate recommendation feature profile view: %w", err)
		}
		if strings.TrimSpace(contentFeatureProfileGoOutput) != "" {
			featureFields, err := loadFields(
				source,
				filepath.Join(featureProfilePath, "fields.yaml"),
			)
			if err != nil {
				return fmt.Errorf("load recommendation feature profile Go fields: %w", err)
			}
			if err := mergeProjectionEntities(source, featureProfilePath, featureFields); err != nil {
				return fmt.Errorf("load recommendation feature profile projections: %w", err)
			}
			featureOperations, err := loadOperations(
				source,
				filepath.Join(featureProfilePath, "operations.yaml"),
			)
			if err != nil {
				return fmt.Errorf("load recommendation feature profile Go operations: %w", err)
			}
			if err := writeFeatureProfileGoTransport(
				contentFeatureProfileGoOutput,
				featureFields,
				featureOperations,
			); err != nil {
				return fmt.Errorf("generate Content feature profile Go transport: %w", err)
			}
		}
	}

	// Generate content features + training sample from
	// content/content/content_behavior_fact/behaviors.yaml
	behaviorsPath := resolveContentBehaviors(source)
	if behaviorsPath != "" {
		beh, err := loadBehaviors(source, behaviorsPath)
		if err == nil && beh != nil {
			if beh.RecommendFeatures.PythonClass != "" {
				featuresPy := generateContentFeaturesPy(beh)
				featsPath := filepath.Join(outputDir, "content_features.py")
				if err := os.WriteFile(featsPath, []byte(featuresPy), 0644); err != nil {
					return err
				}
				fmt.Printf("generated: %s\n", featsPath)
			}
			if beh.TrainingSample.PythonClass != "" {
				samplePy := generateTrainingSamplePy(beh)
				samplePath := filepath.Join(outputDir, "training_sample.py")
				if err := os.WriteFile(samplePath, []byte(samplePy), 0644); err != nil {
					return err
				}
				fmt.Printf("generated: %s\n", samplePath)
			}
		}
	}

	return nil
}

func writeRankedWindowGoTransport(
	outputPath string,
	fields *fieldsFile,
	operations *operationsFile,
) error {
	generated, err := format.Source([]byte(generateRankedWindowGoTransport(fields, operations)))
	if err != nil {
		return fmt.Errorf("format generated Go transport: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(outputPath), 0755); err != nil {
		return err
	}
	return os.WriteFile(outputPath, generated, 0644)
}

func generateRankedWindowGoTransport(
	fields *fieldsFile,
	operations *operationsFile,
) string {
	var b strings.Builder
	b.WriteString("// Code generated by tools/codegen_rec_model_python. DO NOT EDIT.\n")
	b.WriteString("// Source: recommendation-service/contracts/recommendation/ranked_recommendation_window.\n\n")
	b.WriteString("package feeddeliverypage\n\n")
	b.WriteString("import \"time\"\n\n")
	for _, route := range operations.APIRoutes {
		name := route.Operation
		b.WriteString(fmt.Sprintf("const %sPath = %q\n", name, route.Path))
		b.WriteString(fmt.Sprintf("const %sMethod = %q\n", name, strings.ToUpper(route.Method)))
	}
	entityNames := make(map[string]bool, len(fields.Entities))
	for name := range fields.Entities {
		entityNames[name] = true
	}
	for _, name := range rankedWindowTransportOrder {
		entity, ok := fields.Entities[name]
		if !ok {
			continue
		}
		b.WriteString(fmt.Sprintf("\ntype %s struct {\n", name))
		for _, field := range entity.Fields {
			b.WriteString(fmt.Sprintf(
				"\t%s %s `json:%q`\n",
				goExportedName(field.Name),
				goTransportType(field.Type, isRequired(field.Constraints), entityNames),
				field.Name+goJSONOmitEmpty(field.Constraints),
			))
		}
		b.WriteString("}\n")
	}
	for _, route := range operations.APIRoutes {
		if route.RequestEntity == "" || len(route.RequestBindings.Injected) == 0 {
			continue
		}
		entity, ok := fields.Entities[route.RequestEntity]
		if !ok {
			continue
		}
		injected := make(map[string]struct{}, len(route.RequestBindings.Injected))
		for _, binding := range route.RequestBindings.Injected {
			injected[strings.TrimSpace(binding.Field)] = struct{}{}
		}
		b.WriteString(fmt.Sprintf("\ntype %sRequestBody struct {\n", route.Operation))
		for _, field := range entity.Fields {
			if _, excluded := injected[field.Name]; excluded {
				continue
			}
			b.WriteString(fmt.Sprintf(
				"\t%s %s `json:%q`\n",
				goExportedName(field.Name),
				goTransportType(field.Type, isRequired(field.Constraints), entityNames),
				field.Name+goJSONOmitEmpty(field.Constraints),
			))
		}
		b.WriteString("}\n")
	}
	return b.String()
}

func writeFeatureProfileGoTransport(
	outputPath string,
	fields *fieldsFile,
	operations *operationsFile,
) error {
	generated, err := format.Source([]byte(generateFeatureProfileGoTransport(fields, operations)))
	if err != nil {
		return fmt.Errorf("format generated Go transport: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(outputPath), 0755); err != nil {
		return err
	}
	return os.WriteFile(outputPath, generated, 0644)
}

func generateFeatureProfileGoTransport(
	fields *fieldsFile,
	operations *operationsFile,
) string {
	var b strings.Builder
	b.WriteString("// Code generated by tools/codegen_rec_model_python. DO NOT EDIT.\n")
	b.WriteString("// Source: recommendation-service/contracts/recommendation/recommendation_feature_profile_view.\n\n")
	b.WriteString("package generated\n\n")
	b.WriteString("import \"time\"\n\n")
	for _, route := range operations.APIRoutes {
		b.WriteString(fmt.Sprintf("const %sPath = %q\n", route.Operation, route.Path))
		b.WriteString(fmt.Sprintf("const %sMethod = %q\n", route.Operation, strings.ToUpper(route.Method)))
	}
	entityNames := make(map[string]bool, len(fields.Entities))
	for name := range fields.Entities {
		entityNames[name] = true
	}
	for _, name := range featureProfileTransportOrder {
		entity, ok := fields.Entities[name]
		if !ok {
			continue
		}
		b.WriteString(fmt.Sprintf("\ntype %s struct {\n", name))
		for _, field := range entity.Fields {
			b.WriteString(fmt.Sprintf(
				"\t%s %s `json:%q`\n",
				goExportedName(field.Name),
				goTransportType(field.Type, isRequired(field.Constraints), entityNames),
				field.Name+goJSONOmitEmpty(field.Constraints),
			))
		}
		b.WriteString("}\n")
	}
	return b.String()
}

func goExportedName(name string) string {
	if name == "" {
		return ""
	}
	return strings.ToUpper(name[:1]) + name[1:]
}

func goJSONOmitEmpty(constraints []string) string {
	if isRequired(constraints) {
		return ""
	}
	return ",omitempty"
}

func goTransportType(metaType string, required bool, entityNames map[string]bool) string {
	typeName := strings.TrimSpace(metaType)
	if strings.HasPrefix(typeName, "[]") {
		inner := strings.Trim(strings.TrimPrefix(typeName, "[]"), "[]\"'")
		return "[]" + goTransportType(inner, true, entityNames)
	}
	base := "map[string]any"
	switch typeName {
	case "string", "ObjectId":
		base = "string"
	case "float64", "number", "decimal":
		base = "float64"
	case "int64":
		base = "int64"
	case "int":
		base = "int"
	case "bool":
		base = "bool"
	case "timestamp":
		base = "time.Time"
	case "object":
		base = "map[string]any"
	default:
		if entityNames[typeName] {
			base = typeName
		}
	}
	if !required && !strings.HasPrefix(base, "[]") && base != "map[string]any" {
		return "*" + base
	}
	return base
}

func resolveContentBehaviors(source *contractcodegen.Source) string {
	p := filepath.Join("content", "content", "content_behavior_fact", "behaviors.yaml")
	if source.Has(p) {
		return p
	}
	return ""
}

// --- YAML structs ---

type fieldsFile struct {
	Entities map[string]entityDef `yaml:"entities"`
	Types    map[string]entityDef `yaml:"types"`
}

type entityDef struct {
	Description string     `yaml:"description"`
	Fields      []fieldDef `yaml:"fields"`
}

type fieldDef struct {
	Name        string   `yaml:"name"`
	Type        string   `yaml:"type"`
	Constraints []string `yaml:"constraints"`
	Description string   `yaml:"description"`
}

type operationsFile struct {
	APIRoutes []routeDef `yaml:"api_routes"`
}

type routeDef struct {
	Method          string          `yaml:"method"`
	Path            string          `yaml:"path"`
	Operation       string          `yaml:"operation"`
	RequestEntity   string          `yaml:"request_entity"`
	ResponseEntity  string          `yaml:"response_entity"`
	Description     string          `yaml:"description"`
	RequestBindings requestBindings `yaml:"request_bindings"`
}

type requestBindings struct {
	Injected []bindingDef `yaml:"injected"`
}

type bindingDef struct {
	Name  string `yaml:"name"`
	Field string `yaml:"field"`
}

type projectionFile struct {
	ReadModel   string      `yaml:"read_model"`
	Description string      `yaml:"description"`
	Collection  string      `yaml:"collection"`
	Fields      []projField `yaml:"fields"`
}

type projField struct {
	Name        string `yaml:"name"`
	Type        string `yaml:"type"`
	Description string `yaml:"description"`
	Nullable    bool   `yaml:"nullable"`
}

type projectionSpec struct {
	ReadModel  string
	Collection string
	Fields     []projField
}

func loadFields(source *contractcodegen.Source, path string) (*fieldsFile, error) {
	var f fieldsFile
	if err := source.Decode(path, &f); err != nil {
		return nil, err
	}
	if len(f.Entities) == 0 {
		f.Entities = f.Types
	}
	return &f, nil
}

func loadOperations(source *contractcodegen.Source, path string) (*operationsFile, error) {
	var s operationsFile
	if err := source.Decode(path, &s); err != nil {
		return nil, err
	}
	return &s, nil
}

// mergeProjectionEntities makes object-local named projections available to the
// generated internal transport without copying their wire fields into
// fields.yaml. The projection document remains the only schema truth source.
func mergeProjectionEntities(
	source *contractcodegen.Source,
	servicePath string,
	fields *fieldsFile,
) error {
	if fields.Entities == nil {
		fields.Entities = map[string]entityDef{}
	}
	prefix := filepath.Join(servicePath, "projections") + "/"
	for _, path := range source.Paths(prefix, ".yaml") {
		var projection projectionFile
		if err := source.Decode(path, &projection); err != nil {
			return fmt.Errorf("%s: %w", path, err)
		}
		name := strings.TrimSpace(projection.ReadModel)
		if name == "" {
			return fmt.Errorf("%s: read_model is required", path)
		}
		if _, exists := fields.Entities[name]; exists {
			return fmt.Errorf("%s: read_model %s duplicates fields entity", path, name)
		}
		entity := entityDef{Description: projection.Description}
		for _, field := range projection.Fields {
			constraints := []string{"NOT_NULL"}
			if field.Nullable {
				constraints = []string{"NULLABLE"}
			}
			entity.Fields = append(entity.Fields, fieldDef{
				Name: field.Name, Type: field.Type,
				Constraints: constraints, Description: field.Description,
			})
		}
		fields.Entities[name] = entity
	}
	return nil
}

func loadProjections(
	source *contractcodegen.Source,
	projectionsPath string,
) ([]projectionSpec, error) {
	names := []string{"learning_events.yaml", "training_samples.yaml", "model_registry.yaml"}
	var out []projectionSpec
	for _, n := range names {
		path := filepath.Join(projectionsPath, n)
		if !source.Has(path) {
			continue
		}
		var p projectionFile
		if err := source.Decode(path, &p); err != nil {
			return nil, fmt.Errorf("%s: %w", n, err)
		}
		out = append(out, projectionSpec{
			ReadModel:  p.ReadModel,
			Collection: p.Collection,
			Fields:     p.Fields,
		})
	}
	return out, nil
}

// --- Type mapping metadata -> Python ---

func pyType(metaType string, required bool, entityNames map[string]bool) string {
	t := strings.TrimSpace(metaType)
	optional := !required
	wrapOptional := func(s string) string {
		if optional {
			return s + " | None"
		}
		return s
	}
	switch {
	case t == "string":
		return wrapOptional("str")
	case t == "enum":
		return wrapOptional("str")
	case t == "float64" || t == "number" || t == "decimal":
		return wrapOptional("float")
	case t == "int64" || t == "int":
		return wrapOptional("int")
	case t == "bool":
		return wrapOptional("bool")
	case t == "object" || t == "json":
		return wrapOptional("dict[str, Any]")
	case t == "timestamp":
		return wrapOptional("float")
	case t == "ObjectId":
		return wrapOptional("str")
	case strings.HasPrefix(t, "[]"):
		inner := strings.TrimPrefix(t, "[]")
		inner = strings.Trim(inner, "[]\"'")
		innerPy := pyType(inner, true, entityNames)
		return wrapOptional("list[" + innerPy + "]")
	default:
		if entityNames[t] {
			return wrapOptional(t)
		}
		return wrapOptional("dict[str, Any]")
	}
}

func pyTransportType(metaType string, required bool, entityNames map[string]bool) string {
	t := strings.TrimSpace(metaType)
	optional := !required
	wrapOptional := func(s string) string {
		if optional {
			return s + " | None"
		}
		return s
	}
	if t == "timestamp" {
		return wrapOptional("datetime")
	}
	if strings.HasPrefix(t, "[]") {
		inner := strings.TrimPrefix(t, "[]")
		inner = strings.Trim(inner, "[]\"'")
		innerPy := pyTransportType(inner, true, entityNames)
		return wrapOptional("list[" + innerPy + "]")
	}
	return pyType(t, required, entityNames)
}

func isRequired(constraints []string) bool {
	for _, c := range constraints {
		if c == "NOT_NULL" || c == "NOT_BLANK" {
			return true
		}
	}
	return false
}

// --- Request/Response generation (entity order: dependencies first) ---

var requestResponseOrder = []string{
	"StageRecommendationModelReleaseCommand",
	"ActivateRecommendationModelReleaseCommand",
	"RecommendationModelReleaseCommandResult",
	"CandidateInput",
	"CandidateScore",
	"ModelScoreRequest",
	"ModelScoreResponse",
	"BatchModelScoreRequest",
	"BatchModelScoreResponse",
}

var rankedWindowTransportOrder = []string{
	"RecommendationObjectCard",
	"RankedRecommendationItem",
	"CreateRankedRecommendationWindowCommand",
	"GetRankedRecommendationPageQuery",
	"RankedRecommendationPage",
}

var featureProfileTransportOrder = []string{
	"IntersectionTarget",
	"IntersectionVisual",
	"IntersectionTextSpan",
	"IntersectionPoint",
	"IntersectionDimensionTally",
	"IntersectionRepresentativeActor",
	"IntersectionActorEvidence",
	"IntersectionActionHint",
	"IntersectionPropagationPath",
	"IntersectionReason",
	"IntersectionInboxSummary",
	"ListRecommendationSubjectIntersectionsQuery",
	"ListRecommendationObjectIntersectionsQuery",
	"GetRecommendationIntersectionSupplyQuery",
	"RecommendationIntersectionReasonSlice",
	"RecommendationObjectIntersectionReasonSlice",
	"RecommendationIntersectionSupply",
	"GetRecommendationAuthorImpactQuery",
	"ListRecommendationAuthorImpactEvidenceQuery",
	"RecommendationAuthorImpactItem",
	"RecommendationAuthorImpactSummary",
	"RecommendationAuthorImpactEvidence",
	"RecommendationAuthorImpactEvidencePage",
	"GetRecommendationGatheringSocialProofQuery",
	"RecommendationGatheringSocialProofSummary",
	"GetRecommendationFlywheelFunnelQuery",
	"RecommendationFlywheelFunnelSnapshot",
}

func generateRequestResponsePy(f *fieldsFile) string {
	return generateRequestResponsePyForNames(f, requestResponseOrder)
}

func generateRequestResponsePyForNames(f *fieldsFile, names []string) string {
	var b strings.Builder
	b.WriteString(genHeader)
	b.WriteString("\nfrom __future__ import annotations\n\n")
	b.WriteString("from datetime import datetime\n")
	b.WriteString("from typing import Any\n\n")
	b.WriteString("from pydantic import BaseModel, ConfigDict\n\n")

	entityNames := make(map[string]bool)
	for name := range f.Entities {
		entityNames[name] = true
	}

	for _, entityName := range names {
		ent, ok := f.Entities[entityName]
		if !ok {
			continue
		}
		b.WriteString(fmt.Sprintf("\n\nclass %s(BaseModel):\n", entityName))
		if ent.Description != "" {
			b.WriteString(fmt.Sprintf("    \"\"\"%s\"\"\"\n", strings.ReplaceAll(ent.Description, "\n", " ")))
		}
		for _, fd := range ent.Fields {
			req := isRequired(fd.Constraints)
			pyT := pyTransportType(fd.Type, req, entityNames)
			def := ""
			if !req {
				def = " = None"
			}
			b.WriteString(fmt.Sprintf("    %s: %s%s\n", fd.Name, pyT, def))
		}
		b.WriteString("\n    model_config = ConfigDict(extra=\"forbid\")\n")
	}
	return b.String()
}

func generateProjectionsPy(projections []projectionSpec) string {
	var b strings.Builder
	b.WriteString(genHeader)
	b.WriteString("\nfrom __future__ import annotations\n\n")
	b.WriteString("from typing import Any\n\n")
	b.WriteString("from pydantic import BaseModel, ConfigDict\n\n")

	for _, p := range projections {
		className := projectionClassName(p.ReadModel)
		b.WriteString(fmt.Sprintf("\n\nclass %s(BaseModel):\n", className))
		b.WriteString(fmt.Sprintf("    \"\"\"Read model: %s, collection: %s\"\"\"\n", p.ReadModel, p.Collection))
		for _, fd := range p.Fields {
			pyT := pyType(fd.Type, false, nil)
			b.WriteString(fmt.Sprintf("    %s: %s = None\n", fd.Name, pyT))
		}
		b.WriteString("\n    model_config = ConfigDict(populate_by_name=True)\n")
	}
	return b.String()
}

func projectionClassName(readModel string) string {
	className := readModel
	if strings.HasSuffix(className, "s") && len(className) > 1 {
		className = className[:len(className)-1]
	}
	if className == "LearningEvents" {
		return "LearningEvent"
	}
	if className == "TrainingSamples" {
		return "TrainingSample"
	}
	if className == "ModelRegistry" {
		return "ModelRegistryEntry"
	}
	return className
}

func generateModelsInit(projections []projectionSpec) string {
	return generateModelsInitForNames(requestResponseOrder, projections)
}

func generateModelsInitForNames(names []string, projections []projectionSpec) string {
	var b strings.Builder
	b.WriteString(genHeader)
	b.WriteString("\nfrom .request_response import (\n")
	for _, name := range names {
		b.WriteString(fmt.Sprintf("    %s,\n", name))
	}
	b.WriteString(")\n")
	if len(projections) == 0 {
		return b.String()
	}
	b.WriteString("from .projections import (\n")
	for _, projection := range projections {
		b.WriteString(fmt.Sprintf("    %s,\n", projectionClassName(projection.ReadModel)))
	}
	b.WriteString(")\n")
	return b.String()
}

func pythonOperationConstant(operation string) string {
	var b strings.Builder
	for i, r := range operation {
		if i > 0 && r >= 'A' && r <= 'Z' {
			b.WriteByte('_')
		}
		if r >= 'a' && r <= 'z' {
			b.WriteRune(r - ('a' - 'A'))
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

func generateOperationsPy(s *operationsFile) string {
	var b strings.Builder
	b.WriteString(genHeader)
	b.WriteString("\n\"\"\"Operation descriptors generated from ContractGraph metadata.\"\"\"\n\n")
	for _, r := range s.APIRoutes {
		name := pythonOperationConstant(r.Operation)
		b.WriteString(fmt.Sprintf("%s_PATH = %q\n", name, r.Path))
		b.WriteString(fmt.Sprintf("%s_METHOD = %q\n", name, strings.ToUpper(r.Method)))
	}
	return b.String()
}

func generateSchemasPy(f *fieldsFile) string {
	return generateSchemasPyForNames(f, requestResponseOrder)
}

func generateSchemasPyForNames(f *fieldsFile, order []string) string {
	var b strings.Builder
	b.WriteString(genHeader)
	b.WriteString("\n\"\"\"Re-export request/response models for API use.\"\"\"\n\n")
	b.WriteString("from ..models.request_response import (\n")
	names := make([]string, 0, len(order))
	for _, name := range order {
		if _, ok := f.Entities[name]; ok {
			names = append(names, name)
		}
	}
	for _, n := range names {
		b.WriteString(fmt.Sprintf("    %s,\n", n))
	}
	b.WriteString(")\n")
	b.WriteString("\n__all__ = [\n")
	for _, n := range names {
		b.WriteString(fmt.Sprintf("    %q,\n", n))
	}
	b.WriteString("]\n")
	return b.String()
}

func generateObjectTransportPackage(
	source *contractcodegen.Source,
	servicePath string,
	outputDir string,
	order []string,
) error {
	fields, err := loadFields(source, filepath.Join(servicePath, "fields.yaml"))
	if err != nil {
		return fmt.Errorf("load fields: %w", err)
	}
	if err := mergeProjectionEntities(source, servicePath, fields); err != nil {
		return fmt.Errorf("load object projections: %w", err)
	}
	operations, err := loadOperations(source, filepath.Join(servicePath, "operations.yaml"))
	if err != nil {
		return fmt.Errorf("load operations: %w", err)
	}
	for _, directory := range []string{
		filepath.Join(outputDir, "models"),
		filepath.Join(outputDir, "api"),
	} {
		if err := os.MkdirAll(directory, 0755); err != nil {
			return err
		}
	}
	outputs := map[string]string{
		filepath.Join(outputDir, "api", "operations.py"):          generateOperationsPy(operations),
		filepath.Join(outputDir, "api", "schemas.py"):             generateSchemasPyForNames(fields, order),
		filepath.Join(outputDir, "api", "__init__.py"):            generateAPIInit(),
		filepath.Join(outputDir, "models", "request_response.py"): generateRequestResponsePyForNames(fields, order),
		filepath.Join(outputDir, "models", "__init__.py"):         generateModelsInitForNames(order, nil),
		filepath.Join(outputDir, "__init__.py"):                   generateRootInit(),
	}
	for path, content := range outputs {
		if err := os.WriteFile(path, []byte(content), 0644); err != nil {
			return err
		}
	}
	return nil
}

func generateAPIInit() string {
	var b strings.Builder
	b.WriteString(genHeader)
	b.WriteString("\n\"\"\"Generated operation descriptors and transport schemas.\"\"\"\n")
	b.WriteString("\n__all__ = [\"operations\", \"schemas\"]\n")
	return b.String()
}

func generateRootInit() string {
	var b strings.Builder
	b.WriteString(genHeader)
	b.WriteString("\n\"\"\"Generated models and API for recommendation-service. DO NOT EDIT.\"\"\"\n\n")
	b.WriteString("# Lazy subpackages so models can be imported without requiring fastapi.\n")
	b.WriteString("__all__ = [\"api\", \"models\"]\n")
	return b.String()
}
