// Code generated by generate_canonical_test_bridges.py. DO NOT EDIT.
package api_integration

import (
	"os/exec"
	"testing"
)

func TestVisitEventContractApiIntegrationTest(t *testing.T) {
	cmd := exec.Command(
		"go",
		"test",
		"..",
		"-run",
		"^(TestTelemetryService_ExceptionMirrorFailureDoesNotBlockAck|TestTelemetryStore_RecordVisitAndStats|TestTelemetryStore_ReportEventBatchIdempotent)$",
		"-count=1",
	)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("source bridge failed for quwoquan_service/services/product-ops-service/tests/visit_event_contract_test.go: %v\n%s", err, output)
	}
}
