// Code generated by codegen_storage from contracts/metadata/user/user_profile. DO NOT EDIT.
package model

import (
	"time"
)

type UserDevice struct {
	ID           string    `json:"id" db:"id"`
	UserID       string    `json:"userId" db:"user_id"`
	DeviceID     string    `json:"deviceId" db:"device_id"`
	Platform     string    `json:"platform" db:"platform"`
	PushToken    string    `json:"pushToken" db:"push_token"`
	AppVersion   string    `json:"appVersion" db:"app_version"`
	LastActiveAt time.Time `json:"-" db:"last_active_at"`
	CreatedAt    time.Time `json:"-" db:"created_at"`
}
