// Code generated by codegen_storage from contracts/metadata/user/user_profile. DO NOT EDIT.
package model

import (
	"time"
)

type UserProfile struct {
	UserID           string    `json:"userId" db:"user_id"`
	Phone            string    `json:"-" db:"phone"`
	Nickname         string    `json:"nickname" db:"nickname"`
	AvatarURL        string    `json:"avatarUrl" db:"avatar_url"`
	AvatarAssetID    string    `json:"avatarAssetId" db:"avatar_asset_id"`
	AvatarVersion    int       `json:"avatarVersion" db:"avatar_version"`
	Bio              string    `json:"bio" db:"bio"`
	Gender           string    `json:"gender" db:"gender"`
	BirthDate        *string   `json:"birthDate" db:"birth_date"`
	Region           string    `json:"region" db:"region"`
	Status           string    `json:"status" db:"status"`
	ProfileVersion   int       `json:"profileVersion" db:"profile_version"`
	FollowerCount    int64     `json:"followerCount" db:"follower_count"`
	FollowingCount   int64     `json:"followingCount" db:"following_count"`
	PostCount        int64     `json:"postCount" db:"post_count"`
	CircleCount      int64     `json:"circleCount" db:"circle_count"`
	LikeCount        int64     `json:"likeCount" db:"like_count"`
	OwnerDisplayName string    `json:"-" db:"owner_display_name"`
	SubAccountCount  int64     `json:"subAccountCount" db:"sub_account_count"`
	CreatedAt        time.Time `json:"createdAt" db:"created_at"`
	UpdatedAt        time.Time `json:"updatedAt" db:"updated_at"`
}
