package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"text/template"

	"quwoquan_service/runtime/codegen"
)

type mongoStoreData struct {
	CollName    string
	EntityName  string
	ShortName   string
	BaseName    string
	DomainPkg   string
	ModelImport string
	Indexes     []mongoIdxData
}

type mongoIdxData struct {
	Name   string
	Keys   []mongoKeyData
	Unique bool
	Sparse bool
}

type mongoKeyData struct {
	Field string
	Order int
}

func generateMongoStore(ctx *genContext, collName string, coll CollectionDef) error {
	dir := filepath.Join(ctx.outputDir(), "infrastructure", "persistence")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	entity := coll.Entity
	shortName := ctx.source.resolveStoreName(entity)
	snakeShort := codegen.CamelToSnake(shortName)

	data := mongoStoreData{
		CollName:    collName,
		EntityName:  entity,
		ShortName:   shortName,
		BaseName:    "mongo" + shortName + "StoreBase",
		DomainPkg:   ctx.domainPkg(),
		ModelImport: ctx.modulePath() + "/domain/" + ctx.domainPkg() + "/model",
	}

	for _, idx := range coll.Indexes {
		id := mongoIdxData{
			Name:   idx.Name,
			Unique: idx.Unique,
			Sparse: idx.Sparse,
		}
		keys := make([]string, 0, len(idx.Keys))
		for k := range idx.Keys {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			id.Keys = append(id.Keys, mongoKeyData{Field: k, Order: idx.Keys[k]})
		}
		data.Indexes = append(data.Indexes, id)
	}

	tmpl, err := template.New("mongo_store").Parse(mongoStoreTemplate)
	if err != nil {
		return fmt.Errorf("parse mongo template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("execute mongo template: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		formatted = buf.Bytes()
	}

	fileName := "mongo_" + snakeShort + "_store.g.go"
	path := filepath.Join(dir, fileName)
	fmt.Printf("  mongo_store: %s\n", fileName)
	return os.WriteFile(path, formatted, 0644)
}

const mongoStoreTemplate = `// Code generated by codegen_storage. DO NOT EDIT.
package persistence

import (
	"context"
	"time"

	"go.mongodb.org/mongo-driver/v2/bson"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"go.mongodb.org/mongo-driver/v2/mongo/options"

	model "{{.ModelImport}}"
)

var _ = time.Now

// {{.BaseName}} provides generated MongoDB operations for {{.EntityName}}.
// Embed this in a public store type defined in _ext.go.
type {{.BaseName}} struct {
	coll *mongo.Collection
}

// EnsureIndexes creates required indexes on the {{.CollName}} collection.
func (s *{{.BaseName}}) EnsureIndexes(ctx context.Context) error {
	models := []mongo.IndexModel{
{{- range .Indexes}}
		{
			Keys: bson.D{
{{- range .Keys}}
				{Key: "{{.Field}}", Value: {{.Order}}},
{{- end}}
			},
			Options: options.Index().SetName("{{.Name}}"){{if .Unique}}.SetUnique(true){{end}}{{if .Sparse}}.SetSparse(true){{end}},
		},
{{- end}}
	}
	_, err := s.coll.Indexes().CreateMany(ctx, models)
	return err
}

// Create inserts a new {{.EntityName}} document. Returns false if duplicate key.
func (s *{{.BaseName}}) Create(ctx context.Context, e *model.{{.EntityName}}) (bool, error) {
	e.CreatedAt = time.Now().UTC()
	_, err := s.coll.InsertOne(ctx, e)
	if err != nil {
		if mongo.IsDuplicateKeyError(err) {
			return false, nil
		}
		return false, err
	}
	return true, nil
}

// DeleteByFilter removes a document matching the filter.
func (s *{{.BaseName}}) DeleteByFilter(ctx context.Context, filter bson.M) (int64, error) {
	result, err := s.coll.DeleteOne(ctx, filter)
	if err != nil {
		return 0, err
	}
	return result.DeletedCount, nil
}

// ExistsByFilter checks if a document matching the filter exists.
func (s *{{.BaseName}}) ExistsByFilter(ctx context.Context, filter bson.M) (bool, error) {
	count, err := s.coll.CountDocuments(ctx, filter, options.Count().SetLimit(1))
	return count > 0, err
}

// CountByFilter returns the number of documents matching the filter.
func (s *{{.BaseName}}) CountByFilter(ctx context.Context, filter bson.M) (int64, error) {
	return s.coll.CountDocuments(ctx, filter)
}
`
