// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../patrol/content/create_entry_start_actions_e2e_test.dart' as source_test;

void main() {
  source_test.main();
}
