// Code generated by runtime_error_codegen. DO NOT EDIT.

abstract final class RuntimeFailureCodes {
  static const String assistantMiddlewareLlmTimeout =
      'ASSISTANT.MIDDLEWARE.llm_timeout';
  static const String assistantSystemContractParseFailed =
      'ASSISTANT.SYSTEM.contract_parse_failed';
  static const String assistantSystemInternalError =
      'ASSISTANT.SYSTEM.internal_error';
  static const String appNetworkOffline = 'APP.NETWORK.offline';
  static const String appNetworkSecureConnectionFailed =
      'APP.NETWORK.secure_connection_failed';
  static const String appTimeoutRequestTimeout = 'APP.TIMEOUT.request_timeout';
  static const String appCancelledOperationCancelled =
      'APP.CANCELLED.operation_cancelled';
  static const String appContractInvalidResponse =
      'APP.CONTRACT.invalid_response';
  static const String appContractInvalidJson = 'APP.CONTRACT.invalid_json';
  static const String appSystemUnknownError = 'APP.SYSTEM.unknown_error';
  static const String appUserUnauthorized = 'APP.USER.unauthorized';
  static const String appUserForbidden = 'APP.USER.forbidden';
  static const String appUserNotFound = 'APP.USER.not_found';
  static const String cloudSystemUnavailable = 'CLOUD.SYSTEM.unavailable';
  static const String appUserPermissionRequired =
      'APP.USER.permission_required';
  static const String cloudSystemUnknownError = 'CLOUD.SYSTEM.unknown_error';
  static const String opsConfigBaseUrlMissing = 'OPS.CONFIG.base_url_missing';
  static const String opsNetworkFetchFailed = 'OPS.NETWORK.fetch_failed';
  static const String opsNetworkRequestFailed = 'OPS.NETWORK.request_failed';
  static const String opsUnavailableControlPlaneUnavailable =
      'OPS.UNAVAILABLE.control_plane_unavailable';
  static const String opsContractInvalidJsonResponse =
      'OPS.CONTRACT.invalid_json_response';
  static const String opsContractInvalidResponse =
      'OPS.CONTRACT.invalid_response';
  static const String opsSystemUnknownError = 'OPS.SYSTEM.unknown_error';
}
