// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../../ui/search/journeys/cross_domain_search_journey_test.dart' as source_0;

void main() {
  source_0.main();
}
