// Code generated by tools/codegen_content_service. DO NOT EDIT.
package http

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strconv"
	"strings"
)

func RegisterGeneratedRoutes(mux *http.ServeMux, h *ContentHandler) {
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		op, ok := resolveGeneratedOperation(r.Method, r.URL.Path)
		if !ok {
			http.NotFound(w, r)
			return
		}
		dispatchGeneratedOperation(h, op, w, r)
	})
}

func dispatchGeneratedOperation(h *ContentHandler, operation string, w http.ResponseWriter, r *http.Request) {
	switch operation {
	case "AbortMediaUpload":
		h.handleNotImplemented(w, r, operation)
	case "CompleteMediaUpload":
		h.handleNotImplemented(w, r, operation)
	case "CreateComment":
		h.handleNotImplemented(w, r, operation)
	case "CreatePost":
		h.handleCreatePost(w, r)
	case "DeleteComment":
		h.handleNotImplemented(w, r, operation)
	case "DeletePost":
		h.handleNotImplemented(w, r, operation)
	case "FavoritePost":
		h.handleNotImplemented(w, r, operation)
	case "GenerateArticleSummary":
		h.handleNotImplemented(w, r, operation)
	case "GetCounters":
		h.handleNotImplemented(w, r, operation)
	case "GetFeed":
		h.handleGetFeed(w, r)
	case "GetHelperRead":
		h.handleNotImplemented(w, r, operation)
	case "GetMediaAsset":
		h.handleNotImplemented(w, r, operation)
	case "GetAppConfig":
		h.handleNotImplemented(w, r, operation)
	case "GetPost":
		h.handleGetPost(w, r)
	case "GetReactionState":
		h.handleNotImplemented(w, r, operation)
	case "GetRecommendation":
		h.handleGetRecommendation(w, r)
	case "InitMediaUpload":
		h.handleNotImplemented(w, r, operation)
	case "LikeComment":
		h.handleNotImplemented(w, r, operation)
	case "LikePost":
		h.handleNotImplemented(w, r, operation)
	case "ListComments":
		h.handleNotImplemented(w, r, operation)
	case "ListCommentsByAuthor":
		h.handleNotImplemented(w, r, operation)
	case "ListCommentsForPostAuthor":
		h.handleNotImplemented(w, r, operation)
	case "PublishPost":
		h.handleNotImplemented(w, r, operation)
	case "QuoteToCircle":
		h.handleNotImplemented(w, r, operation)
	case "ReportBehaviors":
		h.handleReportBehaviors(w, r)
	case "RepostToCircle":
		h.handleNotImplemented(w, r, operation)
	case "SelectAutoVideoCover":
		h.handleNotImplemented(w, r, operation)
	case "SelectManualVideoCover":
		h.handleNotImplemented(w, r, operation)
	case "UnfavoritePost":
		h.handleNotImplemented(w, r, operation)
	case "UnlikeComment":
		h.handleNotImplemented(w, r, operation)
	case "UnlikePost":
		h.handleNotImplemented(w, r, operation)
	case "UpdatePost":
		h.handleUpdatePost(w, r)
	case "UpdatePostCircles":
		h.handleNotImplemented(w, r, operation)
	default:
		h.handleNotImplemented(w, r, operation)
	}
}

var generatedRouteTable = []generatedRouteDef{
	{method: "POST", pathTemplate: "/v1/content/articles/summary:generate", operation: "GenerateArticleSummary"},
	{method: "POST", pathTemplate: "/v1/content/behaviors", operation: "ReportBehaviors"},
	{method: "GET", pathTemplate: "/v1/content/feed", operation: "GetFeed"},
	{method: "GET", pathTemplate: "/v1/content/helper-read/{contentId}", operation: "GetHelperRead"},
	{method: "POST", pathTemplate: "/v1/content/media/uploads/{sessionId}:abort", operation: "AbortMediaUpload"},
	{method: "POST", pathTemplate: "/v1/content/media/uploads/{sessionId}:complete", operation: "CompleteMediaUpload"},
	{method: "POST", pathTemplate: "/v1/content/media/uploads:init", operation: "InitMediaUpload"},
	{method: "GET", pathTemplate: "/v1/content/media/{mediaId}", operation: "GetMediaAsset"},
	{method: "POST", pathTemplate: "/v1/content/media/{mediaId}/cover:auto", operation: "SelectAutoVideoCover"},
	{method: "POST", pathTemplate: "/v1/content/media/{mediaId}/cover:manual", operation: "SelectManualVideoCover"},
	{method: "POST", pathTemplate: "/v1/content/posts", operation: "CreatePost"},
	{method: "DELETE", pathTemplate: "/v1/content/posts/{postId}", operation: "DeletePost"},
	{method: "GET", pathTemplate: "/v1/content/posts/{postId}", operation: "GetPost"},
	{method: "PATCH", pathTemplate: "/v1/content/posts/{postId}", operation: "UpdatePost"},
	{method: "PATCH", pathTemplate: "/v1/content/posts/{postId}/circles", operation: "UpdatePostCircles"},
	{method: "GET", pathTemplate: "/v1/content/posts/{postId}/comments", operation: "ListComments"},
	{method: "POST", pathTemplate: "/v1/content/posts/{postId}/comments", operation: "CreateComment"},
	{method: "DELETE", pathTemplate: "/v1/content/posts/{postId}/comments/{commentId}", operation: "DeleteComment"},
	{method: "GET", pathTemplate: "/v1/content/posts/{postId}/counters", operation: "GetCounters"},
	{method: "DELETE", pathTemplate: "/v1/content/posts/{postId}/favorite", operation: "UnfavoritePost"},
	{method: "POST", pathTemplate: "/v1/content/posts/{postId}/favorite", operation: "FavoritePost"},
	{method: "DELETE", pathTemplate: "/v1/content/posts/{postId}/like", operation: "UnlikePost"},
	{method: "POST", pathTemplate: "/v1/content/posts/{postId}/like", operation: "LikePost"},
	{method: "POST", pathTemplate: "/v1/content/posts/{postId}/publish", operation: "PublishPost"},
	{method: "POST", pathTemplate: "/v1/content/posts/{postId}/quote", operation: "QuoteToCircle"},
	{method: "GET", pathTemplate: "/v1/content/posts/{postId}/reactions", operation: "GetReactionState"},
	{method: "POST", pathTemplate: "/v1/content/posts/{postId}/repost", operation: "RepostToCircle"},
	{method: "POST", pathTemplate: "/v1/content/comments/{commentId}/like", operation: "LikeComment"},
	{method: "DELETE", pathTemplate: "/v1/content/comments/{commentId}/like", operation: "UnlikeComment"},
	{method: "GET", pathTemplate: "/v1/content/users/me/comments", operation: "ListCommentsByAuthor"},
	{method: "GET", pathTemplate: "/v1/content/users/me/received-comments", operation: "ListCommentsForPostAuthor"},
	{method: "GET", pathTemplate: "/v1/config/app", operation: "GetAppConfig"},
	{method: "POST", pathTemplate: "/v1/content/recommend", operation: "GetRecommendation"},
	{method: "GET", pathTemplate: "/v1/orch/discovery/feed", operation: "GetFeed"},
}

type generatedRouteDef struct {
	method       string
	pathTemplate string
	operation    string
}

func resolveGeneratedOperation(method, path string) (string, bool) {
	m := strings.ToUpper(strings.TrimSpace(method))
	for _, route := range generatedRouteTable {
		if route.method != m {
			continue
		}
		if generatedPathMatch(route.pathTemplate, path) {
			return route.operation, true
		}
	}
	return "", false
}

func generatedPathMatch(templatePath, requestPath string) bool {
	tParts := generatedSplitPath(templatePath)
	rParts := generatedSplitPath(requestPath)
	if len(tParts) != len(rParts) {
		return false
	}
	for i := range tParts {
		tp := tParts[i]
		rp := rParts[i]
		if strings.HasPrefix(tp, "{") && strings.HasSuffix(tp, "}") {
			if rp == "" {
				return false
			}
			continue
		}
		if tp != rp {
			return false
		}
	}
	return true
}

func generatedSplitPath(raw string) []string {
	trimmed := strings.Trim(strings.TrimSpace(raw), "/")
	if trimmed == "" {
		return []string{}
	}
	return strings.Split(trimmed, "/")
}

type GeneratedGetFeedParams struct {
	Type        string
	Sort        string
	Cursor      string
	SubCategory string
	Limit       int
}

func BindGeneratedGetFeedParams(r *http.Request, defaultLimit int) GeneratedGetFeedParams {
	out := GeneratedGetFeedParams{Limit: defaultLimit}
	q := r.URL.Query()
	out.Type = strings.TrimSpace(q.Get("type"))
	out.Sort = strings.TrimSpace(q.Get("sort"))
	out.Cursor = strings.TrimSpace(q.Get("cursor"))
	out.SubCategory = strings.TrimSpace(q.Get("subCategory"))
	rawLimit := strings.TrimSpace(q.Get("limit"))
	if rawLimit != "" {
		if parsed, err := strconv.Atoi(rawLimit); err == nil {
			out.Limit = parsed
		}
	}
	if out.Limit <= 0 {
		out.Limit = defaultLimit
	}
	return out
}

var generatedWritableFieldSetByOperation = map[string]map[string]struct{}{
	"CreateComment": {
		"content":          {},
		"replyToCommentId": {},
		"personaId":        {},
	},
	"CreatePost": {
		"contentType":         {},
		"title":               {},
		"body":                {},
		"summary":             {},
		"tags":                {},
		"mediaUrls":           {},
		"coverUrl":            {},
		"videoUrl":            {},
		"illustrationAssetId": {},
		"location":            {},
		"locationName":        {},
		"visibility":          {},
		"circleIds":           {},
		"sourcePostId":        {},
		"sourceType":          {},
		"deviceInfo":          {},
		"publishLocation":     {},
	},
}

func BindGeneratedWritableBodyFromRequest(r *http.Request, operation string) (map[string]any, error) {
	allowed, ok := generatedWritableFieldSetByOperation[operation]
	if !ok {
		return nil, nil
	}
	raw, err := io.ReadAll(r.Body)
	if err != nil {
		return nil, fmt.Errorf("read request body: %w", err)
	}
	if len(strings.TrimSpace(string(raw))) == 0 {
		return map[string]any{}, nil
	}
	var input map[string]any
	if err := json.Unmarshal(raw, &input); err != nil {
		return nil, fmt.Errorf("decode request body: %w", err)
	}
	sanitized := make(map[string]any, len(input))
	for key, value := range input {
		if _, allowedKey := allowed[key]; !allowedKey {
			return nil, fmt.Errorf("field %q is not writable for operation %s", key, operation)
		}
		sanitized[key] = value
	}
	return sanitized, nil
}
