"""Web bootstrap surface 产物生成（runtime-client-foundation DEC-005）。

Flutter 引擎启动前只允许一个平台实现的 bootstrap surface：loading 为
`role=status + aria-live=polite`，字体 404/首次离线为 `startupDependencyUnavailable`
全屏恢复态，唯一动作是重新加载。本 generator 从设计系统与 l10n ARB 真相源
生成 `web/qwq_bootstrap.css` 与 `web/qwq_bootstrap.js`，HTML 不复制品牌字面值。
"""

from __future__ import annotations

import json
import re
from pathlib import Path

from _common.paths import APP_ROOT

_COLORS_PATH = APP_ROOT / "lib/design_system/colors/app_colors.dart"
_TYPOGRAPHY_PATH = APP_ROOT / "lib/design_system/typography/app_typography.dart"
_SPACING_PATH = APP_ROOT / "lib/design_system/spacing/app_spacing_values.dart"
_ARB_ZH_PATH = APP_ROOT / "lib/l10n/app_zh.arb"
_ARB_EN_PATH = APP_ROOT / "lib/l10n/app_en.arb"
CSS_OUTPUT = APP_ROOT / "web/qwq_bootstrap.css"
JS_OUTPUT = APP_ROOT / "web/qwq_bootstrap.js"

_L10N_KEYS = (
    "webBootstrapLoading",
    "webBootstrapUnavailableTitle",
    "webBootstrapUnavailableBody",
    "webBootstrapReload",
)

_CONFIG_L10N = {
    "zh": {
        "webBootstrapConfigTitle": "应用配置不可用",
        "webBootstrapConfigBody": (
            "当前站点的启动配置缺失、已过期或未通过安全校验。"
            "请联系站点管理员修复配置后重试。"
        ),
        "webBootstrapConfigCode": "配置错误代码：",
    },
    "en": {
        "webBootstrapConfigTitle": "Application configuration unavailable",
        "webBootstrapConfigBody": (
            "This site's startup configuration is missing, expired, or failed "
            "security verification. Ask the site administrator to repair it, then retry."
        ),
        "webBootstrapConfigCode": "Configuration error code: ",
    },
}

_GENERATED_HEADER = (
    "GENERATED by quwoquan_app/scripts/web/bootstrap_assets.py -- do not edit.\n"
    "Sources: lib/design_system (AppColors/AppTypography/AppSpacing) and lib/l10n ARB."
)


class WebBootstrapAssetsError(RuntimeError):
    pass


def _read(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except OSError as error:
        raise WebBootstrapAssetsError(f"cannot read source: {path}: {error}") from error


def _dart_color_to_css(value: str) -> str:
    match = re.fullmatch(r"0x([0-9A-Fa-f]{2})([0-9A-Fa-f]{6})", value)
    if match is None:
        raise WebBootstrapAssetsError(f"not a canonical Dart color literal: {value}")
    alpha = int(match.group(1), 16)
    rgb = match.group(2).lower()
    if alpha == 0xFF:
        return f"#{rgb}"
    return f"#{rgb}{match.group(1).lower()}"


def _named_color(source: str, name: str) -> str:
    match = re.search(
        rf"static const Color {re.escape(name)} = Color\((0x[0-9A-Fa-f]{{8}})\)", source
    )
    if match is None:
        raise WebBootstrapAssetsError(f"AppColors.{name} literal not found")
    return _dart_color_to_css(match.group(1))


def _theme_getter_colors(source: str, getter: str) -> tuple[str, str]:
    """返回 AppColorsTheme getter 的 (dark, light) CSS 颜色。"""

    match = re.search(
        rf"Color get {re.escape(getter)} =>\s*isDark\s*\?\s*const Color\((0x[0-9A-Fa-f]{{8}})\)"
        rf"\s*:\s*const Color\((0x[0-9A-Fa-f]{{8}})\);",
        source,
    )
    if match is None:
        raise WebBootstrapAssetsError(
            f"AppColorsTheme.{getter} does not expose two color literals"
        )
    return _dart_color_to_css(match.group(1)), _dart_color_to_css(match.group(2))


def _named_double(source: str, class_hint: str, name: str) -> float:
    match = re.search(
        rf"static const double (?:[A-Za-z0-9_]+ = [0-9.]+, )*{re.escape(name)} = ([0-9.]+)",
        source,
    )
    if match is None:
        raise WebBootstrapAssetsError(f"{class_hint}.{name} literal not found")
    return float(match.group(1))


def _l10n_messages(path: Path) -> dict[str, str]:
    try:
        payload = json.loads(_read(path))
    except json.JSONDecodeError as error:
        raise WebBootstrapAssetsError(f"invalid ARB {path}: {error}") from error
    messages: dict[str, str] = {}
    for key in _L10N_KEYS:
        value = payload.get(key)
        if not isinstance(value, str) or not value.strip():
            raise WebBootstrapAssetsError(f"ARB {path.name} is missing {key}")
        messages[key] = value
    return messages


def _tokens() -> dict[str, object]:
    colors = _read(_COLORS_PATH)
    typography = _read(_TYPOGRAPHY_PATH)
    spacing = _read(_SPACING_PATH)
    foreground_dark, foreground_light = _theme_getter_colors(colors, "foregroundPrimary")
    secondary_dark, secondary_light = _theme_getter_colors(colors, "foregroundSecondary")
    return {
        "backgroundLight": _named_color(colors, "iosGroupedBackgroundLight"),
        "backgroundDark": _named_color(colors, "iosGroupedBackgroundDark"),
        "foregroundLight": foreground_light,
        "foregroundDark": foreground_dark,
        "foregroundSecondaryLight": secondary_light,
        "foregroundSecondaryDark": secondary_dark,
        "accent": _named_color(colors, "brandBlue600"),
        "fontTitlePx": _named_double(typography, "AppTypography", "xl"),
        "fontBodyPx": _named_double(typography, "AppTypography", "base"),
        "spaceMdPx": _named_double(spacing, "AppSpacing", "md"),
        "spaceLgPx": _named_double(spacing, "AppSpacing", "lg"),
        "radiusPx": _named_double(spacing, "AppSpacing", "radiusTen"),
    }


def _px(value: object) -> str:
    number = float(value)  # type: ignore[arg-type]
    return f"{number:g}px"


def render_css() -> str:
    tokens = _tokens()
    header = "\n".join(f" * {line}" for line in _GENERATED_HEADER.splitlines())
    return f"""/*
{header}
 */
:root {{
  --qwq-background: {tokens['backgroundLight']};
  --qwq-foreground: {tokens['foregroundLight']};
  --qwq-foreground-secondary: {tokens['foregroundSecondaryLight']};
  --qwq-accent: {tokens['accent']};
  --qwq-font-title: {_px(tokens['fontTitlePx'])};
  --qwq-font-body: {_px(tokens['fontBodyPx'])};
  --qwq-space-md: {_px(tokens['spaceMdPx'])};
  --qwq-space-lg: {_px(tokens['spaceLgPx'])};
  --qwq-radius: {_px(tokens['radiusPx'])};
}}
@media (prefers-color-scheme: dark) {{
  :root {{
    --qwq-background: {tokens['backgroundDark']};
    --qwq-foreground: {tokens['foregroundDark']};
    --qwq-foreground-secondary: {tokens['foregroundSecondaryDark']};
  }}
}}
html,
body {{
  min-height: 100%;
  margin: 0;
  background: var(--qwq-background);
  font-family:
    -apple-system, BlinkMacSystemFont, "SF Pro Text", "PingFang SC",
    "Hiragino Sans GB", "Microsoft YaHei", "Noto Sans CJK SC",
    "Noto Sans SC", sans-serif;
}}
.qwq-bootstrap-surface {{
  position: fixed;
  inset: 0;
  z-index: 2147483000;
  display: flex;
  align-items: center;
  justify-content: center;
  background: var(--qwq-background);
  color: var(--qwq-foreground);
  font-size: var(--qwq-font-body);
  line-height: 1.5;
  text-align: center;
  padding: var(--qwq-space-lg);
  box-sizing: border-box;
  overflow-wrap: break-word;
}}
.qwq-bootstrap-surface[hidden] {{
  display: none;
}}
.qwq-bootstrap-panel {{
  max-width: 30rem;
  width: 100%;
}}
.qwq-bootstrap-panel[hidden] {{
  display: none;
}}
.qwq-bootstrap-title {{
  font-size: var(--qwq-font-title);
  font-weight: 600;
  margin: 0 0 var(--qwq-space-md);
}}
.qwq-bootstrap-body {{
  color: var(--qwq-foreground-secondary);
  margin: 0 0 var(--qwq-space-lg);
}}
.qwq-bootstrap-spinner {{
  width: 2rem;
  height: 2rem;
  margin: 0 auto var(--qwq-space-md);
  border: 3px solid var(--qwq-foreground-secondary);
  border-top-color: var(--qwq-accent);
  border-radius: 50%;
  animation: qwq-bootstrap-spin 1s linear infinite;
}}
@media (prefers-reduced-motion: reduce) {{
  .qwq-bootstrap-spinner {{
    animation: none;
  }}
}}
@keyframes qwq-bootstrap-spin {{
  to {{
    transform: rotate(360deg);
  }}
}}
.qwq-bootstrap-reload {{
  font: inherit;
  font-size: var(--qwq-font-body);
  color: #ffffff;
  background: var(--qwq-accent);
  border: 0;
  border-radius: var(--qwq-radius);
  padding: var(--qwq-space-md) var(--qwq-space-lg);
  min-height: 44px;
  min-width: 44px;
  cursor: pointer;
}}
.qwq-bootstrap-reload:focus-visible {{
  outline: 3px solid var(--qwq-foreground);
  outline-offset: 2px;
}}
"""


def render_js() -> str:
    zh = {**_l10n_messages(_ARB_ZH_PATH), **_CONFIG_L10N["zh"]}
    en = {**_l10n_messages(_ARB_EN_PATH), **_CONFIG_L10N["en"]}
    header = "\n".join(f" * {line}" for line in _GENERATED_HEADER.splitlines())
    l10n_literal = json.dumps({"zh": zh, "en": en}, ensure_ascii=False, indent=2)
    return f"""/*
{header}
 */
(function () {{
  "use strict";
  var L10N = {l10n_literal};
  var RUNTIME_CONFIG_TRUST_PATH = "/runtime-config-trust.json";
  var RUNTIME_CONFIG_PACKAGE_PATH = "/runtime-config-package.json";
  var TRUST_SCHEMA = "app-runtime-config-trust";
  var PACKAGE_SCHEMA = "app-runtime-config-package";
  var EXPECTED_SCHEMA_VERSION = "1";
  var MAX_LIFETIME_MS = 24 * 60 * 60 * 1000;
  var MAX_FUTURE_SKEW_MS = 5 * 60 * 1000;
  var CRITICAL_RESOURCE = /(flutter_bootstrap\\.js|flutter\\.js|main\\.dart\\.(js|mjs|wasm)|canvaskit|FontManifest\\.json|\\.ttf|\\.otf|\\.woff2?)([?#].*)?$/;
  var RECOVERY_DEADLINE_MS = 30000;
  var VALUE_KEYS = [
    "appRuntimeEnv",
    "gatewayBaseUrl",
    "legalBaseUrl",
    "publicWebBaseUrl",
    "appDownloadBaseUrl",
    "realtimeBaseUrl",
    "mediaAvatarCdnBaseUrl",
    "mediaImageCdnBaseUrl",
    "mediaVideoCdnBaseUrl",
    "mediaUploadBaseUrl",
    "rtcMediaConnectionUrl",
  ];
  var ENDPOINT_KEYS = VALUE_KEYS.slice(1);
  var PACKAGE_KEYS = [
    "schema",
    "schemaVersion",
    "environment",
    "buildProfile",
    "target",
    "launchPolicy",
    "issuedAt",
    "expiresAt",
    "sourceGitSha",
    "sourceTreeDigest",
    "runtime",
    "payloadDigest",
    "signatureAlgorithm",
    "signatureKeyId",
    "trustedPublicKeys",
    "signature",
  ];
  var TRUST_KEYS = [
    "schema",
    "schemaVersion",
    "buildProfile",
    "signatureAlgorithm",
    "trustedPublicKeys",
  ];
  var FORBIDDEN_KEY =
    /(content.*(release|bundle|manifest|checksum|version)|recommendation.*(policy|release)|gray|rollout|channel|secret|password|private.?key|access.?token|api.?key|credential)/i;

  function messages() {{
    var language = (navigator.language || "zh").toLowerCase();
    return language.indexOf("zh") === 0 ? L10N.zh : L10N.en;
  }}

  var surface = document.getElementById("qwq-bootstrap");
  var loading = document.getElementById("qwq-bootstrap-loading");
  var recovery = document.getElementById("qwq-bootstrap-recovery");
  var configError = document.getElementById("qwq-bootstrap-config-error");
  if (!surface || !loading || !recovery || !configError) {{
    return;
  }}
  var text = messages();
  document.getElementById("qwq-bootstrap-loading-text").textContent =
    text.webBootstrapLoading;
  document.getElementById("qwq-bootstrap-recovery-title").textContent =
    text.webBootstrapUnavailableTitle;
  document.getElementById("qwq-bootstrap-recovery-body").textContent =
    text.webBootstrapUnavailableBody;
  document.getElementById("qwq-bootstrap-config-title").textContent =
    text.webBootstrapConfigTitle;
  document.getElementById("qwq-bootstrap-config-body").textContent =
    text.webBootstrapConfigBody;
  var reload = document.getElementById("qwq-bootstrap-reload");
  var configReload = document.getElementById("qwq-bootstrap-config-reload");
  reload.textContent = text.webBootstrapReload;
  configReload.textContent = text.webBootstrapReload;
  reload.addEventListener("click", function () {{
    location.reload();
  }});
  configReload.addEventListener("click", function () {{
    location.reload();
  }});

  var engineStarted = false;
  var dependencyFailed = false;

  function configFailure(code) {{
    var error = new Error(code);
    error.code = code;
    return error;
  }}

  window.__qwqShowRuntimeConfigError = function (code) {{
    if (engineStarted) {{
      return;
    }}
    loading.hidden = true;
    recovery.hidden = true;
    configError.hidden = false;
    document.getElementById("qwq-bootstrap-config-code").textContent =
      text.webBootstrapConfigCode + String(code || "runtime-config-invalid");
    try {{
      window.__qwqRecordStartupEvent("web_runtime_config_invalid");
    }} catch (_) {{}}
  }};

  // startupDependencyUnavailable：引擎首帧前关键资源失败或首次离线时的
  // 全屏恢复态，唯一动作是重新加载（DEC-005）。
  function showRecovery() {{
    if (engineStarted || !configError.hidden) {{
      return;
    }}
    loading.hidden = true;
    recovery.hidden = false;
    try {{
      window.__qwqRecordStartupEvent("web_bootstrap_dependency_unavailable");
    }} catch (_) {{}}
  }}

  function dismissSurface() {{
    engineStarted = true;
    surface.hidden = true;
  }}

  function strictBase64(value, expectedLength, code) {{
    if (
      typeof value !== "string" ||
      value.length === 0 ||
      value.trim() !== value ||
      value.length % 4 !== 0 ||
      !/^[A-Za-z0-9+/]+={{0,2}}$/.test(value)
    ) {{
      throw configFailure(code);
    }}
    var binary;
    try {{
      binary = atob(value);
    }} catch (_) {{
      throw configFailure(code);
    }}
    var bytes = Uint8Array.from(binary, function (character) {{
      return character.charCodeAt(0);
    }});
    if (bytes.length !== expectedLength) {{
      throw configFailure(code);
    }}
    return bytes;
  }}

  function hex(bytes) {{
    return Array.from(bytes, function (byte) {{
      return byte.toString(16).padStart(2, "0");
    }}).join("");
  }}

  function canonicalJson(value) {{
    if (value === null || typeof value !== "object") {{
      return JSON.stringify(value);
    }}
    if (Array.isArray(value)) {{
      return "[" + value.map(canonicalJson).join(",") + "]";
    }}
    return (
      "{{" +
      Object.keys(value)
        .sort()
        .map(function (key) {{
          return JSON.stringify(key) + ":" + canonicalJson(value[key]);
        }})
        .join(",") +
      "}}"
    );
  }}

  function exactKeys(value, allowed, code) {{
    if (!value || Object.getPrototypeOf(value) !== Object.prototype) {{
      throw configFailure(code);
    }}
    var keys = Object.keys(value);
    if (
      keys.length !== allowed.length ||
      keys.some(function (key) {{
        return allowed.indexOf(key) < 0;
      }}) ||
      allowed.some(function (key) {{
        return !Object.prototype.hasOwnProperty.call(value, key);
      }})
    ) {{
      throw configFailure(code);
    }}
  }}

  function validateTrustEnvelope(trustEnvelope) {{
    exactKeys(trustEnvelope, TRUST_KEYS, "runtime-trust-envelope-invalid");
    if (
      trustEnvelope.schema !== TRUST_SCHEMA ||
      trustEnvelope.schemaVersion !== EXPECTED_SCHEMA_VERSION ||
      ["nonprod", "prod"].indexOf(trustEnvelope.buildProfile) < 0 ||
      trustEnvelope.signatureAlgorithm !== "ed25519"
    ) {{
      throw configFailure("runtime-trust-envelope-invalid");
    }}
    var keyring = trustEnvelope.trustedPublicKeys;
    if (
      !keyring ||
      Object.getPrototypeOf(keyring) !== Object.prototype ||
      Object.keys(keyring).length === 0
    ) {{
      throw configFailure("runtime-trust-keyring-invalid");
    }}
    Object.keys(keyring).forEach(function (keyId) {{
      if (!/^[A-Za-z0-9][A-Za-z0-9._-]{{0,127}}$/.test(keyId)) {{
        throw configFailure("runtime-trust-keyring-invalid");
      }}
      strictBase64(keyring[keyId], 32, "runtime-public-key-invalid");
    }});
    return trustEnvelope;
  }}

  function validateClaims(packageValue) {{
    exactKeys(packageValue, PACKAGE_KEYS, "package-shape-invalid");
    var values = packageValue.runtime;
    if (!values || Object.getPrototypeOf(values) !== Object.prototype) {{
      throw configFailure("runtime-values-invalid");
    }}
    var valueKeys = Object.keys(values);
    if (
      valueKeys.length !== VALUE_KEYS.length ||
      valueKeys.some(function (key) {{
        return VALUE_KEYS.indexOf(key) < 0 || FORBIDDEN_KEY.test(key);
      }}) ||
      VALUE_KEYS.some(function (key) {{
        return typeof values[key] !== "string" || values[key].trim() === "";
      }})
    ) {{
      throw configFailure("runtime-values-invalid");
    }}
    ENDPOINT_KEYS.forEach(function (key) {{
      var url;
      try {{
        url = new URL(values[key]);
      }} catch (_) {{
        throw configFailure("runtime-endpoint-invalid");
      }}
      var webSocket =
        key === "realtimeBaseUrl" || key === "rtcMediaConnectionUrl";
      if (
        (webSocket ? url.protocol !== "wss:" : url.protocol !== "https:") ||
        !url.host ||
        url.username ||
        url.password ||
        url.search ||
        url.hash
      ) {{
        throw configFailure("runtime-endpoint-invalid");
      }}
    }});
    if (
      packageValue.schema !== PACKAGE_SCHEMA ||
      packageValue.schemaVersion !== EXPECTED_SCHEMA_VERSION
    ) {{
      throw configFailure("runtime-schema-invalid");
    }}
    if (
      [
        "alpha-local",
        "beta-local",
        "gamma-local",
        "prod-sim",
        "prod-hosted",
      ].indexOf(packageValue.target) < 0
    ) {{
      throw configFailure("runtime-target-invalid");
    }}
    var profileValid =
      (packageValue.buildProfile === "nonprod" &&
        ["alpha", "beta", "gamma"].indexOf(packageValue.environment) >= 0) ||
      (packageValue.buildProfile === "prod" && packageValue.environment === "prod");
    if (!profileValid) {{
      throw configFailure("runtime-environment-invalid");
    }}
    var targetEnvironment = {{
      "alpha-local": "alpha",
      "beta-local": "beta",
      "gamma-local": "gamma",
      "prod-sim": "prod",
      "prod-hosted": "prod",
    }}[packageValue.target];
    var expectedLaunchPolicy =
      packageValue.environment === "prod" ? "prod_release" : "test_live";
    if (
      targetEnvironment !== packageValue.environment ||
      expectedLaunchPolicy !== packageValue.launchPolicy ||
      values.appRuntimeEnv !== packageValue.environment
    ) {{
      throw configFailure("runtime-launch-policy-invalid");
    }}
    if (packageValue.signatureAlgorithm !== "ed25519") {{
      throw configFailure("runtime-signature-algorithm-invalid");
    }}
    var canonicalTimestamp = /^\\d{{4}}-\\d{{2}}-\\d{{2}}T\\d{{2}}:\\d{{2}}:\\d{{2}}(?:\\.\\d{{3}})?Z$/;
    var issuedAt = Date.parse(packageValue.issuedAt);
    var expiresAt = Date.parse(packageValue.expiresAt);
    var now = Date.now();
    if (
      typeof packageValue.issuedAt !== "string" ||
      typeof packageValue.expiresAt !== "string" ||
      !canonicalTimestamp.test(packageValue.issuedAt) ||
      !canonicalTimestamp.test(packageValue.expiresAt) ||
      new Date(issuedAt).toISOString().replace(".000Z", "Z") !== packageValue.issuedAt ||
      new Date(expiresAt).toISOString().replace(".000Z", "Z") !== packageValue.expiresAt ||
      !Number.isFinite(issuedAt) ||
      !Number.isFinite(expiresAt) ||
      issuedAt > now + MAX_FUTURE_SKEW_MS ||
      expiresAt <= now ||
      expiresAt <= issuedAt ||
      expiresAt - issuedAt > MAX_LIFETIME_MS
    ) {{
      throw configFailure("runtime-freshness-invalid");
    }}
    if (
      !/^[0-9a-f]{{40}}$/.test(packageValue.sourceGitSha) ||
      !/^(?:sha1:[0-9a-f]{{40}}|sha256:[0-9a-f]{{64}})$/.test(
        packageValue.sourceTreeDigest
      ) ||
      !/^sha256:[0-9a-f]{{64}}$/.test(packageValue.payloadDigest)
    ) {{
      throw configFailure("runtime-source-identity-invalid");
    }}
    return packageValue;
  }}

  async function verifyRuntimeConfig(trustEnvelope, packageValue) {{
    if (!window.crypto || !window.crypto.subtle) {{
      throw configFailure("web-crypto-unavailable");
    }}
    validateTrustEnvelope(trustEnvelope);
    validateClaims(packageValue);
    if (packageValue.buildProfile !== trustEnvelope.buildProfile) {{
      throw configFailure("runtime-trust-profile-mismatch");
    }}
    exactKeys(
      packageValue.trustedPublicKeys,
      Object.keys(trustEnvelope.trustedPublicKeys),
      "runtime-trust-keyring-invalid"
    );
    var packageKeyring = canonicalJson(packageValue.trustedPublicKeys);
    var trustedKeyring = canonicalJson(trustEnvelope.trustedPublicKeys);
    if (packageKeyring !== trustedKeyring) {{
      throw configFailure("runtime-trust-keyring-invalid");
    }}
    var publicKeyValue =
      trustEnvelope.trustedPublicKeys[packageValue.signatureKeyId];
    if (typeof publicKeyValue !== "string") {{
      throw configFailure("runtime-signature-key-untrusted");
    }}
    var publicKey = strictBase64(
      publicKeyValue,
      32,
      "runtime-public-key-invalid"
    );
    var signature = strictBase64(
      packageValue.signature,
      64,
      "runtime-signature-invalid"
    );
    var payload = {{}};
    PACKAGE_KEYS.forEach(function (key) {{
      if (key !== "signature") {{
        payload[key] = packageValue[key];
      }}
    }});
    payload.payloadDigest = "";
    var digestPayload = new TextEncoder().encode(canonicalJson(payload));
    var digest = await crypto.subtle.digest("SHA-256", digestPayload);
    var normalizedDigest = packageValue.payloadDigest.replace(/^sha256:/, "");
    if (hex(new Uint8Array(digest)) !== normalizedDigest) {{
      throw configFailure("runtime-payload-digest-invalid");
    }}
    payload.payloadDigest = packageValue.payloadDigest;
    var encodedPayload = new TextEncoder().encode(canonicalJson(payload));
    var cryptoKey;
    try {{
      cryptoKey = await crypto.subtle.importKey(
        "raw",
        publicKey,
        {{ name: "Ed25519" }},
        false,
        ["verify"]
      );
    }} catch (_) {{
      throw configFailure("runtime-public-key-invalid");
    }}
    var verified = await crypto.subtle.verify(
      {{ name: "Ed25519" }},
      cryptoKey,
      signature,
      encodedPayload
    );
    if (!verified) {{
      throw configFailure("runtime-signature-invalid");
    }}
    return packageValue;
  }}

  async function fetchJson(path, kind, options) {{
    var url = new URL(path, window.location.href);
    if (url.origin !== window.location.origin) {{
      throw configFailure("runtime-" + kind + "-origin-invalid");
    }}
    var response;
    try {{
      response = await fetch(url.href, options);
    }} catch (_) {{
      throw configFailure("runtime-" + kind + "-fetch-failed");
    }}
    if (!response.ok) {{
      throw configFailure("runtime-" + kind + "-http-" + response.status);
    }}
    try {{
      return await response.json();
    }} catch (_) {{
      throw configFailure("runtime-" + kind + "-json-invalid");
    }}
  }}

  async function fetchRuntimeConfig() {{
    var fetchOptions = {{
      cache: "no-store",
      credentials: "same-origin",
      headers: {{ Accept: "application/json" }},
    }};
    var trustEnvelope = validateTrustEnvelope(
      await fetchJson(RUNTIME_CONFIG_TRUST_PATH, "trust", fetchOptions)
    );
    var packageValue = await fetchJson(
      RUNTIME_CONFIG_PACKAGE_PATH,
      "package",
      fetchOptions
    );
    return verifyRuntimeConfig(trustEnvelope, packageValue);
  }}

  window.__qwqRuntimeConfigReady = fetchRuntimeConfig().then(function (packageValue) {{
    window.__qwqReadRuntimeConfigPackage = function () {{
      return JSON.stringify(packageValue);
    }};
    return packageValue;
  }});
  window.__qwqRuntimeConfigReady.catch(function (error) {{
    window.__qwqShowRuntimeConfigError(error.code || "runtime-config-invalid");
  }});

  window.addEventListener("flutter-first-frame", dismissSurface);

  window.addEventListener(
    "error",
    function (event) {{
      var target = event.target;
      if (!target || target === window) {{
        return;
      }}
      var url = target.src || target.href || "";
      if (CRITICAL_RESOURCE.test(url)) {{
        dependencyFailed = true;
        showRecovery();
      }}
    }},
    true
  );

  setTimeout(function () {{
    if (!engineStarted && (dependencyFailed || navigator.onLine === false)) {{
      showRecovery();
    }}
  }}, RECOVERY_DEADLINE_MS);
}})();
"""


def generate() -> list[Path]:
    CSS_OUTPUT.write_text(render_css(), encoding="utf-8")
    JS_OUTPUT.write_text(render_js(), encoding="utf-8")
    return [CSS_OUTPUT, JS_OUTPUT]


def check() -> None:
    problems: list[str] = []
    for path, expected in ((CSS_OUTPUT, render_css()), (JS_OUTPUT, render_js())):
        if not path.is_file():
            problems.append(f"missing generated asset: {path.name}")
        elif path.read_text(encoding="utf-8") != expected:
            problems.append(f"generated asset is stale: {path.name}")
    if problems:
        raise WebBootstrapAssetsError(
            "web bootstrap assets are out of sync (run: python3 "
            "quwoquan_app/scripts/cli.py web generate-bootstrap): "
            + "; ".join(problems)
        )
