// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../../ui/rtc/providers/call_session_provider_lifecycle_test.dart' as source_test;

void main() {
  source_test.main();
}
