// spec_ref: specs/feature-tree/runtime/runtime-client-foundation/cold-start-performance/spec.md#gwt-001
// spec_ref: specs/feature-tree/runtime/runtime-client-foundation/cold-start-performance/spec.md#gwt-004

import 'dart:io';

import 'package:flutter/painting.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:quwoquan_app/core/design_system/colors/app_colors.dart';

void main() {
  group('startup native/Flutter handoff contract', () {
    test('Android 使用自适应渐变背景、同源品牌簇与贴底品牌名条，不拉伸整屏截图', () {
      for (final path in const <String>[
        'android/app/src/main/res/drawable/launch_background.xml',
        'android/app/src/main/res/drawable-v21/launch_background.xml',
        'android/app/src/main/res/drawable-night/launch_background.xml',
        'android/app/src/main/res/drawable-night-v21/launch_background.xml',
      ]) {
        final xml = _readAppFile(path);
        expect(
          xml,
          contains(
            'Generated by generate_native_launch_welcome_final_test.dart',
          ),
        );
        expect(xml, contains('<gradient'));
        expect(
          xml,
          contains(
            'android:startColor="${_hexRgb(AppColors.welcomeGradientStart)}"',
          ),
        );
        expect(
          xml,
          contains(
            'android:centerColor="${_hexRgb(AppColors.welcomeBackground)}"',
          ),
        );
        expect(
          xml,
          contains(
            'android:endColor="${_hexRgb(AppColors.welcomeGradientEnd)}"',
          ),
        );
        expect(xml, contains('@drawable/launch_brand_cluster'));
        expect(xml, contains('android:width="393dp"'));
        expect(xml, contains('android:height="500dp"'));
        // 底部品牌名条：852 基准 96dp 贴底，视觉中心约 90% 屏高。
        expect(xml, contains('@drawable/launch_brand_footer'));
        expect(xml, contains('android:height="96dp"'));
        expect(xml, contains('android:gravity="bottom|center_horizontal"'));
        expect(xml, isNot(contains('@drawable/launch_welcome_final')));
      }

      for (final path in const <String>[
        'android/app/src/main/res/drawable-nodpi/launch_brand_cluster.png',
        'assets/brand/launch_welcome_background_master.png',
        'assets/brand/launch_brand_cluster_full_master.png',
      ]) {
        final file = _appFile(path);
        expect(file.existsSync(), isTrue, reason: path);
        expect(file.lengthSync(), greaterThan(10 * 1024), reason: path);
      }
      for (final path in const <String>[
        'android/app/src/main/res/drawable-nodpi/launch_brand_footer.png',
        'assets/brand/launch_brand_footer_master.png',
      ]) {
        final file = _appFile(path);
        expect(file.existsSync(), isTrue, reason: path);
        expect(file.lengthSync(), greaterThan(1024), reason: path);
      }
      const responsiveBuckets = <(int, int)>[(360, 91), (393, 96), (430, 104)];
      for (final bucket in responsiveBuckets) {
        final width = bucket.$1;
        final footerHeight = bucket.$2;
        for (final directory in <String>[
          'drawable-sw${width}dp',
          'drawable-sw${width}dp-v21',
          'drawable-sw${width}dp-night',
          'drawable-sw${width}dp-night-v21',
        ]) {
          final xml = _readAppFile(
            'android/app/src/main/res/$directory/launch_background.xml',
          );
          expect(
            xml,
            contains(
              'Generated by generate_native_launch_welcome_final_test.dart',
            ),
          );
          expect(xml, contains('android:width="${width}dp"'));
          expect(xml, contains('android:height="${footerHeight}dp"'));
          expect(xml, contains('@drawable/launch_brand_cluster'));
          expect(xml, contains('@drawable/launch_brand_footer'));
        }
        final bucketImageRoot =
            'android/app/src/main/res/drawable-sw${width}dp-nodpi';
        expect(
          _pngSize(_appFile('$bucketImageRoot/launch_brand_cluster.png')),
          (width * 3, 1500),
        );
        expect(_pngSize(_appFile('$bucketImageRoot/launch_brand_footer.png')), (
          width * 3,
          footerHeight * 3,
        ));
      }

      final generator = _readAppFile(
        'tool/generate_native_launch_welcome_final_test.dart',
      );
      expect(generator, contains('WelcomeStaticFrame'));
      expect(generator, contains('WelcomeFlowerMark'));
      expect(generator, contains('WelcomeBrandFooter'));
      expect(generator, contains('launch_brand_footer'));
      expect(generator, contains('_centerCrop'));
      expect(generator, contains('_writeAndroidLaunchResources'));
      expect(generator, contains('_androidResponsiveBuckets'));
      expect(generator, contains('_writeAndroidResponsiveBucketResources'));
      expect(generator, contains('WelcomeBrandFooter.resolveStripHeight'));
      expect(generator, contains('width: 360, height: 800'));
      expect(generator, contains('width: 393, height: 852'));
      expect(generator, contains('width: 430, height: 932'));
      expect(generator, contains('AppColors.welcomeGradientStart'));
      expect(generator, contains('AppColors.welcomeBackground'));
      expect(generator, contains('AppColors.welcomeGradientEnd'));
      expect(
        generator,
        contains('FontLoader(AppTypography.welcomeBrandFontFamily)'),
      );
      final wrapper = _readAppFile(
        'scripts/media/generate_native_launch_assets.py',
      );
      expect(wrapper, contains('run_flutter_final_frame_export()'));
      expect(wrapper, contains('require_flutter_outputs()'));
      expect(wrapper, isNot(contains('ensure_fallback_assets')));
      expect(wrapper, isNot(contains('vertical_gradient')));
      expect(wrapper, isNot(contains('WELCOME_GRADIENT_START')));
      expect(wrapper, isNot(contains('from PIL import Image')));
    });

    test('Android launcher 先经原生 fatal gate，正常分支才进入 MainActivity', () {
      expect(
        _appFile(
          'android/app/src/main/java/com/quwoquan/quwoquan_app/NativeWelcomeView.java',
        ).existsSync(),
        isFalse,
      );
      expect(
        _appFile(
          'android/app/src/main/java/com/quwoquan/quwoquan_app/StartupActivity.java',
        ).existsSync(),
        isFalse,
      );

      final manifest = _readAppFile('android/app/src/main/AndroidManifest.xml');
      expect(manifest, contains('android:name=".StartupGateActivity"'));
      expect(manifest, contains('android:name=".MainActivity"'));
      expect(manifest, contains('android:name=".QuwoquanApplication"'));
      expect(manifest, contains('android.intent.category.LAUNCHER'));
      expect(manifest, isNot(contains('.StartupActivity')));
      expect(
        manifest.indexOf('android:name=".StartupGateActivity"'),
        lessThan(manifest.indexOf('android.intent.category.LAUNCHER')),
      );
      final gateDeclaration = manifest.substring(
        manifest.indexOf('android:name=".StartupGateActivity"'),
        manifest.indexOf(
          '</activity>',
          manifest.indexOf('android:name=".StartupGateActivity"'),
        ),
      );
      final mainDeclaration = manifest.substring(
        manifest.indexOf('android:name=".MainActivity"'),
        manifest.indexOf(
          '</activity>',
          manifest.indexOf('android:name=".MainActivity"'),
        ),
      );
      expect(gateDeclaration, contains('android:theme="@style/LaunchTheme"'));
      expect(mainDeclaration, contains('android:theme="@style/NormalTheme"'));

      final java = _readAppFile(
        'android/app/src/main/java/com/quwoquan/quwoquan_app/MainActivity.java',
      );
      final gate = _readAppFile(
        'android/app/src/main/java/com/quwoquan/quwoquan_app/StartupGateActivity.java',
      );
      final health = _readAppFile(
        'android/app/src/main/java/com/quwoquan/quwoquan_app/StartupHealthStore.java',
      );
      final application = _readAppFile(
        'android/app/src/main/java/com/quwoquan/quwoquan_app/QuwoquanApplication.java',
      );
      final clock = _readAppFile(
        'android/app/src/main/java/com/quwoquan/quwoquan_app/StartupProcessClock.java',
      );
      for (final forbidden in const <String>[
        'NativeWelcomeView',
        'StartupActivity',
        'addContentView',
        'drawFlower',
        'flutterWelcomeReady',
        'flutterWelcomeCompleted',
        '启动中',
      ]) {
        expect(java, isNot(contains(forbidden)), reason: forbidden);
      }
      expect(java, contains('elapsedSinceProcessStartMs'));
      expect(java, contains('android_process'));
      expect(
        java,
        contains('StartupProcessClock.elapsedSinceProcessStartMs()'),
      );
      expect(
        java,
        isNot(
          contains('processStartElapsedMs = SystemClock.elapsedRealtime()'),
        ),
      );
      expect(application, contains('StartupProcessClock.initialize();'));
      expect(
        application,
        contains('StartupHealthStore.installNativeCrashMarker(this);'),
      );
      expect(clock, contains('SystemClock.elapsedRealtime()'));
      expect(clock, contains('Process.getStartElapsedRealtime()'));
      expect(clock, contains('platformProcessStart > 0L'));
      expect(clock, contains('platformProcessStart <= now'));
      expect(gate, contains('StartupProcessClock.initialize();'));
      expect(
        gate,
        contains(
          'StartupHealthStore.promoteConfirmedPlatformStartupCrash(this)',
        ),
      );
      expect(
        gate,
        contains('StartupHealthStore.shouldRecoverConfirmedStartupFatal(this)'),
      );
      expect(
        health,
        contains('clearFatalMarker(preferences, "safe_shell_conflict")'),
      );
      expect(
        health,
        contains('clearFatalMarker(preferences, "artifact_mismatch")'),
      );
      expect(health, contains('static boolean markCurrentArtifactFatal'));
      expect(health, contains('preferences.getBoolean(SAFE_SHELL_KEY, false)'));
      expect(java, contains('currentDartAttemptIsHotRestart'));
      expect(java, contains('recordCurrentDartAttemptFatal('));
      expect(java, contains('startup_fatal_marker_ignored reason=hot_restart'));
      expect(
        java,
        contains('startup_fatal_marker_ignored reason=safe_shell_reached'),
      );
      expect(java, contains('startup_fatal_marker_recorded'));
      expect(
        gate.indexOf('shouldRecoverConfirmedStartupFatal(this)'),
        lessThan(gate.indexOf('startFlutterMainActivity();')),
      );
      expect(gate, contains('showNativeStartupRecovery();'));
      expect(
        gate,
        contains('StartupHealthStore.enqueueConfirmedStartupFatal(this)'),
      );
      expect(
        gate.indexOf('enqueueConfirmedStartupFatal(this)'),
        lessThan(gate.indexOf('showNativeStartupRecovery();')),
      );
      expect(gate, contains('STATE_MAIN_HANDOFF_STARTED'));
      expect(gate, contains('mainHandoffStarted = true;'));
      expect(gate, isNot(contains('main.setFlags(incoming.getFlags());')));
      expect(gate, contains('showNativeLaunchFrameThenStartFlutter'));
      expect(gate, contains('R.drawable.launch_background'));
      expect(gate, contains('ViewTreeObserver.OnDrawListener'));
      expect(gate, contains('android_gate_static_frame_drawn'));
      expect(
        gate.indexOf('mainHandler.post(\n                () -> {'),
        greaterThan(gate.indexOf('android_gate_static_frame_drawn')),
      );
      expect(
        gate.indexOf('removeOnDrawListener(this);'),
        greaterThan(gate.indexOf('mainHandler.post(\n                () -> {')),
      );
      expect(gate, isNot(contains('FlutterEngine')));
      expect(gate, isNot(contains('StartupEagerPluginRegistry')));
      expect(health, contains('BuildConfig.QWQ_RUNTIME_CONFIG_DIGEST'));
      expect(
        health,
        contains('BuildConfig.QWQ_EFFECTIVE_LAUNCH_MANIFEST_DIGEST'),
      );
      expect(health, contains('BuildConfig.QWQ_RUNTIME_ENVIRONMENT'));
      expect(health, contains('STARTED_AT_KEY'));
      expect(
        health.indexOf('latestExit.getTimestamp() < previousStartedAt'),
        lessThan(
          health.indexOf('putString(FATAL_BUILD_IDENTITY_KEY, identity)'),
        ),
      );
      for (final field in const <String>[
        'occurredAt',
        'appVersion',
        'buildNumber',
        'platform',
        'osVersion',
        'deviceModel',
        'errorSource',
        'errorType',
        'errorMessage',
        'stackTrace',
      ]) {
        expect(health, contains('failure.put("$field"'), reason: field);
      }
      expect(health, contains('MAX_RECOVERY_RECORDS = 20'));
      expect(health, contains('TimeUnit.DAYS.toMillis(7)'));
      expect(health, contains('clearAllMarkersForInstrumentedTest'));
      expect(health, contains('seedConfirmedStartupFatalForInstrumentedTest'));

      final instrumentation = _readAppFile(
        'android/app/src/androidTest/java/com/quwoquan/quwoquan_app/StartupGateHandoffInstrumentedTest.java',
      );
      expect(
        instrumentation,
        contains('launcherIntentHandsOffToMainWithoutGateFlutterEngine'),
      );
      expect(
        instrumentation,
        contains('repeatedLauncherTapReusesMainAndBackDoesNotRevealDuplicate'),
      );
      expect(gate, contains('android_gate_warm_task_handoff'));
      expect(gate, contains('Intent.FLAG_ACTIVITY_CLEAR_TOP'));
      expect(gate, contains('Intent.FLAG_ACTIVITY_SINGLE_TOP'));
      expect(
        instrumentation,
        contains('confirmedFatalStaysOnNativeRecoveryWithoutFlutterEngine'),
      );
      expect(instrumentation, contains('assertConditionRemains'));
      expect(instrumentation, contains('flutterEngineOf(firstMain)'));
      expect(instrumentation, contains('assertSame(firstEngine'));
      expect(
        instrumentation,
        isNot(contains('gate.toString().contains("FlutterEngine")')),
      );
      expect(instrumentation, contains('mainEarlyFailureIsVisibleToNextGate'));
      expect(instrumentation, contains('AndroidJUnit4'));
      expect(instrumentation, isNot(contains('PatrolJUnitRunner')));
      final resourceInstrumentation = _readAppFile(
        'android/app/src/androidTest/java/com/quwoquan/quwoquan_app/'
        'StartupLaunchResourceInstrumentedTest.java',
      );
      expect(
        resourceInstrumentation,
        contains('sw393LaunchBackgroundMatchesFlutterFinalFrame'),
      );
      expect(resourceInstrumentation, contains('smallestScreenWidthDp ='));
      expect(resourceInstrumentation, contains('R.drawable.launch_background'));
      expect(
        resourceInstrumentation,
        contains('R.drawable.launch_welcome_final'),
      );
      final gradle = _readAppFile('android/app/build.gradle.kts');
      expect(
        gradle,
        contains('androidTestImplementation("androidx.test.ext:junit'),
      );
      expect(
        gradle,
        contains(
          'androidTestImplementation("androidx.test.espresso:espresso-core',
        ),
      );
      expect(gradle, contains('qwq.nativeStartupInstrumentation'));
      expect(gradle, contains('androidx.test.runner.AndroidJUnitRunner'));
      expect(gradle, contains('"QWQ_RUNTIME_CONFIG_DIGEST"'));
      expect(gradle, contains('expectedRuntimeConfigDigest'));
      expect(gradle, isNot(contains('nativeRuntimeConfigDigest')));
    });

    test('iOS fatal gate 在 FlutterAppDelegate 与 implicit engine 之前终止启动', () {
      final ios = _readAppFile('ios/Runner/AppDelegate.swift');
      final scene = _readAppFile('ios/Runner/AppSceneDelegate.swift');
      final xcodeProject = _readAppFile('ios/Runner.xcodeproj/project.pbxproj');
      final appDelegateGate = ios.substring(
        ios.indexOf(
          '  override func application(\n'
          '    _ application: UIApplication,\n'
          '    willFinishLaunchingWithOptions',
        ),
        ios.indexOf('  func didInitializeImplicitFlutterEngine'),
      );
      expect(
        appDelegateGate,
        contains(
          'confirmedPreviousBuildFatal = '
          'NativeCrashMarkerStore.shouldRecoverCurrentBuild()',
        ),
      );
      expect(appDelegateGate, contains('#if QWQ_STARTUP_GATE_TEST_CONTROL'));
      expect(
        xcodeProject,
        contains(
          'SWIFT_ACTIVE_COMPILATION_CONDITIONS = '
          '"\$(inherited) QWQ_STARTUP_GATE_TEST_CONTROL";',
        ),
      );
      expect(
        'QWQ_STARTUP_GATE_TEST_CONTROL'.allMatches(xcodeProject),
        hasLength(1),
      );
      expect(
        appDelegateGate.indexOf('if confirmedPreviousBuildFatal'),
        lessThan(
          appDelegateGate.indexOf(
            'return super.application(\n'
            '      application,\n'
            '      willFinishLaunchingWithOptions: launchOptions',
          ),
        ),
      );
      expect(
        appDelegateGate,
        contains('configurationForConnecting connectingSceneSession'),
      );
      expect(
        appDelegateGate,
        contains('recovery.delegateClass = StartupRecoverySceneDelegate.self'),
      );
      expect(appDelegateGate, contains('recovery.storyboard = nil'));
      expect(
        appDelegateGate,
        contains('normal.delegateClass = AppSceneDelegate.self'),
      );
      expect(
        appDelegateGate,
        contains('normal.storyboard = UIStoryboard(name: "Main", bundle: nil)'),
      );
      expect(
        appDelegateGate,
        isNot(
          contains(
            'configurationForConnecting: connectingSceneSession,\n'
            '        options: options',
          ),
        ),
      );
      expect(scene, contains('class StartupRecoverySceneDelegate'));
      expect(
        scene,
        contains(
          'appDelegate.installNativeStartupRecoveryRoot(in: recoveryWindow)',
        ),
      );
      expect(scene, contains('appDelegate.showNativeStartupRecovery()'));
      final recoveryScene = scene.substring(
        scene.indexOf('class StartupRecoverySceneDelegate'),
        scene.indexOf('@objc final class AppSceneDelegate'),
      );
      expect(recoveryScene, isNot(contains('FlutterSceneDelegate')));
      final iosGateProbe = _readAppFile(
        'scripts/device/verify_ios_native_startup_gate.py',
      );
      expect(
        iosGateProbe,
        contains('ios_native_startup_recovery_scene_connected'),
      );
      expect(iosGateProbe, contains('ios_implicit_flutter_engine_initialized'));
      expect(iosGateProbe, contains('--qwq-test-confirmed-startup-fatal'));
      expect(iosGateProbe, contains('--qwq-test-clear-startup-fatal'));
      expect(iosGateProbe, isNot(contains('"uninstall"')));
      expect(iosGateProbe, contains('"normalLaunchVerified"'));
      expect(iosGateProbe, contains('"status": "passed" if not issues'));
      expect(ios, contains('effectiveLaunchManifestDigest'));
      expect(ios, contains('clearFatalMarker(reason: "safe_shell_conflict")'));
      expect(ios, contains('clearFatalMarker(reason: "artifact_mismatch")'));
      expect(ios, contains('static func markFatalStartup() -> Bool'));
      expect(ios, contains('currentDartAttemptIsHotRestart'));
      expect(ios, contains('recordCurrentDartAttemptFatal('));
      expect(ios, contains('startup_fatal_marker_ignored reason=hot_restart'));
      expect(
        ios,
        contains('startup_fatal_marker_ignored reason=safe_shell_reached'),
      );
      expect(ios, contains('startup_fatal_marker_recorded'));
      expect(
        ios,
        contains(
          'assertionFailure('
          '"Flutter engine initialized behind native startup recovery gate"',
        ),
      );
      expect(ios, contains('maximumRecoveryRecords = 20'));
      expect(
        ios,
        contains('recoveryRetention: TimeInterval = 7 * 24 * 60 * 60'),
      );
    });

    test('Android 12 使用同源静态花瓣 icon，Launch/Normal 使用同一背景', () {
      for (final path in const <String>[
        'android/app/src/main/res/values/styles.xml',
        'android/app/src/main/res/values-night/styles.xml',
        'android/app/src/main/res/values-v31/styles.xml',
        'android/app/src/main/res/values-night-v31/styles.xml',
      ]) {
        final xml = _readAppFile(path);
        expect(xml, contains('<style name="LaunchTheme"'));
        expect(xml, contains('<style name="NormalTheme"'));
        expect(xml, contains('@drawable/launch_background'));
        // 状态栏透明 + 浅色内容：原生阶段与 Flutter 品牌 overlay 同源。
        expect(
          xml,
          contains(
            '<item name="android:statusBarColor">@android:color/transparent</item>',
          ),
        );
        expect(
          xml,
          contains('<item name="android:windowLightStatusBar">false</item>'),
        );
        expect(xml, isNot(contains('FlutterStartupTheme')));
        expect(xml, isNot(contains('Theme.SplashScreen')));
        expect(xml, isNot(contains('android:windowIsTranslucent')));
      }
      for (final path in const <String>[
        'android/app/src/main/res/values-v31/styles.xml',
        'android/app/src/main/res/values-night-v31/styles.xml',
      ]) {
        final xml = _readAppFile(path);
        expect(
          xml,
          contains(
            '<item name="android:windowSplashScreenBackground">@color/quwoquan_launch_blue</item>',
          ),
        );
        expect(
          xml,
          contains(
            '<item name="android:windowSplashScreenIconBackgroundColor">@color/quwoquan_launch_blue</item>',
          ),
        );
        expect(xml, contains('@mipmap/ic_launcher'));
        expect(xml, contains('windowSplashScreenIconBackgroundColor'));
        expect(xml, isNot(contains('@drawable/launch_empty_icon')));
      }
      final colors = _readAppFile('android/app/src/main/res/values/colors.xml');
      expect(
        colors,
        contains(
          '<color name="quwoquan_launch_blue">${_hexRgb(AppColors.welcomeBackground)}</color>',
        ),
      );
    });

    test('Flutter 是唯一动效所有者，生产没有最少等待 6 秒', () {
      final welcome = _readAppFile('lib/ui/welcome/pages/welcome_screen.dart');
      final timeline = _readAppFile(
        'lib/ui/welcome/welcome_motion_timeline.dart',
      );
      final flower = _readAppFile(
        'lib/ui/welcome/widgets/welcome_flower_mark.dart',
      );
      final shell = _readAppFile('lib/quwoquan_app_shell.dart');

      expect(timeline, contains('StartupWelcomeTiming production'));
      expect(timeline, contains('Duration(seconds: 3)'));
      expect(timeline, contains('Duration(seconds: 6)'));
      expect(timeline, contains('maxReplayCount: 2'));
      expect(timeline, contains('minimumCompressionRatio = 0.65'));
      expect(timeline, contains("motionSpec = 'petal_bloom'"));
      expect(
        timeline,
        contains('gatheringOrder = <int>[7, 6, 5, 4, 3, 2, 1, 0]'),
      );
      expect(
        timeline,
        contains('bloomingOrder = <int>[0, 1, 2, 3, 4, 5, 6, 7]'),
      );
      expect(welcome, contains('SingleTickerProviderStateMixin'));
      expect(welcome, contains('_terminal'));
      expect(welcome, contains('WelcomeExitReason.deadline'));
      expect(welcome, contains('WelcomeFlowMode.startup'));
      expect(welcome, isNot(contains('waitUntilFirstFrameRasterized')));
      expect(welcome, isNot(contains('WidgetsBinding.instance.endOfFrame')));
      expect(welcome, isNot(contains('minEnterDelay')));
      expect(welcome, isNot(contains('maxWaitingBloomCycles')));
      expect(welcome, isNot(contains('List<AnimationController>')));
      expect(flower, contains('historicalBudVisualFactor = 0.561024'));
      expect(flower, contains('canvas.scale(visualFactor)'));
      expect(flower, isNot(contains('Matrix4')));
      expect(flower, isNot(contains('rotateX')));
      expect(flower, isNot(contains('scaleY')));
      expect(shell, contains('ensureAppRouterLibraryLoaded'));
      expect(shell, contains('WelcomeFlowMode.frozen'));
      expect(shell, contains('Duration(milliseconds: 120)'));
      expect(shell, contains("phase: 'welcome_overlay_removed'"));
      expect(shell, contains("'overlayRemovedMs': removedMs"));
      expect(shell, contains("trigger: 'shell_first_paint'"));
      expect(shell, contains('StartupStateMachine'));
      expect(shell, contains('_armStartupDeadline'));
      expect(
        shell,
        isNot(contains('remaining + const Duration(milliseconds: 800)')),
      );
      expect(shell, contains('_buildStartupFallbackApp'));
    });

    test('欢迎页高保调色不外溢到 RTC 通话舞台', () {
      expect(AppColors.callStageGradientStartLight, const Color(0xFF1491FF));
      expect(AppColors.callStageGradientEndLight, const Color(0xFF1554D1));
      expect(AppColors.callStageForeground, AppColors.white);
      for (final path in const <String>[
        'lib/ui/rtc/pages/outgoing_call_page.dart',
        'lib/ui/rtc/pages/incoming_call_page.dart',
        'lib/ui/rtc/widgets/call_stage_chrome.dart',
      ]) {
        final source = _readAppFile(path);
        expect(source, isNot(contains('welcomeGradient')), reason: path);
        expect(source, isNot(contains('welcomeForeground')), reason: path);
      }
    });

    test('三端从平台最早时钟计算 6 秒预算，只传时间不传动画状态', () {
      final bridge = _readAppFile(
        'lib/core/platform/startup_native_bridge.dart',
      );
      final runtime = _readAppFile('lib/app/app_startup_runtime.dart');
      final android = _readAppFile(
        'android/app/src/main/java/com/quwoquan/quwoquan_app/MainActivity.java',
      );
      final androidGate = _readAppFile(
        'android/app/src/main/java/com/quwoquan/quwoquan_app/StartupGateActivity.java',
      );
      final ios = _readAppFile('ios/Runner/AppDelegate.swift');
      final web = _readAppFile('web/index.html');

      expect(bridge, contains('elapsedSinceProcessStartMs'));
      expect(bridge, contains('deadlineOrigin'));
      expect(bridge, contains('StartupJournalNativeBridge'));
      expect(bridge, contains('readStartupJournal'));
      expect(bridge, contains('clearStartupJournal'));
      expect(runtime, contains('elapsedSinceProcessStart'));
      expect(runtime, contains("'fallbackDart'"));
      final welcome = _readAppFile('lib/ui/welcome/pages/welcome_screen.dart');
      expect(welcome, contains('hydrateNativeProcessSegments'));
      expect(welcome, contains('unawaited('));
      expect(welcome, contains('_armDeadline();'));
      expect(welcome, contains('_refreshNativeSegmentsWithoutBlockingWelcome'));
      expect(android, contains('SystemClock.elapsedRealtime()'));
      expect(android, contains('android_process'));
      expect(android, contains('recordStartupEvent'));
      expect(android, contains('startup_event'));
      expect(android, contains('FLUTTER_FIRST_FRAME_DEADLINE_MS'));
      expect(android, contains('FLUTTER_FIRST_FRAME_DEADLINE_MS = 3000L'));
      expect(android, contains('FlutterUiDisplayListener'));
      expect(android, contains('addIsDisplayingFlutterUiListener'));
      expect(android, isNot(contains('scheduleNativeRecoveryTerminal')));
      expect(android, isNot(contains('showNativeStartupRecovery')));
      expect(androidGate, contains('showNativeStartupRecovery'));
      expect(android, contains('flutter_first_frame'));
      expect(
        android,
        contains('StartupEagerPluginRegistry.registerWith(flutterEngine)'),
      );
      expect(android, contains('ScheduledExecutorService'));
      expect(android, contains('consumeForegroundFirstFrameBudget'));
      expect(android, contains('startupWatchdogExecutor.schedule'));
      expect(android, contains('nativeFirstFrameDeadlineReached'));
      expect(android, contains('startup_probe phase='));
      expect(android, contains('startupSafeTerminalConfirmed'));
      expect(android, contains('startup_safe_terminal'));
      expect(
        android,
        isNot(contains('dismissNativeStartupRecoveryForSafeTerminalRace')),
      );
      expect(
        android.indexOf('registerStartupTimingsChannel(flutterEngine);'),
        lessThan(
          android.indexOf(
            'StartupEagerPluginRegistry.registerWith(flutterEngine);',
          ),
        ),
      );
      expect(ios, contains('ProcessInfo.processInfo.systemUptime'));
      expect(ios, contains('ios_process'));
      expect(ios, contains('currentArtifactIdentity'));
      expect(ios, contains('runtimeConfigDigest'));
      expect(ios, contains('recordStartupEvent'));
      expect(ios, contains('flutterFirstFrameDeadline'));
      expect(ios, contains('currentDartAttemptStartedUptime'));
      expect(ios, contains('showNativeStartupRecovery'));
      expect(ios, contains('consumeForegroundFirstFrameBudget'));
      expect(ios, contains('nativeRecoveryDeadlineReached'));
      expect(ios, contains('startup_probe phase='));
      expect(ios, contains('startupSafeTerminalConfirmed'));
      expect(ios, contains('startup_safe_terminal'));
      expect(ios, contains('setFlutterViewDidRenderCallback'));
      expect(ios, contains('scheduleNativeRecoveryTerminal'));
      expect(ios, contains('cancelNativeRecoveryTerminalReconciliation'));
      expect(ios, contains('dismissNativeStartupRecoveryForSafeTerminalRace'));
      expect(ios, contains('ios_startup_safe_terminal_race_dismissed'));
      final iosDidFinishLaunch = ios.substring(
        ios.indexOf('    didFinishLaunchingWithOptions launchOptions:'),
        ios.indexOf('    configurationForConnecting connectingSceneSession:'),
      );
      expect(iosDidFinishLaunch, isNot(contains('registrar(forPlugin:')));
      expect(
        iosDidFinishLaunch,
        isNot(contains('configureIncomingCallInfrastructure')),
      );
      final iosImplicitEngineInitialization = ios.substring(
        ios.indexOf('func didInitializeImplicitFlutterEngine'),
        ios.indexOf('private func registerMethodChannels'),
      );
      expect(
        iosImplicitEngineInitialization,
        contains(
          'configureIncomingCallInfrastructure('
          'pluginRegistry: engineBridge.pluginRegistry)',
        ),
      );
      expect(
        iosImplicitEngineInitialization,
        contains(
          'GeneratedPluginRegistrant.register('
          'with: engineBridge.pluginRegistry)',
        ),
      );
      expect(
        iosImplicitEngineInitialization.indexOf(
          'configureIncomingCallInfrastructure',
        ),
        lessThan(
          iosImplicitEngineInitialization.indexOf(
            'GeneratedPluginRegistrant.register',
          ),
        ),
      );
      expect(
        iosImplicitEngineInitialization.indexOf(
          'GeneratedPluginRegistrant.register',
        ),
        lessThan(
          iosImplicitEngineInitialization.indexOf('registerMethodChannels('),
        ),
      );
      expect(ios, isNot(contains('deferredPluginRegistry')));
      expect(ios, isNot(contains('registerGeneratedPluginsAfterFirstFrame')));
      expect(web, contains('__qwqStartupStartedAtMs'));
      expect(web, contains('__qwqStartupElapsedMs'));
      expect(web, isNot(contains('__qwqShowStartupRecovery')));
      expect(web, isNot(contains('web_first_frame_timeout')));
      expect(web, isNot(contains('qwq-startup-recovery')));
      expect(web, isNot(contains('indexedDB.open')));
      expect(web, isNot(contains('location.reload()')));
      expect(web, contains('__qwqReadStartupJournal'));
      expect(web, contains('__qwqClearStartupJournal'));
      expect(web, contains('<html lang="zh-CN">'));
      expect(web, contains('<meta charset="utf-8">'));
      expect(android, contains('StartupNativeTelemetryJournal'));
      expect(android, contains('readStartupJournal'));
      expect(android, contains('clearStartupJournal'));
      final androidJournal = _readAppFile(
        'android/app/src/main/java/com/quwoquan/quwoquan_app/StartupNativeTelemetryJournal.java',
      );
      expect(androidJournal, contains('startup_telemetry_native_attempt'));
      expect(androidJournal, isNot(contains('_v1')));
      expect(
        androidJournal,
        contains('remove(ATTEMPT_KEY).remove(EVENTS_KEY)'),
      );
      expect(androidJournal, isNot(contains('lastElapsedMs')));
      expect(androidJournal, isNot(contains('phaseDurationMs')));
      expect(ios, contains('StartupNativeTelemetryJournal'));
      expect(ios, contains('readStartupJournal'));
      expect(ios, contains('clearStartupJournal'));
      expect(ios, isNot(contains('private var lastElapsedMs')));
      expect(web, isNot(contains('__qwqStartupNativeLastElapsedMs')));
      for (final source in <String>[android, ios, bridge]) {
        expect(source, isNot(contains('animationProgress')));
        expect(source, isNot(contains('replayCount')));
        expect(source, isNot(contains('petal')));
      }
    });

    test('iOS LaunchScreen 使用自适应背景、同源品牌簇与贴底品牌名条', () {
      final plist = _readAppFile('ios/Runner/Info.plist');
      final storyboard = _readAppFile(
        'ios/Runner/Base.lproj/LaunchTransitionScreen.storyboard',
      );
      expect(plist, contains('<string>LaunchTransitionScreen</string>'));
      // 原生启动阶段状态栏即为浅色内容，与 Flutter 品牌 overlay 无明暗闪变。
      expect(plist, contains('<string>UIStatusBarStyleLightContent</string>'));
      expect(storyboard, contains('image="LaunchTransitionBackground"'));
      expect(storyboard, contains('image="LaunchBrandCluster"'));
      expect(storyboard, contains('QWQ-LAUNCH-BRAND-CENTER-X'));
      expect(storyboard, contains('QWQ-LAUNCH-BRAND-CENTER-Y'));
      expect(storyboard, contains('constant="393"'));
      expect(storyboard, contains('constant="500"'));
      expect(storyboard, contains('image="LaunchBrandFooter"'));
      expect(storyboard, contains('QWQ-LAUNCH-BRAND-FOOTER-BOTTOM'));
      expect(storyboard, contains('QWQ-LAUNCH-BRAND-FOOTER-CENTER-X'));
      expect(storyboard, contains('constant="96"'));

      final adaptiveBackgrounds = <String, (int, int)>{
        'ios/Runner/Assets.xcassets/LaunchTransitionBackground.imageset/LaunchTransitionBackground.png':
            (1, 3),
        'ios/Runner/Assets.xcassets/LaunchTransitionBackground.imageset/LaunchTransitionBackground@2x.png':
            (2, 6),
        'ios/Runner/Assets.xcassets/LaunchTransitionBackground.imageset/LaunchTransitionBackground@3x.png':
            (3, 9),
      };
      for (final entry in adaptiveBackgrounds.entries) {
        final file = _appFile(entry.key);
        expect(file.existsSync(), isTrue, reason: entry.key);
        expect(_pngSize(file), entry.value, reason: entry.key);
      }

      for (final path in const <String>[
        'ios/Runner/Assets.xcassets/LaunchBrandCluster.imageset/LaunchBrandCluster.png',
        'ios/Runner/Assets.xcassets/LaunchBrandCluster.imageset/LaunchBrandCluster@2x.png',
        'ios/Runner/Assets.xcassets/LaunchBrandCluster.imageset/LaunchBrandCluster@3x.png',
      ]) {
        final file = _appFile(path);
        expect(file.existsSync(), isTrue, reason: path);
        expect(file.lengthSync(), greaterThan(5 * 1024), reason: path);
      }

      final footerSizes = <String, (int, int)>{
        'ios/Runner/Assets.xcassets/LaunchBrandFooter.imageset/LaunchBrandFooter.png':
            (393, 96),
        'ios/Runner/Assets.xcassets/LaunchBrandFooter.imageset/LaunchBrandFooter@2x.png':
            (786, 192),
        'ios/Runner/Assets.xcassets/LaunchBrandFooter.imageset/LaunchBrandFooter@3x.png':
            (1179, 288),
      };
      for (final entry in footerSizes.entries) {
        final file = _appFile(entry.key);
        expect(file.existsSync(), isTrue, reason: entry.key);
        expect(_pngSize(file), entry.value, reason: entry.key);
      }
    });

    test('设备 probe 明确检查原生镜像、可见时限和 Flutter 欢迎事件', () {
      final probe = _readAppFile(
        'scripts/device/verify_startup_first_frame.py',
      );
      final motionProbe = _readAppFile(
        'scripts/device/verify_welcome_motion_frames.py',
      );
      final shell = _readAppFile('lib/quwoquan_app_shell.dart');
      expect(
        probe,
        contains(
          'DEFAULT_ANDROID_ACTIVITY = "com.quwoquan.quwoquan_app/.StartupGateActivity"',
        ),
      );
      expect(probe, contains('nativeWelcomeDetected'));
      expect(probe, contains('FORBIDDEN_NATIVE_WELCOME_LOG_PATTERNS'));
      expect(probe, contains('--android-visible-by-ms'));
      expect(probe, contains('--android-blue-transition-budget-ms'));
      expect(probe, contains('detect_prolonged_system_blue'));
      expect(probe, contains('detect_repeated_splash'));
      expect(probe, contains('detect_native_static_petal_mismatch'));
      expect(probe, contains('system_splash_icon'));
      expect(probe, contains('prolongedSystemBlueDetected'));
      expect(probe, contains('repeatedSplashDetected'));
      expect(probe, contains('nativeStaticPetalMismatch'));
      expect(probe, contains('systemSplashIconDetected'));
      expect(probe, contains('"android.intent.action.MAIN"'));
      expect(probe, contains('"android.intent.category.LAUNCHER"'));
      expect(probe, contains('android-launcher-resolution.txt'));
      expect(probe, contains('android-task-stack.txt'));
      expect(probe, contains('launcherStarted'));
      expect(probe, contains('gateMainOrderObserved'));
      expect(probe, contains('singleMainTask'));
      expect(probe, contains('attempt_id not in {"", "unknown"}'));
      expect(shell, contains('motionSpec=\${WelcomeSequenceEvent.motionSpec}'));
      expect(probe, contains('native_launch_visual_provenance'));
      expect(probe, contains('--skip-screenshots'));
      expect(probe, contains('firstVisibleMs'));
      expect(probe, contains('startupSequenceMotionCurrent'));
      expect(probe, contains('petal_bloom'));
      expect(probe, contains('android_flutter_welcome_ready'));
      expect(probe, isNot(contains('.StartupActivity')));
      expect(
        motionProbe,
        contains('GATHERING_ORDER = (7, 6, 5, 4, 3, 2, 1, 0)'),
      );
      expect(
        motionProbe,
        contains('BLOOMING_ORDER = (0, 1, 2, 3, 4, 5, 6, 7)'),
      );
      expect(motionProbe, contains('oriented_minor'));
      expect(motionProbe, contains('center_radius'));
      expect(motionProbe, contains('frame_displacement'));
    });

    test('公共 CA 单轨不在 Flutter bootstrap 注入本地 trust', () {
      final bootstrap = _readAppFile('lib/app_bootstrap.dart');
      final scheduler = _readAppFile('lib/app/startup_init_scheduler.dart');
      final beforeRunApp = bootstrap.substring(0, bootstrap.indexOf('runApp('));
      expect(beforeRunApp, isNot(contains('await startupPrerequisites')));
      expect(beforeRunApp, isNot(contains('hydrateNativeProcessSegments')));
      // SecureStorage / package_info 不得阻塞 runApp，否则挤爆原生首帧预算。
      expect(beforeRunApp, contains('bootstrapForColdStart'));
      expect(
        beforeRunApp,
        isNot(contains('await AppTelemetrySessionStore.instance.initialize')),
      );
      expect(
        beforeRunApp,
        isNot(
          contains('await AppTelemetryContextProvider.instance.initialize'),
        ),
      );
      expect(bootstrap, contains('reconcilePersistedGuestKey'));
      expect(bootstrap, contains('_hydratePostFirstFrameStartupState'));
      expect(bootstrap, contains('postFirstFrameTasks:'));
      expect(bootstrap, contains('authNetworkPrerequisites:'));
      expect(bootstrap, isNot(contains('LocalDevHttpsTrust')));
      expect(
        beforeRunApp,
        isNot(contains('_hydratePostFirstFrameStartupState()')),
      );
      expect(scheduler, contains('void _markShellReady('));
      expect(scheduler, contains('void _startPostFirstFrameTasks()'));
      expect(scheduler, contains('void _startAuthNetworkPrerequisite()'));
      expect(scheduler, contains('ensureStartupPostFirstFrame'));
      expect(scheduler, contains('_startAuthAfterStartupPrerequisites'));
      expect(scheduler, contains('onShellReady(true)'));
      expect(
        scheduler.indexOf('_markShellReady(onShellReady);'),
        lessThan(scheduler.indexOf('_startAuthAfterStartupPrerequisites();')),
      );
      expect(
        scheduler.indexOf('onShellReady(true)'),
        lessThan(scheduler.indexOf('_startupPrerequisiteTimer = Timer')),
      );
      expect(scheduler, isNot(contains('await prerequisites')));
    });

    test('iOS 仅允许 canonical launcher 传入完整 Dart defines', () {
      final script = _readAppFile('scripts/ios/prepare_dart_defines.sh');
      final logHygiene = _readAppFile(
        'scripts/ios/ios_shortcut_log_hygiene.py',
      );
      final wrapper = _readAppFile('scripts/ios/xcode_backend_build.sh');
      final project = _readAppFile('ios/Runner.xcodeproj/project.pbxproj');
      expect(script, contains('print_app_env_dart_defines.py'));
      expect(script, contains('use ./run.sh -d <device>'));
      expect(script, isNot(contains('DIRECT_ALPHA_HANDOFF')));
      expect(script, isNot(contains('xcode-direct-alpha')));
      expect(script, isNot(contains('export FLUTTER_TARGET=')));
      expect(script, contains('QWQ_IOS_DART_DEFINES_READY'));
      expect(wrapper, contains('runtime package preparation failed'));
      expect(wrapper, contains('QWQ_IOS_DART_DEFINES_READY'));
      expect(project, contains('xcode_backend_build.sh'));
      expect(project, isNot(contains('eval \\"')));
      expect(logHygiene, contains('APP_ROOT / "run.sh"'));
      expect(logHygiene, isNot(contains('cmd = ["flutter", "run"')));
    });

    test('Android 插件由稳定应用注册器分层装配，生成注册器不在构建期修改', () {
      final pluginPolicy = _readAppFile(
        'configs/plugin_registration_policy.json',
      );
      final policyVerifier = _readAppFile(
        'scripts/runtime/verify_plugin_registration_policy.py',
      );
      final registrant = _readAppFile(
        'android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java',
      );
      final deferredRegistry = _readAppFile(
        'android/app/src/main/java/com/quwoquan/quwoquan_app/StartupDeferredPluginRegistry.java',
      );
      final eagerRegistry = _readAppFile(
        'android/app/src/main/java/com/quwoquan/quwoquan_app/StartupEagerPluginRegistry.java',
      );
      final gradle = _readAppFile('android/app/build.gradle.kts');
      final activity = _readAppFile(
        'android/app/src/main/java/com/quwoquan/quwoquan_app/MainActivity.java',
      );
      expect(pluginPolicy, contains('startupPostFirstFrame'));
      expect(pluginPolicy, contains('eagerRuntime'));
      expect(pluginPolicy, contains('contentEntry'));
      expect(
        policyVerifier,
        contains(
          'legacy GeneratedPluginRegistrant patch script must not exist',
        ),
      );
      expect(registrant, contains('new com.github.dart_lang.jni.JniPlugin()'));
      expect(eagerRegistry, contains('com.github.dart_lang.jni.JniPlugin'));
      expect(
        deferredRegistry,
        isNot(contains('com.github.dart_lang.jni.JniPlugin')),
      );
      expect(activity, contains('initializeDartJniClassLoader();'));
      expect(
        activity.indexOf('initializeDartJniClassLoader();'),
        lessThan(activity.indexOf('super.onCreate(savedInstanceState);')),
      );
      expect(activity, contains('android_dart_jni_class_loader_initialized'));
      expect(eagerRegistry, isNot(contains('FlutterWebRTCPlugin')));
      expect(eagerRegistry, isNot(contains('CameraAndroidCameraxPlugin')));
      expect(deferredRegistry, contains('FlutterWebRTCPlugin'));
      expect(deferredRegistry, contains('CameraAndroidCameraxPlugin'));
      expect(
        activity,
        contains('StartupEagerPluginRegistry.registerWith(flutterEngine);'),
      );
      expect(
        activity,
        isNot(contains('super.configureFlutterEngine(flutterEngine);')),
      );
      expect(gradle, contains('afterEvaluate {'));
      expect(gradle, contains('requireCompleteRuntimeDartDefines'));
      expect(gradle, contains('verifyAndroidLocalLauncherContract'));
      expect(gradle, contains('QWQ_CONSUMER_LEASE_ACQUIRED'));
      expect(gradle, contains('QWQ_RUN_DEVICE_ID'));
      expect(gradle, contains('QWQ_RUN_CONSUMER_ID'));
      expect(gradle, contains('QWQ_ANDROID_LOCAL_PORTS'));
      expect(gradle, contains('QWQ_ANDROID_REVERSE_EXPECTED_PORTS'));
      expect(gradle, contains('QWQ_ANDROID_REVERSE_ACTUAL_PORTS'));
      expect(gradle, contains('QWQ_ANDROID_REVERSE_RECEIPT_DIGEST'));
      expect(gradle, isNot(contains('QWQ_LOCAL_TLS_BUNDLE_DIGEST')));
      expect(gradle, contains('QWQ_CONSUMER_LEASE_ID'));
      expect(gradle, contains('QWQ_RUNTIME_CONFIG_DIGEST'));
      expect(
        gradle,
        contains(
          'runtimeEnvironment in setOf("alpha", "beta", "gamma", "prod")',
        ),
      );
      expect(
        gradle,
        contains('expectedEnvironment = effectiveAppRuntimeEnvironment'),
      );
      expect(gradle, isNot(contains('expectedEnvironment = "alpha"')));
      expect(gradle, isNot(contains('mergeAlphaLocalDartDefines')));
      expect(gradle, isNot(contains('prepareAndroidLocalAlphaStack')));
      expect(gradle, isNot(contains('prepareAndroidLocalAdbReverse')));
      expect(gradle, isNot(contains('consumer-lease",\n')));
      expect(gradle, contains('providers.gradleProperty("target-platform")'));
      expect(gradle, contains('abiFilters.addAll(flutterTargetAndroidAbis)'));
      expect(
        gradle,
        contains('Flutter build requires complete runtime dart-defines'),
      );
      expect(
        activity,
        contains('private CommercialAuthPlugin commercialAuthPlugin;'),
      );
      expect(
        activity,
        contains('private CommercialAuthPlugin commercialAuthPlugin()'),
      );
      expect(
        activity,
        contains('private AliyunOneTapPlugin aliyunOneTapPlugin()'),
      );
      expect(
        activity.indexOf(
          'StartupEagerPluginRegistry.registerWith(flutterEngine);',
        ),
        lessThan(activity.indexOf('commercialAuthPlugin().handle')),
      );

      final instanceLauncher = _readAppFile(
        'scripts/device/start_app_instance.sh',
      );
      final launcherHandoff = _readAppFile(
        'scripts/device/build_launcher_handoff.py',
      );
      expect(instanceLauncher, contains('build_launcher_handoff.py'));
      expect(
        launcherHandoff,
        contains(
          'entrypoint = effective_schema["fields"]["entrypoint"]["const"]',
        ),
      );
      expect(launcherHandoff, contains('effectiveLaunchManifestDigest'));
      expect(launcherHandoff, isNot(contains('runners/alpha')));
      expect(instanceLauncher, contains('QWQ_ANDROID_LOCAL_TARGET'));
      expect(instanceLauncher, contains('consumer-lease acquire'));
      expect(instanceLauncher, contains('runtimeConfigDigest'));
      expect(
        instanceLauncher,
        contains('QWQ_EFFECTIVE_LAUNCH_MANIFEST_DIGEST'),
      );
      expect(instanceLauncher, contains('--transport-required'));
      expect(instanceLauncher, contains('QWQ_CONSUMER_LEASE_ID'));
    });

    test('production 启动装配匿名遥测 Remote，并只接受服务端持久化 ACK', () {
      final bootstrap = _readAppFile('lib/app_bootstrap.dart');
      final telemetry = _readAppFile('lib/app/startup/startup_telemetry.dart');
      final remote = _readAppFile(
        'lib/cloud/remote/ops/startup_telemetry_remote.dart',
      );
      expect(bootstrap, contains('StartupTelemetryRuntime.instance.configure'));
      expect(bootstrap, contains('RemoteStartupTelemetryTransport'));
      expect(bootstrap, contains('SharedPreferencesStartupJournalStore'));
      expect(remote, contains('requireAuth: false'));
      expect(remote, contains('OpsApiMetadata.reportStartupEventBatchPath'));
      expect(telemetry, contains('ack.acknowledges(batch.length)'));
      expect(telemetry, contains('startup_telemetry_ack attemptId='));
    });

    test('Root deadline 只在安全终态真实绘制后取消，不能以 Router 状态提前豁免', () {
      final shell = _readAppFile('lib/quwoquan_app_shell.dart');
      final deadlineStart = shell.indexOf('void _armStartupDeadline()');
      final deadlineEnd = shell.indexOf(
        'Future<void> _hydrateNativeTimingForTelemetry()',
        deadlineStart,
      );
      expect(deadlineStart, greaterThanOrEqualTo(0));
      expect(deadlineEnd, greaterThan(deadlineStart));
      final deadlineBody = shell.substring(deadlineStart, deadlineEnd);
      expect(deadlineBody, contains('_routerShellFirstPainted'));
      expect(deadlineBody, isNot(contains('StartupRootPhase.routerShell')));
    });
  });
}

String _readAppFile(String relativePath) =>
    _appFile(relativePath).readAsStringSync();

File _appFile(String relativePath) {
  final direct = File(relativePath);
  if (direct.existsSync()) {
    return direct;
  }
  return File('quwoquan_app/$relativePath');
}

(int, int) _pngSize(File file) {
  final bytes = file.readAsBytesSync();
  expect(bytes.length, greaterThanOrEqualTo(24), reason: file.path);
  int uint32(int offset) =>
      (bytes[offset] << 24) |
      (bytes[offset + 1] << 16) |
      (bytes[offset + 2] << 8) |
      bytes[offset + 3];
  return (uint32(16), uint32(20));
}

String _hexRgb(Color color) {
  final value = color.toARGB32() & 0x00FFFFFF;
  return '#${value.toRadixString(16).padLeft(6, '0').toUpperCase()}';
}
