import 'package:quwoquan_app/runtime/alpha_rehearsal/handlers/chat_handlers.dart';
import 'package:quwoquan_app/runtime/alpha_rehearsal/handlers/content_handlers.dart';
import 'package:quwoquan_app/runtime/alpha_rehearsal/handlers/search_assistant_handlers.dart';
import 'package:quwoquan_app/runtime/alpha_rehearsal/handlers/user_handlers.dart';
import 'package:quwoquan_app/runtime/alpha_rehearsal/kernel/rehearsal_ports.dart';
import 'package:quwoquan_app/runtime/errors/cloud_exception.dart';

final class AlphaRehearsalHandlerRegistry {
  const AlphaRehearsalHandlerRegistry()
    : _contentHandler = const ContentRehearsalHandler();

  AlphaRehearsalHandlerRegistry.withPostExists(PostExistenceResolver postExists)
    : _contentHandler = ContentRehearsalHandler(postExists: postExists);

  final ContentRehearsalHandler _contentHandler;
  // 仅登记实际对象行为；目录声明不是已实现证明。
  static const _bindings = <String, RehearsalObjectHandler>{
    'user.authentication_challenge.GetOtpDeliveryReadiness':
        UserRehearsalHandler(),
    'user.authentication_challenge.SendOtp': UserRehearsalHandler(),
    'user.account_session.LoginWithPhone': UserRehearsalHandler(),
    'user.account_session.Logout': UserRehearsalHandler(),
    'user.persona_relationship.FollowUser': UserRehearsalHandler(),
    'user.persona_relationship.UnfollowUser': UserRehearsalHandler(),
    'user.persona_relationship.GetRelationshipCapability':
        UserRehearsalHandler(),
    'user.persona_relationship.ListFollowing': UserRehearsalHandler(),
    'user.persona_relationship.ListFollowers': UserRehearsalHandler(),
    'user.subject_follow.FollowSubject': UserRehearsalHandler(),
    'user.subject_follow.UnfollowSubject': UserRehearsalHandler(),
    'user.following_subject.ListFollowingSubjects': UserRehearsalHandler(),
    'chat.conversation.CreateConversation': ChatRehearsalHandler(),
    'chat.conversation.GetConversation': ChatRehearsalHandler(),
    'chat.conversation.ListConversations': ChatRehearsalHandler(),
    'chat.message.SendMessage': ChatRehearsalHandler(),
    'chat.message.ListMessages': ChatRehearsalHandler(),
    'gateway.persisted_query_execution.ExecutePersistedGraphQLQuery':
        SearchAssistantRehearsalHandler(),
    'gateway.persisted_query_execution.SearchPage':
        SearchAssistantRehearsalHandler(),
    'assistant.assistant_session.CreateAssistantSession':
        SearchAssistantRehearsalHandler(),
    'assistant.assistant_session.GetAssistantSession':
        SearchAssistantRehearsalHandler(),
    'assistant.assistant_session.ListAssistantSessions':
        SearchAssistantRehearsalHandler(),
    'assistant.assistant_run.StartAssistantRun':
        SearchAssistantRehearsalHandler(),
    'assistant.assistant_run.CancelAssistantRun':
        SearchAssistantRehearsalHandler(),
    'assistant.assistant_run.StreamAssistantRunEvents':
        SearchAssistantRehearsalHandler(),
  };

  static const Set<String> _contentBindings = <String>{
    'content.post.ListUserPosts',
    'content.content_reaction.LikePost',
    'content.content_reaction.UnlikePost',
    'content.content_reaction.GetContentReactionState',
    'content.comment.CreateComment',
    'content.comment.DeleteComment',
    'content.comment.ListComments',
    'content.comment.ListCommentReplies',
  };

  /// 当前 App contract 中尚无真实 Alpha 行为实现的显式清单。
  ///
  /// 此清单不由 `appCloudOperationContracts - supported` 在运行期推导：新增 contract
  /// 必须明确实现或明确登记为 unsupported，避免伪全覆盖。
  static const Set<String> _unsupportedCanonicalIds = <String>{
    'assistant.assistant_entry_view.GetAssistantEntry',
    'assistant.assistant_learning_fact.AppendAssistantLearningFact',
    'assistant.assistant_preference.ListAssistantPreferences',
    'assistant.assistant_preference.RestoreAssistantPreference',
    'assistant.assistant_preference.RevokeAssistantPreference',
    'assistant.assistant_preference.SetAssistantPreference',
    'assistant.assistant_run.ApproveAssistantToolUse',
    'assistant.assistant_run.GetAssistantRun',
    'assistant.assistant_run.PauseAssistantRun',
    'assistant.assistant_run.ResumeAssistantRun',
    'assistant.assistant_run.SteerAssistantRun',
    'assistant.assistant_run.SubmitDeviceActionReceipt',
    'assistant.assistant_task_view.ListAssistantTasks',
    'assistant.assistant_turn_view.ListSessionTurns',
    'assistant.page_context.ReportPageContext',
    'assistant.skill_activity_view.ListSkillActivities',
    'assistant.skill_catalog.GetSkillCatalogItem',
    'assistant.skill_catalog.ListSkills',
    'assistant.skill_consent.GrantSkillConsent',
    'assistant.skill_consent.ListConsents',
    'assistant.skill_consent.RevokeSkillConsent',
    'assistant.skill_data_control_request.ConfirmSkillDataControlRequest',
    'assistant.skill_data_control_request.CreateSkillDataControlRequest',
    'assistant.skill_data_control_request.GetSkillDataControlRequest',
    'assistant.skill_subscription.CreateSkillSubscription',
    'assistant.skill_subscription.GetSkillSubscription',
    'assistant.skill_subscription.ListSkillSubscriptions',
    'assistant.skill_subscription.UpdateSkillSubscriptionStatus',
    'assistant.skill_surface_placement.GetSkillSurfacePlacement',
    'assistant.skill_surface_placement.PutSkillSurfacePlacement',
    'assistant.skill_user_setting.GetSkillUserSetting',
    'assistant.skill_user_setting.ListSkillUserSettings',
    'assistant.skill_user_setting.PutSkillUserSetting',
    'chat.chat_inbox_view.ListInbox',
    'chat.conversation.BatchGetConversations',
    'chat.conversation.DissolveConversation',
    'chat.conversation.GetGatheringChatBoard',
    'chat.conversation.GetGroupHome',
    'chat.conversation.ListContactHome',
    'chat.conversation.ListContacts',
    'chat.conversation.ListConversationTimestamps',
    'chat.conversation.ListGroupCandidates',
    'chat.conversation.ListMessageHome',
    'chat.conversation.ListSelectableGroupContactMembers',
    'chat.conversation.ListSelectableGroupConversations',
    'chat.conversation.UpdateAnnouncement',
    'chat.conversation.UpdateConversationTitle',
    'chat.conversation.UpdateGroupGovernanceSettings',
    'chat.conversation_membership.AddMembers',
    'chat.conversation_membership.InviteAssistant',
    'chat.conversation_membership.LeaveConversation',
    'chat.conversation_membership.ListMembers',
    'chat.conversation_membership.RemoveAssistant',
    'chat.conversation_membership.RemoveMember',
    'chat.conversation_membership.TransferOwnership',
    'chat.conversation_membership.UpdateGroupAdmins',
    'chat.conversation_user_state.MarkAsRead',
    'chat.conversation_user_state.UpdateConversationSettings',
    'chat.message.ListConversationAssets',
    'chat.message.RecallMessage',
    'chat.message.SyncMessages',
    'chat.message_receipt_fact.GetReceipts',
    'circle.circle.ArchiveCircle',
    'circle.circle.CreateCircle',
    'circle.circle.GetCircle',
    'circle.circle.GetCircleFeed',
    'circle.circle.GetCircleImpact',
    'circle.circle.GetCircleStats',
    'circle.circle.ListCircleDiscoveryFeed',
    'circle.circle.ListCircles',
    'circle.circle.SearchCircles',
    'circle.circle.UpdateCircle',
    'circle.circle.UpdateCircleSections',
    'circle.circle_behavior_fact.ReportCircleBehavior',
    'circle.circle_file.CreateCircleFile',
    'circle.circle_file.DeleteCircleFile',
    'circle.circle_file.GetCircleFile',
    'circle.circle_file.ListCircleFiles',
    'circle.circle_file.UpdateCircleFile',
    'circle.circle_group.ArchiveCircleGroup',
    'circle.circle_group.CreateCircleGroup',
    'circle.circle_group.GetCircleGroup',
    'circle.circle_group.ListCircleGroups',
    'circle.circle_group.SearchCircleGroups',
    'circle.circle_group.UpdateCircleGroup',
    'circle.circle_group_membership.ApplyJoinCircleGroup',
    'circle.circle_group_membership.ApproveCircleGroupMember',
    'circle.circle_group_membership.GetMyCircleGroupMembership',
    'circle.circle_group_membership.LeaveCircleGroup',
    'circle.circle_group_membership.ListCircleGroupMemberships',
    'circle.circle_group_membership.RejectCircleGroupMember',
    'circle.circle_group_membership.RemoveCircleGroupMember',
    'circle.circle_group_membership.UpdateCircleGroupMemberRole',
    'circle.circle_membership.ApproveCircleMember',
    'circle.circle_membership.GetMyCircleMembership',
    'circle.circle_membership.JoinCircle',
    'circle.circle_membership.LeaveCircle',
    'circle.circle_membership.ListCircleMemberships',
    'circle.circle_membership.ListPendingCircleMemberships',
    'circle.circle_membership.ListPersonaCircles',
    'circle.circle_membership.RejectCircleMember',
    'circle.circle_membership.UpdateCircleMembershipRole',
    'circle.circle_post_placement.FeatureCirclePost',
    'circle.circle_post_placement.PinCirclePost',
    'circle.circle_post_placement.PlacePostInCircle',
    'circle.circle_post_placement.RemovePostFromCircle',
    'circle.gathering.AcceptGatheringInvitation',
    'circle.gathering.ApplyToGathering',
    'circle.gathering.CancelGathering',
    'circle.gathering.ChangeGatheringCapacity',
    'circle.gathering.CompleteGathering',
    'circle.gathering.CompleteGatheringSelf',
    'circle.gathering.CreateGatheringDraft',
    'circle.gathering.DeclineGatheringInvitation',
    'circle.gathering.EndGatheringEarly',
    'circle.gathering.GetGathering',
    'circle.gathering.GetPublicGathering',
    'circle.gathering.InviteToGathering',
    'circle.gathering.JoinOpenGathering',
    'circle.gathering.ListGatheringsByHost',
    'circle.gathering.ListGatheringsBySource',
    'circle.gathering.ListMyHostedGatherings',
    'circle.gathering.PauseGatheringAdmission',
    'circle.gathering.PublishGathering',
    'circle.gathering.RemoveGatheringParticipant',
    'circle.gathering.ResumeGatheringAdmission',
    'circle.gathering.ReviewGatheringApplication',
    'circle.gathering.SafetyTerminateGathering',
    'circle.gathering.UpdateGathering',
    'circle.gathering.WatchGatheringAvailability',
    'circle.gathering_plan.GetGatheringPlan',
    'circle.gathering_plan.ListGatheringPlanRevisions',
    'content.comment.BindMediaAssetsToComment',
    'content.comment.ListCommentsByAuthor',
    'content.comment.ListCommentsForPostAuthor',
    'content.comment.PinComment',
    'content.comment.UnpinComment',
    'content.content_behavior_fact.ReportBehaviors',
    'content.content_reaction.ReactToComment',
    'content.filter_catalog_release.GetActiveFilterCatalog',
    'content.intersection_visit_state.GetMyIntersectionSummary',
    'content.intersection_visit_state.GetObjectIntersections',
    'content.intersection_visit_state.ListMyIntersections',
    'content.intersection_visit_state.MarkIntersectionsVisited',
    'content.media_asset.DiscardMediaAsset',
    'content.media_asset.GetMediaAsset',
    'content.media_asset.SelectAutoVideoCover',
    'content.media_asset.SelectManualVideoCover',
    'content.media_upload_session.AbortMediaUpload',
    'content.media_upload_session.CompleteMediaUpload',
    'content.media_upload_session.GetMediaUploadSession',
    'content.media_upload_session.InitMediaUpload',
    'content.original_access_quota.ReserveOriginalImageAccessGrant',
    'content.outbound_share_fact.AppendOutboundShareFact',
    'content.post.DeletePost',
    'content.post.GetAppConfig',
    'content.post.GetAuthorImpact',
    'content.post.GetEntityWishlistState',
    'content.post.GetFeed',
    'content.post.GetGatheringSocialProof',
    'content.post.GetMyFootprint',
    'content.post.GetPost',
    'content.post.ListAuthorImpactEvidence',
    'content.post.ListPostsByGathering',
    'content.post.SubmitPostPublication',
    'content.post_collection.DeletePostCollection',
    'content.post_collection.GetPostCollection',
    'content.post_collection.GetPostCollectionManagement',
    'content.post_collection.SavePostCollection',
    'content.profile_interaction_activity_view.ListProfileInteractionActivitiesReceived',
    'content.profile_interaction_activity_view.ListProfileInteractionActivitiesSent',
    'content.profile_interaction_read_fact.AppendProfileInteractionReadFact',
    'content.report.CreateReport',
    'content.report.ListMyReports',
    'entity.homepage.GetEntityImpact',
    'entity.homepage.GetHomepageDetail',
    'entity.homepage.GetHomepageIntroduction',
    'entity.homepage.GetHomepageRelatedGroups',
    'entity.homepage.GetHomepageReviewSummary',
    'entity.homepage.GetHomepageShell',
    'entity.homepage.GetObjectPageBundle',
    'entity.homepage.SearchHomepages',
    'entity.homepage.SuggestHomepageCandidate',
    'entity.homepage.UpdateClaimedHomepageBasics',
    'entity.homepage_claim_request.CreateHomepageClaimRequest',
    'entity.homepage_claim_request.GetMyPendingHomepageClaimRequest',
    'entity.homepage_review.CreateHomepageReview',
    'entity.homepage_review.DeleteHomepageReview',
    'entity.homepage_review.GetMyHomepageReview',
    'entity.homepage_review.ListHomepageReviews',
    'entity.homepage_review.UpdateHomepageReview',
    'entity.homepage_status_report.CreateHomepageStatusReport',
    'entity.homepage_status_report.GetMyPendingHomepageStatusReport',
    'integration.connector_connection.CreateConnectorConnection',
    'integration.connector_connection.GetConnectorConnection',
    'integration.connector_connection.ListConnectorConnections',
    'integration.connector_connection.RevokeConnectorConnection',
    'integration.connector_definition.GetConnectorDefinition',
    'integration.connector_definition.ListConnectorDefinitions',
    'integration.connector_invocation.GetConnectorInvocation',
    'integration.connector_invocation.ListConnectorInvocations',
    'integration.location.GetNearbyLocations',
    'integration.location.SearchLocations',
    'notification.notification.AckAppMessage',
    'notification.notification.GetAppMessage',
    'notification.notification.GetAppMessageUnreadCount',
    'notification.notification.ListAppMessages',
    'notification.notification.ReadAppMessage',
    'notification.notification_delivery_job.AckIncomingCallPresentation',
    'ops.app_release.GetAppRecoveryVersion',
    'ops.event_record.ReportEventBatch',
    'ops.event_record.ReportRuntimeLogBatch',
    'ops.event_record.ReportStartupEventBatch',
    'ops.recovery_failure.ReportRecoveryFailure',
    'ops.visit_record.RecordVisit',
    'realtime.connection.IssueConnectionTicket',
    'realtime.connection.LongPoll',
    'realtime.connection.WebSocketUpgrade',
    'rtc.call_session.AnswerCall',
    'rtc.call_session.CancelCall',
    'rtc.call_session.GetCall',
    'rtc.call_session.HangupCall',
    'rtc.call_session.InitiateCall',
    'rtc.call_session.InviteToCall',
    'rtc.call_session.JoinCall',
    'rtc.call_session.LeaveCall',
    'rtc.call_session.ListCalls',
    'rtc.call_session.RejectCall',
    'rtc.call_session.ReportMediaConnected',
    'rtc.call_session.StartScreenShare',
    'rtc.call_session.StopScreenShare',
    'rtc.call_session.ToggleCamera',
    'rtc.call_session.ToggleMute',
    'search.recent_search_state.ClearRecentSearches',
    'search.recent_search_state.DeleteRecentSearch',
    'search.recent_search_state.ListRecentSearches',
    'search.recent_search_state.UpsertRecentSearch',
    'search.search_feedback_fact.ReportSearchFeedback',
    'search.search_index_view.Search',
    'search.search_request_fact.ListHotQueries',
    'tag.tag_feedback_fact.ReportTagFeedback',
    'tag.tag_node_view.ListTagChildren',
    'tag.tag_node_view.ResolveTag',
    'tag.tag_node_view.ValidateTagRefs',
    'user.account_session.LoginAnonymous',
    'user.account_session.LoginOneTap',
    'user.account_session.LoginWithAlipay',
    'user.account_session.LoginWithQq',
    'user.account_session.LoginWithWechat',
    'user.account_session.RefreshToken',
    'user.authentication_challenge.CreateAlipayAuthorizationRequest',
    'user.authentication_challenge.ResolveOneTapLoginHint',
    'user.contact_discovery_record.DismissContactDiscovery',
    'user.contact_discovery_record.GetLatestContactDiscovery',
    'user.contact_discovery_record.InitiateContactDiscovery',
    'user.credential_binding.BindCarrierPhoneCredential',
    'user.credential_binding.BindPhoneCredential',
    'user.credential_binding.CompleteFederatedPhoneBinding',
    'user.credential_binding.ListCredentials',
    'user.credential_binding.UnbindCredential',
    'user.device_registration.RemoveDevicePushEndpoint',
    'user.device_registration.UpsertDevicePushEndpoint',
    'user.followed_subject_visit_state.MarkFollowedSubjectVisited',
    'user.greeting_request.CancelGreetingRequest',
    'user.greeting_request.IgnoreGreetingRequest',
    'user.greeting_request.ListGreetingInbox',
    'user.greeting_request.ListGreetingOutbox',
    'user.greeting_request.ReplyGreetingRequest',
    'user.greeting_request.SendGreetingRequest',
    'user.persona.ActivatePersona',
    'user.persona.ApplyPersonaProfileSync',
    'user.persona.CreatePersona',
    'user.persona.RetirePersona',
    'user.persona.UpdatePersona',
    'user.persona.UpdateUserProfile',
    'user.persona_relationship.BlockUser',
    'user.persona_relationship.ListBlockedUsers',
    'user.persona_relationship.UnblockUser',
    'user.profile_update_proposal.ApplyProposal',
    'user.profile_update_proposal.ConfirmProposal',
    'user.profile_update_proposal.CreateProfileUpdateProposal',
    'user.profile_update_proposal.GetProfileUpdateProposal',
    'user.profile_update_proposal.ListProfileUpdateProposals',
    'user.profile_update_proposal.RejectProposal',
    'user.profile_update_proposal.RollbackProposal',
    'user.user_account.CloseAccount',
    'user.user_account.GetActivePersonaContext',
    'user.user_account.GetMeProfile',
    'user.user_account.GetPersonaLifecycleGuard',
    'user.user_account.GetPersonaManagementSummary',
    'user.user_account.GetPersonaProfile',
    'user.user_account.GetProfileEditSnapshot',
    'user.user_account.GetProfileQrCard',
    'user.user_account.GetUserHomepageBundle',
    'user.user_account.ListPersonas',
    'user.user_account.PullUserSync',
    'user.user_account.ResolveProfileQrToken',
    'user.user_account.SearchSocialRelations',
    'user.user_settings.GetAppearanceSettings',
    'user.user_settings.GetCallSettings',
    'user.user_settings.GetNotificationSettings',
    'user.user_settings.GetPrivacySettings',
    'user.user_settings.UpdateAppearanceSettings',
    'user.user_settings.UpdateCallSettings',
    'user.user_settings.UpdateNotificationSettings',
    'user.user_settings.UpdatePrivacySettings',
  };

  Set<String> get supportedCanonicalIds =>
      {..._bindings.keys, ..._contentBindings}
        ..removeAll(transportCanonicalIds);

  Set<String> get unsupportedCanonicalIds => _unsupportedCanonicalIds;

  Set<String> get transportCanonicalIds => const <String>{
    'gateway.persisted_query_execution.ExecutePersistedGraphQLQuery',
  };

  Set<String> get coveredCanonicalIds => {
    ..._bindings.keys,
    ..._contentBindings,
  };

  RehearsalObjectHandler? _handler(RehearsalInvocation invocation) {
    final canonicalId = invocation.operation.canonicalOperationId;
    if (_contentBindings.contains(canonicalId)) return _contentHandler;
    final handler = _bindings[canonicalId];
    if (handler != null) return handler;
    if (_unsupportedCanonicalIds.contains(canonicalId)) return null;
    throw StateError(
      'Alpha rehearsal operation is neither bound nor explicitly unsupported: '
      '$canonicalId',
    );
  }

  Future<Object?> dispatch(RehearsalInvocation invocation) {
    final handler = _handler(invocation);
    if (handler != null) return handler.handle(invocation);
    return Future<Object?>.error(_unsupportedError(invocation));
  }

  Stream<Object?>? stream(RehearsalInvocation invocation) {
    final handler = _handler(invocation);
    if (handler != null) return handler.stream(invocation);
    return Stream<Object?>.error(_unsupportedError(invocation));
  }

  Object _unsupportedError(RehearsalInvocation invocation) {
    try {
      rehearsalUnsupported();
    } on CloudException catch (error) {
      return error.withSourceOperationId(
        invocation.operation.canonicalOperationId,
      );
    }
  }
}
