// Code generated by runtime/codegen. DO NOT EDIT.
package event

// Event type constants for Conversation.
const (
	ConversationCreated         = "ConversationCreated"
	MessageSent                 = "MessageSent"
	MessageRecalled             = "MessageRecalled"
	MemberJoined                = "MemberJoined"
	ConversationRosterUpdated   = "ConversationRosterUpdated"
	ConversationAvatarUpdated   = "ConversationAvatarUpdated"
	MemberLeft                  = "MemberLeft"
	ConversationSettingsUpdated = "ConversationSettingsUpdated"
	ReadReceiptSent             = "ReadReceiptSent"
	AssistantInvited            = "AssistantInvited"
	AssistantRemoved            = "AssistantRemoved"
	AssistantMentioned          = "AssistantMentioned"
	ConversationArchived        = "ConversationArchived"
)
