// Code generated by generate_canonical_test_bridges.py. DO NOT EDIT.
package api_integration

import (
	"os/exec"
	"testing"
)

func TestContractFixtureSeedContractApiIntegrationTest(t *testing.T) {
	cmd := exec.Command(
		"go",
		"test",
		"..",
		"-run",
		"^(TestContentFixturePostFromFixture_UsesExplicitUpdatedAndPublishedAt|TestContractFixtureSeed_ContentAlphaReadsViaHandler)$",
		"-count=1",
	)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("source bridge failed for quwoquan_service/services/content-service/tests/contract_fixture_seed_contract_test.go: %v\n%s", err, output)
	}
}
