// Code generated by generate_canonical_test_bridges.py. DO NOT EDIT.
package api_integration

import (
	"os/exec"
	"testing"
)

func TestPostBehaviorContractApiIntegrationTest(t *testing.T) {
	cmd := exec.Command(
		"go",
		"test",
		"..",
		"-run",
		"^(TestAuthorImpactTravelCountTargetFromBehaviorAggregation|TestBehaviorBatchAssistantInterestAllowsEmptyContentID|TestBehaviorBatchAssistantInterestProjectsTagInteraction|TestBehaviorBatchDeduplicatesClientEventID|TestBehaviorBatchEmpty|TestBehaviorBatchIntersectionConversionsUpdateMetricsAndAuthorImpact|TestBehaviorBatchRejectsLike|TestBehaviorBatchReport|TestBehaviorBatchSevenStateImpressionExcludesVisibleCountsClick|TestBehaviorBatchWireAliases|TestBehaviorEventInputDecodesAttributionFields|TestFavoriteRouteRetired|TestGetAuthorImpactReturnsBehaviorAggregation|TestLikePost)$",
		"-count=1",
	)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("source bridge failed for quwoquan_service/services/content-service/tests/post_behavior_contract_test.go: %v\n%s", err, output)
	}
}
