#!/usr/bin/env python3
"""Generate and verify Redis routes from redis_keyspace.yaml.

Eliminates the hand-maintained duplicate in DefaultRouterConfig().
"""
import argparse
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("pip install pyyaml", file=sys.stderr)
    sys.exit(1)

REPO = Path(__file__).resolve().parents[2]
KEYSPACE = REPO / "contracts" / "metadata" / "_shared" / "redis_keyspace.yaml"
OUTPUT = REPO / "runtime" / "redis" / "default_prefix_routes.g.go"

HEADER = '''// Code generated by quwoquan_service/scripts/codegen/gen_redis_router_config.py — DO NOT EDIT.

package redis
'''


def _validate(spec: dict) -> list[str]:
    errors: list[str] = []
    routing = spec.get("scene_routing", {})
    fallback = routing.get("fallback", "general")
    scenes = routing.get("scenes", {})
    if fallback not in scenes:
        errors.append(f"fallback scene is not declared: {fallback}")

    prefix_owner: dict[str, str] = {}
    scene_prefixes: dict[str, list[str]] = {}
    for scene_name, scene_def in scenes.items():
        prefixes = scene_def.get("key_prefixes", [])
        scene_prefixes[scene_name] = prefixes
        for prefix in prefixes:
            if not isinstance(prefix, str) or not prefix:
                errors.append(f"scene {scene_name} contains an empty/non-string prefix")
                continue
            previous = prefix_owner.get(prefix)
            if previous is not None:
                errors.append(
                    f"prefix {prefix!r} is declared by both {previous} and {scene_name}"
                )
            prefix_owner[prefix] = scene_name

    seen_patterns: set[str] = set()
    for item in spec.get("key_patterns", []):
        pattern = item.get("pattern")
        scene_name = item.get("redis_scene")
        if not isinstance(pattern, str) or not pattern:
            errors.append("key pattern is missing a non-empty pattern")
            continue
        if pattern in seen_patterns:
            errors.append(f"duplicate key pattern: {pattern}")
        seen_patterns.add(pattern)
        if scene_name not in scenes:
            errors.append(f"key pattern {pattern!r} references unknown scene {scene_name!r}")
            continue
        prefixes = scene_prefixes.get(scene_name, [])
        if not any(pattern.startswith(prefix) for prefix in prefixes):
            errors.append(
                f"key pattern {pattern!r} does not match scene {scene_name!r} prefixes"
            )
        ttl_seconds = item.get("ttl_seconds")
        ttl_source = item.get("ttl_source")
        explicit_ttl = "ttl_seconds" in item and (
            ttl_seconds is None or isinstance(ttl_seconds, int) and ttl_seconds > 0
        )
        derived_ttl = isinstance(ttl_source, str) and bool(ttl_source.strip())
        if not (explicit_ttl or derived_ttl):
            errors.append(
                f"key pattern {pattern!r} has no explicit TTL policy or ttl_source"
            )
    return errors


def _render(spec: dict) -> str:
    routing = spec.get("scene_routing", {})
    fallback = routing.get("fallback", "general")
    scenes = routing.get("scenes", {})

    # Collect all prefix -> scene mappings
    routes: list[tuple[str, str]] = []
    scene_names: list[str] = []
    for scene_name, scene_def in sorted(scenes.items()):
        scene_names.append(scene_name)
        for prefix in scene_def.get("key_prefixes", []):
            routes.append((prefix, scene_name))

    # Sort by prefix for deterministic output
    routes.sort(key=lambda r: r[0])

    lines = [HEADER]
    lines.append("// GeneratedPrefixRoutes returns prefix routes derived from redis_keyspace.yaml.")
    lines.append("func GeneratedPrefixRoutes() []PrefixRoute {")
    lines.append("\treturn []PrefixRoute{")
    for prefix, scene in routes:
        lines.append(f'\t\t{{Prefix: "{prefix}", Scene: "{scene}"}},')
    lines.append("\t}")
    lines.append("}")
    lines.append("")
    lines.append(f'// GeneratedDefaultScene is the fallback scene from redis_keyspace.yaml.')
    lines.append(f'const GeneratedDefaultScene = "{fallback}"')
    lines.append("")
    lines.append("// GeneratedSceneNames returns all scene names from redis_keyspace.yaml.")
    lines.append("func GeneratedSceneNames() []string {")
    lines.append("\treturn []string{")
    for name in sorted(scene_names):
        lines.append(f'\t\t"{name}",')
    lines.append("\t}")
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Validate metadata and fail when generated output is stale.",
    )
    args = parser.parse_args()

    with open(KEYSPACE, encoding="utf-8") as source:
        spec = yaml.safe_load(source)
    errors = _validate(spec)
    if errors:
        print("[gen_redis_router_config] FAIL", file=sys.stderr)
        for error in errors:
            print(f"  - {error}", file=sys.stderr)
        return 1

    output = _render(spec)
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.is_file() else ""
        if current != output:
            print(
                f"[gen_redis_router_config] FAIL: generated output is stale: {OUTPUT}",
                file=sys.stderr,
            )
            return 1
        print("[gen_redis_router_config] OK")
        return 0

    OUTPUT.write_text(output, encoding="utf-8")
    print(f"Generated {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
