// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../../cloud/runtime/recommendation/intersection_action_keys_test.dart' as source_0;

void main() {
  source_0.main();
}
