// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../../../ui/content/post/contract/post_view_projection_contract_test.dart' as source_test;

void main() {
  source_test.main();
}
