// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../../cloud/user/contract/author_impact_evidence_contract_test.dart' as source_0;

void main() {
  source_0.main();
}
