// Code generated by runtime/codegen. DO NOT EDIT.
package circle

import "time"

var _ = time.Now

// CircleStatus enumerates circle lifecycle states.
type CircleStatus string

const (
	CircleStatusActive   CircleStatus = "active"
	CircleStatusArchived CircleStatus = "archived"
)

// CircleVisibility controls who can discover the circle.
type CircleVisibility string

const (
	CircleVisibilityPublic  CircleVisibility = "public"
	CircleVisibilityPrivate CircleVisibility = "private"
)

// CircleJoinPolicy controls how users join the circle.
type CircleJoinPolicy string

const (
	CircleJoinPolicyOpen       CircleJoinPolicy = "open"
	CircleJoinPolicyApproval   CircleJoinPolicy = "approval"
	CircleJoinPolicyInviteOnly CircleJoinPolicy = "invite_only"
)

// CircleMemberRole represents a member's role within a circle.
type CircleMemberRole string

const (
	CircleMemberRoleOwner  CircleMemberRole = "owner"
	CircleMemberRoleAdmin  CircleMemberRole = "admin"
	CircleMemberRoleMember CircleMemberRole = "member"
)

// CircleSectionType identifies the type of a circle homepage section.
type CircleSectionType string

const (
	CircleSectionTypeWorks       CircleSectionType = "works"
	CircleSectionTypeChat        CircleSectionType = "chat"
	CircleSectionTypeStorage     CircleSectionType = "storage"
	CircleSectionTypeInteraction CircleSectionType = "interaction"
	CircleSectionTypeCustom      CircleSectionType = "custom"
)

// CircleFileType distinguishes files from folders.
type CircleFileType string

const (
	CircleFileTypeFile   CircleFileType = "file"
	CircleFileTypeFolder CircleFileType = "folder"
)

// CircleFileStatus tracks file upload lifecycle.
type CircleFileStatus string

const (
	CircleFileStatusActive    CircleFileStatus = "active"
	CircleFileStatusUploading CircleFileStatus = "uploading"
	CircleFileStatusDeleted   CircleFileStatus = "deleted"
)

// Circle domain model (aggregate root).
type Circle struct {
	ID               string             `json:"_id" bson:"_id"`
	Name             string             `json:"name" bson:"name"`
	Description      string             `json:"description" bson:"description"`
	CoverUrl         string             `json:"coverUrl" bson:"coverUrl"`
	OwnerID          string             `json:"ownerId" bson:"ownerId"`
	Category         string             `json:"category" bson:"category"`
	Tags             []string           `json:"tags" bson:"tags"`
	MemberCount      int64              `json:"memberCount" bson:"memberCount"`
	PostCount        int64              `json:"postCount" bson:"postCount"`
	WeeklyActiveCount int64             `json:"weeklyActiveCount" bson:"weeklyActiveCount"`
	Status           CircleStatus       `json:"status" bson:"status"`
	Visibility       CircleVisibility   `json:"visibility" bson:"visibility"`
	JoinPolicy       CircleJoinPolicy   `json:"joinPolicy" bson:"joinPolicy"`
	ConversationID   string             `json:"conversationId" bson:"conversationId"`
	AutoSyncChat     bool               `json:"autoSyncChat" bson:"autoSyncChat"`
	SectionConfig    []CircleSectionConfig `json:"sectionConfig" bson:"sectionConfig"`
	StorageUsedBytes int64              `json:"storageUsedBytes" bson:"storageUsedBytes"`
	StorageQuotaBytes int64             `json:"storageQuotaBytes" bson:"storageQuotaBytes"`
	DomainID         string             `json:"domainId" bson:"domainId"`
	CreatedAt        time.Time          `json:"createdAt" bson:"createdAt"`
	UpdatedAt        time.Time          `json:"updatedAt" bson:"updatedAt"`
}

// CircleSectionConfig is an embedded document within Circle.
type CircleSectionConfig struct {
	SectionType CircleSectionType `json:"sectionType" bson:"sectionType"`
	Visible     bool              `json:"visible" bson:"visible"`
	Order       int               `json:"order" bson:"order"`
	CustomTitle string            `json:"customTitle" bson:"customTitle"`
}

// CircleMember domain model.
type CircleMember struct {
	ID           string           `json:"_id" bson:"_id"`
	CircleID     string           `json:"circleId" bson:"circleId"`
	UserID       string           `json:"userId" bson:"userId"`
	Role         CircleMemberRole `json:"role" bson:"role"`
	JoinedAt     time.Time        `json:"joinedAt" bson:"joinedAt"`
	LastActiveAt time.Time        `json:"lastActiveAt" bson:"lastActiveAt"`
	Contribution int64            `json:"contribution" bson:"contribution"`
}

// CircleFile domain model.
type CircleFile struct {
	ID             string           `json:"_id" bson:"_id"`
	CircleID       string           `json:"circleId" bson:"circleId"`
	ParentFolderID string           `json:"parentFolderId" bson:"parentFolderId"`
	Name           string           `json:"name" bson:"name"`
	FileType       CircleFileType   `json:"fileType" bson:"fileType"`
	MimeType       string           `json:"mimeType" bson:"mimeType"`
	SizeBytes      int64            `json:"sizeBytes" bson:"sizeBytes"`
	ObjectKey      string           `json:"objectKey" bson:"objectKey"`
	UploaderID     string           `json:"uploaderId" bson:"uploaderId"`
	Status         CircleFileStatus `json:"status" bson:"status"`
	CreatedAt      time.Time        `json:"createdAt" bson:"createdAt"`
	UpdatedAt      time.Time        `json:"updatedAt" bson:"updatedAt"`
}
