// Code generated by generate_canonical_test_bridges.py. DO NOT EDIT.
package local_contract

import (
	"os/exec"
	"testing"
)

func TestIntersectionServiceLocalContractTest(t *testing.T) {
	cmd := exec.Command(
		"go",
		"test",
		"../../../../internal/application",
		"-run",
		"^(TestEvidenceKindRank_MatchesWP1AppendixA|TestIntersectionService_AffinityChannelLabeled|TestIntersectionService_ExplainPipelineInstantiatesPrimaryText|TestIntersectionService_ExposureRetainsButDemotesSeen|TestIntersectionService_FeedFactBeforeAffinityAndFreshness|TestIntersectionService_ListFiltersAndPaginates|TestIntersectionService_MarkVisited_DurableErrorSurfaces|TestIntersectionService_MarkVisited_RedisDownPersistsDurable|TestIntersectionService_MaxCandidateWindowCapsBeforeLimit|TestIntersectionService_ObjectIntersectionsEmptyObjectID|TestIntersectionService_ObjectIntersectionsRanksByAnchorStrength|TestIntersectionService_PointSummaryDerivedFromVisiblePoints|TestIntersectionService_ReportExposure_RedisDownDegrades|TestIntersectionService_SpotlightFiltersIncompleteDisplay|TestIntersectionService_SummaryNewCountAndVisitClears|TestIntersectionService_Watermarks_RedisDownFallsBackToDurable|TestIntersectionService_Watermarks_RedisFlushRecoversAndWarms)$",
		"-count=1",
	)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("source bridge failed for quwoquan_service/services/content-service/internal/application/intersection_service_test.go: %v\n%s", err, output)
	}
}
