// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../../../ui/discovery/post/contract/discovery_feed_query_contract_test.dart' as source_0;

void main() {
  source_0.main();
}
