// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../../ui/content/pageflip/curl_renderer_root_cause_test.dart' as source_0;

void main() {
  source_0.main();
}
