package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"
)

const generatedMarker = "Code generated by codegen_semantic_document; DO NOT EDIT."

var semverPattern = regexp.MustCompile(`^[0-9]+\.[0-9]+\.[0-9]+$`)

type contract struct {
	Schema                      string               `yaml:"schema"`
	SchemaVersion               string               `yaml:"schemaVersion"`
	Dialect                     string               `yaml:"dialect"`
	DialectVersion              string               `yaml:"dialectVersion"`
	CanonicalizationVersion     string               `yaml:"canonicalizationVersion"`
	OffsetEncoding              string               `yaml:"offsetEncoding"`
	RawHTMLPolicy               string               `yaml:"rawHtmlPolicy"`
	UnknownValuePolicy          string               `yaml:"unknownValuePolicy"`
	ImplementationStatus        implementationStatus `yaml:"implementationStatus"`
	CanonicalMarkdown           yaml.Node            `yaml:"canonicalMarkdown"`
	ClosedSets                  closedSets           `yaml:"closedSets"`
	IdentityAndCanonicalization yaml.Node            `yaml:"identityAndCanonicalization"`
	Model                       model                `yaml:"model"`
	CapabilityCatalog           capabilityCatalog    `yaml:"capabilityCatalog"`
	NodeRegistry                map[string]nodeSpec  `yaml:"nodeRegistry"`
	NodeRegistryPolicy          yaml.Node            `yaml:"nodeRegistryPolicy"`
	InlineRegistry              inlineRegistry       `yaml:"inlineRegistry"`
	MarkdownToSemantic          yaml.Node            `yaml:"markdownToSemantic"`
	HTMLToSemantic              yaml.Node            `yaml:"htmlToSemantic"`
	SafeProjection              yaml.Node            `yaml:"safeProjection"`
	SemanticToSafeHTML          yaml.Node            `yaml:"semanticToSafeHtml"`
	StructureContracts          yaml.Node            `yaml:"structureContracts"`
	Compatibility               yaml.Node            `yaml:"compatibility"`
	Diagnostics                 yaml.Node            `yaml:"diagnostics"`
}

type implementationStatus struct {
	Role                   string `yaml:"role"`
	MetadataValidator      string `yaml:"metadataValidator"`
	CrossLanguageCodegen   string `yaml:"crossLanguageCodegen"`
	CodegenGap             string `yaml:"codegenGap"`
	CanonicalMarkdownCodec string `yaml:"canonicalMarkdownCodec"`
	ConformanceCorpus      string `yaml:"conformanceCorpus"`
}

type closedSets struct {
	ProcessingDispositions []string `yaml:"processingDispositions"`
	PublicationDecisions   []string `yaml:"publicationDecisions"`
	CompatibilityDecisions []string `yaml:"compatibilityDecisions"`
	NodeStatuses           []string `yaml:"nodeStatuses"`
	DiagnosticSeverities   []string `yaml:"diagnosticSeverities"`
	DiagnosticCodes        []string `yaml:"diagnosticCodes"`
}

type model struct {
	DocumentEnvelope envelopeSpec `yaml:"documentEnvelope"`
	NodeCommon       yaml.Node    `yaml:"nodeCommon"`
	InlineCommon     yaml.Node    `yaml:"inlineCommon"`
}

type envelopeSpec struct {
	AdditionalProperties bool                 `yaml:"additionalProperties"`
	Required             []string             `yaml:"required"`
	Fields               map[string]yaml.Node `yaml:"fields"`
}

type capabilityCatalog struct {
	Dimensions               map[string][]string `yaml:"dimensions"`
	IDs                      []string            `yaml:"ids"`
	CapabilityRequiredFields []string            `yaml:"capabilityRequiredFields"`
	AllowedOrigins           []string            `yaml:"allowedOrigins"`
	FallbackPolicies         []string            `yaml:"fallbackPolicies"`
	FormalNodeRule           string              `yaml:"formalNodeRule"`
	OpaqueMutationRule       string              `yaml:"opaqueMutationRule"`
}

type nodeSpec struct {
	Status               string   `yaml:"status"`
	RequiredCapabilities []string `yaml:"requiredCapabilities"`
	FallbackPolicy       string   `yaml:"fallbackPolicy,omitempty"`
	PublicationDecision  string   `yaml:"publicationDecision,omitempty"`
}

type inlineRegistry struct {
	Kinds                    []string `yaml:"kinds"`
	LinkAllowedSchemes       []string `yaml:"linkAllowedSchemes"`
	UnsafeLinkDisposition    string   `yaml:"unsafeLinkDisposition"`
	UnknownInlineDisposition string   `yaml:"unknownInlineDisposition"`
}

type output struct {
	path string
	data []byte
}

func main() {
	var source, repoRoot string
	var check bool
	flag.StringVar(&source, "source", "contracts/metadata/_shared/semantic_document.yaml", "canonical semantic document YAML")
	flag.StringVar(&repoRoot, "repo-root", "..", "repository root")
	flag.BoolVar(&check, "check", false, "fail when generated outputs drift")
	flag.Parse()

	c, err := loadContract(source)
	if err != nil {
		fatal(err)
	}
	outputs, err := renderAll(c, repoRoot)
	if err != nil {
		fatal(err)
	}
	if check {
		if err := checkOutputs(outputs); err != nil {
			fatal(err)
		}
		return
	}
	for _, out := range outputs {
		if err := writeOutputAtomically(out); err != nil {
			fatal(err)
		}
	}
}

func writeOutputAtomically(out output) error {
	parent := filepath.Dir(out.path)
	if err := os.MkdirAll(parent, 0o755); err != nil {
		return err
	}
	temporary, err := os.CreateTemp(parent, ".semantic-document-*.tmp")
	if err != nil {
		return err
	}
	temporaryPath := temporary.Name()
	committed := false
	defer func() {
		_ = temporary.Close()
		if !committed {
			_ = os.Remove(temporaryPath)
		}
	}()
	if err := temporary.Chmod(0o644); err != nil {
		return err
	}
	if _, err := temporary.Write(out.data); err != nil {
		return err
	}
	if err := temporary.Sync(); err != nil {
		return err
	}
	if err := temporary.Close(); err != nil {
		return err
	}
	if err := os.Rename(temporaryPath, out.path); err != nil {
		return err
	}
	committed = true
	return nil
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "semantic document codegen:", err)
	os.Exit(1)
}

func loadContract(path string) (contract, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return contract{}, err
	}
	dec := yaml.NewDecoder(bytes.NewReader(data))
	dec.KnownFields(true)
	var c contract
	if err := dec.Decode(&c); err != nil {
		return contract{}, fmt.Errorf("strict YAML decode: %w", err)
	}
	if err := validateContract(c); err != nil {
		return contract{}, err
	}
	return c, nil
}

func validateContract(c contract) error {
	if c.Schema != "semantic_document.authoring" || c.Dialect == "" || c.OffsetEncoding == "" || c.RawHTMLPolicy == "" || c.UnknownValuePolicy != "reject" {
		return errors.New("schema, dialect, offsetEncoding, rawHtmlPolicy, and reject unknownValuePolicy must be declared")
	}
	if c.ImplementationStatus.Role != "authoring_contract" || c.ImplementationStatus.MetadataValidator == "" || c.ImplementationStatus.CrossLanguageCodegen == "" || c.ImplementationStatus.CanonicalMarkdownCodec == "" || c.ImplementationStatus.ConformanceCorpus == "" || c.ImplementationStatus.CodegenGap == "" {
		return errors.New("implementationStatus fields must be declared")
	}
	for name, node := range map[string]yaml.Node{"identityAndCanonicalization": c.IdentityAndCanonicalization, "canonicalMarkdown": c.CanonicalMarkdown, "nodeCommon": c.Model.NodeCommon, "inlineCommon": c.Model.InlineCommon, "nodeRegistryPolicy": c.NodeRegistryPolicy, "markdownToSemantic": c.MarkdownToSemantic, "htmlToSemantic": c.HTMLToSemantic, "safeProjection": c.SafeProjection, "semanticToSafeHtml": c.SemanticToSafeHTML, "structureContracts": c.StructureContracts, "compatibility": c.Compatibility, "diagnostics": c.Diagnostics} {
		if node.Kind == 0 {
			return fmt.Errorf("required section %s is missing", name)
		}
	}
	for name, value := range map[string]string{"schemaVersion": c.SchemaVersion, "dialectVersion": c.DialectVersion, "canonicalizationVersion": c.CanonicalizationVersion} {
		if !semverPattern.MatchString(value) {
			return fmt.Errorf("%s must be an exact major.minor.patch triplet", name)
		}
	}
	if err := exactSet("processingDispositions", c.ClosedSets.ProcessingDispositions, []string{"preserved", "normalized", "degraded", "metadata_only", "dropped_noise", "unsupported_opaque", "blocked_unsafe"}); err != nil {
		return err
	}
	if err := exactSet("publicationDecisions", c.ClosedSets.PublicationDecisions, []string{"publish", "publish_with_losses", "block"}); err != nil {
		return err
	}
	if err := exactSet("compatibilityDecisions", c.ClosedSets.CompatibilityDecisions, []string{"compatible", "migrate_explicitly", "incompatible"}); err != nil {
		return err
	}
	if err := exactSet("nodeStatuses", c.ClosedSets.NodeStatuses, []string{"formal", "experimental"}); err != nil {
		return err
	}
	if len(c.Model.DocumentEnvelope.Required) == 0 || c.Model.DocumentEnvelope.AdditionalProperties {
		return errors.New("documentEnvelope must be closed and declare required fields")
	}
	if len(c.CapabilityCatalog.IDs) == 0 || len(c.NodeRegistry) == 0 || len(c.InlineRegistry.Kinds) == 0 {
		return errors.New("capability, node, and inline registries must be non-empty")
	}
	if err := exactSet("capabilityRequiredFields", c.CapabilityCatalog.CapabilityRequiredFields, []string{"id", "allowedOrigins", "fallbackPolicy"}); err != nil {
		return err
	}
	if len(c.CapabilityCatalog.AllowedOrigins) == 0 || len(c.CapabilityCatalog.FallbackPolicies) == 0 || c.CapabilityCatalog.FormalNodeRule == "" || c.CapabilityCatalog.OpaqueMutationRule == "" {
		return errors.New("capability policy fields must be declared")
	}
	capabilities := stringSet(c.CapabilityCatalog.IDs)
	statuses := stringSet(c.ClosedSets.NodeStatuses)
	publication := stringSet(c.ClosedSets.PublicationDecisions)
	fallback := stringSet(c.CapabilityCatalog.FallbackPolicies)
	for kind, spec := range c.NodeRegistry {
		if kind == "" || !statuses[spec.Status] {
			return fmt.Errorf("node %q has invalid status %q", kind, spec.Status)
		}
		if spec.Status == "formal" && len(spec.RequiredCapabilities) == 0 {
			return fmt.Errorf("formal node %q has no required capabilities", kind)
		}
		for _, id := range spec.RequiredCapabilities {
			if !capabilities[id] {
				return fmt.Errorf("node %q references unknown capability %q", kind, id)
			}
		}
		if spec.FallbackPolicy != "" && !fallback[spec.FallbackPolicy] {
			return fmt.Errorf("node %q has unknown fallback policy %q", kind, spec.FallbackPolicy)
		}
		if spec.PublicationDecision != "" && !publication[spec.PublicationDecision] {
			return fmt.Errorf("node %q has unknown publication decision %q", kind, spec.PublicationDecision)
		}
	}
	for _, id := range c.CapabilityCatalog.IDs {
		parts := strings.Split(id, ".")
		if len(parts) != 2 || !contains(c.CapabilityCatalog.Dimensions[parts[0]], parts[1]) {
			return fmt.Errorf("capability id %q is absent from dimensions", id)
		}
	}
	return nil
}

func exactSet(name string, got, want []string) error {
	if len(got) != len(want) {
		return fmt.Errorf("%s must contain exactly %d values", name, len(want))
	}
	gs, ws := stringSet(got), stringSet(want)
	if len(gs) != len(got) {
		return fmt.Errorf("%s contains duplicates", name)
	}
	for value := range ws {
		if !gs[value] {
			return fmt.Errorf("%s missing required value %q", name, value)
		}
	}
	for value := range gs {
		if !ws[value] {
			return fmt.Errorf("%s contains unknown value %q", name, value)
		}
	}
	return nil
}

const goValidatorTest = `// Code generated by codegen_semantic_document; DO NOT EDIT.
package semantic_document

import "testing"

func validWire() map[string]any {
	caps := []any{"parse.markdown", "parse.html", "serialize.markdown", "render.app", "render.web", "render.workbench", "author.editContent"}
	return map[string]any{"schemaVersion": "1.0.0", "dialectVersion": "1.0.0", "canonicalizationVersion": "1.0.0", "offsetEncoding": "unicode_scalar_value", "nodes": []any{map[string]any{"kind": "paragraph", "disposition": "preserved", "requiredCapabilities": caps, "inlines": []any{map[string]any{"kind": "text", "start": 0, "end": 1}}}}, "requiredCapabilities": caps, "assets": map[string]any{}, "sourceMap": map[string]any{}, "policyVersion": "1.0.0", "losses": []any{}, "semanticFingerprint": "x", "canonicalDigest": "x"}
}
func available() map[CapabilityID]bool {
	m := map[CapabilityID]bool{}
	for id := range CapabilityRegistry {
		m[id] = true
	}
	return m
}
func TestValidateEnvelopeFailsClosed(t *testing.T) {
	cases := []struct {
		name   string
		mutate func(map[string]any)
		code   ValidationCode
	}{{"numeric capability", func(v map[string]any) { v["requiredCapabilities"] = []any{123} }, ValidationInvalidFieldType}, {"nodes type", func(v map[string]any) { v["nodes"] = "bad" }, ValidationInvalidFieldType}, {"unknown node", func(v map[string]any) { v["nodes"].([]any)[0].(map[string]any)["kind"] = "unknown" }, ValidationInvalidFieldType}, {"unknown inline", func(v map[string]any) {
		v["nodes"].([]any)[0].(map[string]any)["inlines"].([]any)[0].(map[string]any)["kind"] = "unknown"
	}, ValidationInvalidFieldType}, {"unknown disposition", func(v map[string]any) { v["nodes"].([]any)[0].(map[string]any)["disposition"] = "unknown" }, ValidationInvalidFieldType}, {"formal missing declared", func(v map[string]any) { v["requiredCapabilities"] = []any{"parse.markdown"} }, ValidationCapabilityMissing}, {"consumer missing", func(v map[string]any) {}, ValidationCapabilityMissing}, {"canonical mismatch", func(v map[string]any) { v["canonicalizationVersion"] = "2.0.0" }, ValidationCanonicalizationMismatch}, {"offset mismatch", func(v map[string]any) { v["offsetEncoding"] = "utf16" }, ValidationOffsetEncodingMismatch}, {"unknown field", func(v map[string]any) { v["surprise"] = true }, ValidationUnknownField}}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			v := validWire()
			tc.mutate(v)
			a := available()
			if tc.name == "consumer missing" {
				delete(a, CapabilityIDRenderApp)
			}
			if got := ValidateEnvelope(v, a); got.Code != tc.code {
				t.Fatalf("got %#v want %s", got, tc.code)
			}
		})
	}
}
func TestValidateEnvelopeAcceptsValidFormalNode(t *testing.T) {
	if got := ValidateEnvelope(validWire(), available()); got.Code != ValidationOK {
		t.Fatal(got)
	}
}
`

func renderAll(c contract, repoRoot string) ([]output, error) {
	goData, err := renderGo(c)
	if err != nil {
		return nil, err
	}
	dartData, err := formatDart([]byte(renderDart(c) + dartWireCodec))
	if err != nil {
		return nil, err
	}
	return []output{
		{filepath.Join(repoRoot, "quwoquan_service/services/content-service/generated/content/post/semantic_document/semantic_document.g.go"), goData},
		{filepath.Join(repoRoot, "quwoquan_service/services/entity-service/generated/entity_homepage/homepage/semantic_document/semantic_document.g.go"), goData},
		{filepath.Join(repoRoot, "quwoquan_service/services/content-service/generated/content/post/semantic_document/validator__local_contract_test.go"), []byte(goValidatorTest)},
		{filepath.Join(repoRoot, "quwoquan_app/lib/service/content_service/content/post/generated/semantic_document.g.dart"), dartData},
		{filepath.Join(repoRoot, "quwoquan_app/packages/quwoquan_cloud_contracts/lib/src/entity/semantic_document.g.dart"), dartData},
		{filepath.Join(repoRoot, "quwoquan_data/scripts/generated/semantic_document.py"), []byte(renderPython(c))},
		{filepath.Join(repoRoot, "quwoquan_data/control_plane/content_workbench/portal/src/generated/semanticDocument.ts"), []byte(renderTypeScript(c))},
	}, nil
}

func formatDart(data []byte) ([]byte, error) {
	cmd := exec.Command("dart", "format")
	cmd.Stdin = bytes.NewReader(data)
	var stdout, stderr bytes.Buffer
	cmd.Stdout, cmd.Stderr = &stdout, &stderr
	if err := cmd.Run(); err != nil {
		return nil, fmt.Errorf("dart format: %w: %s", err, strings.TrimSpace(stderr.String()))
	}
	return stdout.Bytes(), nil
}

func checkOutputs(outputs []output) error {
	expected := map[string]bool{}
	for _, out := range outputs {
		path, _ := filepath.Abs(out.path)
		expected[path] = true
		actual, err := os.ReadFile(out.path)
		if err != nil {
			if errors.Is(err, fs.ErrNotExist) {
				return fmt.Errorf("generated output missing: %s", out.path)
			}
			return err
		}
		if !bytes.Equal(actual, out.data) {
			return fmt.Errorf("generated output stale: %s", out.path)
		}
	}
	parents := map[string]bool{}
	for _, out := range outputs {
		parents[filepath.Dir(out.path)] = true
	}
	for parent := range parents {
		entries, err := os.ReadDir(parent)
		if err != nil {
			return err
		}
		for _, entry := range entries {
			if entry.IsDir() {
				continue
			}
			path := filepath.Join(parent, entry.Name())
			abs, _ := filepath.Abs(path)
			if expected[abs] {
				continue
			}
			data, err := os.ReadFile(path)
			if err != nil {
				return err
			}
			if bytes.Contains(data, []byte(generatedMarker)) {
				return fmt.Errorf("unexpected semantic document generated output: %s", path)
			}
		}
	}
	return nil
}

func renderGo(c contract) ([]byte, error) {
	var b strings.Builder
	fmt.Fprintf(&b, "// %s\npackage semantic_document\n\nimport \"fmt\"\n\n", generatedMarker)
	fmt.Fprintf(&b, "const ( SchemaVersion = %q; DialectVersion = %q; CanonicalizationVersion = %q; OffsetEncoding = %q )\n\n", c.SchemaVersion, c.DialectVersion, c.CanonicalizationVersion, c.OffsetEncoding)
	renderGoEnum(&b, "ProcessingDisposition", c.ClosedSets.ProcessingDispositions)
	renderGoEnum(&b, "PublicationDecision", c.ClosedSets.PublicationDecisions)
	renderGoEnum(&b, "CompatibilityDecision", c.ClosedSets.CompatibilityDecisions)
	renderGoEnum(&b, "NodeKind", sortedKeys(c.NodeRegistry))
	renderGoEnum(&b, "InlineKind", c.InlineRegistry.Kinds)
	renderGoEnum(&b, "CapabilityID", c.CapabilityCatalog.IDs)
	fmt.Fprintf(&b, `type SourceAnchor struct { Origin string %[1]sjson:"origin"%[1]s; Start int %[1]sjson:"start"%[1]s; End int %[1]sjson:"end"%[1]s; Selector string %[1]sjson:"selector"%[1]s }
type SemanticLoss struct { Code string %[1]sjson:"code"%[1]s; SourceAnchor SourceAnchor %[1]sjson:"sourceAnchor"%[1]s; DetailKey string %[1]sjson:"detailKey"%[1]s }
type SemanticDiagnostic struct { Code string %[1]sjson:"code"%[1]s; Severity string %[1]sjson:"severity"%[1]s; Disposition ProcessingDisposition %[1]sjson:"disposition"%[1]s; SourceAnchor SourceAnchor %[1]sjson:"sourceAnchor"%[1]s; MessageKey string %[1]sjson:"messageKey"%[1]s }
type SemanticInline struct { Kind InlineKind %[1]sjson:"kind"%[1]s; Start int %[1]sjson:"start"%[1]s; End int %[1]sjson:"end"%[1]s; Attributes map[string]any %[1]sjson:"attributes,omitempty"%[1]s }
type SemanticNode struct { NodeID string %[1]sjson:"nodeId"%[1]s; Kind NodeKind %[1]sjson:"kind"%[1]s; Disposition ProcessingDisposition %[1]sjson:"disposition"%[1]s; PolicyVersion string %[1]sjson:"policyVersion"%[1]s; RequiredCapabilities []CapabilityID %[1]sjson:"requiredCapabilities"%[1]s; Losses []SemanticLoss %[1]sjson:"losses"%[1]s; SemanticFingerprint string %[1]sjson:"semanticFingerprint"%[1]s; SourceAnchor SourceAnchor %[1]sjson:"sourceAnchor"%[1]s; Diagnostics []SemanticDiagnostic %[1]sjson:"diagnostics,omitempty"%[1]s; RawSlice string %[1]sjson:"rawSlice,omitempty"%[1]s; RawSliceFingerprint string %[1]sjson:"rawSliceFingerprint,omitempty"%[1]s; Attributes map[string]any %[1]sjson:"attributes,omitempty"%[1]s; Children []SemanticNode %[1]sjson:"children,omitempty"%[1]s; Inlines []SemanticInline %[1]sjson:"inlines,omitempty"%[1]s }
type SemanticAsset struct { ID string %[1]sjson:"id"%[1]s; Attributes map[string]any %[1]sjson:"attributes,omitempty"%[1]s }
type DocumentEnvelope struct { SchemaVersion string %[1]sjson:"schemaVersion"%[1]s; DialectVersion string %[1]sjson:"dialectVersion"%[1]s; CanonicalizationVersion string %[1]sjson:"canonicalizationVersion"%[1]s; OffsetEncoding string %[1]sjson:"offsetEncoding"%[1]s; Nodes []SemanticNode %[1]sjson:"nodes"%[1]s; RequiredCapabilities []CapabilityID %[1]sjson:"requiredCapabilities"%[1]s; Assets map[string]SemanticAsset %[1]sjson:"assets"%[1]s; SourceMap map[string]SourceAnchor %[1]sjson:"sourceMap"%[1]s; PolicyVersion string %[1]sjson:"policyVersion"%[1]s; Losses []SemanticLoss %[1]sjson:"losses"%[1]s; SemanticFingerprint string %[1]sjson:"semanticFingerprint"%[1]s; CanonicalDigest string %[1]sjson:"canonicalDigest"%[1]s }

`, "`")
	fmt.Fprintf(&b, "var CapabilityRegistry = map[CapabilityID]bool{%s}\nvar InlineRegistry = map[InlineKind]bool{%s}\nvar DispositionRegistry = map[ProcessingDisposition]bool{%s}\ntype NodeDescriptor struct { Status string; RequiredCapabilities []CapabilityID }\nvar NodeRegistry = map[NodeKind]NodeDescriptor{\n", goBoolMap("CapabilityID", c.CapabilityCatalog.IDs), goBoolMap("InlineKind", c.InlineRegistry.Kinds), goBoolMap("ProcessingDisposition", c.ClosedSets.ProcessingDispositions))
	for _, kind := range sortedKeys(c.NodeRegistry) {
		spec := c.NodeRegistry[kind]
		fmt.Fprintf(&b, "NodeKind%s: {Status:%q, RequiredCapabilities: []CapabilityID{%s}},\n", pascal(kind), spec.Status, goConstants("CapabilityID", spec.RequiredCapabilities))
	}
	fmt.Fprintf(&b, `}
var EnvelopeRequiredFields = []string{%s}
var EnvelopeAllowedFields = map[string]bool{%s}
type ValidationCode string
const ( ValidationOK ValidationCode="ok"; ValidationMissingRequiredField ValidationCode="missing_required_field"; ValidationInvalidFieldType ValidationCode="SEMANTIC_DOCUMENT.INVALID.FIELD_TYPE"; ValidationUnknownField ValidationCode="SEMANTIC_DOCUMENT.INVALID.UNKNOWN_FIELD"; ValidationSchemaMajorMismatch ValidationCode="SEMANTIC_DOCUMENT.INCOMPATIBLE.SCHEMA_MAJOR"; ValidationDialectMajorMismatch ValidationCode="SEMANTIC_DOCUMENT.INCOMPATIBLE.DIALECT_MAJOR"; ValidationCanonicalizationMismatch ValidationCode="SEMANTIC_DOCUMENT.INCOMPATIBLE.CANONICALIZATION_VERSION"; ValidationOffsetEncodingMismatch ValidationCode="SEMANTIC_DOCUMENT.INCOMPATIBLE.OFFSET_ENCODING"; ValidationCapabilityMissing ValidationCode="SEMANTIC_DOCUMENT.CAPABILITY.MISSING"; ValidationExperimentalNode ValidationCode="SEMANTIC_DOCUMENT.EXPERIMENTAL.PUBLISH_FORBIDDEN" )
type ValidationResult struct { Code ValidationCode; Detail string; Decision PublicationDecision }
func failure(code ValidationCode, detail string) ValidationResult { return ValidationResult{code,detail,PublicationDecisionBlock} }
func ValidateEnvelope(fields map[string]any, available map[CapabilityID]bool) ValidationResult {
 for key := range fields { if !EnvelopeAllowedFields[key] { return failure(ValidationUnknownField,key) } }
 for _, field := range EnvelopeRequiredFields { if _,ok:=fields[field]; !ok { return failure(ValidationMissingRequiredField,field) } }
 schema,ok:=fields["schemaVersion"].(string); if !ok { return failure(ValidationInvalidFieldType,"schemaVersion") }; if major(schema)!=major(SchemaVersion) { return failure(ValidationSchemaMajorMismatch,schema) }
 dialect,ok:=fields["dialectVersion"].(string); if !ok { return failure(ValidationInvalidFieldType,"dialectVersion") }; if major(dialect)!=major(DialectVersion) { return failure(ValidationDialectMajorMismatch,dialect) }
 canonical,ok:=fields["canonicalizationVersion"].(string); if !ok { return failure(ValidationInvalidFieldType,"canonicalizationVersion") }; if canonical!=CanonicalizationVersion { return failure(ValidationCanonicalizationMismatch,canonical) }
 offset,ok:=fields["offsetEncoding"].(string); if !ok { return failure(ValidationInvalidFieldType,"offsetEncoding") }; if offset!=OffsetEncoding { return failure(ValidationOffsetEncodingMismatch,offset) }
 required,ok:=strictStrings(fields["requiredCapabilities"]); if !ok { return failure(ValidationInvalidFieldType,"requiredCapabilities") }; declared:=map[CapabilityID]bool{}; for _,raw:=range required { id:=CapabilityID(raw); if !CapabilityRegistry[id]||!available[id] { return failure(ValidationCapabilityMissing,raw) }; declared[id]=true }
 nodes,ok:=fields["nodes"].([]any); if !ok { return failure(ValidationInvalidFieldType,"nodes") }; for i,node:=range nodes { m,ok:=node.(map[string]any); if !ok { return failure(ValidationInvalidFieldType,fmt.Sprintf("nodes[%%d]",i)) }; if r:=validateNode(m,declared,available); r.Code!=ValidationOK{return r} }
 return ValidationResult{Code:ValidationOK,Decision:PublicationDecisionPublish}
}
func validateNode(node map[string]any, declared map[CapabilityID]bool, available map[CapabilityID]bool) ValidationResult { rawKind,ok:=node["kind"].(string); if !ok{return failure(ValidationInvalidFieldType,"node.kind")}; descriptor,ok:=NodeRegistry[NodeKind(rawKind)]; if !ok{return failure(ValidationInvalidFieldType,"node.kind")}; rawDisposition,ok:=node["disposition"].(string); if !ok||!DispositionRegistry[ProcessingDisposition(rawDisposition)]{return failure(ValidationInvalidFieldType,"node.disposition")}; caps,ok:=strictStrings(node["requiredCapabilities"]); if !ok{return failure(ValidationInvalidFieldType,"node.requiredCapabilities")}; for _,raw:=range caps{id:=CapabilityID(raw);if !CapabilityRegistry[id]||!declared[id]||!available[id]{return failure(ValidationCapabilityMissing,raw)}}; if descriptor.Status=="formal"{for _,id:=range descriptor.RequiredCapabilities{if !declared[id]||!available[id]{return failure(ValidationCapabilityMissing,string(id))}}}else{return failure(ValidationExperimentalNode,rawKind)}; if inlines,exists:=node["inlines"];exists{items,ok:=inlines.([]any);if !ok{return failure(ValidationInvalidFieldType,"node.inlines")};for _,item:=range items{inline,ok:=item.(map[string]any);if !ok{return failure(ValidationInvalidFieldType,"inline")};kind,ok:=inline["kind"].(string);if !ok||!InlineRegistry[InlineKind(kind)]{return failure(ValidationInvalidFieldType,"inline.kind")};start,sok:=strictInt(inline["start"]);end,eok:=strictInt(inline["end"]);if !sok||!eok||start<0||end<start{return failure(ValidationInvalidFieldType,"inline.offset")}}}; return ValidationResult{Code:ValidationOK,Decision:PublicationDecisionPublish} }
func strictInt(v any)(int,bool){switch n:=v.(type){case int:return n,true;case float64:if n==float64(int(n)){return int(n),true}};return 0,false}
func strictStrings(v any)([]string,bool){if values,ok:=v.([]string);ok{return values,true}; values,ok:=v.([]any);if !ok{return nil,false};out:=make([]string,len(values));for i,value:=range values{s,ok:=value.(string);if !ok{return nil,false};out[i]=s};return out,true}
func major(v string)string{for i,r:=range v{if r=='.'{return v[:i]}};return ""}
`, quotedCSV(c.Model.DocumentEnvelope.Required), goStringBoolMap(c.Model.DocumentEnvelope.Required))
	return format.Source([]byte(b.String()))
}
func renderGoEnum(b *strings.Builder, typ string, values []string) {
	fmt.Fprintf(b, "type %s string\nconst (\n", typ)
	for _, value := range values {
		fmt.Fprintf(b, "\t%s%s %s = %q\n", typ, pascal(value), typ, value)
	}
	fmt.Fprintln(b, ")")
}

func renderDart(c contract) string {
	return fmt.Sprintf(`// %s
const semanticDocumentSchemaVersion = %s;
const semanticDocumentDialectVersion = %s;
const semanticDocumentCanonicalizationVersion = %s;
const semanticDocumentOffsetEncoding = %s;

enum ProcessingDisposition { %s }
enum PublicationDecision { %s }
enum CompatibilityDecision { %s }
enum SemanticNodeKind { %s }
enum SemanticInlineKind { %s }

typedef CapabilityId = String;
const semanticDocumentCapabilityIds = <CapabilityId>{%s};
const semanticDocumentInlineKinds = <SemanticInlineKind>{%s};
final class SourceAnchor { const SourceAnchor({required this.origin, required this.start, required this.end, required this.selector}); final String origin; final int start; final int end; final String selector; }
final class SemanticLoss { const SemanticLoss({required this.code, required this.sourceAnchor, required this.detailKey}); final String code; final SourceAnchor sourceAnchor; final String detailKey; }
final class SemanticDiagnostic { const SemanticDiagnostic({required this.code, required this.severity, required this.disposition, required this.sourceAnchor, required this.messageKey}); final String code; final String severity; final ProcessingDisposition disposition; final SourceAnchor sourceAnchor; final String messageKey; }
final class SemanticInline { const SemanticInline({required this.kind, required this.start, required this.end, this.attributes = const {}}); final SemanticInlineKind kind; final int start; final int end; final Map<String, Object?> attributes; }
final class SemanticNode { const SemanticNode({required this.nodeId, required this.kind, required this.disposition, required this.policyVersion, required this.requiredCapabilities, required this.losses, required this.semanticFingerprint, required this.sourceAnchor, this.diagnostics = const [], this.rawSlice, this.rawSliceFingerprint, this.attributes = const {}, this.children = const [], this.inlines = const []}); final String nodeId; final SemanticNodeKind kind; final ProcessingDisposition disposition; final String policyVersion; final List<CapabilityId> requiredCapabilities; final List<SemanticLoss> losses; final String semanticFingerprint; final SourceAnchor sourceAnchor; final List<SemanticDiagnostic> diagnostics; final String? rawSlice; final String? rawSliceFingerprint; final Map<String,Object?> attributes; final List<SemanticNode> children; final List<SemanticInline> inlines; }
final class SemanticAsset { const SemanticAsset({required this.id, this.attributes = const {}}); final String id; final Map<String,Object?> attributes; }
final class DocumentEnvelope { const DocumentEnvelope({required this.schemaVersion, required this.dialectVersion, required this.canonicalizationVersion, required this.offsetEncoding, required this.nodes, required this.requiredCapabilities, required this.assets, required this.sourceMap, required this.policyVersion, required this.losses, required this.semanticFingerprint, required this.canonicalDigest}); final String schemaVersion; final String dialectVersion; final String canonicalizationVersion; final String offsetEncoding; final List<SemanticNode> nodes; final List<CapabilityId> requiredCapabilities; final Map<String,SemanticAsset> assets; final Map<String,SourceAnchor> sourceMap; final String policyVersion; final List<SemanticLoss> losses; final String semanticFingerprint; final String canonicalDigest; }
final class SemanticNodeDescriptor { const SemanticNodeDescriptor(this.status, this.requiredCapabilities); final String status; final Set<CapabilityId> requiredCapabilities; }
const semanticDocumentNodeRegistry = <SemanticNodeKind, SemanticNodeDescriptor>{%s};
const semanticDocumentEnvelopeRequiredFields = <String>{%s};

enum SemanticDocumentValidationCode { ok, missingRequiredField, invalidFieldType, unknownField, schemaMajorMismatch, dialectMajorMismatch, canonicalizationMismatch, offsetEncodingMismatch, capabilityMissing, experimentalNode }
final class SemanticDocumentValidationResult { const SemanticDocumentValidationResult(this.code, [this.detail]); final SemanticDocumentValidationCode code; final String? detail; }
SemanticDocumentValidationResult validateSemanticDocumentEnvelope(Map<String, Object?> value, Set<CapabilityId> available) {
  for (final key in value.keys) { if (!semanticDocumentEnvelopeRequiredFields.contains(key)) { return SemanticDocumentValidationResult(SemanticDocumentValidationCode.unknownField, key); } }
  for (final field in semanticDocumentEnvelopeRequiredFields) { if (!value.containsKey(field)) { return SemanticDocumentValidationResult(SemanticDocumentValidationCode.missingRequiredField, field); } }
  if (value['schemaVersion'] is! String || value['dialectVersion'] is! String || value['canonicalizationVersion'] is! String || value['offsetEncoding'] is! String) { return const SemanticDocumentValidationResult(SemanticDocumentValidationCode.invalidFieldType, 'version'); }
  if (_major(value['schemaVersion']) != _major(semanticDocumentSchemaVersion)) { return SemanticDocumentValidationResult(SemanticDocumentValidationCode.schemaMajorMismatch, '${value['schemaVersion']}'); }
  if (_major(value['dialectVersion']) != _major(semanticDocumentDialectVersion)) { return SemanticDocumentValidationResult(SemanticDocumentValidationCode.dialectMajorMismatch, '${value['dialectVersion']}'); }
  if (value['canonicalizationVersion'] != semanticDocumentCanonicalizationVersion) { return SemanticDocumentValidationResult(SemanticDocumentValidationCode.canonicalizationMismatch, '${value['canonicalizationVersion']}'); }
  if (value['offsetEncoding'] != semanticDocumentOffsetEncoding) { return SemanticDocumentValidationResult(SemanticDocumentValidationCode.offsetEncodingMismatch, '${value['offsetEncoding']}'); }
  final required = value['requiredCapabilities']; if (required is! List || required.any((id) => id is! String)) { return const SemanticDocumentValidationResult(SemanticDocumentValidationCode.invalidFieldType, 'requiredCapabilities'); }
  final declared = required.cast<String>().toSet(); for (final id in declared) { if (!semanticDocumentCapabilityIds.contains(id) || !available.contains(id)) { return SemanticDocumentValidationResult(SemanticDocumentValidationCode.capabilityMissing, id); } }
  final nodes = value['nodes']; if (nodes is! List) { return const SemanticDocumentValidationResult(SemanticDocumentValidationCode.invalidFieldType, 'nodes'); }
  for (final raw in nodes) { if (raw is! Map<String,Object?>) { return const SemanticDocumentValidationResult(SemanticDocumentValidationCode.invalidFieldType, 'node'); } final result = _validateNode(raw, declared, available); if (result.code != SemanticDocumentValidationCode.ok) { return result; } }
  return const SemanticDocumentValidationResult(SemanticDocumentValidationCode.ok);
}
SemanticDocumentValidationResult _validateNode(Map<String,Object?> node, Set<String> declared, Set<String> available) {
  final kind = _enumByName(SemanticNodeKind.values, node['kind']); final disposition = _enumByName(ProcessingDisposition.values, node['disposition']); if (kind == null || disposition == null) { return const SemanticDocumentValidationResult(SemanticDocumentValidationCode.invalidFieldType, 'node.kind/disposition'); }
  final caps=node['requiredCapabilities']; if (caps is! List || caps.any((id)=>id is! String)) { return const SemanticDocumentValidationResult(SemanticDocumentValidationCode.invalidFieldType,'node.requiredCapabilities'); } for(final id in caps.cast<String>()){if(!semanticDocumentCapabilityIds.contains(id)||!declared.contains(id)||!available.contains(id)){return SemanticDocumentValidationResult(SemanticDocumentValidationCode.capabilityMissing,id);}}
  final descriptor=semanticDocumentNodeRegistry[kind]!; if(descriptor.status=='experimental'){return SemanticDocumentValidationResult(SemanticDocumentValidationCode.experimentalNode,'${node['kind']}');} for(final id in descriptor.requiredCapabilities){if(!declared.contains(id)||!available.contains(id)){return SemanticDocumentValidationResult(SemanticDocumentValidationCode.capabilityMissing,id);}}
  final inlines=node['inlines']; if(inlines!=null){if(inlines is! List){return const SemanticDocumentValidationResult(SemanticDocumentValidationCode.invalidFieldType,'node.inlines');}for(final raw in inlines){if(raw is! Map<String,Object?>||_enumByName(SemanticInlineKind.values,raw['kind'])==null||raw['start'] is! int||raw['end'] is! int||(raw['start'] as int)<0||(raw['end'] as int)<(raw['start'] as int)){return const SemanticDocumentValidationResult(SemanticDocumentValidationCode.invalidFieldType,'inline');}}}
  return const SemanticDocumentValidationResult(SemanticDocumentValidationCode.ok);
}
T? _enumByName<T extends Enum>(List<T> values,Object? raw){if(raw is! String)return null;for(final value in values){if(value.name==_wireToEnumName(raw))return value;}return null;}
String _wireToEnumName(String value){final parts=value.split('_');return parts.first+parts.skip(1).map((part)=>part[0].toUpperCase()+part.substring(1)).join();}
String _major(Object? value) { final text = value is String ? value : ''; final dot = text.indexOf('.'); return dot < 0 ? '' : text.substring(0, dot); }
`, generatedMarker, dartString(c.SchemaVersion), dartString(c.DialectVersion), dartString(c.CanonicalizationVersion), dartString(c.OffsetEncoding), dartEnum(c.ClosedSets.ProcessingDispositions), dartEnum(c.ClosedSets.PublicationDecisions), dartEnum(c.ClosedSets.CompatibilityDecisions), dartEnum(sortedKeys(c.NodeRegistry)), dartEnum(c.InlineRegistry.Kinds), dartStrings(c.CapabilityCatalog.IDs), dartEnumRefs("SemanticInlineKind", c.InlineRegistry.Kinds), dartNodeRegistry(c), dartStrings(c.Model.DocumentEnvelope.Required))
}

func renderPython(c contract) string {
	return fmt.Sprintf(`# %s
from __future__ import annotations
from dataclasses import dataclass
from enum import Enum
from typing import Any, Mapping, FrozenSet

SCHEMA_VERSION = %s
DIALECT_VERSION = %s
CANONICALIZATION_VERSION = %s
OFFSET_ENCODING = %s
%s
CAPABILITY_IDS: FrozenSet[str] = frozenset(%s)
INLINE_KINDS: FrozenSet[InlineKind] = frozenset(%s)
NODE_REGISTRY: Mapping[NodeKind, tuple[str, FrozenSet[str]]] = {%s}
ENVELOPE_REQUIRED_FIELDS: FrozenSet[str] = frozenset(%s)

class ValidationCode(str, Enum):
    OK = "ok"
    MISSING_REQUIRED_FIELD = "missing_required_field"
    INVALID_FIELD_TYPE = "SEMANTIC_DOCUMENT.INVALID.FIELD_TYPE"
    UNKNOWN_FIELD = "SEMANTIC_DOCUMENT.INVALID.UNKNOWN_FIELD"
    SCHEMA_MAJOR_MISMATCH = "SEMANTIC_DOCUMENT.INCOMPATIBLE.SCHEMA_MAJOR"
    DIALECT_MAJOR_MISMATCH = "SEMANTIC_DOCUMENT.INCOMPATIBLE.DIALECT_MAJOR"
    CANONICALIZATION_MISMATCH = "SEMANTIC_DOCUMENT.INCOMPATIBLE.CANONICALIZATION_VERSION"
    OFFSET_ENCODING_MISMATCH = "SEMANTIC_DOCUMENT.INCOMPATIBLE.OFFSET_ENCODING"
    CAPABILITY_MISSING = "SEMANTIC_DOCUMENT.CAPABILITY.MISSING"
    EXPERIMENTAL_NODE = "SEMANTIC_DOCUMENT.EXPERIMENTAL.PUBLISH_FORBIDDEN"

@dataclass(frozen=True)
class SourceAnchor:
    origin: str
    start: int
    end: int
    selector: str
@dataclass(frozen=True)
class SemanticLoss:
    code: str
    sourceAnchor: SourceAnchor
    detailKey: str
@dataclass(frozen=True)
class SemanticDiagnostic:
    code: str
    severity: str
    disposition: ProcessingDisposition
    sourceAnchor: SourceAnchor
    messageKey: str
@dataclass(frozen=True)
class SemanticInline:
    kind: InlineKind
    start: int
    end: int
    attributes: Mapping[str, Any]
@dataclass(frozen=True)
class SemanticNode:
    nodeId: str
    kind: NodeKind
    disposition: ProcessingDisposition
    policyVersion: str
    requiredCapabilities: tuple[str, ...]
    losses: tuple[SemanticLoss, ...]
    semanticFingerprint: str
    sourceAnchor: SourceAnchor
    diagnostics: tuple[SemanticDiagnostic, ...] = ()
    rawSlice: str | None = None
    rawSliceFingerprint: str | None = None
    attributes: Mapping[str, Any] | None = None
    children: tuple["SemanticNode", ...] = ()
    inlines: tuple[SemanticInline, ...] = ()
@dataclass(frozen=True)
class SemanticAsset:
    id: str
    attributes: Mapping[str, Any]
@dataclass(frozen=True)
class DocumentEnvelope:
    schemaVersion: str
    dialectVersion: str
    canonicalizationVersion: str
    offsetEncoding: str
    nodes: tuple[SemanticNode, ...]
    requiredCapabilities: tuple[str, ...]
    assets: Mapping[str, SemanticAsset]
    sourceMap: Mapping[str, SourceAnchor]
    policyVersion: str
    losses: tuple[SemanticLoss, ...]
    semanticFingerprint: str
    canonicalDigest: str

@dataclass(frozen=True)
class ValidationResult:
    code: ValidationCode
    detail: str = ""

def validate_envelope(value: Mapping[str, Any], available: FrozenSet[str]) -> ValidationResult:
    unknown=set(value)-ENVELOPE_REQUIRED_FIELDS
    if unknown: return ValidationResult(ValidationCode.UNKNOWN_FIELD, sorted(unknown)[0])
    for field in sorted(ENVELOPE_REQUIRED_FIELDS):
        if field not in value: return ValidationResult(ValidationCode.MISSING_REQUIRED_FIELD, field)
    for field in ("schemaVersion","dialectVersion","canonicalizationVersion","offsetEncoding"):
        if not isinstance(value[field],str): return ValidationResult(ValidationCode.INVALID_FIELD_TYPE,field)
    if _major(value["schemaVersion"]) != _major(SCHEMA_VERSION): return ValidationResult(ValidationCode.SCHEMA_MAJOR_MISMATCH,value["schemaVersion"])
    if _major(value["dialectVersion"]) != _major(DIALECT_VERSION): return ValidationResult(ValidationCode.DIALECT_MAJOR_MISMATCH,value["dialectVersion"])
    if value["canonicalizationVersion"] != CANONICALIZATION_VERSION: return ValidationResult(ValidationCode.CANONICALIZATION_MISMATCH,value["canonicalizationVersion"])
    if value["offsetEncoding"] != OFFSET_ENCODING: return ValidationResult(ValidationCode.OFFSET_ENCODING_MISMATCH,value["offsetEncoding"])
    required=value["requiredCapabilities"]
    if not isinstance(required,list) or any(not isinstance(x,str) for x in required): return ValidationResult(ValidationCode.INVALID_FIELD_TYPE,"requiredCapabilities")
    declared=frozenset(required)
    for capability in declared:
        if capability not in CAPABILITY_IDS or capability not in available: return ValidationResult(ValidationCode.CAPABILITY_MISSING,capability)
    nodes=value["nodes"]
    if not isinstance(nodes,list): return ValidationResult(ValidationCode.INVALID_FIELD_TYPE,"nodes")
    for node in nodes:
        if not isinstance(node,dict): return ValidationResult(ValidationCode.INVALID_FIELD_TYPE,"node")
        result=_validate_node(node,declared,available)
        if result.code != ValidationCode.OK: return result
    return ValidationResult(ValidationCode.OK)

def _validate_node(node: Mapping[str,Any], declared: FrozenSet[str], available: FrozenSet[str]) -> ValidationResult:
    try: kind=NodeKind(node.get("kind")); ProcessingDisposition(node.get("disposition"))
    except (ValueError,TypeError): return ValidationResult(ValidationCode.INVALID_FIELD_TYPE,"node.kind/disposition")
    caps=node.get("requiredCapabilities")
    if not isinstance(caps,list) or any(not isinstance(x,str) for x in caps): return ValidationResult(ValidationCode.INVALID_FIELD_TYPE,"node.requiredCapabilities")
    for capability in caps:
        if capability not in CAPABILITY_IDS or capability not in declared or capability not in available: return ValidationResult(ValidationCode.CAPABILITY_MISSING,capability)
    status,needed=NODE_REGISTRY[kind]
    if status=="experimental": return ValidationResult(ValidationCode.EXPERIMENTAL_NODE,kind.value)
    for capability in needed:
        if capability not in declared or capability not in available: return ValidationResult(ValidationCode.CAPABILITY_MISSING,capability)
    inlines=node.get("inlines",[])
    if not isinstance(inlines,list): return ValidationResult(ValidationCode.INVALID_FIELD_TYPE,"node.inlines")
    for inline in inlines:
        try:
            if not isinstance(inline,dict): raise ValueError()
            InlineKind(inline.get("kind")); start=inline.get("start"); end=inline.get("end")
            if type(start) is not int or type(end) is not int or start<0 or end<start: raise ValueError()
        except (ValueError,TypeError): return ValidationResult(ValidationCode.INVALID_FIELD_TYPE,"inline")
    return ValidationResult(ValidationCode.OK)

def _major(value: Any) -> str:
    return value.split(".", 1)[0] if isinstance(value, str) and "." in value else ""
`, generatedMarker, strconv.Quote(c.SchemaVersion), strconv.Quote(c.DialectVersion), strconv.Quote(c.CanonicalizationVersion), strconv.Quote(c.OffsetEncoding), pythonEnums(c), pythonTuple(c.CapabilityCatalog.IDs), pythonEnumTuple("InlineKind", c.InlineRegistry.Kinds), pythonNodeRegistry(c), pythonTuple(c.Model.DocumentEnvelope.Required))
}

const dartWireCodec = `
Map<String, Object?> _semanticObject(Object? value, String path) {
  if (value is Map<String, Object?>) return value;
  if (value is Map) return value.map((key, value) => MapEntry(key.toString(), value));
  throw FormatException('$path must be an object');
}
List<Object?> _semanticList(Object? value, String path) { if (value is List) return value.cast<Object?>(); throw FormatException('$path must be a list'); }
String _semanticString(Object? value, String path) { if (value is String) return value; throw FormatException('$path must be a string'); }
int _semanticInt(Object? value, String path) { if (value is int) return value; throw FormatException('$path must be an integer'); }
T _semanticEnum<T extends Enum>(List<T> values, Object? raw, String path) {
  if (raw is String) { for (final value in values) { final snake=value.name.replaceAllMapped(RegExp(r'[A-Z]'),(m)=>'_${m[0]!.toLowerCase()}'); if (value.name==raw || snake==raw) return value; } }
  throw FormatException('$path has an invalid enum value');
}
SourceAnchor _sourceAnchorFromWire(Object? v,String p){final m=_semanticObject(v,p);return SourceAnchor(origin:_semanticString(m['origin'],'$p.origin'),start:_semanticInt(m['start'],'$p.start'),end:_semanticInt(m['end'],'$p.end'),selector:_semanticString(m['selector'],'$p.selector'));}
Map<String,Object?> _sourceAnchorToWire(SourceAnchor v)=>{'origin':v.origin,'start':v.start,'end':v.end,'selector':v.selector};
SemanticLoss _lossFromWire(Object? v,String p){final m=_semanticObject(v,p);return SemanticLoss(code:_semanticString(m['code'],'$p.code'),sourceAnchor:_sourceAnchorFromWire(m['sourceAnchor'],'$p.sourceAnchor'),detailKey:_semanticString(m['detailKey'],'$p.detailKey'));}
Map<String,Object?> _lossToWire(SemanticLoss v)=>{'code':v.code,'sourceAnchor':_sourceAnchorToWire(v.sourceAnchor),'detailKey':v.detailKey};
SemanticDiagnostic _diagnosticFromWire(Object? v,String p){final m=_semanticObject(v,p);return SemanticDiagnostic(code:_semanticString(m['code'],'$p.code'),severity:_semanticString(m['severity'],'$p.severity'),disposition:_semanticEnum(ProcessingDisposition.values,m['disposition'],'$p.disposition'),sourceAnchor:_sourceAnchorFromWire(m['sourceAnchor'],'$p.sourceAnchor'),messageKey:_semanticString(m['messageKey'],'$p.messageKey'));}
Map<String,Object?> _diagnosticToWire(SemanticDiagnostic v)=>{'code':v.code,'severity':v.severity,'disposition':v.disposition.name.replaceAllMapped(RegExp(r'[A-Z]'),(m)=>'_${m[0]!.toLowerCase()}'),'sourceAnchor':_sourceAnchorToWire(v.sourceAnchor),'messageKey':v.messageKey};
SemanticInline _inlineFromWire(Object? v,String p){final m=_semanticObject(v,p);return SemanticInline(kind:_semanticEnum(SemanticInlineKind.values,m['kind'],'$p.kind'),start:_semanticInt(m['start'],'$p.start'),end:_semanticInt(m['end'],'$p.end'),attributes:m['attributes']==null?const {}:_semanticObject(m['attributes'],'$p.attributes'));}
SemanticNode _nodeFromWire(Object? v,String p){final m=_semanticObject(v,p);return SemanticNode(nodeId:_semanticString(m['nodeId'],'$p.nodeId'),kind:_semanticEnum(SemanticNodeKind.values,m['kind'],'$p.kind'),disposition:_semanticEnum(ProcessingDisposition.values,m['disposition'],'$p.disposition'),policyVersion:_semanticString(m['policyVersion'],'$p.policyVersion'),requiredCapabilities:_semanticList(m['requiredCapabilities'],'$p.requiredCapabilities').map((e)=>_semanticString(e,p)).toList(),losses:_semanticList(m['losses'],'$p.losses').asMap().entries.map((e)=>_lossFromWire(e.value,'$p.losses[${e.key}]')).toList(),semanticFingerprint:_semanticString(m['semanticFingerprint'],'$p.semanticFingerprint'),sourceAnchor:_sourceAnchorFromWire(m['sourceAnchor'],'$p.sourceAnchor'),diagnostics:(m['diagnostics']==null?const <Object?>[]:_semanticList(m['diagnostics'],'$p.diagnostics')).asMap().entries.map((e)=>_diagnosticFromWire(e.value,'$p.diagnostics[${e.key}]')).toList(),rawSlice:m['rawSlice'] as String?,rawSliceFingerprint:m['rawSliceFingerprint'] as String?,attributes:m['attributes']==null?const {}:_semanticObject(m['attributes'],'$p.attributes'),children:(m['children']==null?const <Object?>[]:_semanticList(m['children'],'$p.children')).asMap().entries.map((e)=>_nodeFromWire(e.value,'$p.children[${e.key}]')).toList(),inlines:(m['inlines']==null?const <Object?>[]:_semanticList(m['inlines'],'$p.inlines')).asMap().entries.map((e)=>_inlineFromWire(e.value,'$p.inlines[${e.key}]')).toList());}
Map<String,Object?> _inlineToWire(SemanticInline v)=>{'kind':v.kind.name,'start':v.start,'end':v.end,'attributes':v.attributes};
Map<String,Object?> _nodeToWire(SemanticNode v)=>{'nodeId':v.nodeId,'kind':v.kind.name,'disposition':v.disposition.name.replaceAllMapped(RegExp(r'[A-Z]'),(m)=>'_${m[0]!.toLowerCase()}'),'policyVersion':v.policyVersion,'requiredCapabilities':v.requiredCapabilities,'losses':v.losses.map(_lossToWire).toList(),'semanticFingerprint':v.semanticFingerprint,'sourceAnchor':_sourceAnchorToWire(v.sourceAnchor),'diagnostics':v.diagnostics.map(_diagnosticToWire).toList(),'rawSlice':v.rawSlice,'rawSliceFingerprint':v.rawSliceFingerprint,'attributes':v.attributes,'children':v.children.map(_nodeToWire).toList(),'inlines':v.inlines.map(_inlineToWire).toList()};
DocumentEnvelope documentEnvelopeFromWire(Map<String,Object?> m,[String p='DocumentEnvelope'])=>DocumentEnvelope(schemaVersion:_semanticString(m['schemaVersion'],'$p.schemaVersion'),dialectVersion:_semanticString(m['dialectVersion'],'$p.dialectVersion'),canonicalizationVersion:_semanticString(m['canonicalizationVersion'],'$p.canonicalizationVersion'),offsetEncoding:_semanticString(m['offsetEncoding'],'$p.offsetEncoding'),nodes:_semanticList(m['nodes'],'$p.nodes').asMap().entries.map((e)=>_nodeFromWire(e.value,'$p.nodes[${e.key}]')).toList(),requiredCapabilities:_semanticList(m['requiredCapabilities'],'$p.requiredCapabilities').map((e)=>_semanticString(e,p)).toList(),assets:_semanticObject(m['assets'],'$p.assets').map((k,v){final a=_semanticObject(v,'$p.assets.$k');return MapEntry(k,SemanticAsset(id:_semanticString(a['id'],'$p.assets.$k.id'),attributes:a['attributes']==null?const {}:_semanticObject(a['attributes'],'$p.assets.$k.attributes')));}),sourceMap:_semanticObject(m['sourceMap'],'$p.sourceMap').map((k,v)=>MapEntry(k,_sourceAnchorFromWire(v,'$p.sourceMap.$k'))),policyVersion:_semanticString(m['policyVersion'],'$p.policyVersion'),losses:_semanticList(m['losses'],'$p.losses').asMap().entries.map((e)=>_lossFromWire(e.value,'$p.losses[${e.key}]')).toList(),semanticFingerprint:_semanticString(m['semanticFingerprint'],'$p.semanticFingerprint'),canonicalDigest:_semanticString(m['canonicalDigest'],'$p.canonicalDigest'));
Map<String,Object?> documentEnvelopeToWire(DocumentEnvelope v)=>{'schemaVersion':v.schemaVersion,'dialectVersion':v.dialectVersion,'canonicalizationVersion':v.canonicalizationVersion,'offsetEncoding':v.offsetEncoding,'nodes':v.nodes.map(_nodeToWire).toList(),'requiredCapabilities':v.requiredCapabilities,'assets':v.assets.map((k,a)=>MapEntry(k,{'id':a.id,'attributes':a.attributes})),'sourceMap':v.sourceMap.map((k,a)=>MapEntry(k,_sourceAnchorToWire(a))),'policyVersion':v.policyVersion,'losses':v.losses.map(_lossToWire).toList(),'semanticFingerprint':v.semanticFingerprint,'canonicalDigest':v.canonicalDigest};
`

func renderTypeScript(c contract) string {
	return fmt.Sprintf(`// %s
export const SCHEMA_VERSION = %s as const;
export const DIALECT_VERSION = %s as const;
export const CANONICALIZATION_VERSION = %s as const;
export const OFFSET_ENCODING = %s as const;
export type ProcessingDisposition = %s;
export type PublicationDecision = %s;
export type CompatibilityDecision = %s;
export type SemanticNodeKind = %s;
export type SemanticInlineKind = %s;
export type CapabilityId = %s;
export const CAPABILITY_IDS = new Set<CapabilityId>([%s]);
export const INLINE_KINDS = new Set<SemanticInlineKind>([%s]);
export const NODE_REGISTRY: Readonly<Record<SemanticNodeKind, { readonly status: "formal" | "experimental"; readonly requiredCapabilities: readonly CapabilityId[] }>> = {%s};
export interface SourceAnchor { readonly origin: string; readonly start: number; readonly end: number; readonly selector: string }
export interface SemanticLoss { readonly code: string; readonly sourceAnchor: SourceAnchor; readonly detailKey: string }
export interface SemanticDiagnostic { readonly code: string; readonly severity: "info" | "warning" | "error"; readonly disposition: ProcessingDisposition; readonly sourceAnchor: SourceAnchor; readonly messageKey: string }
export interface SemanticInline { readonly kind: SemanticInlineKind; readonly start: number; readonly end: number; readonly attributes?: Readonly<Record<string, unknown>> }
export interface SemanticNode { readonly nodeId: string; readonly kind: SemanticNodeKind; readonly disposition: ProcessingDisposition; readonly policyVersion: string; readonly requiredCapabilities: readonly CapabilityId[]; readonly losses: readonly SemanticLoss[]; readonly semanticFingerprint: string; readonly sourceAnchor: SourceAnchor; readonly diagnostics?: readonly SemanticDiagnostic[]; readonly rawSlice?: string; readonly rawSliceFingerprint?: string; readonly attributes?: Readonly<Record<string, unknown>>; readonly children?: readonly SemanticNode[]; readonly inlines?: readonly SemanticInline[] }
export interface SemanticAsset { readonly id: string; readonly attributes?: Readonly<Record<string, unknown>> }
export interface DocumentEnvelope { readonly schemaVersion: string; readonly dialectVersion: string; readonly canonicalizationVersion: string; readonly offsetEncoding: string; readonly nodes: readonly SemanticNode[]; readonly requiredCapabilities: readonly CapabilityId[]; readonly assets: Readonly<Record<string, SemanticAsset>>; readonly sourceMap: Readonly<Record<string, SourceAnchor>>; readonly policyVersion: string; readonly losses: readonly SemanticLoss[]; readonly semanticFingerprint: string; readonly canonicalDigest: string }
export const ENVELOPE_REQUIRED_FIELDS = [%s] as const;
export type ValidationResult =
  | { code: "ok" }
  | { code: "missing_required_field" | "SEMANTIC_DOCUMENT.INVALID.FIELD_TYPE" | "SEMANTIC_DOCUMENT.INVALID.UNKNOWN_FIELD" | "SEMANTIC_DOCUMENT.INCOMPATIBLE.SCHEMA_MAJOR" | "SEMANTIC_DOCUMENT.INCOMPATIBLE.DIALECT_MAJOR" | "SEMANTIC_DOCUMENT.INCOMPATIBLE.CANONICALIZATION_VERSION" | "SEMANTIC_DOCUMENT.INCOMPATIBLE.OFFSET_ENCODING" | "SEMANTIC_DOCUMENT.CAPABILITY.MISSING" | "SEMANTIC_DOCUMENT.EXPERIMENTAL.PUBLISH_FORBIDDEN"; detail: string };
export function validateSemanticDocumentEnvelope(value: Readonly<Record<string, unknown>>, available: ReadonlySet<CapabilityId>): ValidationResult {
  for(const key of Object.keys(value))if(!(ENVELOPE_REQUIRED_FIELDS as readonly string[]).includes(key))return {code:"SEMANTIC_DOCUMENT.INVALID.UNKNOWN_FIELD",detail:key};
  for(const field of ENVELOPE_REQUIRED_FIELDS)if(!(field in value))return {code:"missing_required_field",detail:field};
  for(const field of ["schemaVersion","dialectVersion","canonicalizationVersion","offsetEncoding"] as const)if(typeof value[field]!=="string")return {code:"SEMANTIC_DOCUMENT.INVALID.FIELD_TYPE",detail:field};
  if(major(value.schemaVersion)!==major(SCHEMA_VERSION))return {code:"SEMANTIC_DOCUMENT.INCOMPATIBLE.SCHEMA_MAJOR",detail:String(value.schemaVersion)};
  if(major(value.dialectVersion)!==major(DIALECT_VERSION))return {code:"SEMANTIC_DOCUMENT.INCOMPATIBLE.DIALECT_MAJOR",detail:String(value.dialectVersion)};
  if(value.canonicalizationVersion!==CANONICALIZATION_VERSION)return {code:"SEMANTIC_DOCUMENT.INCOMPATIBLE.CANONICALIZATION_VERSION",detail:String(value.canonicalizationVersion)};
  if(value.offsetEncoding!==OFFSET_ENCODING)return {code:"SEMANTIC_DOCUMENT.INCOMPATIBLE.OFFSET_ENCODING",detail:String(value.offsetEncoding)};
  if(!Array.isArray(value.requiredCapabilities)||value.requiredCapabilities.some(x=>typeof x!=="string"))return {code:"SEMANTIC_DOCUMENT.INVALID.FIELD_TYPE",detail:"requiredCapabilities"};
  const declared=new Set(value.requiredCapabilities as string[]);for(const id of declared)if(!CAPABILITY_IDS.has(id as CapabilityId)||!available.has(id as CapabilityId))return {code:"SEMANTIC_DOCUMENT.CAPABILITY.MISSING",detail:id};
  if(!Array.isArray(value.nodes))return {code:"SEMANT_DOCUMENT.INVALID.FIELD_TYPE".replace("SEMANT_DOCUMENT","SEMANTIC_DOCUMENT") as "SEMANTIC_DOCUMENT.INVALID.FIELD_TYPE",detail:"nodes"};
  for(const raw of value.nodes){if(!isRecord(raw))return {code:"SEMANTIC_DOCUMENT.INVALID.FIELD_TYPE",detail:"node"};const result=validateNode(raw,declared,available);if(result.code!=="ok")return result;}return {code:"ok"};
}
function validateNode(node:Readonly<Record<string,unknown>>,declared:ReadonlySet<string>,available:ReadonlySet<CapabilityId>):ValidationResult{const kind=node.kind;const disposition=node.disposition;if(typeof kind!=="string"||!(kind in NODE_REGISTRY)||typeof disposition!=="string"||!(["preserved","normalized","degraded","metadata_only","dropped_noise","unsupported_opaque","blocked_unsafe"] as string[]).includes(disposition))return {code:"SEMANTIC_DOCUMENT.INVALID.FIELD_TYPE",detail:"node.kind/disposition"};const caps=node.requiredCapabilities;if(!Array.isArray(caps)||caps.some(x=>typeof x!=="string"))return {code:"SEMANTIC_DOCUMENT.INVALID.FIELD_TYPE",detail:"node.requiredCapabilities"};for(const id of caps as string[])if(!CAPABILITY_IDS.has(id as CapabilityId)||!declared.has(id)||!available.has(id as CapabilityId))return {code:"SEMANTIC_DOCUMENT.CAPABILITY.MISSING",detail:id};const descriptor=NODE_REGISTRY[kind as SemanticNodeKind];if(descriptor.status==="experimental")return {code:"SEMANTIC_DOCUMENT.EXPERIMENTAL.PUBLISH_FORBIDDEN",detail:kind};for(const id of descriptor.requiredCapabilities)if(!declared.has(id)||!available.has(id))return {code:"SEMANTIC_DOCUMENT.CAPABILITY.MISSING",detail:id};if(node.inlines!==undefined){if(!Array.isArray(node.inlines))return {code:"SEMANTIC_DOCUMENT.INVALID.FIELD_TYPE",detail:"node.inlines"};for(const inline of node.inlines){if(!isRecord(inline)||typeof inline.kind!=="string"||!INLINE_KINDS.has(inline.kind as SemanticInlineKind)||!Number.isInteger(inline.start)||!Number.isInteger(inline.end)||(inline.start as number)<0||(inline.end as number)<(inline.start as number))return {code:"SEMANTIC_DOCUMENT.INVALID.FIELD_TYPE",detail:"inline"};}}return {code:"ok"};}
function isRecord(value:unknown):value is Readonly<Record<string,unknown>>{return typeof value==="object"&&value!==null&&!Array.isArray(value);}
function major(value: unknown): string { return typeof value === "string" && value.includes(".") ? value.split(".", 1)[0] : ""; }
`, generatedMarker, tsString(c.SchemaVersion), tsString(c.DialectVersion), tsString(c.CanonicalizationVersion), tsString(c.OffsetEncoding), tsUnion(c.ClosedSets.ProcessingDispositions), tsUnion(c.ClosedSets.PublicationDecisions), tsUnion(c.ClosedSets.CompatibilityDecisions), tsUnion(sortedKeys(c.NodeRegistry)), tsUnion(c.InlineRegistry.Kinds), tsUnion(c.CapabilityCatalog.IDs), tsList(c.CapabilityCatalog.IDs), tsList(c.InlineRegistry.Kinds), tsNodeRegistry(c), tsList(c.Model.DocumentEnvelope.Required))
}

func sortedKeys[V any](m map[string]V) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
func stringSet(values []string) map[string]bool {
	out := map[string]bool{}
	for _, v := range values {
		out[v] = true
	}
	return out
}
func contains(values []string, want string) bool {
	for _, value := range values {
		if value == want {
			return true
		}
	}
	return false
}
func pascal(value string) string {
	parts := regexp.MustCompile(`[^A-Za-z0-9]+`).Split(value, -1)
	if len(parts) == 1 {
		split := regexp.MustCompile(`([a-z0-9])([A-Z])`).ReplaceAllString(parts[0], `$1 $2`)
		parts = strings.Fields(split)
	}
	for i := range parts {
		if parts[i] != "" {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}
func quotedCSV(values []string) string {
	parts := make([]string, len(values))
	for i, v := range values {
		parts[i] = strconv.Quote(v)
	}
	return strings.Join(parts, ", ")
}
func goStringBoolMap(values []string) string {
	parts := make([]string, len(values))
	for i, v := range values {
		parts[i] = strconv.Quote(v) + ": true"
	}
	return strings.Join(parts, ", ")
}
func goBoolMap(prefix string, values []string) string {
	parts := make([]string, len(values))
	for i, v := range values {
		parts[i] = prefix + pascal(v) + ": true"
	}
	return strings.Join(parts, ", ")
}
func goConstants(prefix string, values []string) string {
	parts := make([]string, len(values))
	for i, v := range values {
		parts[i] = prefix + pascal(v)
	}
	return strings.Join(parts, ", ")
}
func dartString(v string) string { return strconv.Quote(v) }
func dartEnum(values []string) string {
	out := make([]string, len(values))
	for i, v := range values {
		out[i] = lowerCamel(pascal(v))
	}
	return strings.Join(out, ", ")
}
func lowerCamel(v string) string {
	if v == "" {
		return v
	}
	return strings.ToLower(v[:1]) + v[1:]
}
func dartStrings(values []string) string { return quotedCSV(values) }
func dartEnumRefs(prefix string, values []string) string {
	parts := make([]string, len(values))
	for i, v := range values {
		parts[i] = prefix + "." + lowerCamel(pascal(v))
	}
	return strings.Join(parts, ", ")
}
func dartNodeRegistry(c contract) string {
	var out []string
	for _, kind := range sortedKeys(c.NodeRegistry) {
		spec := c.NodeRegistry[kind]
		out = append(out, fmt.Sprintf("\n  SemanticNodeKind.%s: SemanticNodeDescriptor(%q, <CapabilityId>{%s})", lowerCamel(pascal(kind)), spec.Status, dartStrings(spec.RequiredCapabilities)))
	}
	return strings.Join(out, ",") + "\n"
}
func pythonEnumTuple(prefix string, values []string) string {
	parts := make([]string, len(values))
	for i, v := range values {
		parts[i] = prefix + "." + screaming(v)
	}
	if len(parts) == 1 {
		return "(" + parts[0] + ",)"
	}
	return "(" + strings.Join(parts, ", ") + ")"
}
func pythonTuple(values []string) string {
	if len(values) == 1 {
		return "(" + strconv.Quote(values[0]) + ",)"
	}
	return "(" + quotedCSV(values) + ")"
}
func pythonEnums(c contract) string {
	sets := []struct {
		name   string
		values []string
	}{{"ProcessingDisposition", c.ClosedSets.ProcessingDispositions}, {"PublicationDecision", c.ClosedSets.PublicationDecisions}, {"CompatibilityDecision", c.ClosedSets.CompatibilityDecisions}, {"NodeKind", sortedKeys(c.NodeRegistry)}, {"InlineKind", c.InlineRegistry.Kinds}}
	var b strings.Builder
	for _, set := range sets {
		fmt.Fprintf(&b, "class %s(str, Enum):\n", set.name)
		for _, v := range set.values {
			fmt.Fprintf(&b, "    %s = %s\n", screaming(v), strconv.Quote(v))
		}
		b.WriteString("\n")
	}
	return b.String()
}
func screaming(v string) string {
	words := regexp.MustCompile(`([a-z0-9])([A-Z])`).ReplaceAllString(v, `${1}_${2}`)
	words = regexp.MustCompile(`[^A-Za-z0-9]+`).ReplaceAllString(words, "_")
	return strings.ToUpper(words)
}
func pythonNodeRegistry(c contract) string {
	var out []string
	for _, kind := range sortedKeys(c.NodeRegistry) {
		spec := c.NodeRegistry[kind]
		out = append(out, fmt.Sprintf("\n    NodeKind.%s: (%q, frozenset(%s))", screaming(kind), spec.Status, pythonTuple(spec.RequiredCapabilities)))
	}
	return strings.Join(out, ",") + "\n"
}
func tsString(v string) string { return strconv.Quote(v) }
func tsUnion(values []string) string {
	parts := make([]string, len(values))
	for i, v := range values {
		parts[i] = tsString(v)
	}
	return strings.Join(parts, " | ")
}
func tsList(values []string) string { return quotedCSV(values) }
func tsNodeRegistry(c contract) string {
	var out []string
	for _, kind := range sortedKeys(c.NodeRegistry) {
		spec := c.NodeRegistry[kind]
		out = append(out, fmt.Sprintf("\n  %s: { status: %s, requiredCapabilities: [%s] }", strconv.Quote(kind), tsString(spec.Status), tsList(spec.RequiredCapabilities)))
	}
	return strings.Join(out, ",") + "\n"
}
