#!/usr/bin/env python3
"""
lib/ui 内 `Map<String, dynamic>` 字面量出现次数预算（防回退）。

预算文件：specs/gates/ui_map_literal_budget.json
  { "max_ui_map_string_dynamic_occurrences": <int> }

当前计数 > 预算 → exit 1。

更新预算（刻意放宽时）：
  python3 scripts/verify_ui_map_literal_budget.py --write-baseline
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BUDGET_PATH = ROOT / "specs" / "gates" / "ui_map_literal_budget.json"
UI_LIB = ROOT / "quwoquan_app" / "lib" / "ui"
MAP_RE = re.compile(r"Map<String,\s*dynamic>")


def count_ui() -> int:
    n = 0
    for path in UI_LIB.rglob("*.dart"):
        if path.name.endswith(".g.dart"):
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        n += len(MAP_RE.findall(text))
    return n


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--write-baseline",
        action="store_true",
        help="Write specs/gates/ui_map_literal_budget.json from current count",
    )
    args = ap.parse_args()

    current = count_ui()

    if args.write_baseline:
        BUDGET_PATH.parent.mkdir(parents=True, exist_ok=True)
        payload = {
            "max_ui_map_string_dynamic_occurrences": current,
            "_comment": "Regenerated by verify_ui_map_literal_budget.py --write-baseline; do not increase without remediation plan.",
        }
        BUDGET_PATH.write_text(
            json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        print(f"verify_ui_map_literal_budget: wrote baseline count={current} -> {BUDGET_PATH}")
        return 0

    if not BUDGET_PATH.is_file():
        print(
            f"verify_ui_map_literal_budget: BLOCK: missing {BUDGET_PATH} "
            f"(run with --write-baseline once)",
            file=sys.stderr,
        )
        return 2

    data = json.loads(BUDGET_PATH.read_text(encoding="utf-8"))
    budget = data.get("max_ui_map_string_dynamic_occurrences")
    if not isinstance(budget, int):
        print("verify_ui_map_literal_budget: BLOCK: budget file missing int key", file=sys.stderr)
        return 2

    if current > budget:
        print(
            f"verify_ui_map_literal_budget: BLOCK: ui Map count {current} > budget {budget} "
            f"(reduce literals or intentionally run --write-baseline after review)",
            file=sys.stderr,
        )
        return 1

    print(
        f"verify_ui_map_literal_budget: ok ui Map<String,dynamic> count={current} budget={budget}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
