// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../../ui/content/seo/markdown_seo_html_renderer_test.dart' as legacy_test;

void main() {
  legacy_test.main();
}
