// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../cloud/content/content_repository_delete_contract_test.dart' as source_test;

void main() {
  source_test.main();
}
