// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../cloud/content/intersection_repository_contract_test.dart' as legacy_test;

void main() {
  legacy_test.main();
}
