// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../cloud/content/moment_post_intersection_reasons_test.dart' as legacy_test;

void main() {
  legacy_test.main();
}
