// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../ui/discovery/home_intersection_object_nav_test.dart' as source_test;

void main() {
  source_test.main();
}
