// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../ui/discovery/home_feed_video_autoplay_policy_test.dart' as source_test;

void main() {
  source_test.main();
}
