// Code generated by generate_canonical_test_bridges.py. DO NOT EDIT.

import '../../../../ui/assistant/contract/assistant_message_history_contract_test.dart' as source_0;
import '../../../../ui/chat/journeys/chat_assistant_journey_test.dart' as source_1;

void main() {
  source_0.main();
  source_1.main();
}
