// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../core/platform/platform_capabilities_incoming_call_test.dart' as source_0;

void main() {
  source_0.main();
}
