// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../../ui/entity/pages/homepage_introduction_page_widget_test.dart' as legacy_test;

void main() {
  legacy_test.main();
}
