// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../cloud/notification/notification_metadata_contract_test.dart' as source_test;

void main() {
  source_test.main();
}
