// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../common/assistant/personal_assistant_multiturn_beta_test.dart' as legacy_test;

void main() {
  legacy_test.main();
}
