// Code generated by generate_canonical_test_bridges.py. DO NOT EDIT.
package local_contract

import (
	"os/exec"
	"testing"
)

func TestMetadataWireRoundtripLocalContractTest(t *testing.T) {
	cmd := exec.Command(
		"go",
		"test",
		"../../../../../internal/domain/assistant",
		"-run",
		"^(TestAssistantLearningOpsSummaryView_DecodeSharedFixture|TestAssistantLearningOpsSummaryView_JSONRoundTrip)$",
		"-count=1",
	)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("source bridge failed for quwoquan_service/services/assistant-service/internal/domain/assistant/metadata_wire_roundtrip_test.go: %v\n%s", err, output)
	}
}
