package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

func renderAppLaunchContractArtifacts(contract appLaunchContract) ([]appLaunchContractArtifact, error) {
	document := appLaunchContractGeneratedDocument{
		Schema:                     "qwq.app-launch-contract.generated",
		SourceDigest:               contract.SourceDigest,
		Sources:                    contract.Sources,
		Environments:               contract.Environments,
		TargetEnvironment:          contract.TargetEnvironment,
		LocalTransportTargets:      contract.LocalTransportTargets,
		BuildProfileEnvironments:   contract.BuildProfileEnvironments,
		BuildProfileLaunchPolicies: contract.BuildProfileLaunchPolicies,
		LaunchProvenances:          contract.LaunchProvenances,
		RuntimeConfigSupplyModes:   contract.RuntimeConfigSupplyModes,
		RuntimeValueKeys:           contract.RuntimeValueKeys,
		LaunchBlockers:             contract.LaunchBlockers,
		RuntimeConfigErrorCodes:    contract.RuntimeConfigErrorCodes,
		SchemaValues:               contract.SchemaValues,
		SchemaRequiredFields:       contract.SchemaRequiredFields,
		RuntimeConfigPackageRuntimeRequiredFields:         contract.RuntimePackageRuntimeFields,
		AppEffectiveLaunchManifestTransportRequiredFields: contract.EffectiveManifestTransportFields,
		AppEffectiveLaunchManifestEntrypoint:              contract.EffectiveManifestEntrypoint,
		RuntimeConfigPackageSignatureAlgorithm:            contract.RuntimePackageSignatureAlgorithm,
		RuntimeConfigPackageMaxLifetimeSeconds:            contract.RuntimePackageMaxLifetimeSeconds,
		RuntimeConfigPackageMaxFutureSkewSeconds:          contract.RuntimePackageMaxFutureSkewSeconds,
		RuntimeConfigActivationReceiptStatuses:            contract.ActivationReceiptStatuses,
		AppLaunchAttemptRequiredFields:                    contract.AttemptRequiredFields,
		AppLaunchAttemptStatuses:                          contract.AttemptStatuses,
		AppLaunchAttemptForwardStates:                     contract.AttemptForwardStates,
		AppLaunchAttemptTerminalStates:                    contract.AttemptTerminalStates,
		AppLaunchManifest:                                 contract.NormalizedAppLaunchManifest,
		AppArtifactContract:                               contract.NormalizedAppArtifactContract,
	}
	jsonPayload, err := json.MarshalIndent(document, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("encode neutral App launch contract projection: %w", err)
	}
	jsonPayload = append(jsonPayload, '\n')
	pythonPayload, err := renderAppLaunchContractPython(contract)
	if err != nil {
		return nil, err
	}
	return []appLaunchContractArtifact{
		{RelativePath: appLaunchContractPythonOutput, Content: pythonPayload},
		{RelativePath: appLaunchContractJSONOutput, Content: jsonPayload},
		{RelativePath: appLaunchContractDartOutput, Content: renderAppLaunchContractDart(contract)},
		{RelativePath: appLaunchContractSwiftOutput, Content: renderAppLaunchContractSwift(contract)},
		{RelativePath: appLaunchContractJavaOutput, Content: renderAppLaunchContractJava(contract)},
	}, nil
}

func renderAppLaunchContractDart(contract appLaunchContract) []byte {
	launchJSON, err := json.Marshal(contract.NormalizedAppLaunchManifest)
	if err != nil {
		panic(err)
	}
	artifactJSON, err := json.Marshal(contract.NormalizedAppArtifactContract)
	if err != nil {
		panic(err)
	}
	var output strings.Builder
	output.WriteString("// Code generated by tools/codegen_app_metadata --app-launch-contract-only. DO NOT EDIT.\n\n")
	output.WriteString("const String appLaunchContractSourceDigest =\n    ")
	output.WriteString(strconv.Quote(contract.SourceDigest))
	output.WriteString(";\n")
	writeDartStringSet(&output, "appLaunchProvenances", contract.LaunchProvenances)
	writeDartStringSet(&output, "appLaunchLocalTransportTargets", contract.LocalTransportTargets)
	writeDartStringSet(&output, "runtimeConfigSupplyModes", contract.RuntimeConfigSupplyModes)
	writeDartStringSet(
		&output,
		"runtimeConfigTrustEnvelopeRequiredFields",
		contract.SchemaRequiredFields["runtime_config_trust_envelope"],
	)
	writeDartStringSet(
		&output,
		"runtimeConfigPackageRequiredFields",
		contract.SchemaRequiredFields["runtime_config_package"],
	)
	writeDartStringSet(
		&output,
		"appEffectiveLaunchManifestRequiredFields",
		contract.SchemaRequiredFields["app_effective_launch_manifest"],
	)
	output.WriteString("const String appLaunchManifestJson =\n    ")
	output.WriteString(strconv.Quote(string(launchJSON)))
	output.WriteString(";\n")
	output.WriteString("const String appArtifactContractJson =\n    ")
	output.WriteString(strconv.Quote(string(artifactJSON)))
	output.WriteString(";\n")
	return []byte(output.String())
}

func writeDartStringSet(output *strings.Builder, name string, values []string) {
	output.WriteString("const Set<String> ")
	output.WriteString(name)
	output.WriteString(" = <String>{\n")
	for _, value := range values {
		output.WriteString("  ")
		output.WriteString(strconv.Quote(value))
		output.WriteString(",\n")
	}
	output.WriteString("};\n")
}

func renderAppLaunchContractPython(contract appLaunchContract) ([]byte, error) {
	launchJSON, err := json.Marshal(contract.NormalizedAppLaunchManifest)
	if err != nil {
		return nil, fmt.Errorf("encode Python app launch manifest projection: %w", err)
	}
	artifactJSON, err := json.Marshal(contract.NormalizedAppArtifactContract)
	if err != nil {
		return nil, fmt.Errorf("encode Python app artifact contract projection: %w", err)
	}
	var output strings.Builder
	output.WriteString("# Code generated by tools/codegen_app_metadata --app-launch-contract-only. DO NOT EDIT.\n")
	output.WriteString("from __future__ import annotations\n\n")
	output.WriteString("import json as _json\n\n")
	output.WriteString("SOURCE_DIGEST = ")
	output.WriteString(strconv.Quote(contract.SourceDigest))
	output.WriteString("\n")
	writePythonStringTuple(&output, "ENVIRONMENTS", contract.Environments)
	writePythonStringMap(&output, "TARGET_ENVIRONMENT", contract.TargetEnvironment)
	writePythonStringTuple(&output, "LOCAL_TRANSPORT_TARGETS", contract.LocalTransportTargets)
	writePythonStringSliceMap(&output, "BUILD_PROFILE_ENVIRONMENTS", contract.BuildProfileEnvironments)
	writePythonStringMap(&output, "BUILD_PROFILE_LAUNCH_POLICIES", contract.BuildProfileLaunchPolicies)
	writePythonStringTuple(&output, "LAUNCH_PROVENANCES", contract.LaunchProvenances)
	writePythonStringTuple(&output, "RUNTIME_CONFIG_SUPPLY_MODES", contract.RuntimeConfigSupplyModes)
	writePythonStringTuple(&output, "RUNTIME_VALUE_KEYS", contract.RuntimeValueKeys)
	writePythonStringMap(&output, "LAUNCH_BLOCKERS", contract.LaunchBlockers)
	writePythonStringMap(&output, "RUNTIME_CONFIG_ERROR_CODES", contract.RuntimeConfigErrorCodes)
	writePythonStringMap(&output, "SCHEMA_VALUES", contract.SchemaValues)
	for _, schemaName := range sortedStringSliceMapKeys(contract.SchemaRequiredFields) {
		writePythonStringTuple(
			&output,
			strings.ToUpper(schemaName)+"_REQUIRED_FIELDS",
			contract.SchemaRequiredFields[schemaName],
		)
	}
	writePythonStringTuple(
		&output,
		"RUNTIME_CONFIG_PACKAGE_RUNTIME_REQUIRED_FIELDS",
		contract.RuntimePackageRuntimeFields,
	)
	writePythonStringTuple(
		&output,
		"APP_EFFECTIVE_LAUNCH_MANIFEST_TRANSPORT_REQUIRED_FIELDS",
		contract.EffectiveManifestTransportFields,
	)
	output.WriteString("APP_EFFECTIVE_LAUNCH_MANIFEST_ENTRYPOINT = ")
	output.WriteString(strconv.Quote(contract.EffectiveManifestEntrypoint))
	output.WriteString("\n")
	output.WriteString("RUNTIME_CONFIG_PACKAGE_SIGNATURE_ALGORITHM = ")
	output.WriteString(strconv.Quote(contract.RuntimePackageSignatureAlgorithm))
	output.WriteString("\nRUNTIME_CONFIG_PACKAGE_MAX_LIFETIME_SECONDS = ")
	output.WriteString(strconv.Itoa(contract.RuntimePackageMaxLifetimeSeconds))
	output.WriteString("\nRUNTIME_CONFIG_PACKAGE_MAX_FUTURE_SKEW_SECONDS = ")
	output.WriteString(strconv.Itoa(contract.RuntimePackageMaxFutureSkewSeconds))
	output.WriteString("\n")
	writePythonStringTuple(
		&output,
		"RUNTIME_CONFIG_ACTIVATION_RECEIPT_STATUSES",
		contract.ActivationReceiptStatuses,
	)
	writePythonStringTuple(&output, "APP_LAUNCH_ATTEMPT_STATUSES", contract.AttemptStatuses)
	writePythonStringTuple(&output, "APP_LAUNCH_ATTEMPT_FORWARD_STATES", contract.AttemptForwardStates)
	writePythonStringTuple(&output, "APP_LAUNCH_ATTEMPT_TERMINAL_STATES", contract.AttemptTerminalStates)
	output.WriteString("APP_LAUNCH_MANIFEST = _json.loads(")
	output.WriteString(strconv.Quote(string(launchJSON)))
	output.WriteString(")\n")
	output.WriteString("APP_ARTIFACT_CONTRACT = _json.loads(")
	output.WriteString(strconv.Quote(string(artifactJSON)))
	output.WriteString(")\n")
	return []byte(output.String()), nil
}

func writePythonStringTuple(output *strings.Builder, name string, values []string) {
	output.WriteString(name)
	output.WriteString(" = (\n")
	for _, value := range values {
		output.WriteString("    ")
		output.WriteString(strconv.Quote(value))
		output.WriteString(",\n")
	}
	output.WriteString(")\n")
}

func writePythonStringMap(output *strings.Builder, name string, values map[string]string) {
	output.WriteString(name)
	output.WriteString(" = {\n")
	for _, key := range sortedStringMapKeys(values) {
		output.WriteString("    ")
		output.WriteString(strconv.Quote(key))
		output.WriteString(": ")
		output.WriteString(strconv.Quote(values[key]))
		output.WriteString(",\n")
	}
	output.WriteString("}\n")
}

func writePythonStringSliceMap(output *strings.Builder, name string, values map[string][]string) {
	output.WriteString(name)
	output.WriteString(" = {\n")
	for _, key := range sortedStringSliceMapKeys(values) {
		output.WriteString("    ")
		output.WriteString(strconv.Quote(key))
		output.WriteString(": (")
		for _, value := range values[key] {
			output.WriteString(strconv.Quote(value))
			output.WriteString(", ")
		}
		output.WriteString("),\n")
	}
	output.WriteString("}\n")
}

func renderAppLaunchContractSwift(contract appLaunchContract) []byte {
	var output strings.Builder
	output.WriteString("// Code generated by tools/codegen_app_metadata --app-launch-contract-only. DO NOT EDIT.\n")
	output.WriteString("import Foundation\n\n")
	output.WriteString("enum AppLaunchContract {\n")
	output.WriteString("  static let sourceDigest = ")
	output.WriteString(quoteAppLaunchString(contract.SourceDigest))
	output.WriteString("\n")
	writeSwiftStringArray(&output, "environments", contract.Environments)
	writeSwiftStringMap(&output, "targetEnvironment", contract.TargetEnvironment)
	writeSwiftStringArray(&output, "localTransportTargets", contract.LocalTransportTargets)
	writeSwiftStringSliceMap(&output, "buildProfileEnvironments", contract.BuildProfileEnvironments)
	writeSwiftStringMap(&output, "buildProfileLaunchPolicies", contract.BuildProfileLaunchPolicies)
	writeSwiftStringArray(&output, "launchProvenances", contract.LaunchProvenances)
	writeSwiftStringArray(&output, "runtimeConfigSupplyModes", contract.RuntimeConfigSupplyModes)
	writeSwiftStringArray(&output, "runtimeValueKeys", contract.RuntimeValueKeys)
	writeSwiftStringMap(&output, "launchBlockers", contract.LaunchBlockers)
	writeSwiftStringMap(&output, "runtimeConfigErrorCodes", contract.RuntimeConfigErrorCodes)
	writeSwiftStringMap(&output, "schemaValues", contract.SchemaValues)
	for _, schemaName := range sortedStringSliceMapKeys(contract.SchemaRequiredFields) {
		writeSwiftStringArray(
			&output,
			appLaunchLowerCamel(schemaName)+"RequiredFields",
			contract.SchemaRequiredFields[schemaName],
		)
	}
	writeSwiftStringArray(
		&output,
		"runtimeConfigPackageRuntimeRequiredFields",
		contract.RuntimePackageRuntimeFields,
	)
	writeSwiftStringArray(
		&output,
		"appEffectiveLaunchManifestTransportRequiredFields",
		contract.EffectiveManifestTransportFields,
	)
	output.WriteString("  static let appEffectiveLaunchManifestEntrypoint = ")
	output.WriteString(quoteAppLaunchString(contract.EffectiveManifestEntrypoint))
	output.WriteString("\n")
	output.WriteString("  static let runtimeConfigPackageSignatureAlgorithm = ")
	output.WriteString(quoteAppLaunchString(contract.RuntimePackageSignatureAlgorithm))
	output.WriteString("\n  static let runtimeConfigPackageMaxLifetimeSeconds = ")
	output.WriteString(strconv.Itoa(contract.RuntimePackageMaxLifetimeSeconds))
	output.WriteString("\n  static let runtimeConfigPackageMaxFutureSkewSeconds = ")
	output.WriteString(strconv.Itoa(contract.RuntimePackageMaxFutureSkewSeconds))
	output.WriteString("\n")
	writeSwiftStringArray(
		&output,
		"runtimeConfigActivationReceiptStatuses",
		contract.ActivationReceiptStatuses,
	)
	writeSwiftStringArray(&output, "appLaunchAttemptStatuses", contract.AttemptStatuses)
	writeSwiftStringArray(&output, "appLaunchAttemptForwardStates", contract.AttemptForwardStates)
	writeSwiftStringArray(&output, "appLaunchAttemptTerminalStates", contract.AttemptTerminalStates)
	output.WriteString("}\n")
	return []byte(output.String())
}

func writeSwiftStringArray(output *strings.Builder, name string, values []string) {
	output.WriteString("  static let ")
	output.WriteString(name)
	output.WriteString(": [String] = [\n")
	for _, value := range values {
		output.WriteString("    ")
		output.WriteString(quoteAppLaunchString(value))
		output.WriteString(",\n")
	}
	output.WriteString("  ]\n")
}

func writeSwiftStringMap(output *strings.Builder, name string, values map[string]string) {
	output.WriteString("  static let ")
	output.WriteString(name)
	output.WriteString(": [String: String] = [\n")
	for _, key := range sortedStringMapKeys(values) {
		output.WriteString("    ")
		output.WriteString(quoteAppLaunchString(key))
		output.WriteString(": ")
		output.WriteString(quoteAppLaunchString(values[key]))
		output.WriteString(",\n")
	}
	output.WriteString("  ]\n")
}

func writeSwiftStringSliceMap(output *strings.Builder, name string, values map[string][]string) {
	output.WriteString("  static let ")
	output.WriteString(name)
	output.WriteString(": [String: [String]] = [\n")
	for _, key := range sortedStringSliceMapKeys(values) {
		output.WriteString("    ")
		output.WriteString(quoteAppLaunchString(key))
		output.WriteString(": [")
		for index, value := range values[key] {
			if index > 0 {
				output.WriteString(", ")
			}
			output.WriteString(quoteAppLaunchString(value))
		}
		output.WriteString("],\n")
	}
	output.WriteString("  ]\n")
}

func renderAppLaunchContractJava(contract appLaunchContract) []byte {
	var output strings.Builder
	output.WriteString("// Code generated by tools/codegen_app_metadata --app-launch-contract-only. DO NOT EDIT.\n")
	output.WriteString("package com.quwoquan.quwoquan_app;\n\n")
	output.WriteString("import java.util.Arrays;\n")
	output.WriteString("import java.util.Collections;\n")
	output.WriteString("import java.util.LinkedHashMap;\n")
	output.WriteString("import java.util.List;\n")
	output.WriteString("import java.util.Map;\n\n")
	output.WriteString("public final class AppLaunchContract {\n")
	output.WriteString("  public static final String SOURCE_DIGEST = ")
	output.WriteString(quoteAppLaunchString(contract.SourceDigest))
	output.WriteString(";\n")
	writeJavaStringList(&output, "ENVIRONMENTS", contract.Environments)
	writeJavaStringMap(&output, "TARGET_ENVIRONMENT", contract.TargetEnvironment)
	writeJavaStringList(&output, "LOCAL_TRANSPORT_TARGETS", contract.LocalTransportTargets)
	writeJavaStringListMap(&output, "BUILD_PROFILE_ENVIRONMENTS", contract.BuildProfileEnvironments)
	writeJavaStringMap(&output, "BUILD_PROFILE_LAUNCH_POLICIES", contract.BuildProfileLaunchPolicies)
	writeJavaStringList(&output, "LAUNCH_PROVENANCES", contract.LaunchProvenances)
	writeJavaStringList(&output, "RUNTIME_CONFIG_SUPPLY_MODES", contract.RuntimeConfigSupplyModes)
	writeJavaStringList(&output, "RUNTIME_VALUE_KEYS", contract.RuntimeValueKeys)
	writeJavaStringMap(&output, "LAUNCH_BLOCKERS", contract.LaunchBlockers)
	writeJavaStringMap(&output, "RUNTIME_CONFIG_ERROR_CODES", contract.RuntimeConfigErrorCodes)
	writeJavaStringMap(&output, "SCHEMA_VALUES", contract.SchemaValues)
	for _, schemaName := range sortedStringSliceMapKeys(contract.SchemaRequiredFields) {
		writeJavaStringList(
			&output,
			strings.ToUpper(schemaName)+"_REQUIRED_FIELDS",
			contract.SchemaRequiredFields[schemaName],
		)
	}
	writeJavaStringList(
		&output,
		"RUNTIME_CONFIG_PACKAGE_RUNTIME_REQUIRED_FIELDS",
		contract.RuntimePackageRuntimeFields,
	)
	writeJavaStringList(
		&output,
		"APP_EFFECTIVE_LAUNCH_MANIFEST_TRANSPORT_REQUIRED_FIELDS",
		contract.EffectiveManifestTransportFields,
	)
	output.WriteString("  public static final String APP_EFFECTIVE_LAUNCH_MANIFEST_ENTRYPOINT = ")
	output.WriteString(quoteAppLaunchString(contract.EffectiveManifestEntrypoint))
	output.WriteString(";\n")
	output.WriteString("  public static final String RUNTIME_CONFIG_PACKAGE_SIGNATURE_ALGORITHM = ")
	output.WriteString(quoteAppLaunchString(contract.RuntimePackageSignatureAlgorithm))
	output.WriteString(";\n  public static final int RUNTIME_CONFIG_PACKAGE_MAX_LIFETIME_SECONDS = ")
	output.WriteString(strconv.Itoa(contract.RuntimePackageMaxLifetimeSeconds))
	output.WriteString(";\n  public static final int RUNTIME_CONFIG_PACKAGE_MAX_FUTURE_SKEW_SECONDS = ")
	output.WriteString(strconv.Itoa(contract.RuntimePackageMaxFutureSkewSeconds))
	output.WriteString(";\n")
	writeJavaStringList(
		&output,
		"RUNTIME_CONFIG_ACTIVATION_RECEIPT_STATUSES",
		contract.ActivationReceiptStatuses,
	)
	writeJavaStringList(&output, "APP_LAUNCH_ATTEMPT_STATUSES", contract.AttemptStatuses)
	writeJavaStringList(&output, "APP_LAUNCH_ATTEMPT_FORWARD_STATES", contract.AttemptForwardStates)
	writeJavaStringList(&output, "APP_LAUNCH_ATTEMPT_TERMINAL_STATES", contract.AttemptTerminalStates)
	output.WriteString("\n  private static Map<String, String> stringMap(String[][] entries) {\n")
	output.WriteString("    LinkedHashMap<String, String> values = new LinkedHashMap<>();\n")
	output.WriteString("    for (String[] entry : entries) {\n")
	output.WriteString("      values.put(entry[0], entry[1]);\n")
	output.WriteString("    }\n")
	output.WriteString("    return Collections.unmodifiableMap(values);\n")
	output.WriteString("  }\n\n")
	output.WriteString("  private static Map<String, List<String>> stringListMap(String[][] entries) {\n")
	output.WriteString("    LinkedHashMap<String, List<String>> values = new LinkedHashMap<>();\n")
	output.WriteString("    for (String[] entry : entries) {\n")
	output.WriteString("      values.put(entry[0], Collections.unmodifiableList(Arrays.asList(Arrays.copyOfRange(entry, 1, entry.length))));\n")
	output.WriteString("    }\n")
	output.WriteString("    return Collections.unmodifiableMap(values);\n")
	output.WriteString("  }\n\n")
	output.WriteString("  private AppLaunchContract() {}\n")
	output.WriteString("}\n")
	return []byte(output.String())
}

func writeJavaStringList(output *strings.Builder, name string, values []string) {
	output.WriteString("  public static final List<String> ")
	output.WriteString(name)
	output.WriteString(" = Collections.unmodifiableList(Arrays.asList(\n")
	for index, value := range values {
		output.WriteString("      ")
		output.WriteString(quoteAppLaunchString(value))
		if index != len(values)-1 {
			output.WriteString(",")
		}
		output.WriteString("\n")
	}
	output.WriteString("  ));\n")
}

func writeJavaStringMap(output *strings.Builder, name string, values map[string]string) {
	output.WriteString("  public static final Map<String, String> ")
	output.WriteString(name)
	output.WriteString(" = stringMap(new String[][] {\n")
	keys := sortedStringMapKeys(values)
	for index, key := range keys {
		output.WriteString("      {")
		output.WriteString(quoteAppLaunchString(key))
		output.WriteString(", ")
		output.WriteString(quoteAppLaunchString(values[key]))
		output.WriteString("}")
		if index != len(keys)-1 {
			output.WriteString(",")
		}
		output.WriteString("\n")
	}
	output.WriteString("  });\n")
}

func writeJavaStringListMap(output *strings.Builder, name string, values map[string][]string) {
	output.WriteString("  public static final Map<String, List<String>> ")
	output.WriteString(name)
	output.WriteString(" = stringListMap(new String[][] {\n")
	keys := sortedStringSliceMapKeys(values)
	for index, key := range keys {
		output.WriteString("      {")
		output.WriteString(quoteAppLaunchString(key))
		for _, value := range values[key] {
			output.WriteString(", ")
			output.WriteString(quoteAppLaunchString(value))
		}
		output.WriteString("}")
		if index != len(keys)-1 {
			output.WriteString(",")
		}
		output.WriteString("\n")
	}
	output.WriteString("  });\n")
}

func quoteAppLaunchString(value string) string {
	payload, err := json.Marshal(value)
	if err != nil {
		panic(err)
	}
	return string(payload)
}

func buildAppLaunchContractGeneratedManifest(
	contract appLaunchContract,
	artifacts []appLaunchContractArtifact,
) appLaunchContractGeneratedManifest {
	inputs := make([]appLaunchContractSource, len(contract.Sources))
	for index, source := range contract.Sources {
		inputs[index] = appLaunchContractSource{Path: source.Path, SHA256: source.SHA256}
	}
	outputs := make([]appLaunchContractManifestOutput, 0, len(artifacts))
	for _, artifact := range artifacts {
		sum := sha256.Sum256(artifact.Content)
		outputs = append(outputs, appLaunchContractManifestOutput{
			Path:   artifact.RelativePath,
			SHA256: "sha256:" + hex.EncodeToString(sum[:]),
			Bytes:  len(artifact.Content),
		})
	}
	sort.Slice(outputs, func(i, j int) bool { return outputs[i].Path < outputs[j].Path })
	return appLaunchContractGeneratedManifest{
		Schema:       "qwq.app-launch-contract-codegen-manifest",
		Generator:    "tools/codegen_app_metadata --app-launch-contract-only",
		SourceDigest: contract.SourceDigest,
		Inputs:       inputs,
		Outputs:      outputs,
	}
}

func writeAppLaunchContractArtifacts(
	appDir string,
	manifestPath string,
	artifacts []appLaunchContractArtifact,
	manifest appLaunchContractGeneratedManifest,
) error {
	for _, artifact := range artifacts {
		path, err := resolveAppLaunchContractOutputPath(appDir, artifact.RelativePath)
		if err != nil {
			return err
		}
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return fmt.Errorf("create App launch contract output directory: %w", err)
		}
		if err := os.WriteFile(path, artifact.Content, 0o644); err != nil {
			return fmt.Errorf("write App launch contract output %s: %w", path, err)
		}
		fmt.Printf("generated: %s\n", path)
	}
	manifestPayload, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		return fmt.Errorf("encode App launch contract generated manifest: %w", err)
	}
	manifestPayload = append(manifestPayload, '\n')
	if err := os.MkdirAll(filepath.Dir(manifestPath), 0o755); err != nil {
		return fmt.Errorf("create App launch contract generated manifest directory: %w", err)
	}
	if err := os.WriteFile(manifestPath, manifestPayload, 0o644); err != nil {
		return fmt.Errorf("write App launch contract generated manifest: %w", err)
	}
	fmt.Printf("generated manifest: %s\n", manifestPath)
	return nil
}

func checkAppLaunchContractArtifacts(
	appDir string,
	manifestPath string,
	artifacts []appLaunchContractArtifact,
	manifest appLaunchContractGeneratedManifest,
) error {
	for _, artifact := range artifacts {
		path, err := resolveAppLaunchContractOutputPath(appDir, artifact.RelativePath)
		if err != nil {
			return err
		}
		actual, err := os.ReadFile(path)
		if err != nil {
			if errors.Is(err, os.ErrNotExist) {
				return fmt.Errorf("generated App launch contract output is missing: %s", path)
			}
			return fmt.Errorf("read generated App launch contract output %s: %w", path, err)
		}
		if !bytes.Equal(actual, artifact.Content) {
			return fmt.Errorf("generated App launch contract output is stale: %s", path)
		}
	}
	expectedManifest, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		return fmt.Errorf("encode expected App launch contract generated manifest: %w", err)
	}
	expectedManifest = append(expectedManifest, '\n')
	actualManifest, err := os.ReadFile(manifestPath)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return fmt.Errorf("App launch contract generated manifest is missing: %s", manifestPath)
		}
		return fmt.Errorf("read App launch contract generated manifest %s: %w", manifestPath, err)
	}
	if !bytes.Equal(actualManifest, expectedManifest) {
		return fmt.Errorf("App launch contract generated manifest is stale: %s", manifestPath)
	}
	fmt.Printf(
		"PASS: App launch contract outputs are current (outputs=%d, source=%s)\n",
		len(artifacts),
		manifest.SourceDigest,
	)
	return nil
}

func resolveAppLaunchContractOutputPath(appDir, repoRelativePath string) (string, error) {
	path := filepath.ToSlash(filepath.Clean(filepath.FromSlash(repoRelativePath)))
	const appPrefix = "quwoquan_app/"
	if strings.HasPrefix(path, appPrefix) {
		return filepath.Join(appDir, filepath.FromSlash(strings.TrimPrefix(path, appPrefix))), nil
	}
	if strings.HasPrefix(path, "quwoquan_ops/") {
		return filepath.Join(filepath.Dir(filepath.Clean(appDir)), filepath.FromSlash(path)), nil
	}
	return "", fmt.Errorf("unsupported App launch contract output path %q", repoRelativePath)
}

func requireExactOrderedStrings(name string, actual, expected []string) error {
	if err := requireUniqueNonEmptyStrings(name, actual); err != nil {
		return err
	}
	if len(actual) != len(expected) {
		return fmt.Errorf("%s has %d values, want %d: actual=%v expected=%v", name, len(actual), len(expected), actual, expected)
	}
	for index := range expected {
		if actual[index] != expected[index] {
			return fmt.Errorf("%s differs at index %d: actual=%v expected=%v", name, index, actual, expected)
		}
	}
	return nil
}

func requireUniqueNonEmptyStrings(name string, values []string) error {
	seen := map[string]struct{}{}
	for _, value := range values {
		if strings.TrimSpace(value) == "" {
			return fmt.Errorf("%s contains an empty value", name)
		}
		if _, exists := seen[value]; exists {
			return fmt.Errorf("duplicate %s value %q", name, value)
		}
		seen[value] = struct{}{}
	}
	return nil
}

func requireExactStringSet(name string, actual, expected []string) error {
	if err := requireUniqueNonEmptyStrings(name, actual); err != nil {
		return err
	}
	actualCopy := append([]string(nil), actual...)
	expectedCopy := append([]string(nil), expected...)
	sort.Strings(actualCopy)
	sort.Strings(expectedCopy)
	if strings.Join(actualCopy, "\x00") != strings.Join(expectedCopy, "\x00") {
		return fmt.Errorf("%s closed set differs: actual=%v expected=%v", name, actualCopy, expectedCopy)
	}
	return nil
}

func requireExactStringMap(name string, actual, expected map[string]string) error {
	if err := requireExactStringSet(name+" keys", mapStringKeys(actual), mapStringKeys(expected)); err != nil {
		return err
	}
	for key, expectedValue := range expected {
		if actual[key] != expectedValue {
			return fmt.Errorf("%s.%s = %q, want %q", name, key, actual[key], expectedValue)
		}
	}
	return nil
}

func requireNonEmptyStringMap(name string, values map[string]string) error {
	if len(values) == 0 {
		return fmt.Errorf("%s is empty", name)
	}
	for key, value := range values {
		if strings.TrimSpace(key) == "" || strings.TrimSpace(value) == "" {
			return fmt.Errorf("%s contains an empty key or description", name)
		}
	}
	return nil
}

func cloneStringMap(source map[string]string) map[string]string {
	result := make(map[string]string, len(source))
	for key, value := range source {
		result[key] = value
	}
	return result
}

func mapStringKeys(values map[string]string) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	return keys
}

func sortedStringMapKeys(values map[string]string) []string {
	keys := mapStringKeys(values)
	sort.Strings(keys)
	return keys
}

func sortedStringSliceMapKeys(values map[string][]string) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func sortedRuntimeValueKeys(values map[string]appLaunchRuntimeValueKey) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func appLaunchLowerCamel(value string) string {
	parts := strings.Split(value, "_")
	if len(parts) == 0 {
		return value
	}
	var output strings.Builder
	output.WriteString(parts[0])
	for _, part := range parts[1:] {
		if part == "" {
			continue
		}
		output.WriteString(strings.ToUpper(part[:1]))
		output.WriteString(part[1:])
	}
	return output.String()
}

func mapBuildProfileKeys(values map[string]appLaunchBuildProfileContract) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	return keys
}

func appLaunchBuildProfileEnvironments(
	values map[string]appLaunchBuildProfileContract,
) map[string][]string {
	result := make(map[string][]string, len(values))
	for profile, contract := range values {
		result[profile] = append([]string(nil), contract.Environments...)
	}
	return result
}

func appLaunchBuildProfileLaunchPolicies(
	values map[string]appLaunchBuildProfileContract,
) map[string]string {
	result := make(map[string]string, len(values))
	for profile, contract := range values {
		result[profile] = contract.LaunchPolicy
	}
	return result
}

func mapLaunchPolicyKeys(values map[string]appLaunchPolicyContract) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	return keys
}

func mapBaseApplicationIDKeys(values map[string]appLaunchArtifactBaseApplicationID) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	return keys
}

func mapSchemaFieldKeys(values map[string]appLaunchSchemaField) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	return keys
}
