package main

import (
	"fmt"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

func loadAssistantCloudAPISource(
	metadataDir string,
) (*fieldsFile, *serviceFile, *assistantEnumCatalog, error) {
	ff := &fieldsFile{Entities: map[string]entityDef{}}
	fieldPaths, err := assistantObjectDocumentPaths("fields.yaml")
	if err != nil {
		return nil, nil, nil, fmt.Errorf("discover Assistant fields: %w", err)
	}
	fieldPaths = append(fieldPaths, filepath.Join(
		metadataDir,
		"assistant",
		"_shared",
		"types.yaml",
	))
	sort.Strings(fieldPaths)
	for _, path := range fieldPaths {
		additional, readErr := readFields(path)
		if readErr != nil {
			return nil, nil, nil, readErr
		}
		for name, entity := range additional.Entities {
			if _, exists := ff.Entities[name]; exists {
				return nil, nil, nil, fmt.Errorf(
					"assistant wire entity %q declared more than once",
					name,
				)
			}
			ff.Entities[name] = entity
		}
	}
	enumCatalog, err := loadAssistantEnumCatalog(metadataDir)
	if err != nil {
		return nil, nil, nil, err
	}
	operationPaths, err := assistantObjectDocumentPaths("operations.yaml")
	if err != nil {
		return nil, nil, nil, fmt.Errorf("discover Assistant operations: %w", err)
	}
	sort.Strings(operationPaths)
	svc := &serviceFile{}
	for _, path := range operationPaths {
		additional, readErr := readService(path)
		if readErr != nil {
			return nil, nil, nil, readErr
		}
		svc.APIRoutes = append(svc.APIRoutes, additional.APIRoutes...)
	}
	return ff, svc, enumCatalog, nil
}

func assistantObjectDocumentPaths(fileName string) ([]string, error) {
	fileName = strings.TrimSpace(fileName)
	if fileName == "" || strings.ContainsAny(fileName, `/\\`) {
		return nil, fmt.Errorf("invalid Assistant object document name %q", fileName)
	}
	paths := metadataDocumentPaths("assistant/assistant/", "/"+fileName)
	result := make([]string, 0, len(paths))
	for _, path := range paths {
		relative, err := metadataDocumentPath(path)
		if err != nil {
			return nil, err
		}
		segments := strings.Split(filepath.ToSlash(relative), "/")
		if len(segments) != 4 ||
			segments[0] != "assistant" ||
			segments[1] != "assistant" ||
			segments[3] != fileName {
			continue
		}
		result = append(result, path)
	}
	sort.Strings(result)
	return result, nil
}

func collectAssistantWireEntities(ff *fieldsFile, svc *serviceFile) []string {
	initial := make([]string, 0, len(svc.APIRoutes)*2)
	for _, route := range svc.APIRoutes {
		initial = append(initial, route.RequestEntity, route.ResponseEntity)
	}
	return collectAssistantWireEntityClosure(ff, initial)
}

func collectAssistantWireResponseEntities(
	ff *fieldsFile,
	svc *serviceFile,
) []string {
	initial := make([]string, 0, len(svc.APIRoutes))
	for _, route := range svc.APIRoutes {
		initial = append(initial, route.ResponseEntity)
	}
	return collectAssistantWireEntityClosure(ff, initial)
}

func collectAssistantWireEntityClosure(
	ff *fieldsFile,
	initial []string,
) []string {
	seen := map[string]bool{}
	var names []string
	add := func(name string) {
		name = strings.TrimSpace(name)
		if name != "" && !seen[name] {
			seen[name] = true
			names = append(names, name)
		}
	}
	for _, name := range initial {
		add(name)
	}
	expanded := map[string]bool{}
	var visit func(string)
	visit = func(name string) {
		name = strings.TrimSpace(name)
		if name == "" || expanded[name] {
			return
		}
		ent, ok := ff.Entities[name]
		if !ok {
			return
		}
		expanded[name] = true
		for _, field := range ent.Fields {
			inner, ok := assistantWireListElementType(field.Type)
			if ok {
				if _, exists := ff.Entities[inner]; exists {
					add(inner)
					visit(inner)
				}
				continue
			}
			fieldType := strings.TrimSpace(field.Type)
			if _, exists := ff.Entities[fieldType]; exists {
				add(fieldType)
				visit(fieldType)
			}
		}
	}
	for _, name := range append([]string(nil), names...) {
		visit(name)
	}
	sort.Strings(names)
	return names
}

func renderAssistantCloudApiWireDart(
	ff *fieldsFile,
	entityNames []string,
	enumCatalog *assistantEnumCatalog,
) string {
	deps := map[string]map[string]bool{}
	for _, n := range entityNames {
		deps[n] = map[string]bool{}
		ent, ok := ff.Entities[n]
		if !ok {
			continue
		}
		for _, f := range ent.Fields {
			if _, isEnt := ff.Entities[strings.TrimSpace(f.Type)]; isEnt {
				deps[n][strings.TrimSpace(f.Type)] = true
			}
			inner, ok := assistantWireListElementType(f.Type)
			if ok && containsString(entityNames, inner) {
				deps[n][inner] = true
			}
		}
	}
	order := assistantWireTopoEntityOrder(entityNames, deps)

	var b strings.Builder
	b.WriteString("// Code generated by tools/codegen_app_metadata from assistant metadata fields. DO NOT EDIT.\n")
	b.WriteString("// ignore_for_file: prefer_const_constructors, unnecessary_null_in_if_null_operators\n\n")
	b.WriteString(renderAssistantCloudWireEnumsDart(enumCatalog))

	for _, name := range order {
		ent, ok := ff.Entities[name]
		if !ok {
			continue
		}
		assistantWireEmitEntityDart(&b, ff, enumCatalog, name, ent)
		b.WriteString("\n")
	}

	return b.String()
}

func renderAssistantCloudWireEnumsDart(catalog *assistantEnumCatalog) string {
	if catalog == nil || len(catalog.Enums) == 0 {
		return ""
	}
	return "import 'assistant_runtime_enums.g.dart';\n\n"
}

func assistantWireHasEnum(catalog *assistantEnumCatalog, name string) bool {
	if catalog == nil {
		return false
	}
	for _, enum := range catalog.Enums {
		if enum.Name == strings.TrimSpace(name) {
			return true
		}
	}
	return false
}

func containsString(slice []string, s string) bool {
	for _, x := range slice {
		if x == s {
			return true
		}
	}
	return false
}

var (
	assistantWireListTypeRe        = regexp.MustCompile(`^\[\](.+)$`)
	assistantWireNullDerivedBoolRe = regexp.MustCompile(
		`^([A-Za-z_][A-Za-z0-9_]*)\s+IS\s+NULL$`,
	)
)

func assistantWireNullDerivedBoolean(field fieldDef) (string, bool) {
	if strings.TrimSpace(field.Type) != "bool" {
		return "", false
	}
	match := assistantWireNullDerivedBoolRe.FindStringSubmatch(
		strings.TrimSpace(field.Source),
	)
	if len(match) != 2 {
		return "", false
	}
	return match[1], true
}

func assistantWireListElementType(t string) (string, bool) {
	t = strings.TrimSpace(t)
	m := assistantWireListTypeRe.FindStringSubmatch(t)
	if m == nil {
		return "", false
	}
	return strings.TrimSpace(m[1]), true
}

func assistantWireListEnumRef(
	catalog *assistantEnumCatalog,
	field fieldDef,
) (string, bool) {
	inner, isList := assistantWireListElementType(field.Type)
	enumRef := strings.TrimSpace(field.EnumRef)
	if !isList || inner != "enum" || enumRef == "" ||
		!assistantWireHasEnum(catalog, enumRef) {
		return "", false
	}
	return enumRef, true
}

func assistantWireTopoEntityOrder(names []string, deps map[string]map[string]bool) []string {
	seen := map[string]bool{}
	var order []string
	var visit func(n string)
	visit = func(n string) {
		if seen[n] {
			return
		}
		seen[n] = true
		dependencyNames := make([]string, 0, len(deps[n]))
		for d := range deps[n] {
			dependencyNames = append(dependencyNames, d)
		}
		sort.Strings(dependencyNames)
		for _, d := range dependencyNames {
			if containsString(names, d) {
				visit(d)
			}
		}
		order = append(order, n)
	}
	for _, n := range names {
		visit(n)
	}
	return order
}

func assistantWireFieldNullable(f fieldDef) bool {
	for _, c := range f.Constraints {
		if c == "NOT_NULL" || c == "PK" {
			return false
		}
	}
	for _, c := range f.Constraints {
		if c == "NULLABLE" {
			return true
		}
	}
	return true
}

func assistantWireDartType(
	ff *fieldsFile,
	enumCatalog *assistantEnumCatalog,
	f fieldDef,
	nullable bool,
) string {
	t := strings.TrimSpace(f.Type)
	if t == "enum" && assistantWireHasEnum(enumCatalog, f.EnumRef) {
		if nullable {
			return f.EnumRef + "?"
		}
		return f.EnumRef
	}
	if _, isEnt := ff.Entities[t]; isEnt {
		if nullable {
			return t + "?"
		}
		return t
	}
	if inner, ok := assistantWireListElementType(t); ok {
		if enumRef, isEnum := assistantWireListEnumRef(enumCatalog, f); isEnum {
			if nullable {
				return "List<" + enumRef + ">?"
			}
			return "List<" + enumRef + ">"
		}
		if _, isEnt := ff.Entities[inner]; isEnt {
			if nullable {
				return "List<" + inner + ">?"
			}
			return "List<" + inner + ">"
		}
		switch inner {
		case "string":
			if nullable {
				return "List<String>?"
			}
			return "List<String>"
		case "object":
			if nullable {
				return "List<Map<String, dynamic>>?"
			}
			return "List<Map<String, dynamic>>"
		default:
			if nullable {
				return "List<dynamic>?"
			}
			return "List<dynamic>"
		}
	}
	switch t {
	case "string":
		if nullable {
			return "String?"
		}
		return "String"
	case "bool":
		if nullable {
			return "bool?"
		}
		return "bool"
	case "int", "int64":
		if nullable {
			return "int?"
		}
		return "int"
	case "float":
		if nullable {
			return "double?"
		}
		return "double"
	case "datetime":
		if nullable {
			return "DateTime?"
		}
		return "DateTime"
	case "timestamp":
		if nullable {
			return "String?"
		}
		return "String"
	case "object", "jsonb":
		if nullable {
			return "Map<String, dynamic>?"
		}
		return "Map<String, dynamic>"
	case "enum":
		return "String?"
	default:
		return "dynamic"
	}
}

func assistantWireEmitEntityDart(
	b *strings.Builder,
	ff *fieldsFile,
	enumCatalog *assistantEnumCatalog,
	name string,
	ent entityDef,
) {
	fmt.Fprintf(b, "class %s {\n", name)
	if len(ent.Fields) == 0 {
		fmt.Fprintf(b, "  const %s();\n\n", name)
	} else {
		fmt.Fprintf(b, "  const %s({\n", name)
	}
	for _, f := range ent.Fields {
		nul := assistantWireFieldNullable(f)
		if nul {
			if inner, ok := assistantWireListElementType(f.Type); ok {
				if _, isEnum := assistantWireListEnumRef(enumCatalog, f); isEnum {
					fmt.Fprintf(b, "    this.%s,\n", f.Name)
					continue
				}
				if _, isEnt := ff.Entities[inner]; isEnt {
					fmt.Fprintf(b, "    this.%s = const [],\n", f.Name)
					continue
				}
				if inner == "string" {
					fmt.Fprintf(b, "    this.%s = const [],\n", f.Name)
					continue
				}
				if inner == "object" {
					if !nul {
						fmt.Fprintf(b, "    this.%s = const [],\n", f.Name)
					} else {
						fmt.Fprintf(b, "    this.%s,\n", f.Name)
					}
					continue
				}
			}
			fmt.Fprintf(b, "    this.%s,\n", f.Name)
		} else {
			fmt.Fprintf(b, "    required this.%s,\n", f.Name)
		}
	}
	if len(ent.Fields) > 0 {
		b.WriteString("  });\n\n")
	}
	for _, f := range ent.Fields {
		nul := assistantWireFieldNullable(f)
		// A field declared `type: enum` whose enum_ref is not in the catalog
		// used to fall through to `String`, which is how SkillPackageAssetKind
		// and friends stayed untyped for so long: the contract said enum, the
		// App got an unvalidated string, and nothing reported it.
		if strings.TrimSpace(f.Type) == "enum" &&
			strings.TrimSpace(f.EnumRef) != "" &&
			!assistantWireHasEnum(enumCatalog, f.EnumRef) {
			exitErr(fmt.Errorf(
				"assistant wire %s.%s declares type: enum with enum_ref %q, but no "+
					"assistant contract owns that enum; declare it in the owning "+
					"object's fields.yaml `enums:` block or in "+
					"assistant/_shared/enums.yaml",
				name,
				f.Name,
				strings.TrimSpace(f.EnumRef),
			))
		}
		dt := assistantWireDartType(ff, enumCatalog, f, nul)
		fmt.Fprintf(b, "  final %s %s;\n", dt, f.Name)
		recordEnumFieldBinding(enumFieldBinding{
			DartClass:      name,
			DartField:      f.Name,
			DartType:       dt,
			EnumRef:        f.EnumRef,
			ContractType:   f.Type,
			ClientDartType: f.ClientDartType,
		})
	}
	b.WriteString("\n")
	fmt.Fprintf(b, "  factory %s.fromJson(Map<String, dynamic> json) {\n", name)
	assistantWireEmitJsonValidation(b, ff, enumCatalog, name, ent)
	fmt.Fprintf(b, "    return %s(\n", name)
	for _, f := range ent.Fields {
		fmt.Fprintf(
			b,
			"      %s: %s,\n",
			f.Name,
			assistantWireFromJsonExpr(ff, enumCatalog, name, f),
		)
	}
	b.WriteString("    );\n  }\n\n")
	fmt.Fprintf(b, "  Map<String, dynamic> toJson() => <String, dynamic>{\n")
	for _, f := range ent.Fields {
		fmt.Fprintf(
			b,
			"        '%s': %s,\n",
			f.Name,
			assistantWireToJsonExpr(ff, enumCatalog, f),
		)
	}
	b.WriteString("      };\n")

	if name == "AssistantUserTaskView" {
		b.WriteString(`
  /// 兼容旧 UI 使用的 ` + "`title` / `desc`" + ` Map。
  Map<String, dynamic> toScheduleRowMap() => <String, dynamic>{
        'title': title,
        'desc': description ?? '',
      };
`)
	}
	b.WriteString("}\n")
}

func assistantWireEmitJsonValidation(
	b *strings.Builder,
	ff *fieldsFile,
	enumCatalog *assistantEnumCatalog,
	entityName string,
	ent entityDef,
) {
	b.WriteString("    const allowedFields = <String>{\n")
	for _, field := range ent.Fields {
		fmt.Fprintf(b, "      '%s',\n", field.Name)
	}
	b.WriteString("    };\n")
	b.WriteString("    final unknownFields = json.keys\n")
	b.WriteString("        .where((key) => !allowedFields.contains(key))\n")
	b.WriteString("        .toList(growable: false);\n")
	b.WriteString("    if (unknownFields.isNotEmpty) {\n")
	fmt.Fprintf(
		b,
		"      throw FormatException('%s response contains unknown fields: ${unknownFields.join(', ')}');\n",
		entityName,
	)
	b.WriteString("    }\n")
	for _, field := range ent.Fields {
		if _, derived := assistantWireNullDerivedBoolean(field); derived {
			continue
		}
		condition := assistantWireJsonInvalidCondition(ff, enumCatalog, field)
		if condition == "" {
			continue
		}
		if assistantWireFieldNullable(field) {
			fmt.Fprintf(
				b,
				"    if (json.containsKey('%s') && json['%s'] != null && (%s)) {\n",
				field.Name,
				field.Name,
				condition,
			)
		} else {
			fmt.Fprintf(
				b,
				"    if (!json.containsKey('%s') || json['%s'] == null || (%s)) {\n",
				field.Name,
				field.Name,
				condition,
			)
		}
		fmt.Fprintf(
			b,
			"      throw const FormatException('%s field %s has an invalid wire value');\n",
			entityName,
			field.Name,
		)
		b.WriteString("    }\n")
	}
	declaredDerivedLocals := map[string]bool{}
	for _, field := range ent.Fields {
		sourceField, derived := assistantWireNullDerivedBoolean(field)
		if !derived {
			continue
		}
		if !declaredDerivedLocals[field.Name] {
			fmt.Fprintf(b, "    final %s = json['%s'];\n", field.Name, field.Name)
			declaredDerivedLocals[field.Name] = true
		}
		fmt.Fprintf(b, "    if (%s is! bool) {\n", field.Name)
		fmt.Fprintf(
			b,
			"      throw const FormatException('%s field %s has an invalid wire value');\n",
			entityName,
			field.Name,
		)
		b.WriteString("    }\n")
		if !declaredDerivedLocals[sourceField] {
			fmt.Fprintf(b, "    final %s = json['%s'];\n", sourceField, sourceField)
			declaredDerivedLocals[sourceField] = true
		}
		fmt.Fprintf(b, "    if (%s != null && %s) {\n", sourceField, field.Name)
		fmt.Fprintf(
			b,
			"      throw const FormatException('%s fields %s and %s are inconsistent');\n",
			entityName,
			sourceField,
			field.Name,
		)
		b.WriteString("    }\n")
		fmt.Fprintf(b, "    if (%s == null && !%s) {\n", sourceField, field.Name)
		fmt.Fprintf(
			b,
			"      throw const FormatException('%s fields %s and %s are inconsistent');\n",
			entityName,
			sourceField,
			field.Name,
		)
		b.WriteString("    }\n")
	}
}

func assistantWireJsonInvalidCondition(
	ff *fieldsFile,
	enumCatalog *assistantEnumCatalog,
	field fieldDef,
) string {
	accessor := "json['" + field.Name + "']"
	typeName := strings.TrimSpace(field.Type)
	if typeName == "enum" && assistantWireHasEnum(enumCatalog, field.EnumRef) {
		return accessor + " is! String"
	}
	if _, isEntity := ff.Entities[typeName]; isEntity {
		return accessor + " is! Map"
	}
	if inner, ok := assistantWireListElementType(typeName); ok {
		invalidItemCondition := "false"
		if _, isEnum := assistantWireListEnumRef(enumCatalog, field); isEnum {
			invalidItemCondition = "item is! String"
		} else if _, isEntity := ff.Entities[inner]; isEntity || inner == "object" {
			invalidItemCondition = "item is! Map"
		} else if inner == "string" {
			invalidItemCondition = "item is! String"
		}
		return accessor + " is! List || (" + accessor +
			" as List).any((item) => " + invalidItemCondition + ")"
	}
	switch typeName {
	case "string", "timestamp", "enum":
		return accessor + " is! String"
	case "bool":
		return accessor + " is! bool"
	case "int", "int64", "float":
		return accessor + " is! num"
	case "datetime":
		return accessor + " is! String || DateTime.tryParse(" + accessor + " as String) == null"
	case "object", "jsonb":
		return accessor + " is! Map"
	default:
		return ""
	}
}

func assistantWireFromJsonExpr(
	ff *fieldsFile,
	enumCatalog *assistantEnumCatalog,
	entityName string,
	f fieldDef,
) string {
	n := f.Name
	nul := assistantWireFieldNullable(f)
	t := strings.TrimSpace(f.Type)
	if sourceField, derived := assistantWireNullDerivedBoolean(f); derived {
		return fmt.Sprintf("%s && %s == null", n, sourceField)
	}

	if t == "enum" && assistantWireHasEnum(enumCatalog, f.EnumRef) {
		if nul {
			return fmt.Sprintf(
				"json['%s'] == null ? null : parse%sStrict(json['%s'].toString())",
				n,
				f.EnumRef,
				n,
			)
		}
		return fmt.Sprintf("parse%sStrict((json['%s'] ?? '').toString())", f.EnumRef, n)
	}

	if _, isEnt := ff.Entities[t]; isEnt {
		if nul {
			return fmt.Sprintf(`(json['%s'] as Map?) == null
          ? null
          : %s.fromJson((json['%s'] as Map).cast<String, dynamic>())`, n, t, n)
		}
		return fmt.Sprintf(`%s.fromJson(((json['%s'] as Map?) ?? const <String, dynamic>{}).cast<String, dynamic>())`, t, n)
	}

	if inner, ok := assistantWireListElementType(t); ok {
		if enumRef, isEnum := assistantWireListEnumRef(enumCatalog, f); isEnum {
			return assistantWireEnumListFromJsonExpr(
				entityName,
				n,
				enumRef,
				nul,
			)
		}
		if _, isEnt := ff.Entities[inner]; isEnt {
			if entityName == "AssistantSearchResultView" && n == "citations" {
				return `((json['citations'] as List?) ?? const [])
            .whereType<Map>()
            .map((item) => AssistantSearchCitationView.fromJson(item.cast<String, dynamic>()))
            .where((item) => item.citationId.isNotEmpty || item.title.isNotEmpty)
            .toList(growable: false)`
			}
			return fmt.Sprintf(`((json['%s'] as List?) ?? const [])
            .whereType<Map>()
            .map((item) => %s.fromJson(item.cast<String, dynamic>()))
            .toList(growable: false)`, n, inner)
		}
		if inner == "string" {
			return fmt.Sprintf(`((json['%s'] as List?) ?? const [])
            .map((e) => e.toString())
            .toList(growable: false)`, n)
		}
		if inner == "object" {
			if nul {
				return fmt.Sprintf(`(json['%s'] as List?)
            ?.whereType<Map>()
            .map((m) => m.cast<String, dynamic>())
            .toList(growable: false)`, n)
			}
			return fmt.Sprintf(`((json['%s'] as List?) ?? const [])
            .whereType<Map>()
            .map((m) => m.cast<String, dynamic>())
            .toList(growable: false)`, n)
		}
	}

	switch n {
	case "queryEcho":
		return `(json['queryEcho'] ?? '').toString().trim()`
	case "taskId":
		return `(json['taskId'] ?? '').toString()`
	case "skillId":
		return `(json['skillId'] ?? '').toString()`
	case "displayName":
		return `(json['displayName'] ?? '').toString()`
	case "description":
		if entityName == "AssistantSkillCatalogItemView" {
			return `json['description']?.toString()`
		}
	case "requiresConsent":
		if entityName == "AssistantSkillCatalogItemView" {
			return `json['requiresConsent'] == true`
		}
	case "status":
		if entityName == "AssistantUserTaskView" {
			return `(json['status'] ?? 'pending').toString()`
		}
	case "updatedAt":
		if entityName == "AssistantUserTaskView" {
			return `json['updatedAt']?.toString()`
		}
	case "dueAt":
		if entityName == "AssistantUserTaskView" {
			return `json['dueAt']?.toString()`
		}
	case "sourceSkillId":
		if entityName == "AssistantUserTaskView" {
			return `json['sourceSkillId']?.toString()`
		}
	case "iconHint":
		if entityName == "AssistantSkillCatalogItemView" {
			return `json['iconHint']?.toString()`
		}
	}

	switch t {
	case "string":
		if nul {
			return `json['` + n + `']?.toString()`
		}
		return `(json['` + n + `'] ?? '').toString()`
	case "bool":
		if nul {
			return `(json['` + n + `'] as bool?)`
		}
		return `json['` + n + `'] == true`
	case "int", "int64":
		if nul {
			return `(json['` + n + `'] as num?)?.toInt()`
		}
		return `(json['` + n + `'] as num?)?.toInt() ?? 0`
	case "float":
		if nul {
			return `(json['` + n + `'] as num?)?.toDouble()`
		}
		return `(json['` + n + `'] as num?)?.toDouble() ?? 0.0`
	case "datetime":
		parsed := `DateTime.tryParse((json['` + n + `'] ?? '').toString().trim())`
		if nul {
			return parsed
		}
		return `(` + parsed + ` ?? (throw FormatException('required datetime field ` + n + ` is invalid')))`
	case "timestamp":
		// Single-track: only camelCase wire keys; no snake_case dual-read.
		if !nul {
			return `(json['` + n + `'] as String)`
		}
		return `json['` + n + `']?.toString()`
	case "object", "jsonb":
		if nul {
			return `(json['` + n + `'] as Map?)?.cast<String, dynamic>()`
		}
		return `(json['` + n + `'] as Map?)?.cast<String, dynamic>() ?? const <String, dynamic>{}`
	case "enum":
		return `json['` + n + `']?.toString()`
	default:
		return `json['` + n + `']`
	}
}

func assistantWireEnumListFromJsonExpr(
	entityName string,
	fieldName string,
	enumRef string,
	nullable bool,
) string {
	listAccess := fmt.Sprintf("(json['%s'] as List)", fieldName)
	if nullable {
		listAccess = fmt.Sprintf(
			"json['%s'] == null\n          ? null\n          : (json['%s'] as List)",
			fieldName,
			fieldName,
		)
	}
	return fmt.Sprintf(`%s.asMap().entries.map((entry) {
            final wireValue = entry.value as String;
            try {
              return parse%sStrict(wireValue);
            } on FormatException {
              throw FormatException(
                '%s.%s[${entry.key}] has an invalid enum wire value',
                wireValue,
              );
            }
          }).toList(growable: false)`, listAccess, enumRef, entityName, fieldName)
}

func assistantWireToJsonExpr(
	ff *fieldsFile,
	enumCatalog *assistantEnumCatalog,
	f fieldDef,
) string {
	t := strings.TrimSpace(f.Type)
	if t == "enum" && assistantWireHasEnum(enumCatalog, f.EnumRef) {
		if assistantWireFieldNullable(f) {
			return f.Name + "?.wireName"
		}
		return f.Name + ".wireName"
	}
	if _, isEnt := ff.Entities[t]; isEnt {
		if assistantWireFieldNullable(f) {
			return f.Name + "?.toJson()"
		}
		return f.Name + ".toJson()"
	}
	if inner, ok := assistantWireListElementType(t); ok {
		if _, isEnum := assistantWireListEnumRef(enumCatalog, f); isEnum {
			access := f.Name
			if assistantWireFieldNullable(f) {
				access += "?"
			}
			return access + ".map((item) => item.wireName).toList(growable: false)"
		}
		if _, isEnt := ff.Entities[inner]; isEnt {
			if assistantWireFieldNullable(f) {
				return f.Name + "?.map((item) => item.toJson()).toList(growable: false)"
			}
			return f.Name + ".map((item) => item.toJson()).toList(growable: false)"
		}
	}
	if t == "datetime" {
		if assistantWireFieldNullable(f) {
			return f.Name + "?.toUtc().toIso8601String()"
		}
		return f.Name + ".toUtc().toIso8601String()"
	}
	return f.Name
}
