package main

import (
	"fmt"
	"strings"
)

func renderContentBehaviorsDart(bf *behaviorsFile) string {
	var b strings.Builder
	b.WriteString("// Code generated by tools/codegen_app_metadata from content/post/behaviors.yaml. DO NOT EDIT.\n\n")

	// Collect batch events (those with dart_method and batch=true or batch=false but not dedicated_route)
	var trackedEvents []behaviorEventDef
	batchRoute := ""
	for _, ev := range bf.BehaviorEvents {
		if ev.DartMethod != "" && ev.DedicatedRoute == "" {
			trackedEvents = append(trackedEvents, ev)
			if ev.BatchRoute != "" && batchRoute == "" {
				// Extract path from "POST /content/behaviors"
				parts := strings.SplitN(ev.BatchRoute, " ", 2)
				if len(parts) == 2 {
					batchRoute = parts[1]
				}
			}
		}
	}
	if batchRoute == "" {
		batchRoute = "/content/behaviors"
	}

	b.WriteString("// ignore: avoid_classes_with_only_static_members\n")
	b.WriteString("class ContentBehaviorTracker {\n")
	b.WriteString("  const ContentBehaviorTracker._();\n\n")
	b.WriteString(fmt.Sprintf("  static const String _batchRoute = '%s';\n\n", batchRoute))
	b.WriteString("  /// Public read-only accessor for the batch route (used in contract tests).\n")
	b.WriteString("  static String get batchRoute => _batchRoute;\n\n")
	b.WriteString("  static final List<Map<String, dynamic>> _queue = <Map<String, dynamic>>[];\n")
	b.WriteString("  static const int _flushThreshold = 20;\n\n")
	b.WriteString("  // ignore: invalid_use_of_visible_for_testing_member\n")
	b.WriteString("  /// Returns a read-only snapshot of the pending event queue. For testing only.\n")
	b.WriteString("  static List<Map<String, dynamic>> get pendingQueue =>\n")
	b.WriteString("      List<Map<String, dynamic>>.unmodifiable(_queue);\n\n")
	b.WriteString("  /// Clears the pending queue. For testing only.\n")
	b.WriteString("  static void reset() => _queue.clear();\n\n")

	// Generate track methods - collect positional and named params separately.
	for _, ev := range trackedEvents {
		hasPostId := false
		for _, pf := range ev.PayloadFields {
			if pf == "postId" {
				hasPostId = true
				break
			}
		}
		var positional []string
		if hasPostId {
			positional = append(positional, "String postId")
		}
		var named []string
		for _, pf := range ev.PayloadFields {
			if pf == "postId" {
				continue
			}
			switch pf {
			case "dwellMs":
				positional = append(positional, "int dwellMs")
			case "authorId":
				positional = append(positional, "String authorId")
			case "circleId":
				positional = append(positional, "String circleId")
			case "entityRefs":
				positional = append(positional, "List<String> entityRefs")
			case "tagRefs":
				positional = append(positional, "List<String> tagRefs")
			case "consumedRatio":
				positional = append(positional, "double consumedRatio")
			case "totalUnits":
				positional = append(positional, "int totalUnits")
			case "effectivePlayMs":
				positional = append(positional, "int effectivePlayMs")
			case "subjectId":
				positional = append(positional, "String subjectId")
			case "feedbackKind":
				positional = append(positional, "String feedbackKind")
			case "objectId":
				positional = append(positional, "String objectId")
			case "objectKind":
				positional = append(positional, "String objectKind")
			case "feedPosition":
				named = append(named, "int feedPosition = 0")
			case "contentType":
				named = append(named, "String contentType = ''")
			case "displayName":
				named = append(named, "String displayName = ''")
			case "sourceSurface":
				named = append(named, "String sourceSurface = ''")
			case "shareTarget":
				named = append(named, "String shareTarget = ''")
			case "intersectionDimension":
				named = append(named, "String intersectionDimension = ''")
			case "intersectionTagRefs":
				named = append(named, "List<String> intersectionTagRefs = const <String>[]")
			case "intersectionId":
				named = append(named, "String intersectionId = ''")
			case "intersectionClass":
				named = append(named, "String intersectionClass = ''")
			case "intersectionSourceRef":
				named = append(named, "String intersectionSourceRef = ''")
			case "intersectionEvidenceId":
				named = append(named, "String intersectionEvidenceId = ''")
			case "surfaceId":
				named = append(named, "String surfaceId = ''")
			default:
				// Fail loudly so a newly-added payload_field in behaviors.yaml can never
				// silently emit an undefined variable reference in the generated tracker.
				panic(fmt.Sprintf("content_behaviors codegen: unmapped payload field %q on event %q; add an explicit case in the track-method generator", pf, ev.Type))
			}
		}
		sig := strings.Join(positional, ", ")
		if len(named) > 0 {
			if sig != "" {
				sig += ", "
			}
			sig += "{" + strings.Join(named, ", ") + "}"
		}
		b.WriteString(fmt.Sprintf("  static void %s(%s) {\n", ev.DartMethod, sig))
		b.WriteString("    _enqueue(<String, dynamic>{\n")
		b.WriteString(fmt.Sprintf("      'type': '%s',\n", ev.Type))
		if hasPostId {
			b.WriteString("      'postId': postId,\n")
		}
		for _, pf := range ev.PayloadFields {
			if pf == "postId" {
				continue
			}
			b.WriteString(fmt.Sprintf("      '%s': %s,\n", pf, pf))
		}
		b.WriteString("    });\n")
		b.WriteString("  }\n\n")
	}

	b.WriteString("  static void _enqueue(Map<String, dynamic> event) {\n")
	b.WriteString("    _queue.add(event);\n")
	b.WriteString("    if (_queue.length >= _flushThreshold) {\n")
	b.WriteString("      flush();\n")
	b.WriteString("    }\n")
	b.WriteString("  }\n\n")

	b.WriteString("  static Future<void> flush() async {\n")
	b.WriteString("    if (_queue.isEmpty) return;\n")
	b.WriteString("    final events = List<Map<String, dynamic>>.from(_queue);\n")
	b.WriteString("    _queue.clear();\n")
	b.WriteString("    // Route: $_batchRoute\n")
	b.WriteString("    // Caller injects HTTP client via BehaviorTrackerHttpClient.send(events);\n")
	b.WriteString("    await BehaviorTrackerHttpClient.send(_batchRoute, events);\n")
	b.WriteString("  }\n")
	b.WriteString("}\n\n")

	// Abstract HTTP client interface for testability
	b.WriteString("abstract class BehaviorTrackerHttpClient {\n")
	b.WriteString("  static Future<void> Function(String route, List<Map<String, dynamic>> events) send =\n")
	b.WriteString("      _defaultSend;\n\n")
	b.WriteString("  static Future<void> _defaultSend(\n")
	b.WriteString("    String route,\n")
	b.WriteString("    List<Map<String, dynamic>> events,\n")
	b.WriteString("  ) async {\n")
	b.WriteString("    // Default no-op; override via BehaviorTrackerHttpClient.send = myImpl;\n")
	b.WriteString("  }\n")
	b.WriteString("}\n")

	return b.String()
}

func renderContentPrivacyDart(pf *privacyFile) string {
	var b strings.Builder
	b.WriteString("// Code generated by tools/codegen_app_metadata from content/post/privacy.yaml. DO NOT EDIT.\n\n")
	b.WriteString("// ignore: avoid_classes_with_only_static_members\n")
	b.WriteString("class ContentPrivacyPolicy {\n")
	b.WriteString("  const ContentPrivacyPolicy._();\n\n")

	b.WriteString("  /// Returns sanitized value for app logging. Returns null to drop field.\n")
	b.WriteString("  static dynamic sanitizeForLog(String fieldName, dynamic value) {\n")
	b.WriteString("    switch (fieldName) {\n")

	for _, policy := range pf.AppLogPolicy {
		b.WriteString(fmt.Sprintf("      case '%s':\n", policy.Field))
		switch policy.AppLog {
		case "drop":
			b.WriteString("        return null;\n")
		case "truncate":
			chars := policy.TruncateChars
			if chars <= 0 {
				chars = 200
			}
			b.WriteString(fmt.Sprintf("        if (value is String && value.length > %d) {\n", chars))
			b.WriteString(fmt.Sprintf("          return value.substring(0, %d);\n", chars))
			b.WriteString("        }\n")
			b.WriteString("        return value;\n")
		case "mask":
			switch policy.MaskStrategy {
			case "city_level_only":
				b.WriteString("        if (value is Map) return <String, dynamic>{'city': value['city']};\n")
				b.WriteString("        return null;\n")
			case "strip_detail":
				b.WriteString("        if (value is String) {\n")
				b.WriteString("          final parts = value.split(' ');\n")
				b.WriteString("          return parts.isNotEmpty ? parts.first : '';\n")
				b.WriteString("        }\n")
				b.WriteString("        return null;\n")
			default:
				b.WriteString("        return null;\n")
			}
		default:
			b.WriteString("        return value;\n")
		}
	}

	b.WriteString("      default:\n")
	b.WriteString("        return value;\n")
	b.WriteString("    }\n")
	b.WriteString("  }\n")
	b.WriteString("}\n")

	return b.String()
}
