package main

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"
)

// renderCircleWriteWireWritableKeysDart 从 ContractGraph 固定 bundle 内嵌的 Circle
// 对象 packet 读取 writable_fields，生成尚未迁移对象的 App Wire DTO 键集合。
// CircleGroup 已使用 operation-specific pure contracts，不得在此生成第二套 DTO 键。
func renderCircleWriteWireWritableKeysDart(metadataDir string) (string, error) {
	circleServicePath := filepath.Join(metadataDir, "circle", "circle_management", "circle", "operations.yaml")
	circleService, err := readService(circleServicePath)
	if err != nil {
		return "", fmt.Errorf("read circle operations.yaml: %w", err)
	}
	create := findWritableFields(circleService.APIRoutes, "CreateCircle")
	if len(create) == 0 {
		return "", fmt.Errorf("circle service: CreateCircle writable_fields missing")
	}
	createSorted := append([]string(nil), create...)
	sort.Strings(createSorted)

	var b strings.Builder
	b.WriteString("// Code generated by tools/codegen_app_metadata from ContractGraph object packet api_routes writable_fields. DO NOT EDIT.\n")
	b.WriteString("// ignore_for_file: dangling_library_doc_comments\n\n")
	b.WriteString("/// CreateCircle 可写字段键，与 metadata SSOT 对齐。\n")
	b.WriteString("library;\n\n")
	b.WriteString("// ignore: avoid_classes_with_only_static_members\n")
	b.WriteString("abstract final class CircleWriteWireWritableKeys {\n")
	b.WriteString("  CircleWriteWireWritableKeys._();\n\n")
	writeSet := func(name string, keys []string) {
		b.WriteString(fmt.Sprintf("  static const Set<String> %s = {\n", name))
		for _, k := range keys {
			b.WriteString(fmt.Sprintf("    '%s',\n", k))
		}
		b.WriteString("  };\n\n")
	}
	writeList := func(name string, keys []string) {
		b.WriteString(fmt.Sprintf(
			"  /// operations.yaml 中 `%s` 声明顺序（与对应 Set 成员一致，用于序列化/校验对照）。\n",
			name,
		))
		b.WriteString(fmt.Sprintf("  static const List<String> %s = [\n", name))
		for _, k := range keys {
			b.WriteString(fmt.Sprintf("    '%s',\n", k))
		}
		b.WriteString("  ];\n\n")
	}
	writeSet("createCircle", createSorted)
	writeList("createCircleServiceFieldOrder", create)
	b.WriteString("}\n")
	return b.String(), nil
}
