package main

import (
	"fmt"
	"sort"
	"strings"
)

func renderContentUIConfigDart(uc *uiConfigFile) string {
	var b strings.Builder
	b.WriteString("// Code generated by tools/codegen_app_metadata from content/post/ui_config.yaml. DO NOT EDIT.\n")
	b.WriteString("// ignore_for_file: prefer_const_constructors\n\n")

	b.WriteString("class HomeChannelConfig {\n")
	b.WriteString("  final String id;\n")
	b.WriteString("  final String labelKey;\n")
	b.WriteString("  final String template;\n")
	b.WriteString("  final String layoutTemplate;\n")
	b.WriteString("  final int phoneColumns;\n")
	b.WriteString("  final bool supportsFullSpanModules;\n")
	b.WriteString("  final String intersectionModulePolicy;\n")
	b.WriteString("  final String contentCardPolicy;\n")
	b.WriteString("  final Map<String, String> feedQuery;\n")
	b.WriteString("  final String moodCopyKey;\n")
	b.WriteString("  final int order;\n\n")
	b.WriteString("  const HomeChannelConfig({\n")
	b.WriteString("    required this.id,\n")
	b.WriteString("    required this.labelKey,\n")
	b.WriteString("    required this.template,\n")
	b.WriteString("    required this.layoutTemplate,\n")
	b.WriteString("    required this.phoneColumns,\n")
	b.WriteString("    required this.supportsFullSpanModules,\n")
	b.WriteString("    required this.intersectionModulePolicy,\n")
	b.WriteString("    required this.contentCardPolicy,\n")
	b.WriteString("    required this.feedQuery,\n")
	b.WriteString("    required this.moodCopyKey,\n")
	b.WriteString("    required this.order,\n")
	b.WriteString("  });\n")
	b.WriteString("}\n\n")

	b.WriteString("class DiscoveryTabConfig {\n")
	b.WriteString("  final String id;\n")
	b.WriteString("  final String labelKey;\n")
	b.WriteString("  final String icon;\n")
	b.WriteString("  final String contentType;\n")
	b.WriteString("  final String layout;\n\n")
	b.WriteString("  const DiscoveryTabConfig({\n")
	b.WriteString("    required this.id,\n")
	b.WriteString("    required this.labelKey,\n")
	b.WriteString("    required this.icon,\n")
	b.WriteString("    required this.contentType,\n")
	b.WriteString("    required this.layout,\n")
	b.WriteString("  });\n")
	b.WriteString("}\n\n")

	b.WriteString("class DiscoveryRailConfig {\n")
	b.WriteString("  final String id;\n")
	b.WriteString("  final String labelKey;\n")
	b.WriteString("  final String identity;\n")
	b.WriteString("  final bool isDefault;\n\n")
	b.WriteString("  const DiscoveryRailConfig({\n")
	b.WriteString("    required this.id,\n")
	b.WriteString("    required this.labelKey,\n")
	b.WriteString("    required this.identity,\n")
	b.WriteString("    required this.isDefault,\n")
	b.WriteString("  });\n")
	b.WriteString("}\n\n")

	b.WriteString("class IdentityFilterConfig {\n")
	b.WriteString("  final String id;\n")
	b.WriteString("  final String labelKey;\n")
	b.WriteString("  final String? identity;\n\n")
	b.WriteString("  const IdentityFilterConfig({\n")
	b.WriteString("    required this.id,\n")
	b.WriteString("    required this.labelKey,\n")
	b.WriteString("    required this.identity,\n")
	b.WriteString("  });\n")
	b.WriteString("}\n\n")

	b.WriteString("class WorkFormatFilterConfig {\n")
	b.WriteString("  final String id;\n")
	b.WriteString("  final String labelKey;\n")
	b.WriteString("  final String? contentType;\n\n")
	b.WriteString("  const WorkFormatFilterConfig({\n")
	b.WriteString("    required this.id,\n")
	b.WriteString("    required this.labelKey,\n")
	b.WriteString("    required this.contentType,\n")
	b.WriteString("  });\n")
	b.WriteString("}\n\n")

	b.WriteString("class ShareTemplateProfileConfig {\n")
	b.WriteString("  final String id;\n")
	b.WriteString("  final String titleKey;\n")
	b.WriteString("  final String subtitleKey;\n")
	b.WriteString("  final String layout;\n")
	b.WriteString("  final String coverStrategy;\n")
	b.WriteString("  final bool includeAuthor;\n")
	b.WriteString("  final bool includeTimeContext;\n")
	b.WriteString("  final bool includeCircleContext;\n")
	b.WriteString("  final bool includeTags;\n\n")
	b.WriteString("  const ShareTemplateProfileConfig({\n")
	b.WriteString("    required this.id,\n")
	b.WriteString("    required this.titleKey,\n")
	b.WriteString("    required this.subtitleKey,\n")
	b.WriteString("    required this.layout,\n")
	b.WriteString("    required this.coverStrategy,\n")
	b.WriteString("    required this.includeAuthor,\n")
	b.WriteString("    required this.includeTimeContext,\n")
	b.WriteString("    required this.includeCircleContext,\n")
	b.WriteString("    required this.includeTags,\n")
	b.WriteString("  });\n")
	b.WriteString("}\n\n")

	b.WriteString("class ArticleDistributionProfileConfig {\n")
	b.WriteString("  final String id;\n")
	b.WriteString("  final String surface;\n")
	b.WriteString("  final String layout;\n")
	b.WriteString("  final String coverMode;\n")
	b.WriteString("  final int summaryLineLimit;\n\n")
	b.WriteString("  const ArticleDistributionProfileConfig({\n")
	b.WriteString("    required this.id,\n")
	b.WriteString("    required this.surface,\n")
	b.WriteString("    required this.layout,\n")
	b.WriteString("    required this.coverMode,\n")
	b.WriteString("    required this.summaryLineLimit,\n")
	b.WriteString("  });\n")
	b.WriteString("}\n\n")

	b.WriteString("class ArticleReaderProfileConfig {\n")
	b.WriteString("  final String id;\n")
	b.WriteString("  final String stageLayout;\n")
	b.WriteString("  final String pageIndicatorAnchor;\n")
	b.WriteString("  final String edgeTreatment;\n")
	b.WriteString("  final bool supportsPageCurl;\n\n")
	b.WriteString("  const ArticleReaderProfileConfig({\n")
	b.WriteString("    required this.id,\n")
	b.WriteString("    required this.stageLayout,\n")
	b.WriteString("    required this.pageIndicatorAnchor,\n")
	b.WriteString("    required this.edgeTreatment,\n")
	b.WriteString("    required this.supportsPageCurl,\n")
	b.WriteString("  });\n")
	b.WriteString("}\n\n")

	b.WriteString("class ArticleTemplateConfig {\n")
	b.WriteString("  final String id;\n")
	b.WriteString("  final String defaultFontPreset;\n")
	b.WriteString("  final String paperTexture;\n")
	b.WriteString("  final String decorationStyle;\n")
	b.WriteString("  final String chromeStyle;\n\n")
	b.WriteString("  const ArticleTemplateConfig({\n")
	b.WriteString("    required this.id,\n")
	b.WriteString("    required this.defaultFontPreset,\n")
	b.WriteString("    required this.paperTexture,\n")
	b.WriteString("    required this.decorationStyle,\n")
	b.WriteString("    required this.chromeStyle,\n")
	b.WriteString("  });\n")
	b.WriteString("}\n\n")

	b.WriteString("class ArticleTemplateRecommendationConfig {\n")
	b.WriteString("  final String categoryId;\n")
	b.WriteString("  final List<String> recommendedArticleTemplates;\n\n")
	b.WriteString("  const ArticleTemplateRecommendationConfig({\n")
	b.WriteString("    required this.categoryId,\n")
	b.WriteString("    required this.recommendedArticleTemplates,\n")
	b.WriteString("  });\n")
	b.WriteString("}\n\n")

	b.WriteString("class ArticlePaperThemeOptionConfig {\n")
	b.WriteString("  final String id;\n")
	b.WriteString("  final String labelKey;\n\n")
	b.WriteString("  const ArticlePaperThemeOptionConfig({\n")
	b.WriteString("    required this.id,\n")
	b.WriteString("    required this.labelKey,\n")
	b.WriteString("  });\n")
	b.WriteString("}\n\n")

	b.WriteString("class ArticleDarkPaperThemeConfig {\n")
	b.WriteString("  final String id;\n")
	b.WriteString("  final String stage;\n")
	b.WriteString("  final String paper;\n")
	b.WriteString("  final String text;\n")
	b.WriteString("  final String secondaryText;\n\n")
	b.WriteString("  const ArticleDarkPaperThemeConfig({\n")
	b.WriteString("    required this.id,\n")
	b.WriteString("    required this.stage,\n")
	b.WriteString("    required this.paper,\n")
	b.WriteString("    required this.text,\n")
	b.WriteString("    required this.secondaryText,\n")
	b.WriteString("  });\n")
	b.WriteString("}\n\n")

	tabs := append([]discoveryTabDef(nil), uc.DiscoveryTabs...)
	sort.Slice(tabs, func(i, j int) bool { return tabs[i].Order < tabs[j].Order })
	rails := append([]discoveryRailDef(nil), uc.DiscoveryRails...)
	sort.Slice(rails, func(i, j int) bool { return rails[i].Order < rails[j].Order })
	identityFilters := append([]identityFilterDef(nil), uc.CreationIdentityFilters...)
	sort.Slice(identityFilters, func(i, j int) bool { return identityFilters[i].Order < identityFilters[j].Order })
	workFormatFilters := append([]workFormatFilterDef(nil), uc.WorkFormatFilters...)
	sort.Slice(workFormatFilters, func(i, j int) bool { return workFormatFilters[i].Order < workFormatFilters[j].Order })
	shareProfiles := append([]shareTemplateProfileDef(nil), uc.ShareTemplateProfiles...)
	sort.Slice(shareProfiles, func(i, j int) bool { return shareProfiles[i].ID < shareProfiles[j].ID })
	articleDistributionProfiles := append([]articleDistributionProfileDef(nil), uc.ArticleDistributionProfiles...)
	sort.Slice(articleDistributionProfiles, func(i, j int) bool { return articleDistributionProfiles[i].ID < articleDistributionProfiles[j].ID })
	articleReaderProfiles := append([]articleReaderProfileDef(nil), uc.ArticleReaderProfiles...)
	sort.Slice(articleReaderProfiles, func(i, j int) bool { return articleReaderProfiles[i].ID < articleReaderProfiles[j].ID })
	articleTemplateConfigs := append([]articleTemplateConfigDef(nil), uc.ArticleTemplateConfigs...)
	sort.Slice(articleTemplateConfigs, func(i, j int) bool { return articleTemplateConfigs[i].ID < articleTemplateConfigs[j].ID })
	articleTemplateRecommendations := append([]articleTemplateRecommendationDef(nil), uc.ArticleTemplateRecommendations...)
	sort.Slice(articleTemplateRecommendations, func(i, j int) bool {
		return articleTemplateRecommendations[i].CategoryID < articleTemplateRecommendations[j].CategoryID
	})
	articlePaperThemeOptions := append([]articlePaperThemeOptionDef(nil), uc.ArticleDarkPaperThemes.ReadingSettingOptions...)
	articleDarkPaperThemes := append([]articlePaperThemeDef(nil), uc.ArticleDarkPaperThemes.Themes...)
	sort.Slice(articleDarkPaperThemes, func(i, j int) bool { return articleDarkPaperThemes[i].ID < articleDarkPaperThemes[j].ID })

	b.WriteString("// ignore: avoid_classes_with_only_static_members\n")
	b.WriteString("class ContentUIConfig {\n")
	b.WriteString("  const ContentUIConfig._();\n\n")

	b.WriteString("  static const List<HomeChannelConfig> homeChannels = <HomeChannelConfig>[\n")
	for _, ch := range uc.HomeChannels {
		b.WriteString(fmt.Sprintf("    HomeChannelConfig(id: %s, labelKey: %s, template: %s, layoutTemplate: %s, phoneColumns: %d, supportsFullSpanModules: %t, intersectionModulePolicy: %s, contentCardPolicy: %s, feedQuery: %s, moodCopyKey: %s, order: %d),\n",
			dartStringLiteral(ch.ID),
			dartStringLiteral(ch.LabelKey),
			dartStringLiteral(ch.Template),
			dartStringLiteral(ch.LayoutTemplate),
			ch.PhoneColumns,
			ch.SupportsFullSpanModules,
			dartStringLiteral(ch.IntersectionModulePolicy),
			dartStringLiteral(ch.ContentCardPolicy),
			feedQueryDartLiteral(ch.FeedQuery),
			dartStringLiteral(ch.MoodCopyKey),
			ch.Order))
	}
	b.WriteString("  ];\n\n")

	b.WriteString("  static const List<DiscoveryTabConfig> discoveryTabs = <DiscoveryTabConfig>[\n")
	for _, tab := range tabs {
		b.WriteString(fmt.Sprintf("    DiscoveryTabConfig(id: %s, labelKey: %s, icon: %s, contentType: %s, layout: %s),\n",
			dartStringLiteral(tab.ID),
			dartStringLiteral(tab.LabelKey),
			dartStringLiteral(tab.Icon),
			dartStringLiteral(tab.ContentType),
			dartStringLiteral(tab.Layout)))
	}
	b.WriteString("  ];\n\n")

	b.WriteString("  static const List<DiscoveryRailConfig> discoveryRails = <DiscoveryRailConfig>[\n")
	for _, rail := range rails {
		b.WriteString(fmt.Sprintf("    DiscoveryRailConfig(id: %s, labelKey: %s, identity: %s, isDefault: %v),\n",
			dartStringLiteral(rail.ID),
			dartStringLiteral(rail.LabelKey),
			dartStringLiteral(rail.Identity),
			rail.Default))
	}
	b.WriteString("  ];\n\n")

	b.WriteString("  static const List<IdentityFilterConfig> creationIdentityFilters = <IdentityFilterConfig>[\n")
	for _, filter := range identityFilters {
		b.WriteString(fmt.Sprintf("    IdentityFilterConfig(id: %s, labelKey: %s, identity: %s),\n",
			dartStringLiteral(filter.ID),
			dartStringLiteral(filter.LabelKey),
			dartStringOrNull(filter.Identity)))
	}
	b.WriteString("  ];\n\n")

	b.WriteString("  static const List<WorkFormatFilterConfig> workFormatFilters = <WorkFormatFilterConfig>[\n")
	for _, filter := range workFormatFilters {
		b.WriteString(fmt.Sprintf("    WorkFormatFilterConfig(id: %s, labelKey: %s, contentType: %s),\n",
			dartStringLiteral(filter.ID),
			dartStringLiteral(filter.LabelKey),
			dartStringOrNull(filter.ContentType)))
	}
	b.WriteString("  ];\n\n")

	b.WriteString("  static const List<ShareTemplateProfileConfig> shareTemplateProfiles = <ShareTemplateProfileConfig>[\n")
	for _, profile := range shareProfiles {
		b.WriteString(fmt.Sprintf("    ShareTemplateProfileConfig(id: %s, titleKey: %s, subtitleKey: %s, layout: %s, coverStrategy: %s, includeAuthor: %v, includeTimeContext: %v, includeCircleContext: %v, includeTags: %v),\n",
			dartStringLiteral(profile.ID),
			dartStringLiteral(profile.TitleKey),
			dartStringLiteral(profile.SubtitleKey),
			dartStringLiteral(profile.Layout),
			dartStringLiteral(profile.CoverStrategy),
			profile.IncludeAuthor,
			profile.IncludeTimeContext,
			profile.IncludeCircleContext,
			profile.IncludeTags))
	}
	b.WriteString("  ];\n\n")

	b.WriteString("  static const List<ArticleDistributionProfileConfig> articleDistributionProfiles = <ArticleDistributionProfileConfig>[\n")
	for _, profile := range articleDistributionProfiles {
		b.WriteString(fmt.Sprintf("    ArticleDistributionProfileConfig(id: %s, surface: %s, layout: %s, coverMode: %s, summaryLineLimit: %d),\n",
			dartStringLiteral(profile.ID),
			dartStringLiteral(profile.Surface),
			dartStringLiteral(profile.Layout),
			dartStringLiteral(profile.CoverMode),
			profile.SummaryLineLimit))
	}
	b.WriteString("  ];\n\n")

	b.WriteString("  static const List<ArticleReaderProfileConfig> articleReaderProfiles = <ArticleReaderProfileConfig>[\n")
	for _, profile := range articleReaderProfiles {
		b.WriteString(fmt.Sprintf("    ArticleReaderProfileConfig(id: %s, stageLayout: %s, pageIndicatorAnchor: %s, edgeTreatment: %s, supportsPageCurl: %v),\n",
			dartStringLiteral(profile.ID),
			dartStringLiteral(profile.StageLayout),
			dartStringLiteral(profile.PageIndicatorAnchor),
			dartStringLiteral(profile.EdgeTreatment),
			profile.SupportsPageCurl))
	}
	b.WriteString("  ];\n\n")

	b.WriteString("  static const List<ArticleTemplateConfig> articleTemplateConfigs = <ArticleTemplateConfig>[\n")
	for _, config := range articleTemplateConfigs {
		b.WriteString(fmt.Sprintf("    ArticleTemplateConfig(id: %s, defaultFontPreset: %s, paperTexture: %s, decorationStyle: %s, chromeStyle: %s),\n",
			dartStringLiteral(config.ID),
			dartStringLiteral(config.DefaultFontPreset),
			dartStringLiteral(config.PaperTexture),
			dartStringLiteral(config.DecorationStyle),
			dartStringLiteral(config.ChromeStyle)))
	}
	b.WriteString("  ];\n\n")

	b.WriteString("  static const List<ArticleTemplateRecommendationConfig> articleTemplateRecommendations = <ArticleTemplateRecommendationConfig>[\n")
	for _, recommendation := range articleTemplateRecommendations {
		b.WriteString(fmt.Sprintf("    ArticleTemplateRecommendationConfig(categoryId: %s, recommendedArticleTemplates: <String>[",
			dartStringLiteral(recommendation.CategoryID)))
		for i, templateID := range recommendation.RecommendedArticleTemplates {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(dartStringLiteral(templateID))
		}
		b.WriteString("]),\n")
	}
	b.WriteString("  ];\n\n")

	b.WriteString(fmt.Sprintf("  static const String articleDarkPaperDefaultTheme = %s;\n\n",
		dartStringLiteral(uc.ArticleDarkPaperThemes.DefaultTheme)))

	b.WriteString("  static const List<ArticlePaperThemeOptionConfig> articlePaperThemeOptions = <ArticlePaperThemeOptionConfig>[\n")
	for _, option := range articlePaperThemeOptions {
		b.WriteString(fmt.Sprintf("    ArticlePaperThemeOptionConfig(id: %s, labelKey: %s),\n",
			dartStringLiteral(option.ID),
			dartStringLiteral(option.LabelKey)))
	}
	b.WriteString("  ];\n\n")

	b.WriteString("  static const Map<String, String> articlePaperVerticalDefaults = <String, String>{\n")
	verticalKeys := make([]string, 0, len(uc.ArticleDarkPaperThemes.VerticalDefaults))
	for k := range uc.ArticleDarkPaperThemes.VerticalDefaults {
		verticalKeys = append(verticalKeys, k)
	}
	sort.Strings(verticalKeys)
	for _, k := range verticalKeys {
		b.WriteString(fmt.Sprintf("    %s: %s,\n",
			dartStringLiteral(k),
			dartStringLiteral(uc.ArticleDarkPaperThemes.VerticalDefaults[k])))
	}
	b.WriteString("  };\n\n")

	b.WriteString("  static const List<ArticleDarkPaperThemeConfig> articleDarkPaperThemes = <ArticleDarkPaperThemeConfig>[\n")
	for _, theme := range articleDarkPaperThemes {
		b.WriteString(fmt.Sprintf("    ArticleDarkPaperThemeConfig(id: %s, stage: %s, paper: %s, text: %s, secondaryText: %s),\n",
			dartStringLiteral(theme.ID),
			dartStringLiteral(theme.Stage),
			dartStringLiteral(theme.Paper),
			dartStringLiteral(theme.Text),
			dartStringLiteral(theme.SecondaryText)))
	}
	b.WriteString("  ];\n\n")

	b.WriteString("  static const Map<String, bool> featureFlags = <String, bool>{\n")
	flags := make([]featureFlagDef, len(uc.FeatureFlags))
	copy(flags, uc.FeatureFlags)
	sort.Slice(flags, func(i, j int) bool { return flags[i].Flag < flags[j].Flag })
	for _, ff := range flags {
		b.WriteString(fmt.Sprintf("    '%s': %v,\n", ff.Flag, ff.Default))
	}
	b.WriteString("  };\n\n")

	if len(uc.EmptyStates) > 0 {
		b.WriteString("  static const Map<String, Map<String, String>> emptyStates = <String, Map<String, String>>{\n")
		esKeys := make([]string, 0, len(uc.EmptyStates))
		for k := range uc.EmptyStates {
			esKeys = append(esKeys, k)
		}
		sort.Strings(esKeys)
		for _, k := range esKeys {
			es := uc.EmptyStates[k]
			b.WriteString(fmt.Sprintf("    '%s': <String, String>{\n", k))
			if es.TitleKey != "" {
				b.WriteString(fmt.Sprintf("      'titleKey': '%s',\n", es.TitleKey))
			}
			if es.SubtitleKey != "" {
				b.WriteString(fmt.Sprintf("      'subtitleKey': '%s',\n", es.SubtitleKey))
			}
			if es.CTALabelKey != "" {
				b.WriteString(fmt.Sprintf("      'ctaKey': '%s',\n", es.CTALabelKey))
			}
			b.WriteString("    },\n")
		}
		b.WriteString("  };\n")
	}

	b.WriteString("}\n")
	return b.String()
}
