package main

import (
	"fmt"
	"strings"
)

func renderContentErrorsDart(ef *errorsFile) string {
	var b strings.Builder
	b.WriteString("// Code generated by tools/codegen_app_metadata from content/post/errors.yaml. DO NOT EDIT.\n")
	b.WriteString("// ignore_for_file: constant_identifier_names\n\n")

	// Enum values
	b.WriteString("enum ContentErrorCode {\n")
	for _, e := range ef.Errors {
		b.WriteString(fmt.Sprintf("  %s,\n", e.DartConst))
	}
	b.WriteString("  unknown;\n\n")

	// fromCode factory
	b.WriteString("  static ContentErrorCode fromCode(String code) {\n")
	b.WriteString("    switch (code) {\n")
	for _, e := range ef.Errors {
		b.WriteString(fmt.Sprintf("      case '%s':\n        return ContentErrorCode.%s;\n", e.Code, e.DartConst))
	}
	b.WriteString("      default:\n        return ContentErrorCode.unknown;\n")
	b.WriteString("    }\n")
	b.WriteString("  }\n")
	b.WriteString("}\n\n")

	// ContentErrorMessages
	b.WriteString("// ignore: avoid_classes_with_only_static_members\n")
	b.WriteString("class ContentErrorMessages {\n")
	b.WriteString("  const ContentErrorMessages._();\n\n")

	// zh messages
	b.WriteString("  static const Map<ContentErrorCode, String> zh = <ContentErrorCode, String>{\n")
	for _, e := range ef.Errors {
		if msg, ok := e.UserMessage["zh"]; ok {
			b.WriteString(fmt.Sprintf("    ContentErrorCode.%s: '%s',\n", e.DartConst, strings.ReplaceAll(msg, "'", "\\'")))
		}
	}
	b.WriteString("  };\n\n")

	// en messages
	b.WriteString("  static const Map<ContentErrorCode, String> en = <ContentErrorCode, String>{\n")
	for _, e := range ef.Errors {
		if msg, ok := e.UserMessage["en"]; ok {
			b.WriteString(fmt.Sprintf("    ContentErrorCode.%s: '%s',\n", e.DartConst, strings.ReplaceAll(msg, "'", "\\'")))
		}
	}
	b.WriteString("  };\n")
	b.WriteString("}\n")

	return b.String()
}

func renderChatErrorsDart(ef *errorsFile) string {
	var b strings.Builder
	b.WriteString("// Code generated by tools/codegen_app_metadata from messages/conversation/errors.yaml. DO NOT EDIT.\n")
	b.WriteString("// ignore_for_file: constant_identifier_names\n\n")

	b.WriteString("enum ChatErrorCode {\n")
	for _, e := range ef.Errors {
		b.WriteString(fmt.Sprintf("  %s('%s', '%s', %d),\n", e.DartConst, e.Code, strings.ReplaceAll(e.UserMessage["zh"], "'", "\\'"), e.HTTPStatus))
	}
	b.WriteString("  unknown('', '消息服务异常，请稍后重试', 500);\n\n")

	b.WriteString("  final String code;\n")
	b.WriteString("  final String defaultMessage;\n")
	b.WriteString("  final int httpStatus;\n\n")
	b.WriteString("  const ChatErrorCode(this.code, this.defaultMessage, this.httpStatus);\n\n")
	b.WriteString("  static ChatErrorCode fromCode(String code) {\n")
	b.WriteString("    for (final value in values) {\n")
	b.WriteString("      if (value.code == code) return value;\n")
	b.WriteString("    }\n")
	b.WriteString("    return ChatErrorCode.unknown;\n")
	b.WriteString("  }\n")
	b.WriteString("}\n\n")

	b.WriteString("// ignore: avoid_classes_with_only_static_members\n")
	b.WriteString("class ChatErrorMessages {\n")
	b.WriteString("  const ChatErrorMessages._();\n\n")
	b.WriteString("  static const Map<ChatErrorCode, String> zh = <ChatErrorCode, String>{\n")
	for _, e := range ef.Errors {
		if msg, ok := e.UserMessage["zh"]; ok {
			b.WriteString(fmt.Sprintf("    ChatErrorCode.%s: '%s',\n", e.DartConst, strings.ReplaceAll(msg, "'", "\\'")))
		}
	}
	b.WriteString("  };\n\n")
	b.WriteString("  static const Map<ChatErrorCode, String> en = <ChatErrorCode, String>{\n")
	for _, e := range ef.Errors {
		if msg, ok := e.UserMessage["en"]; ok {
			b.WriteString(fmt.Sprintf("    ChatErrorCode.%s: '%s',\n", e.DartConst, strings.ReplaceAll(msg, "'", "\\'")))
		}
	}
	b.WriteString("  };\n")
	b.WriteString("}\n")

	return b.String()
}

// renderSimpleErrorsDart 生成一个 *ErrorCode Dart enum + *ErrorMessages 文案表，
// 模式与 renderChatErrorsDart 完全一致，抽成通用渲染以避免每个客户端域复制一份
// （军规 R25：横切关注提取统一抽象）。enumName 形如 "AssistantErrorCode"，
// unknownMessage 是 unknown 兜底的 zh 文案。
func renderSimpleErrorsDart(enumName, sourcePath, unknownMessage string, ef *errorsFile) string {
	var b strings.Builder
	messagesClass := strings.TrimSuffix(enumName, "Code") + "Messages"
	b.WriteString(fmt.Sprintf("// Code generated by tools/codegen_app_metadata from %s. DO NOT EDIT.\n", sourcePath))
	b.WriteString("// ignore_for_file: constant_identifier_names\n\n")

	b.WriteString(fmt.Sprintf("enum %s {\n", enumName))
	for _, e := range ef.Errors {
		if e.DartConst == "" {
			continue
		}
		b.WriteString(fmt.Sprintf("  %s('%s', '%s', %d),\n", e.DartConst, e.Code, strings.ReplaceAll(e.UserMessage["zh"], "'", "\\'"), e.HTTPStatus))
	}
	b.WriteString(fmt.Sprintf("  unknown('', '%s', 500);\n\n", strings.ReplaceAll(unknownMessage, "'", "\\'")))

	b.WriteString("  final String code;\n")
	b.WriteString("  final String defaultMessage;\n")
	b.WriteString("  final int httpStatus;\n\n")
	b.WriteString(fmt.Sprintf("  const %s(this.code, this.defaultMessage, this.httpStatus);\n\n", enumName))
	b.WriteString(fmt.Sprintf("  static %s fromCode(String code) {\n", enumName))
	b.WriteString("    for (final value in values) {\n")
	b.WriteString("      if (value.code == code) return value;\n")
	b.WriteString("    }\n")
	b.WriteString(fmt.Sprintf("    return %s.unknown;\n", enumName))
	b.WriteString("  }\n")
	b.WriteString("}\n\n")

	b.WriteString("// ignore: avoid_classes_with_only_static_members\n")
	b.WriteString(fmt.Sprintf("class %s {\n", messagesClass))
	b.WriteString(fmt.Sprintf("  const %s._();\n\n", messagesClass))
	b.WriteString(fmt.Sprintf("  static const Map<%s, String> zh = <%s, String>{\n", enumName, enumName))
	for _, e := range ef.Errors {
		if e.DartConst == "" {
			continue
		}
		if msg, ok := e.UserMessage["zh"]; ok {
			b.WriteString(fmt.Sprintf("    %s.%s: '%s',\n", enumName, e.DartConst, strings.ReplaceAll(msg, "'", "\\'")))
		}
	}
	b.WriteString("  };\n\n")
	b.WriteString(fmt.Sprintf("  static const Map<%s, String> en = <%s, String>{\n", enumName, enumName))
	for _, e := range ef.Errors {
		if e.DartConst == "" {
			continue
		}
		if msg, ok := e.UserMessage["en"]; ok {
			b.WriteString(fmt.Sprintf("    %s.%s: '%s',\n", enumName, e.DartConst, strings.ReplaceAll(msg, "'", "\\'")))
		}
	}
	b.WriteString("  };\n")
	b.WriteString("}\n")

	return b.String()
}

func renderUserErrorsDart(ef *errorsFile) string {
	var b strings.Builder
	b.WriteString("// Code generated by tools/codegen_app_metadata from user/**/errors.yaml. DO NOT EDIT.\n")
	b.WriteString("// ignore_for_file: constant_identifier_names\n\n")
	b.WriteString("enum UserErrorCode {\n")
	for _, e := range ef.Errors {
		if e.DartConst == "" {
			continue
		}
		msg := strings.ReplaceAll(goErrorUserMessage(e), "\\", "\\\\")
		msg = strings.ReplaceAll(msg, "'", "\\'")
		b.WriteString(fmt.Sprintf("  %s('%s', '%s', %d),\n", e.DartConst, e.Code, msg, e.HTTPStatus))
	}
	b.WriteString(";\n\n")
	b.WriteString("  final String code;\n")
	b.WriteString("  final String defaultMessage;\n")
	b.WriteString("  final int httpStatus;\n\n")
	b.WriteString("  const UserErrorCode(this.code, this.defaultMessage, this.httpStatus);\n\n")
	b.WriteString("  static UserErrorCode? fromCode(String code) {\n")
	b.WriteString("    for (final e in values) {\n")
	b.WriteString("      if (e.code == code) return e;\n")
	b.WriteString("    }\n")
	b.WriteString("    return null;\n")
	b.WriteString("  }\n")
	b.WriteString("}\n")
	return b.String()
}

type goErrorsFileOptions struct {
	sourcePath   string
	commentLines []string
	extraImports []string
	trailer      string
}

func goErrorHelperName(goConst string) string {
	if strings.HasPrefix(goConst, "Err") {
		return "AppErrorFrom" + goConst[3:]
	}
	return "AppErrorFrom" + goConst
}

func goErrorUserMessage(e errorDef) string {
	msg := e.UserMessage["zh"]
	if msg == "" {
		msg = e.UserMessage["en"]
	}
	if msg == "" {
		msg = "请稍后重试"
	}
	return msg
}

// goErrorRecoveryCall 据 errors.yaml 的 recovery_action / recovery_after_seconds
// 生成 .WithRecovery(...) 链式调用；未声明 recovery_action 时返回空串，由 runtime 按
// kind/reason 静态推导默认恢复指令。
func goErrorRecoveryCall(e errorDef) string {
	action := strings.TrimSpace(e.RecoveryAction)
	if action == "" {
		return ""
	}
	return fmt.Sprintf(".WithRecovery(%q, %d)", action, e.RecoveryAfterSecs)
}

func renderGoErrorsFile(ef *errorsFile, opts goErrorsFileOptions) string {
	var b strings.Builder
	b.WriteString(fmt.Sprintf("// Code generated by tools/codegen_app_metadata from %s. DO NOT EDIT.\n", opts.sourcePath))
	b.WriteString("package generated\n\n")
	b.WriteString("import (\n")
	for _, imp := range opts.extraImports {
		b.WriteString(fmt.Sprintf("\t%q\n", imp))
	}
	b.WriteString("\t\"errors\"\n\n")
	b.WriteString("\trerrors \"quwoquan_service/runtime/errors\"\n")
	b.WriteString(")\n\n")
	for _, line := range opts.commentLines {
		b.WriteString("// " + line + "\n")
	}
	b.WriteString("//\n//nolint:gochecknoglobals\n")
	b.WriteString("var (\n")
	for _, e := range ef.Errors {
		if e.GoConst == "" {
			continue
		}
		b.WriteString(fmt.Sprintf("\t%s = errors.New(%q)\n", e.GoConst, e.Code))
	}
	b.WriteString(")\n\n")
	for _, e := range ef.Errors {
		if e.GoConst == "" {
			continue
		}
		funcName := goErrorHelperName(e.GoConst)
		b.WriteString(fmt.Sprintf("// %s returns *AppError for %s (user_message from errors.yaml).\n", funcName, e.Code))
		b.WriteString(fmt.Sprintf("func %s(debugMessage string) *rerrors.AppError {\n", funcName))
		b.WriteString(fmt.Sprintf("\tcode, _ := rerrors.ParseCode(string(%s.Error()))\n", e.GoConst))
		b.WriteString(fmt.Sprintf("\treturn rerrors.NewAppError(code, %q, debugMessage)%s\n", goErrorUserMessage(e), goErrorRecoveryCall(e)))
		b.WriteString("}\n\n")
	}
	if opts.trailer != "" {
		b.WriteString(opts.trailer)
		if !strings.HasSuffix(opts.trailer, "\n") {
			b.WriteString("\n")
		}
	}
	return b.String()
}

func renderChatErrorsGo(ef *errorsFile) string {
	return renderGoErrorsFile(ef, goErrorsFileOptions{
		sourcePath:   "messages/conversation/errors.yaml",
		commentLines: []string{"Chat error sentinels and helpers. user_message from errors.yaml user_message.zh."},
	})
}

func renderUserGreetingErrorsGo(ef *errorsFile) string {
	return renderGoErrorsFile(ef, goErrorsFileOptions{
		sourcePath:   "user/greeting_request/errors.yaml",
		commentLines: []string{"Greeting request error sentinels and helpers. user_message from errors.yaml user_message.zh."},
	})
}

func renderUserErrorsGo(ef *errorsFile) string {
	return renderGoErrorsFile(ef, goErrorsFileOptions{
		sourcePath:   "user/**/errors.yaml",
		commentLines: []string{"User domain error sentinels and helpers. user_message from errors.yaml user_message.zh."},
	})
}

// renderIntegrationLocationErrorsDart 生成 IntegrationLocationErrorCode + IntegrationLocationErrorMessages
// code 与 enum 双向可转换，toDisplayMessage 使用 l10n_key 映射到 AppLocalizations
func renderIntegrationLocationErrorsDart(ef *errorsFile) string {
	var b strings.Builder
	b.WriteString("// Code generated by tools/codegen_app_metadata from integration/location/errors.yaml. DO NOT EDIT.\n")
	b.WriteString("// ignore_for_file: constant_identifier_names\n\n")

	b.WriteString("import 'package:quwoquan_app/l10n/l10n.dart';\n\n")

	b.WriteString("enum IntegrationLocationErrorCode {\n")
	for _, e := range ef.Errors {
		b.WriteString(fmt.Sprintf("  %s,\n", e.DartConst))
	}
	b.WriteString("  unknown;\n\n")

	b.WriteString("  /// 枚举对应的云端错误码字符串，与 fromCode 互为逆变换\n")
	b.WriteString("  String get code {\n")
	b.WriteString("    switch (this) {\n")
	for _, e := range ef.Errors {
		b.WriteString(fmt.Sprintf("      case IntegrationLocationErrorCode.%s:\n        return '%s';\n", e.DartConst, e.Code))
	}
	b.WriteString("      case IntegrationLocationErrorCode.unknown:\n        return '';\n")
	b.WriteString("    }\n")
	b.WriteString("  }\n\n")

	b.WriteString("  /// 从云端 code 字符串解析为枚举\n")
	b.WriteString("  static IntegrationLocationErrorCode fromCode(String? code) {\n")
	b.WriteString("    switch (code) {\n")
	for _, e := range ef.Errors {
		b.WriteString(fmt.Sprintf("      case '%s':\n        return IntegrationLocationErrorCode.%s;\n", e.Code, e.DartConst))
	}
	b.WriteString("      default:\n        return IntegrationLocationErrorCode.unknown;\n")
	b.WriteString("    }\n")
	b.WriteString("  }\n\n")

	b.WriteString("  /// 映射到 AppLocalizations 展示文案（使用 errors.yaml 中 l10n_key）\n")
	b.WriteString("  String toDisplayMessage(AppLocalizations l10n) {\n")
	b.WriteString("    switch (this) {\n")
	l10nFallback := "locationLoadFailed"
	for _, e := range ef.Errors {
		key := e.L10nKey
		if key == "" {
			key = l10nFallback
		}
		b.WriteString(fmt.Sprintf("      case IntegrationLocationErrorCode.%s:\n        return l10n.%s;\n", e.DartConst, key))
	}
	b.WriteString("      case IntegrationLocationErrorCode.unknown:\n        return l10n.locationLoadFailed;\n")
	b.WriteString("    }\n")
	b.WriteString("  }\n")
	b.WriteString("}\n\n")

	b.WriteString("// ignore: avoid_classes_with_only_static_members\n")
	b.WriteString("class IntegrationLocationErrorMessages {\n")
	b.WriteString("  const IntegrationLocationErrorMessages._();\n\n")
	b.WriteString("  static const Map<IntegrationLocationErrorCode, String> zh = <IntegrationLocationErrorCode, String>{\n")
	for _, e := range ef.Errors {
		if msg, ok := e.UserMessage["zh"]; ok {
			b.WriteString(fmt.Sprintf("    IntegrationLocationErrorCode.%s: '%s',\n", e.DartConst, strings.ReplaceAll(msg, "'", "\\'")))
		}
	}
	b.WriteString("  };\n\n")
	b.WriteString("  static const Map<IntegrationLocationErrorCode, String> en = <IntegrationLocationErrorCode, String>{\n")
	for _, e := range ef.Errors {
		if msg, ok := e.UserMessage["en"]; ok {
			b.WriteString(fmt.Sprintf("    IntegrationLocationErrorCode.%s: '%s',\n", e.DartConst, strings.ReplaceAll(msg, "'", "\\'")))
		}
	}
	b.WriteString("  };\n")
	b.WriteString("}\n")
	return b.String()
}

// renderIntegrationLocationErrorsGo 从 errors.yaml 生成 integration-service errors.go
// Err* 哨兵 + AppErrorFrom*(debugMessage)，user_message 取 user_message.zh，code 与 message 均来自 metadata
func renderIntegrationLocationErrorsGo(ef *errorsFile) string {
	return renderGoErrorsFile(ef, goErrorsFileOptions{
		sourcePath:   "integration/location/errors.yaml",
		commentLines: []string{"Integration location error sentinels and helpers.", "user_message from errors.yaml user_message.zh"},
		extraImports: []string{"context"},
		trailer: `// IsTimeout returns true if err is context.DeadlineExceeded or contains upstream timeout semantics.
func IsTimeout(err error) bool {
	return errors.Is(err, context.DeadlineExceeded)
}
`,
	})
}

// renderRtcErrorsDart 从 rtc/call_session/errors.yaml 生成 RtcErrorCode enum。
// 形状与既有手维护产物对齐（code/defaultMessage/httpStatus + fromCode + isUser/isSystem），
// 但改为唯一真相源驱动，杜绝旧关系门禁 / blocked 等漂移。
func renderRtcErrorsDart(ef *errorsFile) string {
	var b strings.Builder
	b.WriteString("// Code generated by tools/codegen_app_metadata from rtc/call_session/errors.yaml. DO NOT EDIT.\n")
	b.WriteString("// ignore_for_file: constant_identifier_names\n\n")
	b.WriteString("enum RtcErrorCode {\n")
	last := len(ef.Errors) - 1
	for i, e := range ef.Errors {
		if e.DartConst == "" {
			continue
		}
		msg := strings.ReplaceAll(e.UserMessage["zh"], "\\", "\\\\")
		msg = strings.ReplaceAll(msg, "'", "\\'")
		sep := ","
		if i == last {
			sep = ";"
		}
		b.WriteString(fmt.Sprintf("  %s('%s', '%s', %d)%s\n", e.DartConst, e.Code, msg, e.HTTPStatus, sep))
	}
	b.WriteString("\n  final String code;\n")
	b.WriteString("  final String defaultMessage;\n")
	b.WriteString("  final int httpStatus;\n\n")
	b.WriteString("  const RtcErrorCode(this.code, this.defaultMessage, this.httpStatus);\n\n")
	b.WriteString("  static RtcErrorCode? fromCode(String code) {\n")
	b.WriteString("    for (final v in values) {\n")
	b.WriteString("      if (v.code == code) return v;\n")
	b.WriteString("    }\n")
	b.WriteString("    return null;\n")
	b.WriteString("  }\n\n")
	b.WriteString("  bool get isUserError => code.startsWith('RTC.USER.');\n\n")
	b.WriteString("  bool get isSystemError => code.startsWith('RTC.SYSTEM.');\n")
	b.WriteString("}\n")
	return b.String()
}

// renderRtcErrorsGo 从 rtc/call_session/errors.yaml 生成 rtc-service errors.go
// （Err* 哨兵 + AppErrorFrom*(debugMessage)），code/message 均来自 metadata，
// 取代 orchestrator 里手写的 rterr.NewCode(...,"中文") 旁路。
func renderRtcErrorsGo(ef *errorsFile) string {
	return renderGoErrorsFile(ef, goErrorsFileOptions{
		sourcePath:   "rtc/call_session/errors.yaml",
		commentLines: []string{"RTC error sentinels and helpers. user_message from errors.yaml user_message.zh."},
	})
}
