package main

import (
	"fmt"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// 只导出fields中的显式值根；不声明operation、port或第二份字段表。
func generateClientValues(appDir string) error {
	for _, path := range activeMetadataSource.Paths("", "/fields.yaml") {
		var document fieldsFile
		if err := activeMetadataSource.Decode(path, &document); err != nil {
			return err
		}
		text, err := renderClientValues(path, document)
		if err != nil {
			return err
		}
		if text == "" {
			continue
		}
		parts := strings.Split(path, "/")
		if len(parts) != 4 {
			return fmt.Errorf("client value owner must be domain/context/object: %s", path)
		}
		output := filepath.Join(appDir, "packages/quwoquan_cloud_contracts/lib/src/generated/values", parts[0], parts[1], parts[2]+".values.g.dart")
		writeFile(output, text)
		publicPath := filepath.Join(appDir, "packages/quwoquan_cloud_contracts/lib/generated/values", parts[0], parts[1], parts[2]+".values.dart")
		writeFile(publicPath, fmt.Sprintf("// Code generated from %s. DO NOT EDIT.\nexport 'package:quwoquan_cloud_contracts/src/generated/values/%s/%s/%s.values.g.dart';\n", path, parts[0], parts[1], parts[2]))
	}
	return nil
}

func renderClientValues(source string, document fieldsFile) (string, error) {
	models := map[string]requestModelSpec{}
	visiting := map[string]bool{}
	enums := map[string][]string{}
	var visit func(string) error
	visit = func(name string) error {
		if visiting[name] {
			return fmt.Errorf("client value cycle: %s", name)
		}
		if _, ok := models[name]; ok {
			return nil
		}
		definition, ok := document.Types[name]
		if !ok {
			return fmt.Errorf("client value dependency %s missing in %s", name, source)
		}
		visiting[name] = true
		for _, field := range definition.Fields {
			if field.Pattern != "" {
				if !strings.HasPrefix(field.Pattern, "^") || !strings.HasSuffix(field.Pattern, "$") {
					return fmt.Errorf("%s.%s pattern must be anchored", name, field.Name)
				}
				if _, err := regexp.Compile(field.Pattern); err != nil {
					return err
				}
			}
			if field.Type == "enum" {
				enum, ok := document.Enums[field.EnumRef]
				if !ok || len(enum.Values) == 0 {
					return fmt.Errorf("missing local enum %s", field.EnumRef)
				}
				enums[field.EnumRef] = enum.Values
			} else {
				dt, _, err := requestFieldDartType(field)
				if err != nil {
					return err
				}
				if dependency := requestDartModelBaseType(dt); dependency != "" && dependency != "String" && dependency != "int" && dependency != "double" && dependency != "bool" && dependency != "DateTime" {
					if err := visit(dependency); err != nil {
						return err
					}
				}
			}
		}
		visiting[name] = false
		models[name] = requestModelSpec{Name: name, Fields: definition.Fields, DerivedSource: source}
		return nil
	}
	names := make([]string, 0)
	for name, definition := range document.Types {
		if definition.ClientValue {
			names = append(names, name)
		}
	}
	sort.Strings(names)
	if len(names) == 0 {
		return "", nil
	}
	for _, name := range names {
		if err := visit(name); err != nil {
			return "", err
		}
	}
	var output, body strings.Builder
	fmt.Fprintf(&output, "// Code generated by tools/codegen_app_metadata from %s. DO NOT EDIT.\n\n", source)
	enumNames := make([]string, 0, len(enums))
	for name := range enums {
		enumNames = append(enumNames, name)
	}
	sort.Strings(enumNames)
	for _, name := range enumNames {
		members, err := canonicalRequestEnumMembers(fieldDef{Type: "enum", EnumRef: name}, enums[name])
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&output, "enum %s {", name)
		for _, member := range members {
			fmt.Fprintf(&output, " %s(%q),", member.DartMember, member.WireValue)
		}
		fmt.Fprintf(&output, "; const %s(this.wireName); final String wireName; }\n\n", name)
	}
	names = names[:0]
	for name := range models {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		if err := renderRequestModel(&body, models[name], enums); err != nil {
			return "", err
		}
	}
	writeGeneratedRequestWireDecoderHelpers(&output, body.String())
	output.WriteString(body.String())
	return output.String(), nil
}
