package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

type rtcClientRequestWireFile struct {
	Version                int                       `yaml:"version"`
	FieldTypes             map[string]string         `yaml:"field_types"`
	OmitIfNullByOperation  map[string][]string       `yaml:"omit_if_null_by_operation"`
}

func readRtcClientRequestWire(path string) (*rtcClientRequestWireFile, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var out rtcClientRequestWireFile
	if err := yaml.Unmarshal(raw, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

func rtcWireDartType(wireType string) (dart string, isList bool) {
	switch wireType {
	case "string":
		return "String", false
	case "int":
		return "int", false
	case "bool":
		return "bool", false
	case "list_string":
		return "List<String>", false
	default:
		return "Object?", false
	}
}

func rtcWireToJsonEntry(jsonKey, dartField, wireType string, omitIfNull bool) string {
	switch wireType {
	case "list_string":
		return fmt.Sprintf("      '%s': %s,\n", jsonKey, dartField)
	case "string":
		if omitIfNull {
			return fmt.Sprintf("      if (%s != null) '%s': %s,\n", dartField, jsonKey, dartField)
		}
		return fmt.Sprintf("      '%s': %s,\n", jsonKey, dartField)
	case "int", "bool":
		return fmt.Sprintf("      '%s': %s,\n", jsonKey, dartField)
	default:
		return fmt.Sprintf("      '%s': %s,\n", jsonKey, dartField)
	}
}

func writeRtcRequestWires(appDir, metadataDir string) error {
	svcPath := filepath.Join(metadataDir, "rtc", "call_session", "service.yaml")
	wirePath := filepath.Join(metadataDir, "rtc", "call_session", "client_request_wire.yaml")
	svc, err := readService(svcPath)
	if err != nil {
		return fmt.Errorf("rtc request wires read service: %w", err)
	}
	wf, err := readRtcClientRequestWire(wirePath)
	if err != nil {
		return fmt.Errorf("rtc request wires read client_request_wire: %w", err)
	}
	out := renderRtcRequestWiresDart(svcPath, wirePath, svc, wf)
	outPath := filepath.Join(appDir, "lib", "cloud", "runtime", "generated", "rtc", "rtc_request_wires.g.dart")
	writeFile(outPath, out)
	return nil
}

func renderRtcRequestWiresDart(serviceSource, wireSource string, svc *serviceFile, wf *rtcClientRequestWireFile) string {
	var b strings.Builder
	b.WriteString("// Code generated by tools/codegen_app_metadata from rtc/call_session/service.yaml + client_request_wire.yaml. DO NOT EDIT.\n")
	b.WriteString("// Sources: ")
	b.WriteString(filepath.ToSlash(serviceSource))
	b.WriteString(", ")
	b.WriteString(filepath.ToSlash(wireSource))
	b.WriteString("\n// ignore_for_file: prefer_const_constructors\n\n")

	omitMap := wf.OmitIfNullByOperation
	if omitMap == nil {
		omitMap = map[string][]string{}
	}

	for _, r := range svc.APIRoutes {
		if len(r.RequestFields) == 0 {
			continue
		}
		op := strings.TrimSpace(r.Operation)
		if op == "" {
			continue
		}
		className := "Rtc" + op + "RequestWire"
		b.WriteString(fmt.Sprintf("/// HTTP body for `%s` (%s %s).\n", op, r.Method, r.Path))
		b.WriteString(fmt.Sprintf("class %s {\n", className))
		b.WriteString(fmt.Sprintf("  const %s({\n", className))

		omitSet := map[string]bool{}
		for _, k := range omitMap[op] {
			omitSet[k] = true
		}

		for _, fname := range r.RequestFields {
			_, ok := wf.FieldTypes[fname]
			if !ok {
				panic(fmt.Sprintf("rtc request wire: missing field_types for %q (operation %s)", fname, op))
			}
			if omitSet[fname] {
				b.WriteString(fmt.Sprintf("    this.%s,\n", fname))
				continue
			}
			b.WriteString(fmt.Sprintf("    required this.%s,\n", fname))
		}
		b.WriteString("  });\n\n")

		for _, fname := range r.RequestFields {
			wt := wf.FieldTypes[fname]
			dt, _ := rtcWireDartType(wt)
			if omitSet[fname] && wt == "string" {
				dt = "String?"
			}
			b.WriteString(fmt.Sprintf("  final %s %s;\n", dt, fname))
		}

		b.WriteString("\n  Map<String, dynamic> toJson() {\n")
		b.WriteString("    return {\n")
		for _, fname := range r.RequestFields {
			wt := wf.FieldTypes[fname]
			omit := omitSet[fname] && wt == "string"
			b.WriteString(rtcWireToJsonEntry(fname, fname, wt, omit))
		}
		b.WriteString("    };\n  }\n}\n\n")
	}

	b.WriteString("/// Empty JSON body for RTC POST routes with no fields.\n")
	b.WriteString("class RtcEmptyPostBody {\n")
	b.WriteString("  const RtcEmptyPostBody();\n\n")
	b.WriteString("  Map<String, dynamic> toJson() => const <String, dynamic>{};\n")
	b.WriteString("}\n")

	return b.String()
}
