package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type homepageTabDef struct {
	ID       string `yaml:"id"`
	LabelKey string `yaml:"label_key"`
	BodySlot string `yaml:"body_slot"`
	Order    int    `yaml:"order"`
	Default  bool   `yaml:"default"`
}

type circleTabDef struct {
	ID           string   `yaml:"id"`
	LabelKey     string   `yaml:"label_key"`
	BodySlot     string   `yaml:"body_slot"`
	SectionTypes []string `yaml:"section_types"`
	Order        int      `yaml:"order"`
	Default      bool     `yaml:"default"`
}

type circleSectionDef struct {
	SectionType string `yaml:"section_type"`
	LabelKey    string `yaml:"label_key"`
	Icon        string `yaml:"icon"`
	TabID       string `yaml:"tab_id"`
	Order       int    `yaml:"order"`
}

func writeEntityCircleUIConfigs(metadataDir string, appDir string) {
	homepageUIDir := filepath.Join(metadataDir, "entity", "homepage")
	homepageUIDef, homepageUIErr := readUIConfig(filepath.Join(homepageUIDir, "ui_config.yaml"))
	if homepageUIErr != nil && !os.IsNotExist(homepageUIErr) {
		exitErr(fmt.Errorf("read entity/homepage/ui_config.yaml: %w", homepageUIErr))
	}
	if homepageUIDef != nil {
		out := renderHomepageUIConfigDart(homepageUIDef)
		writeFile(filepath.Join(appDir, "lib", "cloud", "runtime", "generated", "entity", "homepage_ui_config.g.dart"), out)
	}
	circleUIDir := filepath.Join(metadataDir, "social", "circle")
	circleUIDef, circleUIErr := readUIConfig(filepath.Join(circleUIDir, "ui_config.yaml"))
	if circleUIErr != nil && !os.IsNotExist(circleUIErr) {
		exitErr(fmt.Errorf("read social/circle/ui_config.yaml: %w", circleUIErr))
	}
	if circleUIDef != nil {
		out := renderCircleUIConfigDart(circleUIDef)
		writeFile(filepath.Join(appDir, "lib", "cloud", "runtime", "generated", "circle", "circle_ui_config.g.dart"), out)
	}
}

func renderHomepageUIConfigDart(uc *uiConfigFile) string {
	var b strings.Builder
	b.WriteString("// Code generated by tools/codegen_app_metadata from entity/homepage/ui_config.yaml. DO NOT EDIT.\n")
	b.WriteString("// ignore_for_file: prefer_const_constructors\n\n")
	b.WriteString("class HomepageTabConfig {\n")
	b.WriteString("  final String id;\n")
	b.WriteString("  final String labelKey;\n")
	b.WriteString("  final String bodySlot;\n")
	b.WriteString("  final bool isDefault;\n\n")
	b.WriteString("  const HomepageTabConfig({\n")
	b.WriteString("    required this.id,\n")
	b.WriteString("    required this.labelKey,\n")
	b.WriteString("    required this.bodySlot,\n")
	b.WriteString("    required this.isDefault,\n")
	b.WriteString("  });\n")
	b.WriteString("}\n\n")
	tabs := append([]homepageTabDef(nil), uc.HomepageTabs...)
	sort.Slice(tabs, func(i, j int) bool { return tabs[i].Order < tabs[j].Order })
	defaultTabID := "content"
	for _, tab := range tabs {
		if tab.Default {
			defaultTabID = tab.ID
			break
		}
	}
	if len(tabs) > 0 && strings.TrimSpace(defaultTabID) == "" {
		defaultTabID = tabs[0].ID
	}
	b.WriteString("// ignore: avoid_classes_with_only_static_members\n")
	b.WriteString("class HomepageUIConfig {\n")
	b.WriteString("  const HomepageUIConfig._();\n\n")
	b.WriteString(fmt.Sprintf("  static const String defaultTabId = %s;\n\n", dartStringLiteral(defaultTabID)))
	b.WriteString("  static const List<HomepageTabConfig> tabs = <HomepageTabConfig>[\n")
	for _, tab := range tabs {
		b.WriteString(fmt.Sprintf("    HomepageTabConfig(id: %s, labelKey: %s, bodySlot: %s, isDefault: %v),\n",
			dartStringLiteral(tab.ID),
			dartStringLiteral(tab.LabelKey),
			dartStringLiteral(tab.BodySlot),
			tab.Default))
	}
	b.WriteString("  ];\n")
	b.WriteString("}\n")
	return b.String()
}

func renderCircleUIConfigDart(uc *uiConfigFile) string {
	var b strings.Builder
	b.WriteString("// Code generated by tools/codegen_app_metadata from social/circle/ui_config.yaml. DO NOT EDIT.\n")
	b.WriteString("// ignore_for_file: prefer_const_constructors\n\n")
	b.WriteString("class CircleTabConfig {\n")
	b.WriteString("  final String id;\n")
	b.WriteString("  final String labelKey;\n")
	b.WriteString("  final String bodySlot;\n")
	b.WriteString("  final List<String> sectionTypes;\n")
	b.WriteString("  final bool isDefault;\n\n")
	b.WriteString("  const CircleTabConfig({\n")
	b.WriteString("    required this.id,\n")
	b.WriteString("    required this.labelKey,\n")
	b.WriteString("    required this.bodySlot,\n")
	b.WriteString("    required this.sectionTypes,\n")
	b.WriteString("    required this.isDefault,\n")
	b.WriteString("  });\n")
	b.WriteString("}\n\n")
	b.WriteString("class CircleSectionConfig {\n")
	b.WriteString("  final String sectionType;\n")
	b.WriteString("  final String labelKey;\n")
	b.WriteString("  final String icon;\n")
	b.WriteString("  final String tabId;\n\n")
	b.WriteString("  const CircleSectionConfig({\n")
	b.WriteString("    required this.sectionType,\n")
	b.WriteString("    required this.labelKey,\n")
	b.WriteString("    required this.icon,\n")
	b.WriteString("    required this.tabId,\n")
	b.WriteString("  });\n")
	b.WriteString("}\n\n")
	tabs := append([]circleTabDef(nil), uc.CircleTabs...)
	sort.Slice(tabs, func(i, j int) bool { return tabs[i].Order < tabs[j].Order })
	sections := append([]circleSectionDef(nil), uc.CircleSections...)
	sort.Slice(sections, func(i, j int) bool { return sections[i].Order < sections[j].Order })
	defaultTabID := "content"
	for _, tab := range tabs {
		if tab.Default {
			defaultTabID = tab.ID
			break
		}
	}
	if len(tabs) > 0 && strings.TrimSpace(defaultTabID) == "" {
		defaultTabID = tabs[0].ID
	}
	b.WriteString("// ignore: avoid_classes_with_only_static_members\n")
	b.WriteString("class CircleUIConfig {\n")
	b.WriteString("  const CircleUIConfig._();\n\n")
	b.WriteString(fmt.Sprintf("  static const String defaultTabId = %s;\n\n", dartStringLiteral(defaultTabID)))
	b.WriteString("  static const List<CircleTabConfig> tabs = <CircleTabConfig>[\n")
	for _, tab := range tabs {
		b.WriteString(fmt.Sprintf("    CircleTabConfig(id: %s, labelKey: %s, bodySlot: %s, sectionTypes: %s, isDefault: %v),\n",
			dartStringLiteral(tab.ID),
			dartStringLiteral(tab.LabelKey),
			dartStringLiteral(tab.BodySlot),
			renderStringListLiteral(tab.SectionTypes),
			tab.Default))
	}
	b.WriteString("  ];\n\n")
	b.WriteString("  static const List<CircleSectionConfig> sections = <CircleSectionConfig>[\n")
	for _, section := range sections {
		b.WriteString(fmt.Sprintf("    CircleSectionConfig(sectionType: %s, labelKey: %s, icon: %s, tabId: %s),\n",
			dartStringLiteral(section.SectionType),
			dartStringLiteral(section.LabelKey),
			dartStringLiteral(section.Icon),
			dartStringLiteral(section.TabID)))
	}
	b.WriteString("  ];\n")
	b.WriteString("}\n")
	return b.String()
}
