// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../assistant/contracts/run_artifacts_contract_test.dart' as source_test;

void main() {
  source_test.main();
}
