"""Scale readiness gate contract tests（兼容门面）。"""
from __future__ import annotations

import sys
from pathlib import Path

_CASES_ROOT = Path(__file__).resolve().parent / "scale_readiness_cases"
if str(_CASES_ROOT) not in sys.path:
    sys.path.insert(0, str(_CASES_ROOT))

from core_cases import test_scale_readiness_allows_partial_lane_and_object_shortfall as _test_scale_readiness_allows_partial_lane_and_object_shortfall
from core_cases import test_scale_readiness_accepts_homepage_only_publish_count as _test_scale_readiness_accepts_homepage_only_publish_count
from core_cases import test_scale_readiness_blocks_manual_required_batch as _test_scale_readiness_blocks_manual_required_batch
from core_cases import test_scale_readiness_passes_when_scale_evidence_is_complete as _test_scale_readiness_passes_when_scale_evidence_is_complete
from image_replacement_cases import test_scale_readiness_commercial_allows_replaced_abandoned_entity_with_warning as _test_scale_readiness_commercial_allows_replaced_abandoned_entity_with_warning
from image_replacement_cases import test_scale_readiness_reports_structural_open_license_image_shortage as _test_scale_readiness_reports_structural_open_license_image_shortage
from image_replacement_cases import test_scale_readiness_source_admission_uses_active_replacement_targets as _test_scale_readiness_source_admission_uses_active_replacement_targets
from image_replacement_cases import test_scale_readiness_source_admission_reports_source_mix_breakdown as _test_scale_readiness_source_admission_reports_source_mix_breakdown
from image_replacement_cases import test_scale_readiness_trial_allows_replaced_abandoned_entity as _test_scale_readiness_trial_allows_replaced_abandoned_entity
from image_replacement_cases import test_scale_readiness_trial_closes_by_active_targets_not_replacement_history_count as _test_scale_readiness_trial_closes_by_active_targets_not_replacement_history_count
from image_replacement_cases import test_scale_readiness_warns_reference_only_strategy_for_publishable_image_quota as _test_scale_readiness_warns_reference_only_strategy_for_publishable_image_quota
from release_closure_cases import test_scale_readiness_blocks_abandoned_content_even_after_workflow_success as _test_scale_readiness_blocks_abandoned_content_even_after_workflow_success
from release_closure_cases import test_scale_readiness_classifies_image_shortfall_refs_as_image as _test_scale_readiness_classifies_image_shortfall_refs_as_image
from release_closure_cases import test_scale_readiness_commercial_closure_blocks_failed_lane_even_with_partial_flag as _test_scale_readiness_commercial_closure_blocks_failed_lane_even_with_partial_flag
from release_closure_cases import test_scale_readiness_commercial_closure_blocks_release_integrity_issue as _test_scale_readiness_commercial_closure_blocks_release_integrity_issue
from release_closure_cases import test_scale_readiness_accepts_text_only_release_with_explicit_flag as _test_scale_readiness_accepts_text_only_release_with_explicit_flag
from release_closure_cases import test_scale_readiness_commercial_closure_blocks_text_only_release as _test_scale_readiness_commercial_closure_blocks_text_only_release
from release_closure_cases import test_scale_readiness_infers_release_id_from_workflow_state as _test_scale_readiness_infers_release_id_from_workflow_state
from release_closure_cases import test_scale_readiness_trial_accepts_reasoned_reject_completion_when_target_met as _test_scale_readiness_trial_accepts_reasoned_reject_completion_when_target_met
from release_closure_cases import test_scale_readiness_trial_allows_low_abandoned_content_ratio as _test_scale_readiness_trial_allows_low_abandoned_content_ratio
from target_gate_cases import test_scale_readiness_target_gate_reports_funnel_and_blocks_low_capacity as _test_scale_readiness_target_gate_reports_funnel_and_blocks_low_capacity
from throughput_cases import test_scale_readiness_accepts_estimated_token_ledger_with_explicit_flag as _test_scale_readiness_accepts_estimated_token_ledger_with_explicit_flag
from throughput_cases import test_scale_readiness_blocks_estimated_token_ledger as _test_scale_readiness_blocks_estimated_token_ledger
from throughput_cases import test_scale_readiness_blocks_when_measured_throughput_is_below_target as _test_scale_readiness_blocks_when_measured_throughput_is_below_target
from throughput_cases import test_scale_readiness_allows_creator_cadence_spread_across_days_for_commercial as _test_scale_readiness_allows_creator_cadence_spread_across_days_for_commercial
from throughput_cases import test_scale_readiness_derives_first_pass_from_review_repair_report as _test_scale_readiness_derives_first_pass_from_review_repair_report
from throughput_cases import test_scale_readiness_passes_by_per_worker_throughput_projection as _test_scale_readiness_passes_by_per_worker_throughput_projection
from throughput_cases import test_scale_readiness_projection_requires_reliabletask_backend as _test_scale_readiness_projection_requires_reliabletask_backend
from throughput_cases import test_scale_readiness_reports_and_blocks_creator_overload_for_100_level_commercial as _test_scale_readiness_reports_and_blocks_creator_overload_for_100_level_commercial
from throughput_cases import test_scale_readiness_warns_creator_overload_for_100_level_trial as _test_scale_readiness_warns_creator_overload_for_100_level_trial


def test_scale_readiness_blocks_manual_required_batch():
    _test_scale_readiness_blocks_manual_required_batch()


def test_scale_readiness_passes_when_scale_evidence_is_complete():
    _test_scale_readiness_passes_when_scale_evidence_is_complete()


def test_scale_readiness_allows_partial_lane_and_object_shortfall():
    _test_scale_readiness_allows_partial_lane_and_object_shortfall()


def test_scale_readiness_accepts_homepage_only_publish_count():
    _test_scale_readiness_accepts_homepage_only_publish_count()


def test_scale_readiness_passes_by_per_worker_throughput_projection():
    _test_scale_readiness_passes_by_per_worker_throughput_projection()


def test_scale_readiness_projection_requires_reliabletask_backend():
    _test_scale_readiness_projection_requires_reliabletask_backend()


def test_scale_readiness_blocks_when_measured_throughput_is_below_target():
    _test_scale_readiness_blocks_when_measured_throughput_is_below_target()


def test_scale_readiness_blocks_estimated_token_ledger():
    _test_scale_readiness_blocks_estimated_token_ledger()


def test_scale_readiness_accepts_estimated_token_ledger_with_explicit_flag():
    _test_scale_readiness_accepts_estimated_token_ledger_with_explicit_flag()


def test_scale_readiness_derives_first_pass_from_review_repair_report():
    _test_scale_readiness_derives_first_pass_from_review_repair_report()


def test_scale_readiness_reports_and_blocks_creator_overload_for_100_level_commercial():
    _test_scale_readiness_reports_and_blocks_creator_overload_for_100_level_commercial()


def test_scale_readiness_allows_creator_cadence_spread_across_days_for_commercial():
    _test_scale_readiness_allows_creator_cadence_spread_across_days_for_commercial()


def test_scale_readiness_warns_creator_overload_for_100_level_trial():
    _test_scale_readiness_warns_creator_overload_for_100_level_trial()


def test_scale_readiness_infers_release_id_from_workflow_state():
    _test_scale_readiness_infers_release_id_from_workflow_state()


def test_scale_readiness_commercial_closure_blocks_failed_lane_even_with_partial_flag():
    _test_scale_readiness_commercial_closure_blocks_failed_lane_even_with_partial_flag()


def test_scale_readiness_commercial_closure_blocks_release_integrity_issue():
    _test_scale_readiness_commercial_closure_blocks_release_integrity_issue()


def test_scale_readiness_commercial_closure_blocks_text_only_release():
    _test_scale_readiness_commercial_closure_blocks_text_only_release()


def test_scale_readiness_accepts_text_only_release_with_explicit_flag():
    _test_scale_readiness_accepts_text_only_release_with_explicit_flag()


def test_scale_readiness_blocks_abandoned_content_even_after_workflow_success():
    _test_scale_readiness_blocks_abandoned_content_even_after_workflow_success()


def test_scale_readiness_trial_allows_low_abandoned_content_ratio():
    _test_scale_readiness_trial_allows_low_abandoned_content_ratio()


def test_scale_readiness_classifies_image_shortfall_refs_as_image():
    _test_scale_readiness_classifies_image_shortfall_refs_as_image()


def test_scale_readiness_trial_accepts_reasoned_reject_completion_when_target_met():
    _test_scale_readiness_trial_accepts_reasoned_reject_completion_when_target_met()


def test_scale_readiness_reports_structural_open_license_image_shortage():
    _test_scale_readiness_reports_structural_open_license_image_shortage()


def test_scale_readiness_warns_reference_only_strategy_for_publishable_image_quota():
    _test_scale_readiness_warns_reference_only_strategy_for_publishable_image_quota()


def test_scale_readiness_trial_allows_replaced_abandoned_entity():
    _test_scale_readiness_trial_allows_replaced_abandoned_entity()


def test_scale_readiness_trial_closes_by_active_targets_not_replacement_history_count():
    _test_scale_readiness_trial_closes_by_active_targets_not_replacement_history_count()


def test_scale_readiness_commercial_allows_replaced_abandoned_entity_with_warning():
    _test_scale_readiness_commercial_allows_replaced_abandoned_entity_with_warning()


def test_scale_readiness_source_admission_uses_active_replacement_targets():
    _test_scale_readiness_source_admission_uses_active_replacement_targets()


def test_scale_readiness_source_admission_reports_source_mix_breakdown():
    _test_scale_readiness_source_admission_reports_source_mix_breakdown()


def test_scale_readiness_target_gate_reports_funnel_and_blocks_low_capacity():
    _test_scale_readiness_target_gate_reports_funnel_and_blocks_low_capacity()


def _run_all() -> None:
    for name, fn in sorted(globals().items()):
        if name.startswith("test_") and callable(fn):
            fn()
            print(f"PASS {name}")


if __name__ == "__main__":
    _run_all()
