"""Scale readiness gate contract tests（兼容门面）。"""
from __future__ import annotations

import sys
from pathlib import Path

_CASES_ROOT = Path(__file__).resolve().parent / "scale_readiness_cases"
if str(_CASES_ROOT) not in sys.path:
    sys.path.insert(0, str(_CASES_ROOT))

from core_cases import test_scale_readiness_allows_partial_lane_and_object_shortfall as _test_scale_readiness_allows_partial_lane_and_object_shortfall
from core_cases import test_scale_readiness_blocks_manual_required_batch as _test_scale_readiness_blocks_manual_required_batch
from core_cases import test_scale_readiness_passes_when_scale_evidence_is_complete as _test_scale_readiness_passes_when_scale_evidence_is_complete
from image_replacement_cases import test_scale_readiness_commercial_allows_replaced_abandoned_entity_with_warning as _test_scale_readiness_commercial_allows_replaced_abandoned_entity_with_warning
from image_replacement_cases import test_scale_readiness_reports_structural_open_license_image_shortage as _test_scale_readiness_reports_structural_open_license_image_shortage
from image_replacement_cases import test_scale_readiness_trial_allows_replaced_abandoned_entity as _test_scale_readiness_trial_allows_replaced_abandoned_entity
from image_replacement_cases import test_scale_readiness_trial_closes_by_active_targets_not_replacement_history_count as _test_scale_readiness_trial_closes_by_active_targets_not_replacement_history_count
from image_replacement_cases import test_scale_readiness_warns_reference_only_strategy_for_publishable_image_quota as _test_scale_readiness_warns_reference_only_strategy_for_publishable_image_quota
from release_closure_cases import test_scale_readiness_blocks_abandoned_content_even_after_workflow_success as _test_scale_readiness_blocks_abandoned_content_even_after_workflow_success
from release_closure_cases import test_scale_readiness_infers_release_id_from_workflow_state as _test_scale_readiness_infers_release_id_from_workflow_state
from release_closure_cases import test_scale_readiness_trial_allows_low_abandoned_content_ratio as _test_scale_readiness_trial_allows_low_abandoned_content_ratio
from target_gate_cases import test_scale_readiness_target_gate_reports_funnel_and_blocks_low_capacity as _test_scale_readiness_target_gate_reports_funnel_and_blocks_low_capacity
from throughput_cases import test_scale_readiness_blocks_when_measured_throughput_is_below_target as _test_scale_readiness_blocks_when_measured_throughput_is_below_target
from throughput_cases import test_scale_readiness_passes_by_per_worker_throughput_projection as _test_scale_readiness_passes_by_per_worker_throughput_projection
from throughput_cases import test_scale_readiness_projection_requires_reliabletask_backend as _test_scale_readiness_projection_requires_reliabletask_backend
from throughput_cases import test_scale_readiness_reports_and_blocks_creator_overload_for_100_level as _test_scale_readiness_reports_and_blocks_creator_overload_for_100_level


def test_scale_readiness_blocks_manual_required_batch():
    _test_scale_readiness_blocks_manual_required_batch()


def test_scale_readiness_passes_when_scale_evidence_is_complete():
    _test_scale_readiness_passes_when_scale_evidence_is_complete()


def test_scale_readiness_allows_partial_lane_and_object_shortfall():
    _test_scale_readiness_allows_partial_lane_and_object_shortfall()


def test_scale_readiness_passes_by_per_worker_throughput_projection():
    _test_scale_readiness_passes_by_per_worker_throughput_projection()


def test_scale_readiness_projection_requires_reliabletask_backend():
    _test_scale_readiness_projection_requires_reliabletask_backend()


def test_scale_readiness_blocks_when_measured_throughput_is_below_target():
    _test_scale_readiness_blocks_when_measured_throughput_is_below_target()


def test_scale_readiness_reports_and_blocks_creator_overload_for_100_level():
    _test_scale_readiness_reports_and_blocks_creator_overload_for_100_level()


def test_scale_readiness_infers_release_id_from_workflow_state():
    _test_scale_readiness_infers_release_id_from_workflow_state()


def test_scale_readiness_blocks_abandoned_content_even_after_workflow_success():
    _test_scale_readiness_blocks_abandoned_content_even_after_workflow_success()


def test_scale_readiness_trial_allows_low_abandoned_content_ratio():
    _test_scale_readiness_trial_allows_low_abandoned_content_ratio()


def test_scale_readiness_reports_structural_open_license_image_shortage():
    _test_scale_readiness_reports_structural_open_license_image_shortage()


def test_scale_readiness_warns_reference_only_strategy_for_publishable_image_quota():
    _test_scale_readiness_warns_reference_only_strategy_for_publishable_image_quota()


def test_scale_readiness_trial_allows_replaced_abandoned_entity():
    _test_scale_readiness_trial_allows_replaced_abandoned_entity()


def test_scale_readiness_trial_closes_by_active_targets_not_replacement_history_count():
    _test_scale_readiness_trial_closes_by_active_targets_not_replacement_history_count()


def test_scale_readiness_commercial_allows_replaced_abandoned_entity_with_warning():
    _test_scale_readiness_commercial_allows_replaced_abandoned_entity_with_warning()


def test_scale_readiness_target_gate_reports_funnel_and_blocks_low_capacity():
    _test_scale_readiness_target_gate_reports_funnel_and_blocks_low_capacity()


def _run_all() -> None:
    for name, fn in sorted(globals().items()):
        if name.startswith("test_") and callable(fn):
            fn()
            print(f"PASS {name}")


if __name__ == "__main__":
    _run_all()
