// Code generated by internal/metadata/codegen. DO NOT EDIT.
package event

// Event type constants for MediaImageReprocessRun.
const (
	MediaImageReprocessRunStarted    = "MediaImageReprocessRunStarted"
	MediaImageReprocessRunPaused     = "MediaImageReprocessRunPaused"
	MediaImageReprocessRunResumed    = "MediaImageReprocessRunResumed"
	MediaImageReprocessRunCompleted  = "MediaImageReprocessRunCompleted"
	MediaImageReprocessRunRolledBack = "MediaImageReprocessRunRolledBack"
)
