// Code generated by codegen_storage. DO NOT EDIT.
package persistence

import (
	"context"
	"time"

	"go.mongodb.org/mongo-driver/v2/bson"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"go.mongodb.org/mongo-driver/v2/mongo/options"

	model "quwoquan_service/services/tag-service/internal/domain/tag/model"
)

var _ = time.Now

// mongoTagNodeStoreBase provides generated MongoDB operations for TagNode.
// Embed this in a public store type defined in _ext.go.
type mongoTagNodeStoreBase struct {
	coll *mongo.Collection
}

// EnsureIndexes creates required indexes on the tag_nodes collection.
func (s *mongoTagNodeStoreBase) EnsureIndexes(ctx context.Context) error {
	models := []mongo.IndexModel{
		{
			Keys: bson.D{
				{Key: "tagRef", Value: 1},
			},
			Options: options.Index().SetName("idx_tag_ref").SetUnique(true),
		},
		{
			Keys: bson.D{
				{Key: "group", Value: 1},
			},
			Options: options.Index().SetName("idx_tag_group"),
		},
	}
	_, err := s.coll.Indexes().CreateMany(ctx, models)
	return err
}

// Create inserts a new TagNode document. Returns false if duplicate key.
func (s *mongoTagNodeStoreBase) Create(ctx context.Context, e *model.TagNode) (bool, error) {
	e.CreatedAt = time.Now().UTC()
	_, err := s.coll.InsertOne(ctx, e)
	if err != nil {
		if mongo.IsDuplicateKeyError(err) {
			return false, nil
		}
		return false, err
	}
	return true, nil
}

// DeleteByFilter removes a document matching the filter.
func (s *mongoTagNodeStoreBase) DeleteByFilter(ctx context.Context, filter bson.M) (int64, error) {
	result, err := s.coll.DeleteOne(ctx, filter)
	if err != nil {
		return 0, err
	}
	return result.DeletedCount, nil
}

// ExistsByFilter checks if a document matching the filter exists.
func (s *mongoTagNodeStoreBase) ExistsByFilter(ctx context.Context, filter bson.M) (bool, error) {
	count, err := s.coll.CountDocuments(ctx, filter, options.Count().SetLimit(1))
	return count > 0, err
}

// CountByFilter returns the number of documents matching the filter.
func (s *mongoTagNodeStoreBase) CountByFilter(ctx context.Context, filter bson.M) (int64, error) {
	return s.coll.CountDocuments(ctx, filter)
}
