// Code generated by generate_canonical_test_bridges.py. DO NOT EDIT.
package local_contract

import (
	"os/exec"
	"testing"
)

func TestBackfillLocalContractTest(t *testing.T) {
	cmd := exec.Command(
		"go",
		"test",
		"../../../../../internal/infrastructure/searchindex",
		"-run",
		"^(TestBackfillEnsureIndexFailurePropagates|TestBackfillIndexesEligibleOnly|TestBackfillNilInputsNoOp|TestBackfillPaginates)$",
		"-count=1",
	)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("source bridge failed for quwoquan_service/services/circle-service/internal/infrastructure/searchindex/backfill_test.go: %v\n%s", err, output)
	}
}
