#!/usr/bin/env python3
"""从 alpha seed manifest 生成不可变、内容寻址的 Dart fixture bundle。"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]
METADATA = ROOT / "quwoquan_service" / "contracts" / "metadata"
MANIFEST = METADATA / "_shared/test_fixtures/app_alpha_seed_manifest.json"
DEFAULT_OUTPUT = (
    ROOT
    / "quwoquan_app"
    / "packages"
    / "quwoquan_cloud_mock"
    / "lib"
    / "src"
    / "generated"
    / "alpha_fixture_bundle.g.dart"
)


def sha256(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def dart_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True).replace("$", r"\$")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    output = args.output.resolve()
    manifest_bytes = MANIFEST.read_bytes()
    manifest = json.loads(manifest_bytes)
    if manifest.get("environment") != "alpha":
        raise ValueError("alpha fixture bundle 只能消费 environment=alpha manifest")

    assets: list[dict[str, object]] = []
    seen_domains: set[str] = set()
    for seed in manifest.get("seedRefs", []):
        domain = str(seed.get("domain", "")).strip()
        relative = str(seed.get("fixturePath", "")).strip()
        refs = seed.get("refs")
        if not domain or domain in seen_domains:
            raise ValueError(f"fixture domain 缺失或重复: {domain!r}")
        if not relative or not isinstance(refs, list) or not refs:
            raise ValueError(f"{domain}: fixturePath/refs 不完整")
        source = (METADATA / relative).resolve()
        source.relative_to(METADATA.resolve())
        payload = source.read_bytes()
        json.loads(payload)
        seen_domains.add(domain)
        assets.append(
            {
                "domain": domain,
                "sourcePath": relative,
                "sourceSha256": sha256(payload),
                "sourceJson": payload.decode("utf-8"),
                "refs": [str(item) for item in refs],
            }
        )

    lines = [
        "// Code generated by build_alpha_fixture_bundle.py. DO NOT EDIT.",
        f"// Source manifest SHA256: {sha256(manifest_bytes)}",
        "",
        "final class AlphaFixtureAsset {",
        "  const AlphaFixtureAsset({",
        "    required this.domain,",
        "    required this.sourcePath,",
        "    required this.sourceSha256,",
        "    required this.sourceJson,",
        "    required this.refs,",
        "  });",
        "",
        "  final String domain;",
        "  final String sourcePath;",
        "  final String sourceSha256;",
        "  final String sourceJson;",
        "  final List<String> refs;",
        "}",
        "",
        "final class AlphaFixtureBundle {",
        "  const AlphaFixtureBundle({",
        "    required this.manifestSha256,",
        "    required this.assets,",
        "  });",
        "",
        "  final String manifestSha256;",
        "  final Map<String, AlphaFixtureAsset> assets;",
        "}",
        "",
        "const alphaFixtureBundle = AlphaFixtureBundle(",
        f"  manifestSha256: {dart_string(sha256(manifest_bytes))},",
        "  assets: <String, AlphaFixtureAsset>{",
    ]
    for asset in sorted(assets, key=lambda item: str(item["domain"])):
        domain = str(asset["domain"])
        lines.extend(
            [
                f"    {dart_string(domain)}: AlphaFixtureAsset(",
                f"      domain: {dart_string(domain)},",
                f"      sourcePath: {dart_string(str(asset['sourcePath']))},",
                "      sourceSha256: "
                f"{dart_string(str(asset['sourceSha256']))},",
                f"      sourceJson: {dart_string(str(asset['sourceJson']))},",
                "      refs: <String>[",
            ]
        )
        for ref in asset["refs"]:
            lines.append(f"        {dart_string(str(ref))},")
        lines.extend(["      ],", "    ),"])
    lines.extend(["  },", ");", ""])

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")
    print(
        "generated alpha fixture bundle: "
        f"{output} (domains={len(assets)})"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
