// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../components/comment_system/comment_counts_delta_notice_test.dart' as source_test;

void main() {
  source_test.main();
}
