// Code generated by generate_canonical_test_bridges.py. DO NOT EDIT.
package local_contract

import (
	"os/exec"
	"testing"
)

func TestIntersectionReadpathInvariantLocalContractTest(t *testing.T) {
	cmd := exec.Command(
		"go",
		"test",
		"../../../../../internal/application/intersection",
		"-run",
		"^(TestIntersectionService_ReadPathZeroSynchronousScoring)$",
		"-count=1",
	)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("source bridge failed for quwoquan_service/services/content-service/internal/application/intersection/intersection_readpath_invariant_test.go: %v\n%s", err, output)
	}
}
