// Code generated by internal/metadata/codegen. DO NOT EDIT.
package circlegroupmembership

import "time"

// GeoPoint represents a geographic coordinate.
type GeoPoint struct {
	Latitude  float64 `json:"latitude" bson:"latitude"`
	Longitude float64 `json:"longitude" bson:"longitude"`
}

var _ = time.Now

// CircleGroupMembershipRole enumerates allowed wire values for CircleGroupMembershipRole.
type CircleGroupMembershipRole string

const (
	CircleGroupMembershipRoleOwner CircleGroupMembershipRole = "owner"

	CircleGroupMembershipRoleManager CircleGroupMembershipRole = "manager"

	CircleGroupMembershipRoleMember CircleGroupMembershipRole = "member"
)

// CircleGroupMembershipState enumerates allowed wire values for CircleGroupMembershipState.
type CircleGroupMembershipState string

const (
	CircleGroupMembershipStatePending CircleGroupMembershipState = "pending"

	CircleGroupMembershipStateActive CircleGroupMembershipState = "active"

	CircleGroupMembershipStateRejected CircleGroupMembershipState = "rejected"

	CircleGroupMembershipStateLeft CircleGroupMembershipState = "left"

	CircleGroupMembershipStateRemoved CircleGroupMembershipState = "removed"
)

// CircleGroupMembership domain model.
type CircleGroupMembership struct {
	ID                 string                     `json:"_id" bson:"_id"`
	Version            int64                      `json:"version" bson:"version"`
	GroupID            string                     `json:"groupId" bson:"groupId"`
	CircleID           string                     `json:"circleId" bson:"circleId"`
	PersonaID          string                     `json:"personaId" bson:"personaId"`
	Role               CircleGroupMembershipRole  `json:"role" bson:"role"`
	State              CircleGroupMembershipState `json:"state" bson:"state"`
	JoinedAt           time.Time                  `json:"joinedAt" bson:"joinedAt"`
	LeftAt             time.Time                  `json:"leftAt" bson:"leftAt"`
	DecidedAt          time.Time                  `json:"decidedAt" bson:"decidedAt"`
	DecidedByPersonaID string                     `json:"decidedByPersonaId" bson:"decidedByPersonaId"`
	CreatedAt          time.Time                  `json:"createdAt" bson:"createdAt"`
	UpdatedAt          time.Time                  `json:"updatedAt" bson:"updatedAt"`
}
