// Code generated by codegen_storage. DO NOT EDIT.
package persistence

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	model "quwoquan_service/services/user-service/internal/domain/block/model"
)

var _ = fmt.Sprintf
var _ = time.Now

// pgBlockStoreBase provides generated PostgreSQL CRUD for BlockEdge.
// Embed this in a public store type defined in _ext.go.
type pgBlockStoreBase struct {
	pool *pgxpool.Pool
}

const blockEdgeCols = `id, blocker_id, blocked_id, reason, created_at`

func scanBlockEdge(row pgx.Row) (*model.BlockEdge, error) {
	e := &model.BlockEdge{}
	err := row.Scan(&e.ID, &e.BlockerID, &e.BlockedID, &e.Reason, &e.CreatedAt)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return e, nil
}

// FindByID retrieves a BlockEdge by primary key.
func (s *pgBlockStoreBase) FindByID(ctx context.Context, id string) (*model.BlockEdge, error) {
	row := s.pool.QueryRow(ctx, `SELECT `+blockEdgeCols+` FROM block_edges WHERE id = $1`, id)
	return scanBlockEdge(row)
}

// Create inserts a new BlockEdge record.
func (s *pgBlockStoreBase) Create(ctx context.Context, e *model.BlockEdge) error {
	now := time.Now().UTC()
	e.CreatedAt = now
	_, err := s.pool.Exec(ctx,
		`INSERT INTO block_edges (id, blocker_id, blocked_id, reason, created_at) VALUES ($1, $2, $3, $4, $5)`,
		e.ID, e.BlockerID, e.BlockedID, e.Reason, e.CreatedAt)
	return err
}

// Update modifies an existing BlockEdge record (all non-PK columns).
func (s *pgBlockStoreBase) Update(ctx context.Context, e *model.BlockEdge) error {
	tag, err := s.pool.Exec(ctx,
		`UPDATE block_edges SET blocker_id=$2, blocked_id=$3, reason=$4, created_at=$5 WHERE id = $1`,
		e.ID, e.BlockerID, e.BlockedID, e.Reason, e.CreatedAt)
	if err != nil {
		return err
	}
	if tag.RowsAffected() == 0 {
		return fmt.Errorf("BlockEdge not found: %s", e.ID)
	}
	return nil
}

// Delete removes a BlockEdge by primary key.
func (s *pgBlockStoreBase) Delete(ctx context.Context, id string) error {
	_, err := s.pool.Exec(ctx, `DELETE FROM block_edges WHERE id = $1`, id)
	return err
}
