// Code generated by codegen_storage. DO NOT EDIT.
package persistence

import (
	"context"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	model "quwoquan_service/services/user-service/internal/domain/user/model"
)

var _ = fmt.Sprintf

// pgInviteStoreBase provides generated PostgreSQL CRUD for InviteRecord.
// Embed this in a public store type defined in _ext.go.
type pgInviteStoreBase struct {
	pool *pgxpool.Pool
}

const inviteRecordCols = `id, inviter_sub_account_id, inviter_owner_account_id, channel, link_code, invitee_phone_hash, status, expire_at, generated_at, delivered_at, viewed_at, accepted_at, converted_at`

func scanInviteRecord(row pgx.Row) (*model.InviteRecord, error) {
	e := &model.InviteRecord{}
	err := row.Scan(&e.ID, &e.InviterSubAccountID, &e.InviterOwnerAccountID, &e.Channel, &e.LinkCode, &e.InviteePhoneHash, &e.Status, &e.ExpireAt, &e.GeneratedAt, &e.DeliveredAt, &e.ViewedAt, &e.AcceptedAt, &e.ConvertedAt)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return e, nil
}

// FindByID retrieves a InviteRecord by primary key.
func (s *pgInviteStoreBase) FindByID(ctx context.Context, id string) (*model.InviteRecord, error) {
	row := s.pool.QueryRow(ctx, `SELECT `+inviteRecordCols+` FROM invite_records WHERE id = $1`, id)
	return scanInviteRecord(row)
}

// Create inserts a new InviteRecord record.
func (s *pgInviteStoreBase) Create(ctx context.Context, e *model.InviteRecord) error {
	_, err := s.pool.Exec(ctx,
		`INSERT INTO invite_records (id, inviter_sub_account_id, inviter_owner_account_id, channel, link_code, invitee_phone_hash, status, expire_at, generated_at, delivered_at, viewed_at, accepted_at, converted_at) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)`,
		e.ID, e.InviterSubAccountID, e.InviterOwnerAccountID, e.Channel, e.LinkCode, e.InviteePhoneHash, e.Status, e.ExpireAt, e.GeneratedAt, e.DeliveredAt, e.ViewedAt, e.AcceptedAt, e.ConvertedAt)
	return err
}

// Update modifies an existing InviteRecord record (all non-PK columns).
func (s *pgInviteStoreBase) Update(ctx context.Context, e *model.InviteRecord) error {
	tag, err := s.pool.Exec(ctx,
		`UPDATE invite_records SET inviter_sub_account_id=$2, inviter_owner_account_id=$3, channel=$4, link_code=$5, invitee_phone_hash=$6, status=$7, expire_at=$8, generated_at=$9, delivered_at=$10, viewed_at=$11, accepted_at=$12, converted_at=$13 WHERE id = $1`,
		e.ID, e.InviterSubAccountID, e.InviterOwnerAccountID, e.Channel, e.LinkCode, e.InviteePhoneHash, e.Status, e.ExpireAt, e.GeneratedAt, e.DeliveredAt, e.ViewedAt, e.AcceptedAt, e.ConvertedAt)
	if err != nil {
		return err
	}
	if tag.RowsAffected() == 0 {
		return fmt.Errorf("InviteRecord not found: %s", e.ID)
	}
	return nil
}

// Delete removes a InviteRecord by primary key.
func (s *pgInviteStoreBase) Delete(ctx context.Context, id string) error {
	_, err := s.pool.Exec(ctx, `DELETE FROM invite_records WHERE id = $1`, id)
	return err
}
