// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../../ui/search/pages/location_place_landing_page_widget_test.dart' as source_test;

void main() {
  source_test.main();
}
