// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../components/conversation/conversation_link_action_sheet_test.dart' as legacy_test;

void main() {
  legacy_test.main();
}
