// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../components/conversation/message_action_menu_overlay_test.dart' as source_test;

void main() {
  source_test.main();
}
