// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../../../ui/content/article_render/services/article_pagination_engine_test.dart' as source_test;

void main() {
  source_test.main();
}
