// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../ui/circle/circle_content_identity_widget_test.dart' as source_test;

void main() {
  source_test.main();
}
