// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../../ui/content/entry/article_edit_preview_chrome_widget_test.dart' as source_0;

void main() {
  source_0.main();
}
