// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../../ui/content/entry/article_typography_page_widget_test.dart' as legacy_test;

void main() {
  legacy_test.main();
}
