// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../../ui/discovery/widgets/works_immersive_viewer_widget_test.dart' as source_0;

void main() {
  source_0.main();
}
