// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../../cloud/runtime/codec/cloud_response_decoder_test.dart' as source_test;

void main() {
  source_test.main();
}
