// Code generated by generate_canonical_test_bridges.py. DO NOT EDIT.
package api_integration

import (
	"os/exec"
	"testing"
)

func TestCircleFeedContractApiIntegrationTest(t *testing.T) {
	cmd := exec.Command(
		"go",
		"test",
		"..",
		"-run",
		"^(TestGetCircleFeed_Empty|TestGetCircleFeed_Featured|TestGetCircleFeed_Latest|TestGetCircleFeed_Pagination)$",
		"-count=1",
	)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("source bridge failed for quwoquan_service/services/circle-service/tests/circle_feed_contract_test.go: %v\n%s", err, output)
	}
}
