// Code generated by generate_app_canonical_test_wrappers.py. DO NOT EDIT.

import '../../../../../components/media/shared/toolbar/immersive_engagement_bar_widget_test.dart' as legacy_test;

void main() {
  legacy_test.main();
}
