package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	contractcodegen "quwoquan_service/internal/metadata/codegen"
	contractvalidate "quwoquan_service/internal/metadata/validate"
)

type catalogDocument struct {
	Catalog string           `yaml:"catalog"`
	Tools   []map[string]any `yaml:"tools"`
}

type assistantRunErrorDocument struct {
	Errors []struct {
		Code string `yaml:"code"`
	} `yaml:"errors"`
}

func main() {
	var metadataDir string
	var output string
	var check bool
	flag.StringVar(&metadataDir, "metadata-dir", "", "compiled service contract view")
	flag.StringVar(&output, "output", "", "generated Go catalog output")
	flag.BoolVar(&check, "check", false, "fail when generated output is stale")
	flag.Parse()
	if strings.TrimSpace(metadataDir) == "" || strings.TrimSpace(output) == "" {
		fail("--metadata-dir and --output are required")
	}
	content, err := generate(metadataDir)
	if err != nil {
		fail(err.Error())
	}
	if check {
		existing, err := os.ReadFile(output)
		if err != nil || !bytes.Equal(existing, content) {
			fail("generated assistant tool catalog is stale; run make codegen-assistant-tool-catalog")
		}
		return
	}
	if err := os.MkdirAll(filepath.Dir(output), 0o755); err != nil {
		fail(err.Error())
	}
	if err := os.WriteFile(output, content, 0o644); err != nil {
		fail(err.Error())
	}
}

func generate(metadataDir string) ([]byte, error) {
	source, err := contractcodegen.NewSource(metadataDir, contractvalidate.ProfileBaseline)
	if err != nil {
		return nil, fmt.Errorf("compile ContractGraph: %w", err)
	}
	var document catalogDocument
	const sourcePath = "assistant/assistant_tool_metadata/catalog.yaml"
	if err := source.Decode(sourcePath, &document); err != nil {
		return nil, fmt.Errorf("decode assistant tool catalog: %w", err)
	}
	if document.Catalog != "assistant_tool_metadata" {
		return nil, fmt.Errorf("unexpected assistant tool catalog %q", document.Catalog)
	}
	var errorsDocument assistantRunErrorDocument
	if err := source.Decode(
		"assistant/assistant/assistant_run/errors.yaml",
		&errorsDocument,
	); err != nil {
		return nil, fmt.Errorf("decode AssistantRun errors: %w", err)
	}
	canonicalErrorCodes := make(map[string]bool, len(errorsDocument.Errors))
	for _, entry := range errorsDocument.Errors {
		canonicalErrorCodes[strings.TrimSpace(entry.Code)] = true
	}
	if err := validateTools(document.Tools, canonicalErrorCodes); err != nil {
		return nil, err
	}
	sort.Slice(document.Tools, func(i, j int) bool {
		return stringValue(document.Tools[i], "toolName") < stringValue(document.Tools[j], "toolName")
	})
	payload, err := json.MarshalIndent(document.Tools, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("encode assistant tool catalog: %w", err)
	}
	payload = append(payload, '\n')
	digest := sha256.Sum256(payload)
	rendered := fmt.Sprintf(`// Code generated by codegen_assistant_tool_catalog. DO NOT EDIT.

package generated

const AssistantToolCatalogDigest = %s

const AssistantToolCatalogJSON = %s
`, strconv.Quote("sha256:"+hex.EncodeToString(digest[:])), strconv.Quote(string(payload)))
	formatted, err := format.Source([]byte(rendered))
	if err != nil {
		return nil, fmt.Errorf("format generated assistant tool catalog: %w", err)
	}
	return formatted, nil
}

func validateTools(
	tools []map[string]any,
	canonicalErrorCodes map[string]bool,
) error {
	if len(tools) == 0 {
		return fmt.Errorf("assistant tool catalog is empty")
	}
	seen := map[string]bool{}
	namespaceCounts := map[string]int{}
	for index, tool := range tools {
		name := stringValue(tool, "toolName")
		namespace := stringValue(tool, "namespace")
		placement := stringValue(tool, "placement")
		if name == "" || namespace == "" || placement == "" {
			return fmt.Errorf("tool[%d] requires toolName, namespace and placement", index)
		}
		if seen[name] {
			return fmt.Errorf("duplicate assistant tool %q", name)
		}
		seen[name] = true
		namespaceCounts[namespace]++
		for _, key := range []string{"inputSchema", "outputSchema"} {
			schema, ok := tool[key].(map[string]any)
			if !ok || schema["type"] != "object" || schema["additionalProperties"] != false {
				return fmt.Errorf("tool %q %s must be a closed object schema", name, key)
			}
		}
		scopes, ok := tool["environmentScopes"].([]any)
		if !ok || len(scopes) == 0 {
			return fmt.Errorf("tool %q requires environmentScopes", name)
		}
		readOnly, ok := tool["readOnly"].(bool)
		if !ok {
			return fmt.Errorf("tool %q requires readOnly", name)
		}
		if !readOnly {
			requiresConfirmation, _ := tool["requiresConfirmation"].(bool)
			if placement != "device_action" || !requiresConfirmation {
				return fmt.Errorf(
					"mutating tool %q must be a confirmed device_action",
					name,
				)
			}
			if err := validateMutatingCapabilityPolicy(name, tool); err != nil {
				return err
			}
		}
		if err := validateServerInjectedInputs(name, tool); err != nil {
			return err
		}
		if err := validateResearchPolicy(name, tool); err != nil {
			return err
		}
		if err := validateResearchOutput(name, tool); err != nil {
			return err
		}
		if err := validateEmergentTagProjection(name, tool); err != nil {
			return err
		}
		if err := validateFailurePolicy(name, tool, canonicalErrorCodes); err != nil {
			return err
		}
	}
	for namespace, count := range namespaceCounts {
		if count >= 10 {
			return fmt.Errorf("tool namespace %q has %d tools; limit is 9", namespace, count)
		}
	}
	return nil
}

// validateEmergentTagProjection keeps interest extraction declarative. A tool
// may opt in by declaring the standard emergedTagRefs output; AgentLoop then
// consumes it without knowing the tool name or its vertical result shape.
func validateEmergentTagProjection(name string, tool map[string]any) error {
	outputSchema, _ := tool["outputSchema"].(map[string]any)
	properties, _ := outputSchema["properties"].(map[string]any)
	property, found := properties["emergedTagRefs"].(map[string]any)
	if !found {
		return nil
	}
	items, _ := property["items"].(map[string]any)
	if property["type"] != "array" || items["type"] != "string" ||
		!requiredContains(outputSchema["required"], "emergedTagRefs") {
		return fmt.Errorf(
			"tool %q emergedTagRefs must be a required string-array output",
			name,
		)
	}
	return nil
}

func validateResearchOutput(name string, tool map[string]any) error {
	if _, found := tool["research"].(map[string]any); !found {
		return nil
	}
	outputSchema, _ := tool["outputSchema"].(map[string]any)
	properties, _ := outputSchema["properties"].(map[string]any)
	assessment, found := properties["evidenceAssessment"].(map[string]any)
	if !found || assessment["type"] != "object" ||
		assessment["additionalProperties"] != false {
		return fmt.Errorf(
			"research tool %q requires a closed evidenceAssessment output",
			name,
		)
	}
	if !requiredContains(outputSchema["required"], "evidenceAssessment") {
		return fmt.Errorf(
			"research tool %q must require evidenceAssessment output",
			name,
		)
	}
	for _, field := range []string{
		"status", "evidenceSufficient", "replanRequired", "reason",
		"targetIds", "documentIds", "artifactRefs", "sourceIds",
	} {
		if !requiredContains(assessment["required"], field) {
			return fmt.Errorf(
				"research tool %q evidenceAssessment must require %s",
				name,
				field,
			)
		}
	}
	return nil
}

func requiredContains(value any, expected string) bool {
	switch values := value.(type) {
	case []any:
		for _, value := range values {
			if text, ok := value.(string); ok && text == expected {
				return true
			}
		}
	case []string:
		for _, value := range values {
			if value == expected {
				return true
			}
		}
	}
	return false
}

func validateFailurePolicy(
	name string,
	tool map[string]any,
	canonicalErrorCodes map[string]bool,
) error {
	policy, found := tool["failure"].(map[string]any)
	if !found {
		return nil
	}
	code := stringValue(policy, "providerFailureCode")
	if code == "" || !strings.HasPrefix(code, "ASSISTANT.") {
		return fmt.Errorf(
			"tool %q failure providerFailureCode must reference an ASSISTANT error",
			name,
		)
	}
	if !canonicalErrorCodes[code] {
		return fmt.Errorf(
			"tool %q failure providerFailureCode %q is absent from AssistantRun errors",
			name,
			code,
		)
	}
	return nil
}

func validateResearchPolicy(name string, tool map[string]any) error {
	policy, found := tool["research"].(map[string]any)
	if !found {
		return nil
	}
	operation := stringValue(policy, "operation")
	if operation != "discover" && operation != "navigate" && operation != "inspect" {
		return fmt.Errorf("tool %q has unsupported research operation %q", name, operation)
	}
	readOnly, _ := tool["readOnly"].(bool)
	if !readOnly {
		return fmt.Errorf("mutating tool %q cannot declare research policy", name)
	}
	inputSchema, _ := tool["inputSchema"].(map[string]any)
	properties, _ := inputSchema["properties"].(map[string]any)
	parallelField := stringValue(policy, "parallelInputField")
	if parallelField != "" {
		if operation != "discover" {
			return fmt.Errorf(
				"tool %q research parallelInputField is only valid for discover",
				name,
			)
		}
		property, exists := properties[parallelField].(map[string]any)
		if !exists || property["type"] != "array" {
			return fmt.Errorf(
				"tool %q research parallelInputField %q is not an array input",
				name,
				parallelField,
			)
		}
	}
	if operation != "navigate" {
		for _, key := range []string{
			"targetInputField", "targetKindField", "targetValueField",
		} {
			if stringValue(policy, key) != "" {
				return fmt.Errorf(
					"tool %q research %s is only valid for navigate",
					name,
					key,
				)
			}
		}
		for _, key := range []string{
			"reusableSourceTargetKinds", "childTargetKinds",
		} {
			if values, exists := policy[key]; exists {
				items, ok := values.([]any)
				if !ok || len(items) != 0 {
					return fmt.Errorf(
						"tool %q research %s is only valid for navigate",
						name,
						key,
					)
				}
			}
		}
		return nil
	}
	targetField := stringValue(policy, "targetInputField")
	kindField := stringValue(policy, "targetKindField")
	valueField := stringValue(policy, "targetValueField")
	target, exists := properties[targetField].(map[string]any)
	if targetField == "" || kindField == "" || valueField == "" || !exists ||
		target["type"] != "object" {
		return fmt.Errorf("tool %q navigate research bindings are incomplete", name)
	}
	targetProperties, _ := target["properties"].(map[string]any)
	kindProperty, kindExists := targetProperties[kindField].(map[string]any)
	if !kindExists || kindProperty["type"] != "string" {
		return fmt.Errorf("tool %q navigate target kind binding is absent", name)
	}
	valueProperty, valueExists := targetProperties[valueField].(map[string]any)
	if !valueExists || valueProperty["type"] != "string" {
		return fmt.Errorf("tool %q navigate target value binding is absent", name)
	}
	allowedKinds := make(map[string]struct{})
	if values, ok := kindProperty["enum"].([]any); ok {
		for _, value := range values {
			kind := strings.TrimSpace(fmt.Sprint(value))
			if kind != "" {
				allowedKinds[kind] = struct{}{}
			}
		}
	}
	seenKinds := make(map[string]string)
	for _, key := range []string{
		"reusableSourceTargetKinds", "childTargetKinds",
	} {
		values, exists := policy[key]
		if !exists {
			continue
		}
		items, ok := values.([]any)
		if !ok {
			return fmt.Errorf("tool %q research %s must be a string list", name, key)
		}
		for _, value := range items {
			kind := strings.TrimSpace(fmt.Sprint(value))
			if kind == "" {
				return fmt.Errorf("tool %q research %s contains an empty kind", name, key)
			}
			if len(allowedKinds) > 0 {
				if _, exists := allowedKinds[kind]; !exists {
					return fmt.Errorf(
						"tool %q research %s kind %q is outside target enum",
						name,
						key,
						kind,
					)
				}
			}
			if owner, duplicate := seenKinds[kind]; duplicate {
				return fmt.Errorf(
					"tool %q research target kind %q is shared by %s and %s",
					name,
					kind,
					owner,
					key,
				)
			}
			seenKinds[kind] = key
		}
	}
	return nil
}

func validateMutatingCapabilityPolicy(name string, tool map[string]any) error {
	policy, ok := tool["capability"].(map[string]any)
	if !ok {
		return fmt.Errorf("mutating tool %q requires capability policy", name)
	}
	capabilityKey := stringValue(policy, "capabilityKey")
	connectorRequirement := stringValue(policy, "connectorRequirement")
	if capabilityKey == "" || !strings.Contains(capabilityKey, ".") {
		return fmt.Errorf("mutating tool %q requires canonical capabilityKey", name)
	}
	if connectorRequirement != "required" && connectorRequirement != "none" {
		return fmt.Errorf(
			"mutating tool %q has unsupported connectorRequirement %q",
			name,
			connectorRequirement,
		)
	}
	consentScopes, consentOK := policy["consentScopes"].([]any)
	surfaces, surfacesOK := policy["allowedSurfaceKinds"].([]any)
	recheck, recheckOK := policy["recheckAtExecution"].(bool)
	if !consentOK || len(consentScopes) == 0 || !surfacesOK || len(surfaces) == 0 ||
		!recheckOK || !recheck {
		return fmt.Errorf(
			"mutating tool %q requires consent scopes, surface policy and execution recheck",
			name,
		)
	}
	return nil
}

func validateServerInjectedInputs(name string, tool map[string]any) error {
	values, ok := tool["serverInjectedInputs"].([]any)
	if !ok {
		return fmt.Errorf("tool %q requires serverInjectedInputs", name)
	}
	schema, _ := tool["inputSchema"].(map[string]any)
	properties, _ := schema["properties"].(map[string]any)
	for _, value := range values {
		field := strings.TrimSpace(fmt.Sprint(value))
		if field != "runId" && field != "skillId" {
			return fmt.Errorf("tool %q has unsupported server injected input %q", name, field)
		}
		if _, exists := properties[field]; !exists {
			return fmt.Errorf("tool %q injected input %q has no schema property", name, field)
		}
	}
	return nil
}

func stringValue(value map[string]any, key string) string {
	raw, exists := value[key]
	if !exists || raw == nil {
		return ""
	}
	return strings.TrimSpace(fmt.Sprint(raw))
}

func fail(message string) {
	fmt.Fprintln(os.Stderr, "codegen_assistant_tool_catalog:", message)
	os.Exit(1)
}
